[2024-11-18T17:40:01.805+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_recommender_dag_v3.train_embedding_model manual__2024-11-18T17:40:01.281718+00:00 [queued]>
[2024-11-18T17:40:01.809+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_recommender_dag_v3.train_embedding_model manual__2024-11-18T17:40:01.281718+00:00 [queued]>
[2024-11-18T17:40:01.809+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-11-18T17:40:01.815+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_embedding_model> on 2024-11-18 17:40:01.281718+00:00
[2024-11-18T17:40:01.817+0000] {standard_task_runner.py:60} INFO - Started process 339 to run task
[2024-11-18T17:40:01.819+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_recommender_dag_v3', 'train_embedding_model', 'manual__2024-11-18T17:40:01.281718+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/music_process.py', '--cfg-path', '/tmp/tmpt7t04xqs']
[2024-11-18T17:40:01.820+0000] {standard_task_runner.py:88} INFO - Job 43: Subtask train_embedding_model
[2024-11-18T17:40:01.846+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_recommender_dag_v3.train_embedding_model manual__2024-11-18T17:40:01.281718+00:00 [running]> on host 98017b53a184
[2024-11-18T17:40:01.886+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_recommender_dag_v3' AIRFLOW_CTX_TASK_ID='train_embedding_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T17:40:01.281718+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T17:40:01.281718+00:00'
[2024-11-18T17:40:01.887+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvcl2qh9u9 --system-site-packages --python=python
[2024-11-18T17:40:01.890+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T17:40:02.225+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 123ms
[2024-11-18T17:40:02.225+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvcl2qh9u9, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T17:40:02.225+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T17:40:02.226+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-11-18T17:40:02.226+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T17:40:02.244+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvcl2qh9u9/bin/pip install -r /tmp/venvcl2qh9u9/requirements.txt
[2024-11-18T17:40:02.247+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T17:40:03.174+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venvcl2qh9u9/requirements.txt (line 1))
[2024-11-18T17:40:03.175+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T17:40:03.214+0000] {process_utils.py:190} INFO - Collecting mlflow==2.10.2 (from -r /tmp/venvcl2qh9u9/requirements.txt (line 2))
[2024-11-18T17:40:03.215+0000] {process_utils.py:190} INFO -   Using cached mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
[2024-11-18T17:40:03.216+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvcl2qh9u9/requirements.txt (line 3)) (2.0.3)
[2024-11-18T17:40:03.315+0000] {process_utils.py:190} INFO - Collecting tensorflow==2.13.0 (from -r /tmp/venvcl2qh9u9/requirements.txt (line 4))
[2024-11-18T17:40:03.316+0000] {process_utils.py:190} INFO -   Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
[2024-11-18T17:40:03.734+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 1))
[2024-11-18T17:40:03.736+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T17:40:03.737+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 1)) (0.10.0)
[2024-11-18T17:40:03.759+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 1))
[2024-11-18T17:40:03.760+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T17:40:03.811+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (8.1.7)
[2024-11-18T17:40:03.811+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (3.1.0)
[2024-11-18T17:40:03.826+0000] {process_utils.py:190} INFO - Collecting entrypoints<1 (from mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2))
[2024-11-18T17:40:03.828+0000] {process_utils.py:190} INFO -   Using cached entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
[2024-11-18T17:40:03.828+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=2.1.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (3.1.43)
[2024-11-18T17:40:03.829+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (6.0.1)
[2024-11-18T17:40:03.829+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<5,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (4.25.2)
[2024-11-18T17:40:03.830+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz<2024 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T17:40:03.830+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (2.31.0)
[2024-11-18T17:40:03.830+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (23.2)
[2024-11-18T17:40:03.831+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (6.11.0)
[2024-11-18T17:40:03.831+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (0.4.4)
[2024-11-18T17:40:03.832+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (1.13.1)
[2024-11-18T17:40:03.832+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (7.0.0)
[2024-11-18T17:40:03.833+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (2.2.5)
[2024-11-18T17:40:03.833+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (1.24.4)
[2024-11-18T17:40:03.833+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (1.10.1)
[2024-11-18T17:40:03.850+0000] {process_utils.py:190} INFO - Collecting querystring-parser<2 (from mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2))
[2024-11-18T17:40:03.851+0000] {process_utils.py:190} INFO -   Using cached querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
[2024-11-18T17:40:03.852+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (1.4.51)
[2024-11-18T17:40:03.852+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (1.3.2)
[2024-11-18T17:40:03.853+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow<16,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (14.0.2)
[2024-11-18T17:40:03.853+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (3.5.2)
[2024-11-18T17:40:03.854+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (3.7.5)
[2024-11-18T17:40:03.854+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<22 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (21.2.0)
[2024-11-18T17:40:03.855+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (3.1.3)
[2024-11-18T17:40:03.907+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvcl2qh9u9/requirements.txt (line 3)) (2.8.2)
[2024-11-18T17:40:03.907+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvcl2qh9u9/requirements.txt (line 3)) (2023.4)
[2024-11-18T17:40:03.940+0000] {process_utils.py:190} INFO - Collecting absl-py>=1.0.0 (from tensorflow==2.13.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 4))
[2024-11-18T17:40:03.942+0000] {process_utils.py:190} INFO -   Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
[2024-11-18T17:40:03.957+0000] {process_utils.py:190} INFO - Collecting astunparse>=1.6.0 (from tensorflow==2.13.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 4))
[2024-11-18T17:40:03.958+0000] {process_utils.py:190} INFO -   Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
[2024-11-18T17:40:03.976+0000] {process_utils.py:190} INFO - Collecting flatbuffers>=23.1.21 (from tensorflow==2.13.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 4))
[2024-11-18T17:40:03.977+0000] {process_utils.py:190} INFO -   Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
[2024-11-18T17:40:03.996+0000] {process_utils.py:190} INFO - Collecting gast<=0.4.0,>=0.2.1 (from tensorflow==2.13.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 4))
[2024-11-18T17:40:03.997+0000] {process_utils.py:190} INFO -   Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
[2024-11-18T17:40:04.015+0000] {process_utils.py:190} INFO - Collecting google-pasta>=0.1.1 (from tensorflow==2.13.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 4))
[2024-11-18T17:40:04.016+0000] {process_utils.py:190} INFO -   Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
[2024-11-18T17:40:04.017+0000] {process_utils.py:190} INFO - Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 4)) (1.60.0)
[2024-11-18T17:40:04.058+0000] {process_utils.py:190} INFO - Collecting h5py>=2.9.0 (from tensorflow==2.13.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 4))
[2024-11-18T17:40:04.060+0000] {process_utils.py:190} INFO -   Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
[2024-11-18T17:40:04.087+0000] {process_utils.py:190} INFO - Collecting keras<2.14,>=2.13.1 (from tensorflow==2.13.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 4))
[2024-11-18T17:40:04.088+0000] {process_utils.py:190} INFO -   Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
[2024-11-18T17:40:04.108+0000] {process_utils.py:190} INFO - Collecting libclang>=13.0.0 (from tensorflow==2.13.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 4))
[2024-11-18T17:40:04.109+0000] {process_utils.py:190} INFO -   Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
[2024-11-18T17:40:04.257+0000] {process_utils.py:190} INFO - Collecting numpy<2 (from mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2))
[2024-11-18T17:40:04.258+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-11-18T17:40:04.275+0000] {process_utils.py:190} INFO - Collecting opt-einsum>=2.3.2 (from tensorflow==2.13.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 4))
[2024-11-18T17:40:04.276+0000] {process_utils.py:190} INFO -   Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
[2024-11-18T17:40:04.277+0000] {process_utils.py:190} INFO - Requirement already satisfied: setuptools in /tmp/venvcl2qh9u9/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 4)) (69.0.2)
[2024-11-18T17:40:04.277+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.12.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 4)) (1.16.0)
[2024-11-18T17:40:04.303+0000] {process_utils.py:190} INFO - Collecting tensorboard<2.14,>=2.13 (from tensorflow==2.13.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 4))
[2024-11-18T17:40:04.304+0000] {process_utils.py:190} INFO -   Using cached tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T17:40:04.322+0000] {process_utils.py:190} INFO - Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow==2.13.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 4))
[2024-11-18T17:40:04.323+0000] {process_utils.py:190} INFO -   Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
[2024-11-18T17:40:04.324+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.1.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 4)) (2.4.0)
[2024-11-18T17:40:04.346+0000] {process_utils.py:190} INFO - Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow==2.13.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 4))
[2024-11-18T17:40:04.347+0000] {process_utils.py:190} INFO -   Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
[2024-11-18T17:40:04.348+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt>=1.11.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 4)) (1.16.0)
[2024-11-18T17:40:04.399+0000] {process_utils.py:190} INFO - Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow==2.13.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 4))
[2024-11-18T17:40:04.400+0000] {process_utils.py:190} INFO -   Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
[2024-11-18T17:40:04.407+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (1.3.0)
[2024-11-18T17:40:04.411+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (5.13.0)
[2024-11-18T17:40:04.414+0000] {process_utils.py:190} INFO - Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venvcl2qh9u9/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow==2.13.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 4)) (0.42.0)
[2024-11-18T17:40:04.420+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 1)) (1.26.18)
[2024-11-18T17:40:04.435+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (2.2.3)
[2024-11-18T17:40:04.436+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (2.1.2)
[2024-11-18T17:40:04.453+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (4.0.11)
[2024-11-18T17:40:04.486+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (3.17.0)
[2024-11-18T17:40:04.489+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (2.1.3)
[2024-11-18T17:40:04.511+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (1.1.1)
[2024-11-18T17:40:04.511+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (0.12.1)
[2024-11-18T17:40:04.512+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (4.54.1)
[2024-11-18T17:40:04.512+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (1.4.7)
[2024-11-18T17:40:04.522+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (10.4.0)
[2024-11-18T17:40:04.523+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (3.1.1)
[2024-11-18T17:40:04.572+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (3.3.2)
[2024-11-18T17:40:04.573+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (3.6)
[2024-11-18T17:40:04.573+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (2023.11.17)
[2024-11-18T17:40:04.801+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (1.4.2)
[2024-11-18T17:40:04.802+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (3.5.0)
[2024-11-18T17:40:04.874+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (3.0.3)
[2024-11-18T17:40:04.892+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth<3,>=1.6.3 in /home/***/.local/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 4)) (2.26.2)
[2024-11-18T17:40:04.912+0000] {process_utils.py:190} INFO - Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 4))
[2024-11-18T17:40:04.913+0000] {process_utils.py:190} INFO -   Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
[2024-11-18T17:40:04.941+0000] {process_utils.py:190} INFO - Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 4))
[2024-11-18T17:40:04.942+0000] {process_utils.py:190} INFO -   Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
[2024-11-18T17:40:05.078+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvcl2qh9u9/requirements.txt (line 2)) (5.0.1)
[2024-11-18T17:40:05.089+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 4)) (5.3.2)
[2024-11-18T17:40:05.089+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 4)) (0.3.0)
[2024-11-18T17:40:05.090+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 4)) (4.9)
[2024-11-18T17:40:05.096+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 4)) (1.3.1)
[2024-11-18T17:40:05.235+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 4)) (0.5.1)
[2024-11-18T17:40:05.242+0000] {process_utils.py:190} INFO - Requirement already satisfied: oauthlib>=3.0.0 in /home/***/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvcl2qh9u9/requirements.txt (line 4)) (3.2.2)
[2024-11-18T17:40:05.274+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T17:40:05.276+0000] {process_utils.py:190} INFO - Using cached mlflow-2.10.2-py3-none-any.whl (19.5 MB)
[2024-11-18T17:40:05.295+0000] {process_utils.py:190} INFO - Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
[2024-11-18T17:40:05.775+0000] {process_utils.py:190} INFO - Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
[2024-11-18T17:40:05.777+0000] {process_utils.py:190} INFO - Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
[2024-11-18T17:40:05.778+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T17:40:05.789+0000] {process_utils.py:190} INFO - Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
[2024-11-18T17:40:05.790+0000] {process_utils.py:190} INFO - Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
[2024-11-18T17:40:05.791+0000] {process_utils.py:190} INFO - Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
[2024-11-18T17:40:05.792+0000] {process_utils.py:190} INFO - Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
[2024-11-18T17:40:05.793+0000] {process_utils.py:190} INFO - Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
[2024-11-18T17:40:05.799+0000] {process_utils.py:190} INFO - Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)
[2024-11-18T17:40:05.802+0000] {process_utils.py:190} INFO - Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
[2024-11-18T17:40:05.828+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-11-18T17:40:05.847+0000] {process_utils.py:190} INFO - Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
[2024-11-18T17:40:05.848+0000] {process_utils.py:190} INFO - Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
[2024-11-18T17:40:05.849+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T17:40:05.850+0000] {process_utils.py:190} INFO - Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
[2024-11-18T17:40:05.857+0000] {process_utils.py:190} INFO - Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
[2024-11-18T17:40:05.858+0000] {process_utils.py:190} INFO - Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
[2024-11-18T17:40:05.862+0000] {process_utils.py:190} INFO - Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[2024-11-18T17:40:05.863+0000] {process_utils.py:190} INFO - Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
[2024-11-18T17:40:05.864+0000] {process_utils.py:190} INFO - Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
[2024-11-18T17:40:08.000+0000] {process_utils.py:190} INFO - Installing collected packages: libclang, flatbuffers, typing-extensions, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, querystring-parser, opt-einsum, numpy, keras, google-pasta, gast, entrypoints, astunparse, absl-py, h5py, botocore, s3transfer, google-auth-oauthlib, tensorboard, mlflow, boto3, tensorflow
[2024-11-18T17:40:08.255+0000] {process_utils.py:190} INFO -   Attempting uninstall: typing-extensions
[2024-11-18T17:40:08.256+0000] {process_utils.py:190} INFO -     Found existing installation: typing_extensions 4.9.0
[2024-11-18T17:40:08.256+0000] {process_utils.py:190} INFO -     Not uninstalling typing-extensions at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvcl2qh9u9
[2024-11-18T17:40:08.257+0000] {process_utils.py:190} INFO -     Can't uninstall 'typing_extensions'. No files were found to uninstall.
[2024-11-18T17:40:08.517+0000] {process_utils.py:190} INFO -   Attempting uninstall: numpy
[2024-11-18T17:40:08.518+0000] {process_utils.py:190} INFO -     Found existing installation: numpy 1.24.4
[2024-11-18T17:40:08.518+0000] {process_utils.py:190} INFO -     Not uninstalling numpy at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvcl2qh9u9
[2024-11-18T17:40:08.519+0000] {process_utils.py:190} INFO -     Can't uninstall 'numpy'. No files were found to uninstall.
[2024-11-18T17:40:10.197+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T17:40:10.198+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T17:40:10.198+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvcl2qh9u9
[2024-11-18T17:40:10.199+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T17:40:10.601+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T17:40:10.603+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T17:40:10.603+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvcl2qh9u9
[2024-11-18T17:40:10.603+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T17:40:10.627+0000] {process_utils.py:190} INFO -   Attempting uninstall: google-auth-oauthlib
[2024-11-18T17:40:10.628+0000] {process_utils.py:190} INFO -     Found existing installation: google-auth-oauthlib 1.2.0
[2024-11-18T17:40:10.628+0000] {process_utils.py:190} INFO -     Not uninstalling google-auth-oauthlib at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvcl2qh9u9
[2024-11-18T17:40:10.628+0000] {process_utils.py:190} INFO -     Can't uninstall 'google-auth-oauthlib'. No files were found to uninstall.
[2024-11-18T17:40:10.829+0000] {process_utils.py:190} INFO -   Attempting uninstall: mlflow
[2024-11-18T17:40:10.831+0000] {process_utils.py:190} INFO -     Found existing installation: mlflow 2.17.0
[2024-11-18T17:40:10.831+0000] {process_utils.py:190} INFO -     Not uninstalling mlflow at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvcl2qh9u9
[2024-11-18T17:40:10.832+0000] {process_utils.py:190} INFO -     Can't uninstall 'mlflow'. No files were found to uninstall.
[2024-11-18T17:40:11.390+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T17:40:11.391+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T17:40:11.391+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvcl2qh9u9
[2024-11-18T17:40:11.392+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T17:40:18.643+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T17:40:18.643+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T17:40:18.644+0000] {process_utils.py:190} INFO - azure-core 1.29.6 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:40:18.644+0000] {process_utils.py:190} INFO - azure-mgmt-keyvault 10.3.1 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:40:18.644+0000] {process_utils.py:190} INFO - azure-mgmt-network 27.0.0 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:40:18.644+0000] {process_utils.py:190} INFO - graphene 3.4 requires typing-extensions<5,>=4.7.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:40:18.645+0000] {process_utils.py:190} INFO - pydantic 2.5.3 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:40:18.645+0000] {process_utils.py:190} INFO - pydantic-core 2.14.6 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:40:18.645+0000] {process_utils.py:190} INFO - Successfully installed absl-py-2.1.0 astunparse-1.6.3 boto3-1.28.0 botocore-1.31.85 entrypoints-0.4 flatbuffers-24.3.25 gast-0.4.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 h5py-3.11.0 keras-2.13.1 libclang-18.1.1 mlflow-2.10.2 numpy-1.24.3 opt-einsum-3.4.0 querystring-parser-1.2.4 s3transfer-0.6.2 tensorboard-2.13.0 tensorboard-data-server-0.7.2 tensorflow-2.13.0 tensorflow-estimator-2.13.0 tensorflow-io-gcs-filesystem-0.34.0 typing-extensions-4.5.0
[2024-11-18T17:40:18.724+0000] {process_utils.py:190} INFO - 
[2024-11-18T17:40:18.724+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.3.1
[2024-11-18T17:40:18.725+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T17:40:18.921+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvcl2qh9u9/bin/python /tmp/venv-callg3uuli2w/script.py /tmp/venv-callg3uuli2w/script.in /tmp/venv-callg3uuli2w/script.out /tmp/venv-callg3uuli2w/string_args.txt /tmp/venv-callg3uuli2w/termination.log
[2024-11-18T17:40:18.924+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T17:40:19.941+0000] {process_utils.py:190} INFO - 2024-11-18 17:40:19.940857: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-11-18T17:40:19.942+0000] {process_utils.py:190} INFO - 2024-11-18 17:40:19.941933: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T17:40:19.963+0000] {process_utils.py:190} INFO - 2024-11-18 17:40:19.962913: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T17:40:19.963+0000] {process_utils.py:190} INFO - 2024-11-18 17:40:19.963261: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-11-18T17:40:19.964+0000] {process_utils.py:190} INFO - To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-11-18T17:40:20.474+0000] {process_utils.py:190} INFO - 2024-11-18 17:40:20.474627: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-11-18T17:40:21.672+0000] {process_utils.py:190} INFO - Epoch 1/10
[2024-11-18T17:40:22.464+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 2:44 - loss: 0.3794 60/575 [==>...........................] - ETA: 0s - loss: 0.1422  130/575 [=====>........................] - ETA: 0s - loss: 0.0987216/575 [==========>...................] - ETA: 0s - loss: 0.0769300/575 [==============>...............] - ETA: 0s - loss: 0.0654383/575 [==================>...........] - ETA: 0s - loss: 0.0575467/575 [=======================>......] - ETA: 0s - loss: 0.0515554/575 [===========================>..] - ETA: 0s - loss: 0.0466575/575 [==============================] - 1s 882us/step - loss: 0.0457 - val_loss: 0.0073
[2024-11-18T17:40:22.465+0000] {process_utils.py:190} INFO - Epoch 2/10
[2024-11-18T17:40:22.902+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0227 82/575 [===>..........................] - ETA: 0s - loss: 0.0187164/575 [=======>......................] - ETA: 0s - loss: 0.0178249/575 [===========>..................] - ETA: 0s - loss: 0.0172332/575 [================>.............] - ETA: 0s - loss: 0.0166416/575 [====================>.........] - ETA: 0s - loss: 0.0161489/575 [========================>.....] - ETA: 0s - loss: 0.0157566/575 [============================>.] - ETA: 0s - loss: 0.0153575/575 [==============================] - 0s 761us/step - loss: 0.0153 - val_loss: 0.0048
[2024-11-18T17:40:22.903+0000] {process_utils.py:190} INFO - Epoch 3/10
[2024-11-18T17:40:23.336+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0111 82/575 [===>..........................] - ETA: 0s - loss: 0.0125162/575 [=======>......................] - ETA: 0s - loss: 0.0124235/575 [===========>..................] - ETA: 0s - loss: 0.0122321/575 [===============>..............] - ETA: 0s - loss: 0.0120405/575 [====================>.........] - ETA: 0s - loss: 0.0119489/575 [========================>.....] - ETA: 0s - loss: 0.0117564/575 [============================>.] - ETA: 0s - loss: 0.0115575/575 [==============================] - 0s 754us/step - loss: 0.0115 - val_loss: 0.0037
[2024-11-18T17:40:23.336+0000] {process_utils.py:190} INFO - Epoch 4/10
[2024-11-18T17:40:23.776+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0135 84/575 [===>..........................] - ETA: 0s - loss: 0.0101164/575 [=======>......................] - ETA: 0s - loss: 0.0100243/575 [===========>..................] - ETA: 0s - loss: 0.0098319/575 [===============>..............] - ETA: 0s - loss: 0.0097398/575 [===================>..........] - ETA: 0s - loss: 0.0095482/575 [========================>.....] - ETA: 0s - loss: 0.0093562/575 [============================>.] - ETA: 0s - loss: 0.0092575/575 [==============================] - 0s 764us/step - loss: 0.0092 - val_loss: 0.0033
[2024-11-18T17:40:23.777+0000] {process_utils.py:190} INFO - Epoch 5/10
[2024-11-18T17:40:24.204+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0083 82/575 [===>..........................] - ETA: 0s - loss: 0.0084162/575 [=======>......................] - ETA: 0s - loss: 0.0082244/575 [===========>..................] - ETA: 0s - loss: 0.0081324/575 [===============>..............] - ETA: 0s - loss: 0.0080409/575 [====================>.........] - ETA: 0s - loss: 0.0079489/575 [========================>.....] - ETA: 0s - loss: 0.0079572/575 [============================>.] - ETA: 0s - loss: 0.0078575/575 [==============================] - 0s 744us/step - loss: 0.0078 - val_loss: 0.0027
[2024-11-18T17:40:24.205+0000] {process_utils.py:190} INFO - Epoch 6/10
[2024-11-18T17:40:24.642+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0072 78/575 [===>..........................] - ETA: 0s - loss: 0.0077159/575 [=======>......................] - ETA: 0s - loss: 0.0075238/575 [===========>..................] - ETA: 0s - loss: 0.0074321/575 [===============>..............] - ETA: 0s - loss: 0.0074401/575 [===================>..........] - ETA: 0s - loss: 0.0073481/575 [========================>.....] - ETA: 0s - loss: 0.0073560/575 [============================>.] - ETA: 0s - loss: 0.0073575/575 [==============================] - 0s 760us/step - loss: 0.0073 - val_loss: 0.0024
[2024-11-18T17:40:24.642+0000] {process_utils.py:190} INFO - Epoch 7/10
[2024-11-18T17:40:25.079+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0077 80/575 [===>..........................] - ETA: 0s - loss: 0.0070158/575 [=======>......................] - ETA: 0s - loss: 0.0071236/575 [===========>..................] - ETA: 0s - loss: 0.0071317/575 [===============>..............] - ETA: 0s - loss: 0.0070395/575 [===================>..........] - ETA: 0s - loss: 0.0070476/575 [=======================>......] - ETA: 0s - loss: 0.0069555/575 [===========================>..] - ETA: 0s - loss: 0.0069575/575 [==============================] - 0s 760us/step - loss: 0.0069 - val_loss: 0.0022
[2024-11-18T17:40:25.081+0000] {process_utils.py:190} INFO - Epoch 8/10
[2024-11-18T17:40:25.503+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0049 83/575 [===>..........................] - ETA: 0s - loss: 0.0068163/575 [=======>......................] - ETA: 0s - loss: 0.0067244/575 [===========>..................] - ETA: 0s - loss: 0.0067327/575 [================>.............] - ETA: 0s - loss: 0.0067410/575 [====================>.........] - ETA: 0s - loss: 0.0067493/575 [========================>.....] - ETA: 0s - loss: 0.0067575/575 [==============================] - 0s 736us/step - loss: 0.0066 - val_loss: 0.0023
[2024-11-18T17:40:25.503+0000] {process_utils.py:190} INFO - Epoch 9/10
[2024-11-18T17:40:25.934+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0048 81/575 [===>..........................] - ETA: 0s - loss: 0.0064165/575 [=======>......................] - ETA: 0s - loss: 0.0065249/575 [===========>..................] - ETA: 0s - loss: 0.0065331/575 [================>.............] - ETA: 0s - loss: 0.0064408/575 [====================>.........] - ETA: 0s - loss: 0.0064481/575 [========================>.....] - ETA: 0s - loss: 0.0064559/575 [============================>.] - ETA: 0s - loss: 0.0064575/575 [==============================] - 0s 749us/step - loss: 0.0064 - val_loss: 0.0022
[2024-11-18T17:40:25.936+0000] {process_utils.py:190} INFO - Epoch 10/10
[2024-11-18T17:40:26.374+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0072 82/575 [===>..........................] - ETA: 0s - loss: 0.0062165/575 [=======>......................] - ETA: 0s - loss: 0.0064241/575 [===========>..................] - ETA: 0s - loss: 0.0063313/575 [===============>..............] - ETA: 0s - loss: 0.0063397/575 [===================>..........] - ETA: 0s - loss: 0.0063480/575 [========================>.....] - ETA: 0s - loss: 0.0064557/575 [============================>.] - ETA: 0s - loss: 0.0064575/575 [==============================] - 0s 764us/step - loss: 0.0064 - val_loss: 0.0022
[2024-11-18T17:40:26.646+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-11-18T17:40:26.646+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callg3uuli2w/script.py", line 80, in <module>
[2024-11-18T17:40:26.647+0000] {process_utils.py:190} INFO -     res = train_embedding_model(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-18T17:40:26.647+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callg3uuli2w/script.py", line 71, in train_embedding_model
[2024-11-18T17:40:26.647+0000] {process_utils.py:190} INFO -     mlflow.tensorflow.log_model(
[2024-11-18T17:40:26.648+0000] {process_utils.py:190} INFO - TypeError: log_model() got an unexpected keyword argument 'tf_saved_model_dir'
[2024-11-18T17:40:27.442+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
log_model() got an unexpected keyword argument 'tf_saved_model_dir'
[2024-11-18T17:40:27.446+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_recommender_dag_v3, task_id=train_embedding_model, execution_date=20241118T174001, start_date=20241118T174001, end_date=20241118T174027
[2024-11-18T17:40:27.466+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 43 for task train_embedding_model (Process returned non-zero exit status 1.
log_model() got an unexpected keyword argument 'tf_saved_model_dir'; 339)
[2024-11-18T17:40:27.485+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-18T17:40:27.493+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
