[2024-11-18T17:45:28.557+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_recommender_dag_v3.train_embedding_model manual__2024-11-18T17:40:01.281718+00:00 [queued]>
[2024-11-18T17:45:28.561+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_recommender_dag_v3.train_embedding_model manual__2024-11-18T17:40:01.281718+00:00 [queued]>
[2024-11-18T17:45:28.561+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-11-18T17:45:28.568+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_embedding_model> on 2024-11-18 17:40:01.281718+00:00
[2024-11-18T17:45:28.571+0000] {standard_task_runner.py:60} INFO - Started process 337 to run task
[2024-11-18T17:45:28.572+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_recommender_dag_v3', 'train_embedding_model', 'manual__2024-11-18T17:40:01.281718+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/music_process.py', '--cfg-path', '/tmp/tmpjqqei42_']
[2024-11-18T17:45:28.573+0000] {standard_task_runner.py:88} INFO - Job 48: Subtask train_embedding_model
[2024-11-18T17:45:28.599+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_recommender_dag_v3.train_embedding_model manual__2024-11-18T17:40:01.281718+00:00 [running]> on host 98017b53a184
[2024-11-18T17:45:28.637+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_recommender_dag_v3' AIRFLOW_CTX_TASK_ID='train_embedding_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T17:40:01.281718+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T17:40:01.281718+00:00'
[2024-11-18T17:45:28.638+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvzjaq0gkv --system-site-packages --python=python
[2024-11-18T17:45:28.641+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T17:45:28.963+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 109ms
[2024-11-18T17:45:28.964+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvzjaq0gkv, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T17:45:28.964+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T17:45:28.965+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-11-18T17:45:28.965+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T17:45:28.982+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvzjaq0gkv/bin/pip install -r /tmp/venvzjaq0gkv/requirements.txt
[2024-11-18T17:45:28.986+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T17:45:29.931+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venvzjaq0gkv/requirements.txt (line 1))
[2024-11-18T17:45:29.932+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T17:45:29.975+0000] {process_utils.py:190} INFO - Collecting mlflow==2.10.2 (from -r /tmp/venvzjaq0gkv/requirements.txt (line 2))
[2024-11-18T17:45:29.977+0000] {process_utils.py:190} INFO -   Using cached mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
[2024-11-18T17:45:29.978+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvzjaq0gkv/requirements.txt (line 3)) (2.0.3)
[2024-11-18T17:45:30.080+0000] {process_utils.py:190} INFO - Collecting tensorflow==2.13.0 (from -r /tmp/venvzjaq0gkv/requirements.txt (line 4))
[2024-11-18T17:45:30.081+0000] {process_utils.py:190} INFO -   Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
[2024-11-18T17:45:30.500+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 1))
[2024-11-18T17:45:30.502+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T17:45:30.503+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 1)) (0.10.0)
[2024-11-18T17:45:30.530+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 1))
[2024-11-18T17:45:30.531+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T17:45:30.582+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (8.1.7)
[2024-11-18T17:45:30.584+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (3.1.0)
[2024-11-18T17:45:30.603+0000] {process_utils.py:190} INFO - Collecting entrypoints<1 (from mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2))
[2024-11-18T17:45:30.604+0000] {process_utils.py:190} INFO -   Using cached entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
[2024-11-18T17:45:30.605+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=2.1.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (3.1.43)
[2024-11-18T17:45:30.606+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (6.0.1)
[2024-11-18T17:45:30.606+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<5,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (4.25.2)
[2024-11-18T17:45:30.607+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz<2024 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T17:45:30.607+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (2.31.0)
[2024-11-18T17:45:30.608+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (23.2)
[2024-11-18T17:45:30.608+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (6.11.0)
[2024-11-18T17:45:30.609+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (0.4.4)
[2024-11-18T17:45:30.609+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (1.13.1)
[2024-11-18T17:45:30.609+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (7.0.0)
[2024-11-18T17:45:30.610+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (2.2.5)
[2024-11-18T17:45:30.610+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (1.24.4)
[2024-11-18T17:45:30.611+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (1.10.1)
[2024-11-18T17:45:30.630+0000] {process_utils.py:190} INFO - Collecting querystring-parser<2 (from mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2))
[2024-11-18T17:45:30.631+0000] {process_utils.py:190} INFO -   Using cached querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
[2024-11-18T17:45:30.632+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (1.4.51)
[2024-11-18T17:45:30.632+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (1.3.2)
[2024-11-18T17:45:30.633+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow<16,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (14.0.2)
[2024-11-18T17:45:30.633+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (3.5.2)
[2024-11-18T17:45:30.634+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (3.7.5)
[2024-11-18T17:45:30.635+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<22 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (21.2.0)
[2024-11-18T17:45:30.636+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (3.1.3)
[2024-11-18T17:45:30.686+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvzjaq0gkv/requirements.txt (line 3)) (2.8.2)
[2024-11-18T17:45:30.687+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvzjaq0gkv/requirements.txt (line 3)) (2023.4)
[2024-11-18T17:45:30.726+0000] {process_utils.py:190} INFO - Collecting absl-py>=1.0.0 (from tensorflow==2.13.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 4))
[2024-11-18T17:45:30.727+0000] {process_utils.py:190} INFO -   Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
[2024-11-18T17:45:30.749+0000] {process_utils.py:190} INFO - Collecting astunparse>=1.6.0 (from tensorflow==2.13.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 4))
[2024-11-18T17:45:30.750+0000] {process_utils.py:190} INFO -   Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
[2024-11-18T17:45:30.772+0000] {process_utils.py:190} INFO - Collecting flatbuffers>=23.1.21 (from tensorflow==2.13.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 4))
[2024-11-18T17:45:30.774+0000] {process_utils.py:190} INFO -   Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
[2024-11-18T17:45:30.797+0000] {process_utils.py:190} INFO - Collecting gast<=0.4.0,>=0.2.1 (from tensorflow==2.13.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 4))
[2024-11-18T17:45:30.799+0000] {process_utils.py:190} INFO -   Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
[2024-11-18T17:45:30.819+0000] {process_utils.py:190} INFO - Collecting google-pasta>=0.1.1 (from tensorflow==2.13.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 4))
[2024-11-18T17:45:30.820+0000] {process_utils.py:190} INFO -   Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
[2024-11-18T17:45:30.821+0000] {process_utils.py:190} INFO - Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 4)) (1.60.0)
[2024-11-18T17:45:30.870+0000] {process_utils.py:190} INFO - Collecting h5py>=2.9.0 (from tensorflow==2.13.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 4))
[2024-11-18T17:45:30.874+0000] {process_utils.py:190} INFO -   Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
[2024-11-18T17:45:30.903+0000] {process_utils.py:190} INFO - Collecting keras<2.14,>=2.13.1 (from tensorflow==2.13.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 4))
[2024-11-18T17:45:30.904+0000] {process_utils.py:190} INFO -   Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
[2024-11-18T17:45:31.069+0000] {process_utils.py:190} INFO - Collecting libclang>=13.0.0 (from tensorflow==2.13.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 4))
[2024-11-18T17:45:31.070+0000] {process_utils.py:190} INFO -   Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
[2024-11-18T17:45:31.225+0000] {process_utils.py:190} INFO - Collecting numpy<2 (from mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2))
[2024-11-18T17:45:31.227+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-11-18T17:45:31.250+0000] {process_utils.py:190} INFO - Collecting opt-einsum>=2.3.2 (from tensorflow==2.13.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 4))
[2024-11-18T17:45:31.251+0000] {process_utils.py:190} INFO -   Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
[2024-11-18T17:45:31.252+0000] {process_utils.py:190} INFO - Requirement already satisfied: setuptools in /tmp/venvzjaq0gkv/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 4)) (69.0.2)
[2024-11-18T17:45:31.253+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.12.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 4)) (1.16.0)
[2024-11-18T17:45:31.284+0000] {process_utils.py:190} INFO - Collecting tensorboard<2.14,>=2.13 (from tensorflow==2.13.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 4))
[2024-11-18T17:45:31.285+0000] {process_utils.py:190} INFO -   Using cached tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T17:45:31.310+0000] {process_utils.py:190} INFO - Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow==2.13.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 4))
[2024-11-18T17:45:31.311+0000] {process_utils.py:190} INFO -   Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
[2024-11-18T17:45:31.312+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.1.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 4)) (2.4.0)
[2024-11-18T17:45:31.340+0000] {process_utils.py:190} INFO - Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow==2.13.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 4))
[2024-11-18T17:45:31.341+0000] {process_utils.py:190} INFO -   Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
[2024-11-18T17:45:31.342+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt>=1.11.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 4)) (1.16.0)
[2024-11-18T17:45:31.398+0000] {process_utils.py:190} INFO - Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow==2.13.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 4))
[2024-11-18T17:45:31.399+0000] {process_utils.py:190} INFO -   Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
[2024-11-18T17:45:31.406+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (1.3.0)
[2024-11-18T17:45:31.409+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (5.13.0)
[2024-11-18T17:45:31.412+0000] {process_utils.py:190} INFO - Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venvzjaq0gkv/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow==2.13.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 4)) (0.42.0)
[2024-11-18T17:45:31.418+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 1)) (1.26.18)
[2024-11-18T17:45:31.433+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (2.2.3)
[2024-11-18T17:45:31.433+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (2.1.2)
[2024-11-18T17:45:31.450+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (4.0.11)
[2024-11-18T17:45:31.483+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (3.17.0)
[2024-11-18T17:45:31.486+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (2.1.3)
[2024-11-18T17:45:31.508+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (1.1.1)
[2024-11-18T17:45:31.508+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (0.12.1)
[2024-11-18T17:45:31.509+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (4.54.1)
[2024-11-18T17:45:31.509+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (1.4.7)
[2024-11-18T17:45:31.516+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (10.4.0)
[2024-11-18T17:45:31.517+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (3.1.1)
[2024-11-18T17:45:31.557+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (3.3.2)
[2024-11-18T17:45:31.557+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (3.6)
[2024-11-18T17:45:31.558+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (2023.11.17)
[2024-11-18T17:45:31.717+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (1.4.2)
[2024-11-18T17:45:31.719+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (3.5.0)
[2024-11-18T17:45:31.794+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (3.0.3)
[2024-11-18T17:45:31.811+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth<3,>=1.6.3 in /home/***/.local/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 4)) (2.26.2)
[2024-11-18T17:45:31.836+0000] {process_utils.py:190} INFO - Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 4))
[2024-11-18T17:45:31.837+0000] {process_utils.py:190} INFO -   Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
[2024-11-18T17:45:31.875+0000] {process_utils.py:190} INFO - Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 4))
[2024-11-18T17:45:31.876+0000] {process_utils.py:190} INFO -   Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
[2024-11-18T17:45:32.016+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvzjaq0gkv/requirements.txt (line 2)) (5.0.1)
[2024-11-18T17:45:32.027+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 4)) (5.3.2)
[2024-11-18T17:45:32.027+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 4)) (0.3.0)
[2024-11-18T17:45:32.028+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 4)) (4.9)
[2024-11-18T17:45:32.034+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 4)) (1.3.1)
[2024-11-18T17:45:32.170+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 4)) (0.5.1)
[2024-11-18T17:45:32.178+0000] {process_utils.py:190} INFO - Requirement already satisfied: oauthlib>=3.0.0 in /home/***/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvzjaq0gkv/requirements.txt (line 4)) (3.2.2)
[2024-11-18T17:45:32.212+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T17:45:32.213+0000] {process_utils.py:190} INFO - Using cached mlflow-2.10.2-py3-none-any.whl (19.5 MB)
[2024-11-18T17:45:32.233+0000] {process_utils.py:190} INFO - Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
[2024-11-18T17:45:32.737+0000] {process_utils.py:190} INFO - Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
[2024-11-18T17:45:32.738+0000] {process_utils.py:190} INFO - Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
[2024-11-18T17:45:32.739+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T17:45:32.752+0000] {process_utils.py:190} INFO - Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
[2024-11-18T17:45:32.753+0000] {process_utils.py:190} INFO - Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
[2024-11-18T17:45:32.754+0000] {process_utils.py:190} INFO - Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
[2024-11-18T17:45:32.756+0000] {process_utils.py:190} INFO - Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
[2024-11-18T17:45:32.757+0000] {process_utils.py:190} INFO - Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
[2024-11-18T17:45:32.763+0000] {process_utils.py:190} INFO - Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)
[2024-11-18T17:45:32.766+0000] {process_utils.py:190} INFO - Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
[2024-11-18T17:45:32.791+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-11-18T17:45:32.810+0000] {process_utils.py:190} INFO - Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
[2024-11-18T17:45:32.811+0000] {process_utils.py:190} INFO - Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
[2024-11-18T17:45:32.812+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T17:45:32.813+0000] {process_utils.py:190} INFO - Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
[2024-11-18T17:45:32.819+0000] {process_utils.py:190} INFO - Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
[2024-11-18T17:45:32.821+0000] {process_utils.py:190} INFO - Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
[2024-11-18T17:45:32.824+0000] {process_utils.py:190} INFO - Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[2024-11-18T17:45:32.825+0000] {process_utils.py:190} INFO - Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
[2024-11-18T17:45:32.827+0000] {process_utils.py:190} INFO - Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
[2024-11-18T17:45:34.950+0000] {process_utils.py:190} INFO - Installing collected packages: libclang, flatbuffers, typing-extensions, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, querystring-parser, opt-einsum, numpy, keras, google-pasta, gast, entrypoints, astunparse, absl-py, h5py, botocore, s3transfer, google-auth-oauthlib, tensorboard, mlflow, boto3, tensorflow
[2024-11-18T17:45:35.196+0000] {process_utils.py:190} INFO -   Attempting uninstall: typing-extensions
[2024-11-18T17:45:35.198+0000] {process_utils.py:190} INFO -     Found existing installation: typing_extensions 4.9.0
[2024-11-18T17:45:35.198+0000] {process_utils.py:190} INFO -     Not uninstalling typing-extensions at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvzjaq0gkv
[2024-11-18T17:45:35.199+0000] {process_utils.py:190} INFO -     Can't uninstall 'typing_extensions'. No files were found to uninstall.
[2024-11-18T17:45:35.459+0000] {process_utils.py:190} INFO -   Attempting uninstall: numpy
[2024-11-18T17:45:35.460+0000] {process_utils.py:190} INFO -     Found existing installation: numpy 1.24.4
[2024-11-18T17:45:35.460+0000] {process_utils.py:190} INFO -     Not uninstalling numpy at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvzjaq0gkv
[2024-11-18T17:45:35.460+0000] {process_utils.py:190} INFO -     Can't uninstall 'numpy'. No files were found to uninstall.
[2024-11-18T17:45:37.137+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T17:45:37.137+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T17:45:37.138+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvzjaq0gkv
[2024-11-18T17:45:37.138+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T17:45:37.540+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T17:45:37.542+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T17:45:37.542+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvzjaq0gkv
[2024-11-18T17:45:37.542+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T17:45:37.563+0000] {process_utils.py:190} INFO -   Attempting uninstall: google-auth-oauthlib
[2024-11-18T17:45:37.564+0000] {process_utils.py:190} INFO -     Found existing installation: google-auth-oauthlib 1.2.0
[2024-11-18T17:45:37.564+0000] {process_utils.py:190} INFO -     Not uninstalling google-auth-oauthlib at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvzjaq0gkv
[2024-11-18T17:45:37.565+0000] {process_utils.py:190} INFO -     Can't uninstall 'google-auth-oauthlib'. No files were found to uninstall.
[2024-11-18T17:45:37.768+0000] {process_utils.py:190} INFO -   Attempting uninstall: mlflow
[2024-11-18T17:45:37.770+0000] {process_utils.py:190} INFO -     Found existing installation: mlflow 2.17.0
[2024-11-18T17:45:37.770+0000] {process_utils.py:190} INFO -     Not uninstalling mlflow at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvzjaq0gkv
[2024-11-18T17:45:37.771+0000] {process_utils.py:190} INFO -     Can't uninstall 'mlflow'. No files were found to uninstall.
[2024-11-18T17:45:38.335+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T17:45:38.336+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T17:45:38.337+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvzjaq0gkv
[2024-11-18T17:45:38.339+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T17:45:45.509+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T17:45:45.509+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T17:45:45.510+0000] {process_utils.py:190} INFO - azure-core 1.29.6 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:45:45.510+0000] {process_utils.py:190} INFO - azure-mgmt-keyvault 10.3.1 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:45:45.510+0000] {process_utils.py:190} INFO - azure-mgmt-network 27.0.0 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:45:45.510+0000] {process_utils.py:190} INFO - graphene 3.4 requires typing-extensions<5,>=4.7.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:45:45.511+0000] {process_utils.py:190} INFO - pydantic 2.5.3 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:45:45.511+0000] {process_utils.py:190} INFO - pydantic-core 2.14.6 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:45:45.511+0000] {process_utils.py:190} INFO - Successfully installed absl-py-2.1.0 astunparse-1.6.3 boto3-1.28.0 botocore-1.31.85 entrypoints-0.4 flatbuffers-24.3.25 gast-0.4.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 h5py-3.11.0 keras-2.13.1 libclang-18.1.1 mlflow-2.10.2 numpy-1.24.3 opt-einsum-3.4.0 querystring-parser-1.2.4 s3transfer-0.6.2 tensorboard-2.13.0 tensorboard-data-server-0.7.2 tensorflow-2.13.0 tensorflow-estimator-2.13.0 tensorflow-io-gcs-filesystem-0.34.0 typing-extensions-4.5.0
[2024-11-18T17:45:45.588+0000] {process_utils.py:190} INFO - 
[2024-11-18T17:45:45.588+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.3.1
[2024-11-18T17:45:45.589+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T17:45:45.778+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvzjaq0gkv/bin/python /tmp/venv-callu4qhdha3/script.py /tmp/venv-callu4qhdha3/script.in /tmp/venv-callu4qhdha3/script.out /tmp/venv-callu4qhdha3/string_args.txt /tmp/venv-callu4qhdha3/termination.log
[2024-11-18T17:45:45.781+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T17:45:46.749+0000] {process_utils.py:190} INFO - 2024-11-18 17:45:46.749806: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-11-18T17:45:46.751+0000] {process_utils.py:190} INFO - 2024-11-18 17:45:46.750970: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T17:45:46.771+0000] {process_utils.py:190} INFO - 2024-11-18 17:45:46.771828: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T17:45:46.772+0000] {process_utils.py:190} INFO - 2024-11-18 17:45:46.772096: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-11-18T17:45:46.772+0000] {process_utils.py:190} INFO - To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-11-18T17:45:47.266+0000] {process_utils.py:190} INFO - 2024-11-18 17:45:47.266435: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-11-18T17:45:48.690+0000] {process_utils.py:190} INFO - Epoch 1/10
[2024-11-18T17:45:49.496+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 2:49 - loss: 0.4118 51/575 [=>............................] - ETA: 0s - loss: 0.1989  107/575 [====>.........................] - ETA: 0s - loss: 0.1335196/575 [=========>....................] - ETA: 0s - loss: 0.0925283/575 [=============>................] - ETA: 0s - loss: 0.0739370/575 [==================>...........] - ETA: 0s - loss: 0.0631454/575 [======================>.......] - ETA: 0s - loss: 0.0558540/575 [===========================>..] - ETA: 0s - loss: 0.0503575/575 [==============================] - 1s 891us/step - loss: 0.0485 - val_loss: 0.0057
[2024-11-18T17:45:49.497+0000] {process_utils.py:190} INFO - Epoch 2/10
[2024-11-18T17:45:49.916+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0182 83/575 [===>..........................] - ETA: 0s - loss: 0.0194166/575 [=======>......................] - ETA: 0s - loss: 0.0185250/575 [============>.................] - ETA: 0s - loss: 0.0180333/575 [================>.............] - ETA: 0s - loss: 0.0173419/575 [====================>.........] - ETA: 0s - loss: 0.0169504/575 [=========================>....] - ETA: 0s - loss: 0.0164575/575 [==============================] - 0s 729us/step - loss: 0.0162 - val_loss: 0.0052
[2024-11-18T17:45:49.916+0000] {process_utils.py:190} INFO - Epoch 3/10
[2024-11-18T17:45:50.434+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0125 83/575 [===>..........................] - ETA: 0s - loss: 0.0133160/575 [=======>......................] - ETA: 0s - loss: 0.0132239/575 [===========>..................] - ETA: 0s - loss: 0.0130319/575 [===============>..............] - ETA: 0s - loss: 0.0129397/575 [===================>..........] - ETA: 0s - loss: 0.0127477/575 [=======================>......] - ETA: 0s - loss: 0.0126555/575 [===========================>..] - ETA: 0s - loss: 0.0124575/575 [==============================] - 1s 900us/step - loss: 0.0124 - val_loss: 0.0040
[2024-11-18T17:45:50.434+0000] {process_utils.py:190} INFO - Epoch 4/10
[2024-11-18T17:45:50.861+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0118 85/575 [===>..........................] - ETA: 0s - loss: 0.0116173/575 [========>.....................] - ETA: 0s - loss: 0.0112260/575 [============>.................] - ETA: 0s - loss: 0.0110333/575 [================>.............] - ETA: 0s - loss: 0.0108419/575 [====================>.........] - ETA: 0s - loss: 0.0107506/575 [=========================>....] - ETA: 0s - loss: 0.0106575/575 [==============================] - 0s 742us/step - loss: 0.0105 - val_loss: 0.0036
[2024-11-18T17:45:50.862+0000] {process_utils.py:190} INFO - Epoch 5/10
[2024-11-18T17:45:51.272+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0093 90/575 [===>..........................] - ETA: 0s - loss: 0.0101176/575 [========>.....................] - ETA: 0s - loss: 0.0098258/575 [============>.................] - ETA: 0s - loss: 0.0096344/575 [================>.............] - ETA: 0s - loss: 0.0096429/575 [=====================>........] - ETA: 0s - loss: 0.0095515/575 [=========================>....] - ETA: 0s - loss: 0.0094575/575 [==============================] - 0s 713us/step - loss: 0.0094 - val_loss: 0.0034
[2024-11-18T17:45:51.272+0000] {process_utils.py:190} INFO - Epoch 6/10
[2024-11-18T17:45:51.688+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0078 87/575 [===>..........................] - ETA: 0s - loss: 0.0088173/575 [========>.....................] - ETA: 0s - loss: 0.0087259/575 [============>.................] - ETA: 0s - loss: 0.0088343/575 [================>.............] - ETA: 0s - loss: 0.0087428/575 [=====================>........] - ETA: 0s - loss: 0.0087514/575 [=========================>....] - ETA: 0s - loss: 0.0086575/575 [==============================] - 0s 723us/step - loss: 0.0086 - val_loss: 0.0035
[2024-11-18T17:45:51.689+0000] {process_utils.py:190} INFO - Epoch 7/10
[2024-11-18T17:45:52.094+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0068 87/575 [===>..........................] - ETA: 0s - loss: 0.0082173/575 [========>.....................] - ETA: 0s - loss: 0.0081258/575 [============>.................] - ETA: 0s - loss: 0.0081343/575 [================>.............] - ETA: 0s - loss: 0.0082432/575 [=====================>........] - ETA: 0s - loss: 0.0081519/575 [==========================>...] - ETA: 0s - loss: 0.0081575/575 [==============================] - 0s 705us/step - loss: 0.0081 - val_loss: 0.0034
[2024-11-18T17:45:52.094+0000] {process_utils.py:190} INFO - Epoch 8/10
[2024-11-18T17:45:52.504+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0100 85/575 [===>..........................] - ETA: 0s - loss: 0.0078170/575 [=======>......................] - ETA: 0s - loss: 0.0078259/575 [============>.................] - ETA: 0s - loss: 0.0078344/575 [================>.............] - ETA: 0s - loss: 0.0077431/575 [=====================>........] - ETA: 0s - loss: 0.0077520/575 [==========================>...] - ETA: 0s - loss: 0.0076575/575 [==============================] - 0s 713us/step - loss: 0.0076 - val_loss: 0.0027
[2024-11-18T17:45:52.504+0000] {process_utils.py:190} INFO - Epoch 9/10
[2024-11-18T17:45:52.927+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0059 84/575 [===>..........................] - ETA: 0s - loss: 0.0072167/575 [=======>......................] - ETA: 0s - loss: 0.0073249/575 [===========>..................] - ETA: 0s - loss: 0.0073332/575 [================>.............] - ETA: 0s - loss: 0.0073416/575 [====================>.........] - ETA: 0s - loss: 0.0072499/575 [=========================>....] - ETA: 0s - loss: 0.0072575/575 [==============================] - 0s 734us/step - loss: 0.0072 - val_loss: 0.0023
[2024-11-18T17:45:52.927+0000] {process_utils.py:190} INFO - Epoch 10/10
[2024-11-18T17:45:53.342+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0049 84/575 [===>..........................] - ETA: 0s - loss: 0.0072170/575 [=======>......................] - ETA: 0s - loss: 0.0070256/575 [============>.................] - ETA: 0s - loss: 0.0070340/575 [================>.............] - ETA: 0s - loss: 0.0070425/575 [=====================>........] - ETA: 0s - loss: 0.0070510/575 [=========================>....] - ETA: 0s - loss: 0.0069575/575 [==============================] - 0s 721us/step - loss: 0.0069 - val_loss: 0.0021
[2024-11-18T17:45:53.731+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-11-18T17:45:53.731+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callu4qhdha3/script.py", line 83, in <module>
[2024-11-18T17:45:53.732+0000] {process_utils.py:190} INFO -     res = train_embedding_model(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-18T17:45:53.732+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callu4qhdha3/script.py", line 72, in train_embedding_model
[2024-11-18T17:45:53.732+0000] {process_utils.py:190} INFO -     model.save(model_path)
[2024-11-18T17:45:53.732+0000] {process_utils.py:190} INFO -   File "/tmp/venvzjaq0gkv/lib/python3.8/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
[2024-11-18T17:45:53.732+0000] {process_utils.py:190} INFO -     raise e.with_traceback(filtered_tb) from None
[2024-11-18T17:45:53.732+0000] {process_utils.py:190} INFO -   File "/tmp/venvzjaq0gkv/lib/python3.8/site-packages/tensorflow/python/lib/io/file_io.py", line 513, in recursive_create_dir_v2
[2024-11-18T17:45:53.732+0000] {process_utils.py:190} INFO -     _pywrap_file_io.RecursivelyCreateDir(compat.path_to_bytes(path))
[2024-11-18T17:45:53.733+0000] {process_utils.py:190} INFO - tensorflow.python.framework.errors_impl.PermissionDeniedError: /models; Permission denied
[2024-11-18T17:45:54.539+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
/models; Permission denied
[2024-11-18T17:45:54.541+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=spotify_recommender_dag_v3, task_id=train_embedding_model, execution_date=20241118T174001, start_date=20241118T174528, end_date=20241118T174554
[2024-11-18T17:45:54.548+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 48 for task train_embedding_model (Process returned non-zero exit status 1.
/models; Permission denied; 337)
[2024-11-18T17:45:54.560+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-18T17:45:54.569+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
