[2024-11-18T21:22:18.245+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T21:15:19.164424+00:00 [queued]>
[2024-11-18T21:22:18.249+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T21:15:19.164424+00:00 [queued]>
[2024-11-18T21:22:18.249+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-11-18T21:22:18.257+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_challenger_model> on 2024-11-18 21:15:19.164424+00:00
[2024-11-18T21:22:18.259+0000] {standard_task_runner.py:60} INFO - Started process 2912 to run task
[2024-11-18T21:22:18.261+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_retrain_challenge_model_v3', 'train_challenger_model', 'manual__2024-11-18T21:15:19.164424+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/retrain_music_model.py', '--cfg-path', '/tmp/tmpq6lkaj5s']
[2024-11-18T21:22:18.262+0000] {standard_task_runner.py:88} INFO - Job 130: Subtask train_challenger_model
[2024-11-18T21:22:18.287+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T21:15:19.164424+00:00 [running]> on host 46787693bc19
[2024-11-18T21:22:18.328+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_retrain_challenge_model_v3' AIRFLOW_CTX_TASK_ID='train_challenger_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T21:15:19.164424+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T21:15:19.164424+00:00'
[2024-11-18T21:22:18.330+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvo7veikp1 --system-site-packages --python=python
[2024-11-18T21:22:18.334+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T21:22:18.653+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 111ms
[2024-11-18T21:22:18.654+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvo7veikp1, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T21:22:18.654+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T21:22:18.655+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-11-18T21:22:18.656+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T21:22:18.671+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvo7veikp1/bin/pip install -r /tmp/venvo7veikp1/requirements.txt
[2024-11-18T21:22:18.675+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T21:22:19.619+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venvo7veikp1/requirements.txt (line 1))
[2024-11-18T21:22:19.620+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T21:22:19.658+0000] {process_utils.py:190} INFO - Collecting mlflow==2.10.2 (from -r /tmp/venvo7veikp1/requirements.txt (line 2))
[2024-11-18T21:22:19.659+0000] {process_utils.py:190} INFO -   Using cached mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
[2024-11-18T21:22:19.661+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvo7veikp1/requirements.txt (line 3)) (2.0.3)
[2024-11-18T21:22:19.661+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn==1.3.2 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvo7veikp1/requirements.txt (line 4)) (1.3.2)
[2024-11-18T21:22:19.761+0000] {process_utils.py:190} INFO - Collecting tensorflow==2.13.0 (from -r /tmp/venvo7veikp1/requirements.txt (line 5))
[2024-11-18T21:22:19.762+0000] {process_utils.py:190} INFO -   Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
[2024-11-18T21:22:20.177+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venvo7veikp1/requirements.txt (line 1))
[2024-11-18T21:22:20.179+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T21:22:20.180+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venvo7veikp1/requirements.txt (line 1)) (0.10.0)
[2024-11-18T21:22:20.202+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venvo7veikp1/requirements.txt (line 1))
[2024-11-18T21:22:20.204+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T21:22:20.254+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (8.1.7)
[2024-11-18T21:22:20.255+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (3.1.0)
[2024-11-18T21:22:20.271+0000] {process_utils.py:190} INFO - Collecting entrypoints<1 (from mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2))
[2024-11-18T21:22:20.272+0000] {process_utils.py:190} INFO -   Using cached entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
[2024-11-18T21:22:20.273+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=2.1.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (3.1.43)
[2024-11-18T21:22:20.274+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (6.0.1)
[2024-11-18T21:22:20.274+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<5,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (4.25.2)
[2024-11-18T21:22:20.275+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz<2024 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T21:22:20.275+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (2.31.0)
[2024-11-18T21:22:20.275+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (23.2)
[2024-11-18T21:22:20.276+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (6.11.0)
[2024-11-18T21:22:20.276+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (0.4.4)
[2024-11-18T21:22:20.277+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (1.13.1)
[2024-11-18T21:22:20.277+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (7.0.0)
[2024-11-18T21:22:20.278+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (2.2.5)
[2024-11-18T21:22:20.278+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (1.24.4)
[2024-11-18T21:22:20.278+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (1.10.1)
[2024-11-18T21:22:20.294+0000] {process_utils.py:190} INFO - Collecting querystring-parser<2 (from mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2))
[2024-11-18T21:22:20.295+0000] {process_utils.py:190} INFO -   Using cached querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
[2024-11-18T21:22:20.296+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (1.4.51)
[2024-11-18T21:22:20.297+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow<16,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (14.0.2)
[2024-11-18T21:22:20.297+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (3.5.2)
[2024-11-18T21:22:20.298+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (3.7.5)
[2024-11-18T21:22:20.298+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<22 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (21.2.0)
[2024-11-18T21:22:20.299+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (3.1.3)
[2024-11-18T21:22:20.350+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvo7veikp1/requirements.txt (line 3)) (2.8.2)
[2024-11-18T21:22:20.350+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvo7veikp1/requirements.txt (line 3)) (2023.4)
[2024-11-18T21:22:20.370+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvo7veikp1/requirements.txt (line 4)) (1.4.2)
[2024-11-18T21:22:20.371+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvo7veikp1/requirements.txt (line 4)) (3.5.0)
[2024-11-18T21:22:20.402+0000] {process_utils.py:190} INFO - Collecting absl-py>=1.0.0 (from tensorflow==2.13.0->-r /tmp/venvo7veikp1/requirements.txt (line 5))
[2024-11-18T21:22:20.403+0000] {process_utils.py:190} INFO -   Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
[2024-11-18T21:22:20.419+0000] {process_utils.py:190} INFO - Collecting astunparse>=1.6.0 (from tensorflow==2.13.0->-r /tmp/venvo7veikp1/requirements.txt (line 5))
[2024-11-18T21:22:20.421+0000] {process_utils.py:190} INFO -   Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
[2024-11-18T21:22:20.439+0000] {process_utils.py:190} INFO - Collecting flatbuffers>=23.1.21 (from tensorflow==2.13.0->-r /tmp/venvo7veikp1/requirements.txt (line 5))
[2024-11-18T21:22:20.441+0000] {process_utils.py:190} INFO -   Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
[2024-11-18T21:22:20.461+0000] {process_utils.py:190} INFO - Collecting gast<=0.4.0,>=0.2.1 (from tensorflow==2.13.0->-r /tmp/venvo7veikp1/requirements.txt (line 5))
[2024-11-18T21:22:20.463+0000] {process_utils.py:190} INFO -   Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
[2024-11-18T21:22:20.480+0000] {process_utils.py:190} INFO - Collecting google-pasta>=0.1.1 (from tensorflow==2.13.0->-r /tmp/venvo7veikp1/requirements.txt (line 5))
[2024-11-18T21:22:20.481+0000] {process_utils.py:190} INFO -   Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
[2024-11-18T21:22:20.482+0000] {process_utils.py:190} INFO - Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvo7veikp1/requirements.txt (line 5)) (1.60.0)
[2024-11-18T21:22:20.662+0000] {process_utils.py:190} INFO - Collecting h5py>=2.9.0 (from tensorflow==2.13.0->-r /tmp/venvo7veikp1/requirements.txt (line 5))
[2024-11-18T21:22:20.663+0000] {process_utils.py:190} INFO -   Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
[2024-11-18T21:22:20.688+0000] {process_utils.py:190} INFO - Collecting keras<2.14,>=2.13.1 (from tensorflow==2.13.0->-r /tmp/venvo7veikp1/requirements.txt (line 5))
[2024-11-18T21:22:20.689+0000] {process_utils.py:190} INFO -   Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
[2024-11-18T21:22:20.710+0000] {process_utils.py:190} INFO - Collecting libclang>=13.0.0 (from tensorflow==2.13.0->-r /tmp/venvo7veikp1/requirements.txt (line 5))
[2024-11-18T21:22:20.711+0000] {process_utils.py:190} INFO -   Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
[2024-11-18T21:22:20.860+0000] {process_utils.py:190} INFO - Collecting numpy<2 (from mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2))
[2024-11-18T21:22:20.861+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-11-18T21:22:20.880+0000] {process_utils.py:190} INFO - Collecting opt-einsum>=2.3.2 (from tensorflow==2.13.0->-r /tmp/venvo7veikp1/requirements.txt (line 5))
[2024-11-18T21:22:20.881+0000] {process_utils.py:190} INFO -   Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
[2024-11-18T21:22:20.882+0000] {process_utils.py:190} INFO - Requirement already satisfied: setuptools in /tmp/venvo7veikp1/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvo7veikp1/requirements.txt (line 5)) (69.0.2)
[2024-11-18T21:22:20.883+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.12.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvo7veikp1/requirements.txt (line 5)) (1.16.0)
[2024-11-18T21:22:20.907+0000] {process_utils.py:190} INFO - Collecting tensorboard<2.14,>=2.13 (from tensorflow==2.13.0->-r /tmp/venvo7veikp1/requirements.txt (line 5))
[2024-11-18T21:22:20.908+0000] {process_utils.py:190} INFO -   Using cached tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T21:22:21.066+0000] {process_utils.py:190} INFO - Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow==2.13.0->-r /tmp/venvo7veikp1/requirements.txt (line 5))
[2024-11-18T21:22:21.068+0000] {process_utils.py:190} INFO -   Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
[2024-11-18T21:22:21.068+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.1.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvo7veikp1/requirements.txt (line 5)) (2.4.0)
[2024-11-18T21:22:21.094+0000] {process_utils.py:190} INFO - Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow==2.13.0->-r /tmp/venvo7veikp1/requirements.txt (line 5))
[2024-11-18T21:22:21.095+0000] {process_utils.py:190} INFO -   Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
[2024-11-18T21:22:21.096+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt>=1.11.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvo7veikp1/requirements.txt (line 5)) (1.16.0)
[2024-11-18T21:22:21.152+0000] {process_utils.py:190} INFO - Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow==2.13.0->-r /tmp/venvo7veikp1/requirements.txt (line 5))
[2024-11-18T21:22:21.154+0000] {process_utils.py:190} INFO -   Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
[2024-11-18T21:22:21.161+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (1.3.0)
[2024-11-18T21:22:21.164+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (5.13.0)
[2024-11-18T21:22:21.167+0000] {process_utils.py:190} INFO - Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venvo7veikp1/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow==2.13.0->-r /tmp/venvo7veikp1/requirements.txt (line 5)) (0.42.0)
[2024-11-18T21:22:21.172+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venvo7veikp1/requirements.txt (line 1)) (1.26.18)
[2024-11-18T21:22:21.187+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (2.2.3)
[2024-11-18T21:22:21.188+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (2.1.2)
[2024-11-18T21:22:21.205+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (4.0.11)
[2024-11-18T21:22:21.231+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (3.17.0)
[2024-11-18T21:22:21.234+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (2.1.3)
[2024-11-18T21:22:21.259+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (1.1.1)
[2024-11-18T21:22:21.259+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (0.12.1)
[2024-11-18T21:22:21.260+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (4.54.1)
[2024-11-18T21:22:21.261+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (1.4.7)
[2024-11-18T21:22:21.268+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (10.4.0)
[2024-11-18T21:22:21.268+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (3.1.1)
[2024-11-18T21:22:21.313+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (3.3.2)
[2024-11-18T21:22:21.313+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (3.6)
[2024-11-18T21:22:21.314+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (2023.11.17)
[2024-11-18T21:22:21.551+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (3.0.3)
[2024-11-18T21:22:21.568+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth<3,>=1.6.3 in /home/***/.local/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvo7veikp1/requirements.txt (line 5)) (2.26.2)
[2024-11-18T21:22:21.589+0000] {process_utils.py:190} INFO - Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvo7veikp1/requirements.txt (line 5))
[2024-11-18T21:22:21.590+0000] {process_utils.py:190} INFO -   Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
[2024-11-18T21:22:21.619+0000] {process_utils.py:190} INFO - Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvo7veikp1/requirements.txt (line 5))
[2024-11-18T21:22:21.620+0000] {process_utils.py:190} INFO -   Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
[2024-11-18T21:22:21.760+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvo7veikp1/requirements.txt (line 2)) (5.0.1)
[2024-11-18T21:22:21.771+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvo7veikp1/requirements.txt (line 5)) (5.3.2)
[2024-11-18T21:22:21.771+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvo7veikp1/requirements.txt (line 5)) (0.3.0)
[2024-11-18T21:22:21.772+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvo7veikp1/requirements.txt (line 5)) (4.9)
[2024-11-18T21:22:21.779+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvo7veikp1/requirements.txt (line 5)) (1.3.1)
[2024-11-18T21:22:21.907+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvo7veikp1/requirements.txt (line 5)) (0.5.1)
[2024-11-18T21:22:21.915+0000] {process_utils.py:190} INFO - Requirement already satisfied: oauthlib>=3.0.0 in /home/***/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvo7veikp1/requirements.txt (line 5)) (3.2.2)
[2024-11-18T21:22:21.947+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T21:22:21.948+0000] {process_utils.py:190} INFO - Using cached mlflow-2.10.2-py3-none-any.whl (19.5 MB)
[2024-11-18T21:22:21.968+0000] {process_utils.py:190} INFO - Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
[2024-11-18T21:22:22.471+0000] {process_utils.py:190} INFO - Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
[2024-11-18T21:22:22.472+0000] {process_utils.py:190} INFO - Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
[2024-11-18T21:22:22.473+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T21:22:22.485+0000] {process_utils.py:190} INFO - Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
[2024-11-18T21:22:22.486+0000] {process_utils.py:190} INFO - Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
[2024-11-18T21:22:22.487+0000] {process_utils.py:190} INFO - Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
[2024-11-18T21:22:22.488+0000] {process_utils.py:190} INFO - Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
[2024-11-18T21:22:22.489+0000] {process_utils.py:190} INFO - Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
[2024-11-18T21:22:22.495+0000] {process_utils.py:190} INFO - Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)
[2024-11-18T21:22:22.498+0000] {process_utils.py:190} INFO - Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
[2024-11-18T21:22:22.523+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-11-18T21:22:22.541+0000] {process_utils.py:190} INFO - Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
[2024-11-18T21:22:22.542+0000] {process_utils.py:190} INFO - Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
[2024-11-18T21:22:22.543+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T21:22:22.544+0000] {process_utils.py:190} INFO - Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
[2024-11-18T21:22:22.551+0000] {process_utils.py:190} INFO - Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
[2024-11-18T21:22:22.552+0000] {process_utils.py:190} INFO - Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
[2024-11-18T21:22:22.556+0000] {process_utils.py:190} INFO - Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[2024-11-18T21:22:22.557+0000] {process_utils.py:190} INFO - Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
[2024-11-18T21:22:22.558+0000] {process_utils.py:190} INFO - Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
[2024-11-18T21:22:24.663+0000] {process_utils.py:190} INFO - Installing collected packages: libclang, flatbuffers, typing-extensions, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, querystring-parser, opt-einsum, numpy, keras, google-pasta, gast, entrypoints, astunparse, absl-py, h5py, botocore, s3transfer, google-auth-oauthlib, tensorboard, mlflow, boto3, tensorflow
[2024-11-18T21:22:24.905+0000] {process_utils.py:190} INFO -   Attempting uninstall: typing-extensions
[2024-11-18T21:22:24.907+0000] {process_utils.py:190} INFO -     Found existing installation: typing_extensions 4.9.0
[2024-11-18T21:22:24.907+0000] {process_utils.py:190} INFO -     Not uninstalling typing-extensions at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvo7veikp1
[2024-11-18T21:22:24.907+0000] {process_utils.py:190} INFO -     Can't uninstall 'typing_extensions'. No files were found to uninstall.
[2024-11-18T21:22:25.174+0000] {process_utils.py:190} INFO -   Attempting uninstall: numpy
[2024-11-18T21:22:25.175+0000] {process_utils.py:190} INFO -     Found existing installation: numpy 1.24.4
[2024-11-18T21:22:25.176+0000] {process_utils.py:190} INFO -     Not uninstalling numpy at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvo7veikp1
[2024-11-18T21:22:25.176+0000] {process_utils.py:190} INFO -     Can't uninstall 'numpy'. No files were found to uninstall.
[2024-11-18T21:22:26.855+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T21:22:26.856+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T21:22:26.856+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvo7veikp1
[2024-11-18T21:22:26.857+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T21:22:27.257+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T21:22:27.258+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T21:22:27.259+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvo7veikp1
[2024-11-18T21:22:27.259+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T21:22:27.280+0000] {process_utils.py:190} INFO -   Attempting uninstall: google-auth-oauthlib
[2024-11-18T21:22:27.281+0000] {process_utils.py:190} INFO -     Found existing installation: google-auth-oauthlib 1.2.0
[2024-11-18T21:22:27.281+0000] {process_utils.py:190} INFO -     Not uninstalling google-auth-oauthlib at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvo7veikp1
[2024-11-18T21:22:27.282+0000] {process_utils.py:190} INFO -     Can't uninstall 'google-auth-oauthlib'. No files were found to uninstall.
[2024-11-18T21:22:27.482+0000] {process_utils.py:190} INFO -   Attempting uninstall: mlflow
[2024-11-18T21:22:27.483+0000] {process_utils.py:190} INFO -     Found existing installation: mlflow 2.17.0
[2024-11-18T21:22:27.484+0000] {process_utils.py:190} INFO -     Not uninstalling mlflow at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvo7veikp1
[2024-11-18T21:22:27.484+0000] {process_utils.py:190} INFO -     Can't uninstall 'mlflow'. No files were found to uninstall.
[2024-11-18T21:22:28.054+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T21:22:28.055+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T21:22:28.056+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvo7veikp1
[2024-11-18T21:22:28.056+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T21:22:35.054+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T21:22:35.054+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T21:22:35.055+0000] {process_utils.py:190} INFO - azure-core 1.29.6 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:22:35.055+0000] {process_utils.py:190} INFO - azure-mgmt-keyvault 10.3.1 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:22:35.055+0000] {process_utils.py:190} INFO - azure-mgmt-network 27.0.0 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:22:35.056+0000] {process_utils.py:190} INFO - graphene 3.4 requires typing-extensions<5,>=4.7.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:22:35.056+0000] {process_utils.py:190} INFO - pydantic 2.5.3 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:22:35.057+0000] {process_utils.py:190} INFO - pydantic-core 2.14.6 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:22:35.057+0000] {process_utils.py:190} INFO - Successfully installed absl-py-2.1.0 astunparse-1.6.3 boto3-1.28.0 botocore-1.31.85 entrypoints-0.4 flatbuffers-24.3.25 gast-0.4.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 h5py-3.11.0 keras-2.13.1 libclang-18.1.1 mlflow-2.10.2 numpy-1.24.3 opt-einsum-3.4.0 querystring-parser-1.2.4 s3transfer-0.6.2 tensorboard-2.13.0 tensorboard-data-server-0.7.2 tensorflow-2.13.0 tensorflow-estimator-2.13.0 tensorflow-io-gcs-filesystem-0.34.0 typing-extensions-4.5.0
[2024-11-18T21:22:35.131+0000] {process_utils.py:190} INFO - 
[2024-11-18T21:22:35.132+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.3.1
[2024-11-18T21:22:35.132+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T21:22:35.388+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvo7veikp1/bin/python /tmp/venv-callv0jinp4x/script.py /tmp/venv-callv0jinp4x/script.in /tmp/venv-callv0jinp4x/script.out /tmp/venv-callv0jinp4x/string_args.txt /tmp/venv-callv0jinp4x/termination.log
[2024-11-18T21:22:35.392+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T21:22:36.357+0000] {process_utils.py:190} INFO - 2024-11-18 21:22:36.357552: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-11-18T21:22:36.358+0000] {process_utils.py:190} INFO - 2024-11-18 21:22:36.358615: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T21:22:36.379+0000] {process_utils.py:190} INFO - 2024-11-18 21:22:36.379005: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T21:22:36.379+0000] {process_utils.py:190} INFO - 2024-11-18 21:22:36.379274: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-11-18T21:22:36.380+0000] {process_utils.py:190} INFO - To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-11-18T21:22:36.883+0000] {process_utils.py:190} INFO - 2024-11-18 21:22:36.883188: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-11-18T21:22:37.943+0000] {process_utils.py:190} INFO - Epoch 1/10
[2024-11-18T21:22:38.934+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 3:35 - loss: 0.3947 41/575 [=>............................] - ETA: 0s - loss: 0.1941   84/575 [===>..........................] - ETA: 0s - loss: 0.1335124/575 [=====>........................] - ETA: 0s - loss: 0.1080195/575 [=========>....................] - ETA: 0s - loss: 0.0838273/575 [=============>................] - ETA: 0s - loss: 0.0696318/575 [===============>..............] - ETA: 0s - loss: 0.0640389/575 [===================>..........] - ETA: 0s - loss: 0.0574468/575 [=======================>......] - ETA: 0s - loss: 0.0518549/575 [===========================>..] - ETA: 0s - loss: 0.0475575/575 [==============================] - 1s 1ms/step - loss: 0.0463 - val_loss: 0.0075
[2024-11-18T21:22:38.934+0000] {process_utils.py:190} INFO - Epoch 2/10
[2024-11-18T21:22:39.401+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0255 87/575 [===>..........................] - ETA: 0s - loss: 0.0204169/575 [=======>......................] - ETA: 0s - loss: 0.0195253/575 [============>.................] - ETA: 0s - loss: 0.0188329/575 [================>.............] - ETA: 0s - loss: 0.0184413/575 [====================>.........] - ETA: 0s - loss: 0.0179488/575 [========================>.....] - ETA: 0s - loss: 0.0176551/575 [===========================>..] - ETA: 0s - loss: 0.0173575/575 [==============================] - 0s 812us/step - loss: 0.0172 - val_loss: 0.0059
[2024-11-18T21:22:39.402+0000] {process_utils.py:190} INFO - Epoch 3/10
[2024-11-18T21:22:39.856+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0154 76/575 [==>...........................] - ETA: 0s - loss: 0.0148154/575 [=======>......................] - ETA: 0s - loss: 0.0144229/575 [==========>...................] - ETA: 0s - loss: 0.0141308/575 [===============>..............] - ETA: 0s - loss: 0.0138384/575 [===================>..........] - ETA: 0s - loss: 0.0135460/575 [=======================>......] - ETA: 0s - loss: 0.0132541/575 [===========================>..] - ETA: 0s - loss: 0.0129575/575 [==============================] - 0s 789us/step - loss: 0.0128 - val_loss: 0.0044
[2024-11-18T21:22:39.856+0000] {process_utils.py:190} INFO - Epoch 4/10
[2024-11-18T21:22:40.303+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0101 82/575 [===>..........................] - ETA: 0s - loss: 0.0110159/575 [=======>......................] - ETA: 0s - loss: 0.0110233/575 [===========>..................] - ETA: 0s - loss: 0.0109312/575 [===============>..............] - ETA: 0s - loss: 0.0107390/575 [===================>..........] - ETA: 0s - loss: 0.0105467/575 [=======================>......] - ETA: 0s - loss: 0.0104545/575 [===========================>..] - ETA: 0s - loss: 0.0102575/575 [==============================] - 0s 778us/step - loss: 0.0102 - val_loss: 0.0037
[2024-11-18T21:22:40.304+0000] {process_utils.py:190} INFO - Epoch 5/10
[2024-11-18T21:22:40.739+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0092 81/575 [===>..........................] - ETA: 0s - loss: 0.0092156/575 [=======>......................] - ETA: 0s - loss: 0.0092238/575 [===========>..................] - ETA: 0s - loss: 0.0091319/575 [===============>..............] - ETA: 0s - loss: 0.0090402/575 [===================>..........] - ETA: 0s - loss: 0.0089476/575 [=======================>......] - ETA: 0s - loss: 0.0088559/575 [============================>.] - ETA: 0s - loss: 0.0088575/575 [==============================] - 0s 757us/step - loss: 0.0087 - val_loss: 0.0033
[2024-11-18T21:22:40.740+0000] {process_utils.py:190} INFO - Epoch 6/10
[2024-11-18T21:22:41.156+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0080 86/575 [===>..........................] - ETA: 0s - loss: 0.0083171/575 [=======>......................] - ETA: 0s - loss: 0.0082260/575 [============>.................] - ETA: 0s - loss: 0.0080345/575 [=================>............] - ETA: 0s - loss: 0.0079428/575 [=====================>........] - ETA: 0s - loss: 0.0079511/575 [=========================>....] - ETA: 0s - loss: 0.0078575/575 [==============================] - 0s 724us/step - loss: 0.0078 - val_loss: 0.0026
[2024-11-18T21:22:41.156+0000] {process_utils.py:190} INFO - Epoch 7/10
[2024-11-18T21:22:41.588+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0089 83/575 [===>..........................] - ETA: 0s - loss: 0.0073166/575 [=======>......................] - ETA: 0s - loss: 0.0074245/575 [===========>..................] - ETA: 0s - loss: 0.0075330/575 [================>.............] - ETA: 0s - loss: 0.0074403/575 [====================>.........] - ETA: 0s - loss: 0.0073490/575 [========================>.....] - ETA: 0s - loss: 0.0073570/575 [============================>.] - ETA: 0s - loss: 0.0072575/575 [==============================] - 0s 751us/step - loss: 0.0072 - val_loss: 0.0028
[2024-11-18T21:22:41.589+0000] {process_utils.py:190} INFO - Epoch 8/10
[2024-11-18T21:22:42.020+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0065 82/575 [===>..........................] - ETA: 0s - loss: 0.0073166/575 [=======>......................] - ETA: 0s - loss: 0.0072247/575 [===========>..................] - ETA: 0s - loss: 0.0071323/575 [===============>..............] - ETA: 0s - loss: 0.0070407/575 [====================>.........] - ETA: 0s - loss: 0.0070492/575 [========================>.....] - ETA: 0s - loss: 0.0070573/575 [============================>.] - ETA: 0s - loss: 0.0070575/575 [==============================] - 0s 751us/step - loss: 0.0070 - val_loss: 0.0023
[2024-11-18T21:22:42.021+0000] {process_utils.py:190} INFO - Epoch 9/10
[2024-11-18T21:22:42.473+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0069 83/575 [===>..........................] - ETA: 0s - loss: 0.0069167/575 [=======>......................] - ETA: 0s - loss: 0.0069246/575 [===========>..................] - ETA: 0s - loss: 0.0069324/575 [===============>..............] - ETA: 0s - loss: 0.0069406/575 [====================>.........] - ETA: 0s - loss: 0.0068463/575 [=======================>......] - ETA: 0s - loss: 0.0068540/575 [===========================>..] - ETA: 0s - loss: 0.0067575/575 [==============================] - 0s 786us/step - loss: 0.0067 - val_loss: 0.0021
[2024-11-18T21:22:42.473+0000] {process_utils.py:190} INFO - Epoch 10/10
[2024-11-18T21:22:42.902+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0065 82/575 [===>..........................] - ETA: 0s - loss: 0.0067167/575 [=======>......................] - ETA: 0s - loss: 0.0066247/575 [===========>..................] - ETA: 0s - loss: 0.0066324/575 [===============>..............] - ETA: 0s - loss: 0.0066410/575 [====================>.........] - ETA: 0s - loss: 0.0066495/575 [========================>.....] - ETA: 0s - loss: 0.0065575/575 [==============================] - 0s 745us/step - loss: 0.0066 - val_loss: 0.0024
[2024-11-18T21:22:43.280+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 28s111/719 [===>..........................] - ETA: 0s 229/719 [========>.....................] - ETA: 0s338/719 [=============>................] - ETA: 0s452/719 [=================>............] - ETA: 0s573/719 [======================>.......] - ETA: 0s682/719 [===========================>..] - ETA: 0s719/719 [==============================] - 0s 444us/step
[2024-11-18T21:22:43.831+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 7s108/719 [===>..........................] - ETA: 0s217/719 [========>.....................] - ETA: 0s325/719 [============>.................] - ETA: 0s424/719 [================>.............] - ETA: 0s541/719 [=====================>........] - ETA: 0s656/719 [==========================>...] - ETA: 0s719/719 [==============================] - 0s 457us/step
[2024-11-18T21:22:43.901+0000] {process_utils.py:190} INFO - 2024/11/18 21:22:43 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.
[2024-11-18T21:22:44.229+0000] {process_utils.py:190} INFO - [[34m2024-11-18T21:22:44.228+0000[0m] {[34mbuilder_impl.py:[0m804} INFO[0m - Assets written to: /tmp/tmpnq9_k8fj/model/data/model/assets[0m
[2024-11-18T21:22:46.762+0000] {process_utils.py:190} INFO - /tmp/venvo7veikp1/lib/python3.8/site-packages/_distutils_hack/__init__.py:33 UserWarning: Setuptools is replacing distutils.
[2024-11-18T21:22:46.778+0000] {process_utils.py:190} INFO - [[34m2024-11-18T21:22:46.777+0000[0m] {[34mcredentials.py:[0m1124} INFO[0m - Found credentials in environment variables.[0m
[2024-11-18T21:22:46.893+0000] {process_utils.py:190} INFO - Registered model 'spotify_model_prod' already exists. Creating a new version of this model...
[2024-11-18T21:22:46.893+0000] {process_utils.py:190} INFO - 2024/11/18 21:22:46 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: spotify_model_prod, version 16
[2024-11-18T21:22:46.894+0000] {process_utils.py:190} INFO - Created version '16' of model 'spotify_model_prod'.
[2024-11-18T21:22:46.894+0000] {process_utils.py:190} INFO - /tmp/venvo7veikp1/lib/python3.8/site-packages/keras/src/engine/training.py:3000 UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
[2024-11-18T21:22:46.919+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-11-18T21:22:46.919+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callv0jinp4x/script.py", line 106, in <module>
[2024-11-18T21:22:46.919+0000] {process_utils.py:190} INFO -     res = train_challenger_model(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-18T21:22:46.919+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callv0jinp4x/script.py", line 99, in train_challenger_model
[2024-11-18T21:22:46.919+0000] {process_utils.py:190} INFO -     with open(embeddings_path, 'w') as f:
[2024-11-18T21:22:46.920+0000] {process_utils.py:190} INFO - FileNotFoundError: [Errno 2] No such file or directory: 'data_info/song_embeddings.json'
[2024-11-18T21:22:47.818+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
[Errno 2] No such file or directory: 'data_info/song_embeddings.json'
[2024-11-18T21:22:47.820+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=spotify_retrain_challenge_model_v3, task_id=train_challenger_model, execution_date=20241118T211519, start_date=20241118T212218, end_date=20241118T212247
[2024-11-18T21:22:47.826+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 130 for task train_challenger_model (Process returned non-zero exit status 1.
[Errno 2] No such file or directory: 'data_info/song_embeddings.json'; 2912)
[2024-11-18T21:22:47.849+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-18T21:22:47.860+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
