[2024-11-18T17:34:31.708+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_recommender_dag_v3.train_embedding_model manual__2024-11-18T17:27:40.616035+00:00 [queued]>
[2024-11-18T17:34:31.713+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_recommender_dag_v3.train_embedding_model manual__2024-11-18T17:27:40.616035+00:00 [queued]>
[2024-11-18T17:34:31.713+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-11-18T17:34:31.720+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_embedding_model> on 2024-11-18 17:27:40.616035+00:00
[2024-11-18T17:34:31.722+0000] {standard_task_runner.py:60} INFO - Started process 264 to run task
[2024-11-18T17:34:31.724+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_recommender_dag_v3', 'train_embedding_model', 'manual__2024-11-18T17:27:40.616035+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/music_process.py', '--cfg-path', '/tmp/tmpw75sxxc2']
[2024-11-18T17:34:31.726+0000] {standard_task_runner.py:88} INFO - Job 35: Subtask train_embedding_model
[2024-11-18T17:34:31.755+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_recommender_dag_v3.train_embedding_model manual__2024-11-18T17:27:40.616035+00:00 [running]> on host 98017b53a184
[2024-11-18T17:34:31.794+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_recommender_dag_v3' AIRFLOW_CTX_TASK_ID='train_embedding_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T17:27:40.616035+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T17:27:40.616035+00:00'
[2024-11-18T17:34:31.795+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv23y7jj7r --system-site-packages --python=python
[2024-11-18T17:34:31.799+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T17:34:32.117+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 111ms
[2024-11-18T17:34:32.117+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venv23y7jj7r, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T17:34:32.117+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T17:34:32.118+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-11-18T17:34:32.118+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T17:34:32.136+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv23y7jj7r/bin/pip install -r /tmp/venv23y7jj7r/requirements.txt
[2024-11-18T17:34:32.139+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T17:34:33.055+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venv23y7jj7r/requirements.txt (line 1))
[2024-11-18T17:34:33.056+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T17:34:33.093+0000] {process_utils.py:190} INFO - Collecting mlflow==2.10.2 (from -r /tmp/venv23y7jj7r/requirements.txt (line 2))
[2024-11-18T17:34:33.095+0000] {process_utils.py:190} INFO -   Using cached mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
[2024-11-18T17:34:33.096+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv23y7jj7r/requirements.txt (line 3)) (2.0.3)
[2024-11-18T17:34:33.192+0000] {process_utils.py:190} INFO - Collecting tensorflow==2.13.0 (from -r /tmp/venv23y7jj7r/requirements.txt (line 4))
[2024-11-18T17:34:33.193+0000] {process_utils.py:190} INFO -   Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
[2024-11-18T17:34:33.713+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venv23y7jj7r/requirements.txt (line 1))
[2024-11-18T17:34:33.714+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T17:34:33.715+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venv23y7jj7r/requirements.txt (line 1)) (0.10.0)
[2024-11-18T17:34:33.737+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venv23y7jj7r/requirements.txt (line 1))
[2024-11-18T17:34:33.738+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T17:34:33.792+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (8.1.7)
[2024-11-18T17:34:33.793+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (3.1.0)
[2024-11-18T17:34:33.808+0000] {process_utils.py:190} INFO - Collecting entrypoints<1 (from mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2))
[2024-11-18T17:34:33.809+0000] {process_utils.py:190} INFO -   Using cached entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
[2024-11-18T17:34:33.810+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=2.1.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (3.1.43)
[2024-11-18T17:34:33.811+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (6.0.1)
[2024-11-18T17:34:33.811+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<5,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (4.25.2)
[2024-11-18T17:34:33.811+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz<2024 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T17:34:33.812+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (2.31.0)
[2024-11-18T17:34:33.812+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (23.2)
[2024-11-18T17:34:33.813+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (6.11.0)
[2024-11-18T17:34:33.813+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (0.4.4)
[2024-11-18T17:34:33.814+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (1.13.1)
[2024-11-18T17:34:33.814+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (7.0.0)
[2024-11-18T17:34:33.815+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (2.2.5)
[2024-11-18T17:34:33.815+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (1.24.4)
[2024-11-18T17:34:33.815+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (1.10.1)
[2024-11-18T17:34:33.832+0000] {process_utils.py:190} INFO - Collecting querystring-parser<2 (from mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2))
[2024-11-18T17:34:33.833+0000] {process_utils.py:190} INFO -   Using cached querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
[2024-11-18T17:34:33.834+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (1.4.51)
[2024-11-18T17:34:33.834+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (1.3.2)
[2024-11-18T17:34:33.835+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow<16,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (14.0.2)
[2024-11-18T17:34:33.835+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (3.5.2)
[2024-11-18T17:34:33.836+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (3.7.5)
[2024-11-18T17:34:33.836+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<22 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (21.2.0)
[2024-11-18T17:34:33.837+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (3.1.3)
[2024-11-18T17:34:33.889+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venv23y7jj7r/requirements.txt (line 3)) (2.8.2)
[2024-11-18T17:34:33.889+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venv23y7jj7r/requirements.txt (line 3)) (2023.4)
[2024-11-18T17:34:33.919+0000] {process_utils.py:190} INFO - Collecting absl-py>=1.0.0 (from tensorflow==2.13.0->-r /tmp/venv23y7jj7r/requirements.txt (line 4))
[2024-11-18T17:34:33.921+0000] {process_utils.py:190} INFO -   Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
[2024-11-18T17:34:33.937+0000] {process_utils.py:190} INFO - Collecting astunparse>=1.6.0 (from tensorflow==2.13.0->-r /tmp/venv23y7jj7r/requirements.txt (line 4))
[2024-11-18T17:34:33.939+0000] {process_utils.py:190} INFO -   Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
[2024-11-18T17:34:33.957+0000] {process_utils.py:190} INFO - Collecting flatbuffers>=23.1.21 (from tensorflow==2.13.0->-r /tmp/venv23y7jj7r/requirements.txt (line 4))
[2024-11-18T17:34:33.959+0000] {process_utils.py:190} INFO -   Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
[2024-11-18T17:34:33.979+0000] {process_utils.py:190} INFO - Collecting gast<=0.4.0,>=0.2.1 (from tensorflow==2.13.0->-r /tmp/venv23y7jj7r/requirements.txt (line 4))
[2024-11-18T17:34:33.980+0000] {process_utils.py:190} INFO -   Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
[2024-11-18T17:34:33.997+0000] {process_utils.py:190} INFO - Collecting google-pasta>=0.1.1 (from tensorflow==2.13.0->-r /tmp/venv23y7jj7r/requirements.txt (line 4))
[2024-11-18T17:34:33.998+0000] {process_utils.py:190} INFO -   Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
[2024-11-18T17:34:33.999+0000] {process_utils.py:190} INFO - Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv23y7jj7r/requirements.txt (line 4)) (1.60.0)
[2024-11-18T17:34:34.037+0000] {process_utils.py:190} INFO - Collecting h5py>=2.9.0 (from tensorflow==2.13.0->-r /tmp/venv23y7jj7r/requirements.txt (line 4))
[2024-11-18T17:34:34.039+0000] {process_utils.py:190} INFO -   Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
[2024-11-18T17:34:34.065+0000] {process_utils.py:190} INFO - Collecting keras<2.14,>=2.13.1 (from tensorflow==2.13.0->-r /tmp/venv23y7jj7r/requirements.txt (line 4))
[2024-11-18T17:34:34.067+0000] {process_utils.py:190} INFO -   Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
[2024-11-18T17:34:34.089+0000] {process_utils.py:190} INFO - Collecting libclang>=13.0.0 (from tensorflow==2.13.0->-r /tmp/venv23y7jj7r/requirements.txt (line 4))
[2024-11-18T17:34:34.090+0000] {process_utils.py:190} INFO -   Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
[2024-11-18T17:34:34.233+0000] {process_utils.py:190} INFO - Collecting numpy<2 (from mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2))
[2024-11-18T17:34:34.235+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-11-18T17:34:34.253+0000] {process_utils.py:190} INFO - Collecting opt-einsum>=2.3.2 (from tensorflow==2.13.0->-r /tmp/venv23y7jj7r/requirements.txt (line 4))
[2024-11-18T17:34:34.254+0000] {process_utils.py:190} INFO -   Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
[2024-11-18T17:34:34.255+0000] {process_utils.py:190} INFO - Requirement already satisfied: setuptools in /tmp/venv23y7jj7r/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv23y7jj7r/requirements.txt (line 4)) (69.0.2)
[2024-11-18T17:34:34.256+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.12.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv23y7jj7r/requirements.txt (line 4)) (1.16.0)
[2024-11-18T17:34:34.281+0000] {process_utils.py:190} INFO - Collecting tensorboard<2.14,>=2.13 (from tensorflow==2.13.0->-r /tmp/venv23y7jj7r/requirements.txt (line 4))
[2024-11-18T17:34:34.282+0000] {process_utils.py:190} INFO -   Using cached tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T17:34:34.301+0000] {process_utils.py:190} INFO - Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow==2.13.0->-r /tmp/venv23y7jj7r/requirements.txt (line 4))
[2024-11-18T17:34:34.302+0000] {process_utils.py:190} INFO -   Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
[2024-11-18T17:34:34.305+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.1.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv23y7jj7r/requirements.txt (line 4)) (2.4.0)
[2024-11-18T17:34:34.326+0000] {process_utils.py:190} INFO - Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow==2.13.0->-r /tmp/venv23y7jj7r/requirements.txt (line 4))
[2024-11-18T17:34:34.327+0000] {process_utils.py:190} INFO -   Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
[2024-11-18T17:34:34.328+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt>=1.11.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv23y7jj7r/requirements.txt (line 4)) (1.16.0)
[2024-11-18T17:34:34.381+0000] {process_utils.py:190} INFO - Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow==2.13.0->-r /tmp/venv23y7jj7r/requirements.txt (line 4))
[2024-11-18T17:34:34.382+0000] {process_utils.py:190} INFO -   Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
[2024-11-18T17:34:34.389+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (1.3.0)
[2024-11-18T17:34:34.393+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (5.13.0)
[2024-11-18T17:34:34.396+0000] {process_utils.py:190} INFO - Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venv23y7jj7r/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow==2.13.0->-r /tmp/venv23y7jj7r/requirements.txt (line 4)) (0.42.0)
[2024-11-18T17:34:34.401+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venv23y7jj7r/requirements.txt (line 1)) (1.26.18)
[2024-11-18T17:34:34.415+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (2.2.3)
[2024-11-18T17:34:34.415+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (2.1.2)
[2024-11-18T17:34:34.431+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (4.0.11)
[2024-11-18T17:34:34.462+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (3.17.0)
[2024-11-18T17:34:34.465+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (2.1.3)
[2024-11-18T17:34:34.487+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (1.1.1)
[2024-11-18T17:34:34.487+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (0.12.1)
[2024-11-18T17:34:34.488+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (4.54.1)
[2024-11-18T17:34:34.488+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (1.4.7)
[2024-11-18T17:34:34.496+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (10.4.0)
[2024-11-18T17:34:34.497+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (3.1.1)
[2024-11-18T17:34:34.537+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (3.3.2)
[2024-11-18T17:34:34.538+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (3.6)
[2024-11-18T17:34:34.538+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (2023.11.17)
[2024-11-18T17:34:34.669+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (1.4.2)
[2024-11-18T17:34:34.675+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (3.5.0)
[2024-11-18T17:34:34.739+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (3.0.3)
[2024-11-18T17:34:34.757+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth<3,>=1.6.3 in /home/***/.local/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv23y7jj7r/requirements.txt (line 4)) (2.26.2)
[2024-11-18T17:34:34.776+0000] {process_utils.py:190} INFO - Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv23y7jj7r/requirements.txt (line 4))
[2024-11-18T17:34:34.777+0000] {process_utils.py:190} INFO -   Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
[2024-11-18T17:34:34.805+0000] {process_utils.py:190} INFO - Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv23y7jj7r/requirements.txt (line 4))
[2024-11-18T17:34:34.807+0000] {process_utils.py:190} INFO -   Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
[2024-11-18T17:34:34.937+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venv23y7jj7r/requirements.txt (line 2)) (5.0.1)
[2024-11-18T17:34:34.947+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv23y7jj7r/requirements.txt (line 4)) (5.3.2)
[2024-11-18T17:34:34.948+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv23y7jj7r/requirements.txt (line 4)) (0.3.0)
[2024-11-18T17:34:34.949+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv23y7jj7r/requirements.txt (line 4)) (4.9)
[2024-11-18T17:34:34.954+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv23y7jj7r/requirements.txt (line 4)) (1.3.1)
[2024-11-18T17:34:35.085+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv23y7jj7r/requirements.txt (line 4)) (0.5.1)
[2024-11-18T17:34:35.092+0000] {process_utils.py:190} INFO - Requirement already satisfied: oauthlib>=3.0.0 in /home/***/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv23y7jj7r/requirements.txt (line 4)) (3.2.2)
[2024-11-18T17:34:35.125+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T17:34:35.126+0000] {process_utils.py:190} INFO - Using cached mlflow-2.10.2-py3-none-any.whl (19.5 MB)
[2024-11-18T17:34:35.144+0000] {process_utils.py:190} INFO - Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
[2024-11-18T17:34:35.617+0000] {process_utils.py:190} INFO - Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
[2024-11-18T17:34:35.618+0000] {process_utils.py:190} INFO - Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
[2024-11-18T17:34:35.619+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T17:34:35.630+0000] {process_utils.py:190} INFO - Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
[2024-11-18T17:34:35.631+0000] {process_utils.py:190} INFO - Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
[2024-11-18T17:34:35.632+0000] {process_utils.py:190} INFO - Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
[2024-11-18T17:34:35.633+0000] {process_utils.py:190} INFO - Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
[2024-11-18T17:34:35.641+0000] {process_utils.py:190} INFO - Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
[2024-11-18T17:34:35.642+0000] {process_utils.py:190} INFO - Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)
[2024-11-18T17:34:35.644+0000] {process_utils.py:190} INFO - Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
[2024-11-18T17:34:35.667+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-11-18T17:34:35.684+0000] {process_utils.py:190} INFO - Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
[2024-11-18T17:34:35.685+0000] {process_utils.py:190} INFO - Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
[2024-11-18T17:34:35.686+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T17:34:35.687+0000] {process_utils.py:190} INFO - Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
[2024-11-18T17:34:35.693+0000] {process_utils.py:190} INFO - Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
[2024-11-18T17:34:35.695+0000] {process_utils.py:190} INFO - Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
[2024-11-18T17:34:35.698+0000] {process_utils.py:190} INFO - Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[2024-11-18T17:34:35.705+0000] {process_utils.py:190} INFO - Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
[2024-11-18T17:34:35.706+0000] {process_utils.py:190} INFO - Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
[2024-11-18T17:34:37.820+0000] {process_utils.py:190} INFO - Installing collected packages: libclang, flatbuffers, typing-extensions, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, querystring-parser, opt-einsum, numpy, keras, google-pasta, gast, entrypoints, astunparse, absl-py, h5py, botocore, s3transfer, google-auth-oauthlib, tensorboard, mlflow, boto3, tensorflow
[2024-11-18T17:34:38.064+0000] {process_utils.py:190} INFO -   Attempting uninstall: typing-extensions
[2024-11-18T17:34:38.065+0000] {process_utils.py:190} INFO -     Found existing installation: typing_extensions 4.9.0
[2024-11-18T17:34:38.066+0000] {process_utils.py:190} INFO -     Not uninstalling typing-extensions at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv23y7jj7r
[2024-11-18T17:34:38.068+0000] {process_utils.py:190} INFO -     Can't uninstall 'typing_extensions'. No files were found to uninstall.
[2024-11-18T17:34:38.318+0000] {process_utils.py:190} INFO -   Attempting uninstall: numpy
[2024-11-18T17:34:38.320+0000] {process_utils.py:190} INFO -     Found existing installation: numpy 1.24.4
[2024-11-18T17:34:38.321+0000] {process_utils.py:190} INFO -     Not uninstalling numpy at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv23y7jj7r
[2024-11-18T17:34:38.322+0000] {process_utils.py:190} INFO -     Can't uninstall 'numpy'. No files were found to uninstall.
[2024-11-18T17:34:39.977+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T17:34:39.978+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T17:34:39.979+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv23y7jj7r
[2024-11-18T17:34:39.979+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T17:34:40.375+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T17:34:40.377+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T17:34:40.377+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv23y7jj7r
[2024-11-18T17:34:40.377+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T17:34:40.399+0000] {process_utils.py:190} INFO -   Attempting uninstall: google-auth-oauthlib
[2024-11-18T17:34:40.400+0000] {process_utils.py:190} INFO -     Found existing installation: google-auth-oauthlib 1.2.0
[2024-11-18T17:34:40.400+0000] {process_utils.py:190} INFO -     Not uninstalling google-auth-oauthlib at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv23y7jj7r
[2024-11-18T17:34:40.400+0000] {process_utils.py:190} INFO -     Can't uninstall 'google-auth-oauthlib'. No files were found to uninstall.
[2024-11-18T17:34:40.597+0000] {process_utils.py:190} INFO -   Attempting uninstall: mlflow
[2024-11-18T17:34:40.598+0000] {process_utils.py:190} INFO -     Found existing installation: mlflow 2.17.0
[2024-11-18T17:34:40.599+0000] {process_utils.py:190} INFO -     Not uninstalling mlflow at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv23y7jj7r
[2024-11-18T17:34:40.599+0000] {process_utils.py:190} INFO -     Can't uninstall 'mlflow'. No files were found to uninstall.
[2024-11-18T17:34:41.150+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T17:34:41.150+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T17:34:41.151+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv23y7jj7r
[2024-11-18T17:34:41.151+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T17:34:48.451+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T17:34:48.452+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T17:34:48.452+0000] {process_utils.py:190} INFO - azure-core 1.29.6 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:34:48.452+0000] {process_utils.py:190} INFO - azure-mgmt-keyvault 10.3.1 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:34:48.453+0000] {process_utils.py:190} INFO - azure-mgmt-network 27.0.0 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:34:48.453+0000] {process_utils.py:190} INFO - graphene 3.4 requires typing-extensions<5,>=4.7.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:34:48.453+0000] {process_utils.py:190} INFO - pydantic 2.5.3 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:34:48.453+0000] {process_utils.py:190} INFO - pydantic-core 2.14.6 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:34:48.454+0000] {process_utils.py:190} INFO - Successfully installed absl-py-2.1.0 astunparse-1.6.3 boto3-1.28.0 botocore-1.31.85 entrypoints-0.4 flatbuffers-24.3.25 gast-0.4.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 h5py-3.11.0 keras-2.13.1 libclang-18.1.1 mlflow-2.10.2 numpy-1.24.3 opt-einsum-3.4.0 querystring-parser-1.2.4 s3transfer-0.6.2 tensorboard-2.13.0 tensorboard-data-server-0.7.2 tensorflow-2.13.0 tensorflow-estimator-2.13.0 tensorflow-io-gcs-filesystem-0.34.0 typing-extensions-4.5.0
[2024-11-18T17:34:48.526+0000] {process_utils.py:190} INFO - 
[2024-11-18T17:34:48.526+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.3.1
[2024-11-18T17:34:48.526+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T17:34:48.714+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv23y7jj7r/bin/python /tmp/venv-callhtu2y1vx/script.py /tmp/venv-callhtu2y1vx/script.in /tmp/venv-callhtu2y1vx/script.out /tmp/venv-callhtu2y1vx/string_args.txt /tmp/venv-callhtu2y1vx/termination.log
[2024-11-18T17:34:48.717+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T17:34:49.688+0000] {process_utils.py:190} INFO - 2024-11-18 17:34:49.688324: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-11-18T17:34:49.689+0000] {process_utils.py:190} INFO - 2024-11-18 17:34:49.689635: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T17:34:49.710+0000] {process_utils.py:190} INFO - 2024-11-18 17:34:49.709999: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T17:34:49.710+0000] {process_utils.py:190} INFO - 2024-11-18 17:34:49.710281: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-11-18T17:34:49.710+0000] {process_utils.py:190} INFO - To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-11-18T17:34:50.209+0000] {process_utils.py:190} INFO - 2024-11-18 17:34:50.209090: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-11-18T17:34:51.328+0000] {process_utils.py:190} INFO - 2024/11/18 17:34:51 INFO mlflow.tracking.fluent: Experiment with name 'Spotify Recommender' does not exist. Creating a new experiment.
[2024-11-18T17:34:51.736+0000] {process_utils.py:190} INFO - Epoch 1/10
[2024-11-18T17:34:52.557+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 2:44 - loss: 0.4474 58/575 [==>...........................] - ETA: 0s - loss: 0.1551  123/575 [=====>........................] - ETA: 0s - loss: 0.1053204/575 [=========>....................] - ETA: 0s - loss: 0.0806282/575 [=============>................] - ETA: 0s - loss: 0.0675358/575 [=================>............] - ETA: 0s - loss: 0.0591436/575 [=====================>........] - ETA: 0s - loss: 0.0529515/575 [=========================>....] - ETA: 0s - loss: 0.0482575/575 [==============================] - 1s 931us/step - loss: 0.0453 - val_loss: 0.0076
[2024-11-18T17:34:52.557+0000] {process_utils.py:190} INFO - Epoch 2/10
[2024-11-18T17:34:52.977+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0258 84/575 [===>..........................] - ETA: 0s - loss: 0.0196165/575 [=======>......................] - ETA: 0s - loss: 0.0193250/575 [============>.................] - ETA: 0s - loss: 0.0187335/575 [================>.............] - ETA: 0s - loss: 0.0181422/575 [=====================>........] - ETA: 0s - loss: 0.0175506/575 [=========================>....] - ETA: 0s - loss: 0.0172575/575 [==============================] - 0s 729us/step - loss: 0.0168 - val_loss: 0.0054
[2024-11-18T17:34:52.977+0000] {process_utils.py:190} INFO - Epoch 3/10
[2024-11-18T17:34:53.385+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0191 82/575 [===>..........................] - ETA: 0s - loss: 0.0137170/575 [=======>......................] - ETA: 0s - loss: 0.0135257/575 [============>.................] - ETA: 0s - loss: 0.0131345/575 [=================>............] - ETA: 0s - loss: 0.0129432/575 [=====================>........] - ETA: 0s - loss: 0.0126518/575 [==========================>...] - ETA: 0s - loss: 0.0124575/575 [==============================] - 0s 710us/step - loss: 0.0122 - val_loss: 0.0044
[2024-11-18T17:34:53.386+0000] {process_utils.py:190} INFO - Epoch 4/10
[2024-11-18T17:34:53.829+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0122 91/575 [===>..........................] - ETA: 0s - loss: 0.0107179/575 [========>.....................] - ETA: 0s - loss: 0.0105264/575 [============>.................] - ETA: 0s - loss: 0.0104349/575 [=================>............] - ETA: 0s - loss: 0.0103434/575 [=====================>........] - ETA: 0s - loss: 0.0102509/575 [=========================>....] - ETA: 0s - loss: 0.0101560/575 [============================>.] - ETA: 0s - loss: 0.0101575/575 [==============================] - 0s 772us/step - loss: 0.0100 - val_loss: 0.0037
[2024-11-18T17:34:53.830+0000] {process_utils.py:190} INFO - Epoch 5/10
[2024-11-18T17:34:54.290+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0082 74/575 [==>...........................] - ETA: 0s - loss: 0.0093148/575 [======>.......................] - ETA: 0s - loss: 0.0091214/575 [==========>...................] - ETA: 0s - loss: 0.0090294/575 [==============>...............] - ETA: 0s - loss: 0.0090374/575 [==================>...........] - ETA: 0s - loss: 0.0089451/575 [======================>.......] - ETA: 0s - loss: 0.0088529/575 [==========================>...] - ETA: 0s - loss: 0.0088575/575 [==============================] - 0s 800us/step - loss: 0.0088 - val_loss: 0.0034
[2024-11-18T17:34:54.290+0000] {process_utils.py:190} INFO - Epoch 6/10
[2024-11-18T17:34:54.717+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0066 85/575 [===>..........................] - ETA: 0s - loss: 0.0082167/575 [=======>......................] - ETA: 0s - loss: 0.0082251/575 [============>.................] - ETA: 0s - loss: 0.0081328/575 [================>.............] - ETA: 0s - loss: 0.0081410/575 [====================>.........] - ETA: 0s - loss: 0.0081493/575 [========================>.....] - ETA: 0s - loss: 0.0081575/575 [==============================] - 0s 741us/step - loss: 0.0081 - val_loss: 0.0033
[2024-11-18T17:34:54.717+0000] {process_utils.py:190} INFO - Epoch 7/10
[2024-11-18T17:34:55.178+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0091 83/575 [===>..........................] - ETA: 0s - loss: 0.0079165/575 [=======>......................] - ETA: 0s - loss: 0.0079245/575 [===========>..................] - ETA: 0s - loss: 0.0078324/575 [===============>..............] - ETA: 0s - loss: 0.0077403/575 [====================>.........] - ETA: 0s - loss: 0.0077476/575 [=======================>......] - ETA: 0s - loss: 0.0077547/575 [===========================>..] - ETA: 0s - loss: 0.0077575/575 [==============================] - 0s 803us/step - loss: 0.0077 - val_loss: 0.0029
[2024-11-18T17:34:55.179+0000] {process_utils.py:190} INFO - Epoch 8/10
[2024-11-18T17:34:55.653+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0061 71/575 [==>...........................] - ETA: 0s - loss: 0.0076142/575 [======>.......................] - ETA: 0s - loss: 0.0075214/575 [==========>...................] - ETA: 0s - loss: 0.0075285/575 [=============>................] - ETA: 0s - loss: 0.0074360/575 [=================>............] - ETA: 0s - loss: 0.0074434/575 [=====================>........] - ETA: 0s - loss: 0.0074507/575 [=========================>....] - ETA: 0s - loss: 0.0074575/575 [==============================] - 0s 824us/step - loss: 0.0074 - val_loss: 0.0027
[2024-11-18T17:34:55.653+0000] {process_utils.py:190} INFO - Epoch 9/10
[2024-11-18T17:34:56.093+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0065 83/575 [===>..........................] - ETA: 0s - loss: 0.0073162/575 [=======>......................] - ETA: 0s - loss: 0.0073239/575 [===========>..................] - ETA: 0s - loss: 0.0074319/575 [===============>..............] - ETA: 0s - loss: 0.0074402/575 [===================>..........] - ETA: 0s - loss: 0.0074481/575 [========================>.....] - ETA: 0s - loss: 0.0073560/575 [============================>.] - ETA: 0s - loss: 0.0073575/575 [==============================] - 0s 765us/step - loss: 0.0073 - val_loss: 0.0024
[2024-11-18T17:34:56.094+0000] {process_utils.py:190} INFO - Epoch 10/10
[2024-11-18T17:34:56.523+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0068 81/575 [===>..........................] - ETA: 0s - loss: 0.0072163/575 [=======>......................] - ETA: 0s - loss: 0.0071246/575 [===========>..................] - ETA: 0s - loss: 0.0071330/575 [================>.............] - ETA: 0s - loss: 0.0071412/575 [====================>.........] - ETA: 0s - loss: 0.0071492/575 [========================>.....] - ETA: 0s - loss: 0.0071573/575 [============================>.] - ETA: 0s - loss: 0.0071575/575 [==============================] - 0s 747us/step - loss: 0.0071 - val_loss: 0.0026
[2024-11-18T17:34:56.538+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-11-18T17:34:56.539+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callhtu2y1vx/script.py", line 75, in <module>
[2024-11-18T17:34:56.539+0000] {process_utils.py:190} INFO -     res = train_embedding_model(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-18T17:34:56.539+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callhtu2y1vx/script.py", line 70, in train_embedding_model
[2024-11-18T17:34:56.540+0000] {process_utils.py:190} INFO -     mlflow.keras.log_model(model, artifact_path="model", registered_model_name="spotify_embedding_model")
[2024-11-18T17:34:56.540+0000] {process_utils.py:190} INFO - AttributeError: module 'mlflow' has no attribute 'keras'
[2024-11-18T17:34:57.394+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
module 'mlflow' has no attribute 'keras'
[2024-11-18T17:34:57.396+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=spotify_recommender_dag_v3, task_id=train_embedding_model, execution_date=20241118T172740, start_date=20241118T173431, end_date=20241118T173457
[2024-11-18T17:34:57.421+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 35 for task train_embedding_model (Process returned non-zero exit status 1.
module 'mlflow' has no attribute 'keras'; 264)
[2024-11-18T17:34:57.441+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-18T17:34:57.451+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
