[2024-11-18T17:57:08.210+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_recommender_dag_v3.train_embedding_model manual__2024-11-18T17:57:07.325829+00:00 [queued]>
[2024-11-18T17:57:08.214+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_recommender_dag_v3.train_embedding_model manual__2024-11-18T17:57:07.325829+00:00 [queued]>
[2024-11-18T17:57:08.215+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-11-18T17:57:08.221+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_embedding_model> on 2024-11-18 17:57:07.325829+00:00
[2024-11-18T17:57:08.223+0000] {standard_task_runner.py:60} INFO - Started process 1812 to run task
[2024-11-18T17:57:08.225+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_recommender_dag_v3', 'train_embedding_model', 'manual__2024-11-18T17:57:07.325829+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/music_process.py', '--cfg-path', '/tmp/tmpefeul0yj']
[2024-11-18T17:57:08.226+0000] {standard_task_runner.py:88} INFO - Job 57: Subtask train_embedding_model
[2024-11-18T17:57:08.253+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_recommender_dag_v3.train_embedding_model manual__2024-11-18T17:57:07.325829+00:00 [running]> on host 98017b53a184
[2024-11-18T17:57:08.290+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_recommender_dag_v3' AIRFLOW_CTX_TASK_ID='train_embedding_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T17:57:07.325829+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T17:57:07.325829+00:00'
[2024-11-18T17:57:08.291+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvzt0n4jx1 --system-site-packages --python=python
[2024-11-18T17:57:08.295+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T17:57:08.622+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 119ms
[2024-11-18T17:57:08.622+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvzt0n4jx1, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T17:57:08.623+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T17:57:08.623+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-11-18T17:57:08.623+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T17:57:08.642+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvzt0n4jx1/bin/pip install -r /tmp/venvzt0n4jx1/requirements.txt
[2024-11-18T17:57:08.645+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T17:57:09.569+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venvzt0n4jx1/requirements.txt (line 1))
[2024-11-18T17:57:09.571+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T17:57:09.610+0000] {process_utils.py:190} INFO - Collecting mlflow==2.10.2 (from -r /tmp/venvzt0n4jx1/requirements.txt (line 2))
[2024-11-18T17:57:09.611+0000] {process_utils.py:190} INFO -   Using cached mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
[2024-11-18T17:57:09.613+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvzt0n4jx1/requirements.txt (line 3)) (2.0.3)
[2024-11-18T17:57:09.714+0000] {process_utils.py:190} INFO - Collecting tensorflow==2.13.0 (from -r /tmp/venvzt0n4jx1/requirements.txt (line 4))
[2024-11-18T17:57:09.715+0000] {process_utils.py:190} INFO -   Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
[2024-11-18T17:57:10.099+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 1))
[2024-11-18T17:57:10.100+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T17:57:10.101+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 1)) (0.10.0)
[2024-11-18T17:57:10.123+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 1))
[2024-11-18T17:57:10.124+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T17:57:10.172+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (8.1.7)
[2024-11-18T17:57:10.172+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (3.1.0)
[2024-11-18T17:57:10.188+0000] {process_utils.py:190} INFO - Collecting entrypoints<1 (from mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2))
[2024-11-18T17:57:10.189+0000] {process_utils.py:190} INFO -   Using cached entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
[2024-11-18T17:57:10.190+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=2.1.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (3.1.43)
[2024-11-18T17:57:10.191+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (6.0.1)
[2024-11-18T17:57:10.191+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<5,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (4.25.2)
[2024-11-18T17:57:10.191+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz<2024 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T17:57:10.192+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (2.31.0)
[2024-11-18T17:57:10.192+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (23.2)
[2024-11-18T17:57:10.193+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (6.11.0)
[2024-11-18T17:57:10.193+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (0.4.4)
[2024-11-18T17:57:10.194+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (1.13.1)
[2024-11-18T17:57:10.194+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (7.0.0)
[2024-11-18T17:57:10.194+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (2.2.5)
[2024-11-18T17:57:10.195+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (1.24.4)
[2024-11-18T17:57:10.195+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (1.10.1)
[2024-11-18T17:57:10.210+0000] {process_utils.py:190} INFO - Collecting querystring-parser<2 (from mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2))
[2024-11-18T17:57:10.212+0000] {process_utils.py:190} INFO -   Using cached querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
[2024-11-18T17:57:10.212+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (1.4.51)
[2024-11-18T17:57:10.213+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (1.3.2)
[2024-11-18T17:57:10.213+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow<16,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (14.0.2)
[2024-11-18T17:57:10.214+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (3.5.2)
[2024-11-18T17:57:10.214+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (3.7.5)
[2024-11-18T17:57:10.215+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<22 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (21.2.0)
[2024-11-18T17:57:10.215+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (3.1.3)
[2024-11-18T17:57:10.268+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvzt0n4jx1/requirements.txt (line 3)) (2.8.2)
[2024-11-18T17:57:10.269+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvzt0n4jx1/requirements.txt (line 3)) (2023.4)
[2024-11-18T17:57:10.303+0000] {process_utils.py:190} INFO - Collecting absl-py>=1.0.0 (from tensorflow==2.13.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 4))
[2024-11-18T17:57:10.305+0000] {process_utils.py:190} INFO -   Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
[2024-11-18T17:57:10.321+0000] {process_utils.py:190} INFO - Collecting astunparse>=1.6.0 (from tensorflow==2.13.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 4))
[2024-11-18T17:57:10.322+0000] {process_utils.py:190} INFO -   Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
[2024-11-18T17:57:10.341+0000] {process_utils.py:190} INFO - Collecting flatbuffers>=23.1.21 (from tensorflow==2.13.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 4))
[2024-11-18T17:57:10.342+0000] {process_utils.py:190} INFO -   Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
[2024-11-18T17:57:10.362+0000] {process_utils.py:190} INFO - Collecting gast<=0.4.0,>=0.2.1 (from tensorflow==2.13.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 4))
[2024-11-18T17:57:10.363+0000] {process_utils.py:190} INFO -   Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
[2024-11-18T17:57:10.380+0000] {process_utils.py:190} INFO - Collecting google-pasta>=0.1.1 (from tensorflow==2.13.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 4))
[2024-11-18T17:57:10.381+0000] {process_utils.py:190} INFO -   Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
[2024-11-18T17:57:10.382+0000] {process_utils.py:190} INFO - Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 4)) (1.60.0)
[2024-11-18T17:57:10.424+0000] {process_utils.py:190} INFO - Collecting h5py>=2.9.0 (from tensorflow==2.13.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 4))
[2024-11-18T17:57:10.425+0000] {process_utils.py:190} INFO -   Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
[2024-11-18T17:57:10.452+0000] {process_utils.py:190} INFO - Collecting keras<2.14,>=2.13.1 (from tensorflow==2.13.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 4))
[2024-11-18T17:57:10.453+0000] {process_utils.py:190} INFO -   Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
[2024-11-18T17:57:10.473+0000] {process_utils.py:190} INFO - Collecting libclang>=13.0.0 (from tensorflow==2.13.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 4))
[2024-11-18T17:57:10.474+0000] {process_utils.py:190} INFO -   Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
[2024-11-18T17:57:10.625+0000] {process_utils.py:190} INFO - Collecting numpy<2 (from mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2))
[2024-11-18T17:57:10.627+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-11-18T17:57:10.645+0000] {process_utils.py:190} INFO - Collecting opt-einsum>=2.3.2 (from tensorflow==2.13.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 4))
[2024-11-18T17:57:10.647+0000] {process_utils.py:190} INFO -   Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
[2024-11-18T17:57:10.648+0000] {process_utils.py:190} INFO - Requirement already satisfied: setuptools in /tmp/venvzt0n4jx1/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 4)) (69.0.2)
[2024-11-18T17:57:10.648+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.12.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 4)) (1.16.0)
[2024-11-18T17:57:10.679+0000] {process_utils.py:190} INFO - Collecting tensorboard<2.14,>=2.13 (from tensorflow==2.13.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 4))
[2024-11-18T17:57:10.680+0000] {process_utils.py:190} INFO -   Using cached tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T17:57:10.699+0000] {process_utils.py:190} INFO - Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow==2.13.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 4))
[2024-11-18T17:57:10.700+0000] {process_utils.py:190} INFO -   Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
[2024-11-18T17:57:10.701+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.1.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 4)) (2.4.0)
[2024-11-18T17:57:10.724+0000] {process_utils.py:190} INFO - Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow==2.13.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 4))
[2024-11-18T17:57:10.725+0000] {process_utils.py:190} INFO -   Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
[2024-11-18T17:57:10.726+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt>=1.11.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 4)) (1.16.0)
[2024-11-18T17:57:10.779+0000] {process_utils.py:190} INFO - Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow==2.13.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 4))
[2024-11-18T17:57:10.780+0000] {process_utils.py:190} INFO -   Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
[2024-11-18T17:57:10.787+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (1.3.0)
[2024-11-18T17:57:10.791+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (5.13.0)
[2024-11-18T17:57:10.793+0000] {process_utils.py:190} INFO - Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venvzt0n4jx1/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow==2.13.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 4)) (0.42.0)
[2024-11-18T17:57:10.798+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 1)) (1.26.18)
[2024-11-18T17:57:10.813+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (2.2.3)
[2024-11-18T17:57:10.814+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (2.1.2)
[2024-11-18T17:57:10.830+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (4.0.11)
[2024-11-18T17:57:10.864+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (3.17.0)
[2024-11-18T17:57:10.867+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (2.1.3)
[2024-11-18T17:57:10.888+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (1.1.1)
[2024-11-18T17:57:10.888+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (0.12.1)
[2024-11-18T17:57:10.889+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (4.54.1)
[2024-11-18T17:57:10.889+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (1.4.7)
[2024-11-18T17:57:10.900+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (10.4.0)
[2024-11-18T17:57:10.900+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (3.1.1)
[2024-11-18T17:57:10.944+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (3.3.2)
[2024-11-18T17:57:10.944+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (3.6)
[2024-11-18T17:57:10.945+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (2023.11.17)
[2024-11-18T17:57:11.145+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (1.4.2)
[2024-11-18T17:57:11.146+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (3.5.0)
[2024-11-18T17:57:11.226+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (3.0.3)
[2024-11-18T17:57:11.245+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth<3,>=1.6.3 in /home/***/.local/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 4)) (2.26.2)
[2024-11-18T17:57:11.265+0000] {process_utils.py:190} INFO - Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 4))
[2024-11-18T17:57:11.266+0000] {process_utils.py:190} INFO -   Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
[2024-11-18T17:57:11.298+0000] {process_utils.py:190} INFO - Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 4))
[2024-11-18T17:57:11.300+0000] {process_utils.py:190} INFO -   Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
[2024-11-18T17:57:11.440+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvzt0n4jx1/requirements.txt (line 2)) (5.0.1)
[2024-11-18T17:57:11.450+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 4)) (5.3.2)
[2024-11-18T17:57:11.451+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 4)) (0.3.0)
[2024-11-18T17:57:11.453+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 4)) (4.9)
[2024-11-18T17:57:11.459+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 4)) (1.3.1)
[2024-11-18T17:57:11.595+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 4)) (0.5.1)
[2024-11-18T17:57:11.602+0000] {process_utils.py:190} INFO - Requirement already satisfied: oauthlib>=3.0.0 in /home/***/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvzt0n4jx1/requirements.txt (line 4)) (3.2.2)
[2024-11-18T17:57:11.633+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T17:57:11.635+0000] {process_utils.py:190} INFO - Using cached mlflow-2.10.2-py3-none-any.whl (19.5 MB)
[2024-11-18T17:57:11.655+0000] {process_utils.py:190} INFO - Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
[2024-11-18T17:57:12.155+0000] {process_utils.py:190} INFO - Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
[2024-11-18T17:57:12.156+0000] {process_utils.py:190} INFO - Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
[2024-11-18T17:57:12.157+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T17:57:12.169+0000] {process_utils.py:190} INFO - Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
[2024-11-18T17:57:12.170+0000] {process_utils.py:190} INFO - Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
[2024-11-18T17:57:12.171+0000] {process_utils.py:190} INFO - Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
[2024-11-18T17:57:12.172+0000] {process_utils.py:190} INFO - Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
[2024-11-18T17:57:12.173+0000] {process_utils.py:190} INFO - Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
[2024-11-18T17:57:12.179+0000] {process_utils.py:190} INFO - Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)
[2024-11-18T17:57:12.182+0000] {process_utils.py:190} INFO - Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
[2024-11-18T17:57:12.206+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-11-18T17:57:12.224+0000] {process_utils.py:190} INFO - Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
[2024-11-18T17:57:12.225+0000] {process_utils.py:190} INFO - Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
[2024-11-18T17:57:12.226+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T17:57:12.227+0000] {process_utils.py:190} INFO - Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
[2024-11-18T17:57:12.234+0000] {process_utils.py:190} INFO - Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
[2024-11-18T17:57:12.236+0000] {process_utils.py:190} INFO - Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
[2024-11-18T17:57:12.240+0000] {process_utils.py:190} INFO - Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[2024-11-18T17:57:12.241+0000] {process_utils.py:190} INFO - Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
[2024-11-18T17:57:12.242+0000] {process_utils.py:190} INFO - Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
[2024-11-18T17:57:14.394+0000] {process_utils.py:190} INFO - Installing collected packages: libclang, flatbuffers, typing-extensions, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, querystring-parser, opt-einsum, numpy, keras, google-pasta, gast, entrypoints, astunparse, absl-py, h5py, botocore, s3transfer, google-auth-oauthlib, tensorboard, mlflow, boto3, tensorflow
[2024-11-18T17:57:14.649+0000] {process_utils.py:190} INFO -   Attempting uninstall: typing-extensions
[2024-11-18T17:57:14.652+0000] {process_utils.py:190} INFO -     Found existing installation: typing_extensions 4.9.0
[2024-11-18T17:57:14.653+0000] {process_utils.py:190} INFO -     Not uninstalling typing-extensions at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvzt0n4jx1
[2024-11-18T17:57:14.654+0000] {process_utils.py:190} INFO -     Can't uninstall 'typing_extensions'. No files were found to uninstall.
[2024-11-18T17:57:14.920+0000] {process_utils.py:190} INFO -   Attempting uninstall: numpy
[2024-11-18T17:57:14.921+0000] {process_utils.py:190} INFO -     Found existing installation: numpy 1.24.4
[2024-11-18T17:57:14.922+0000] {process_utils.py:190} INFO -     Not uninstalling numpy at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvzt0n4jx1
[2024-11-18T17:57:14.922+0000] {process_utils.py:190} INFO -     Can't uninstall 'numpy'. No files were found to uninstall.
[2024-11-18T17:57:16.578+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T17:57:16.578+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T17:57:16.579+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvzt0n4jx1
[2024-11-18T17:57:16.579+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T17:57:16.973+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T17:57:16.974+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T17:57:16.974+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvzt0n4jx1
[2024-11-18T17:57:16.975+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T17:57:16.995+0000] {process_utils.py:190} INFO -   Attempting uninstall: google-auth-oauthlib
[2024-11-18T17:57:16.996+0000] {process_utils.py:190} INFO -     Found existing installation: google-auth-oauthlib 1.2.0
[2024-11-18T17:57:16.996+0000] {process_utils.py:190} INFO -     Not uninstalling google-auth-oauthlib at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvzt0n4jx1
[2024-11-18T17:57:16.996+0000] {process_utils.py:190} INFO -     Can't uninstall 'google-auth-oauthlib'. No files were found to uninstall.
[2024-11-18T17:57:17.199+0000] {process_utils.py:190} INFO -   Attempting uninstall: mlflow
[2024-11-18T17:57:17.200+0000] {process_utils.py:190} INFO -     Found existing installation: mlflow 2.17.0
[2024-11-18T17:57:17.201+0000] {process_utils.py:190} INFO -     Not uninstalling mlflow at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvzt0n4jx1
[2024-11-18T17:57:17.201+0000] {process_utils.py:190} INFO -     Can't uninstall 'mlflow'. No files were found to uninstall.
[2024-11-18T17:57:17.752+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T17:57:17.753+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T17:57:17.753+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvzt0n4jx1
[2024-11-18T17:57:17.753+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T17:57:25.051+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T17:57:25.052+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T17:57:25.052+0000] {process_utils.py:190} INFO - azure-core 1.29.6 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:57:25.053+0000] {process_utils.py:190} INFO - azure-mgmt-keyvault 10.3.1 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:57:25.053+0000] {process_utils.py:190} INFO - azure-mgmt-network 27.0.0 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:57:25.053+0000] {process_utils.py:190} INFO - graphene 3.4 requires typing-extensions<5,>=4.7.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:57:25.054+0000] {process_utils.py:190} INFO - pydantic 2.5.3 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:57:25.054+0000] {process_utils.py:190} INFO - pydantic-core 2.14.6 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:57:25.054+0000] {process_utils.py:190} INFO - Successfully installed absl-py-2.1.0 astunparse-1.6.3 boto3-1.28.0 botocore-1.31.85 entrypoints-0.4 flatbuffers-24.3.25 gast-0.4.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 h5py-3.11.0 keras-2.13.1 libclang-18.1.1 mlflow-2.10.2 numpy-1.24.3 opt-einsum-3.4.0 querystring-parser-1.2.4 s3transfer-0.6.2 tensorboard-2.13.0 tensorboard-data-server-0.7.2 tensorflow-2.13.0 tensorflow-estimator-2.13.0 tensorflow-io-gcs-filesystem-0.34.0 typing-extensions-4.5.0
[2024-11-18T17:57:25.142+0000] {process_utils.py:190} INFO - 
[2024-11-18T17:57:25.142+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.3.1
[2024-11-18T17:57:25.143+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T17:57:25.350+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvzt0n4jx1/bin/python /tmp/venv-callf2yd6r4v/script.py /tmp/venv-callf2yd6r4v/script.in /tmp/venv-callf2yd6r4v/script.out /tmp/venv-callf2yd6r4v/string_args.txt /tmp/venv-callf2yd6r4v/termination.log
[2024-11-18T17:57:25.353+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T17:57:26.371+0000] {process_utils.py:190} INFO - 2024-11-18 17:57:26.371003: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-11-18T17:57:26.372+0000] {process_utils.py:190} INFO - 2024-11-18 17:57:26.372109: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T17:57:26.392+0000] {process_utils.py:190} INFO - 2024-11-18 17:57:26.392148: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T17:57:26.392+0000] {process_utils.py:190} INFO - 2024-11-18 17:57:26.392414: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-11-18T17:57:26.392+0000] {process_utils.py:190} INFO - To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-11-18T17:57:26.897+0000] {process_utils.py:190} INFO - 2024-11-18 17:57:26.897593: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-11-18T17:57:28.130+0000] {process_utils.py:190} INFO - Epoch 1/10
[2024-11-18T17:57:28.945+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 2:40 - loss: 0.3947 53/575 [=>............................] - ETA: 0s - loss: 0.1700  115/575 [=====>........................] - ETA: 0s - loss: 0.1158194/575 [=========>....................] - ETA: 0s - loss: 0.0879271/575 [=============>................] - ETA: 0s - loss: 0.0734346/575 [=================>............] - ETA: 0s - loss: 0.0639429/575 [=====================>........] - ETA: 0s - loss: 0.0566512/575 [=========================>....] - ETA: 0s - loss: 0.0512575/575 [==============================] - 1s 932us/step - loss: 0.0481 - val_loss: 0.0086
[2024-11-18T17:57:28.945+0000] {process_utils.py:190} INFO - Epoch 2/10
[2024-11-18T17:57:29.383+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0176 82/575 [===>..........................] - ETA: 0s - loss: 0.0198164/575 [=======>......................] - ETA: 0s - loss: 0.0194248/575 [===========>..................] - ETA: 0s - loss: 0.0188331/575 [================>.............] - ETA: 0s - loss: 0.0183405/575 [====================>.........] - ETA: 0s - loss: 0.0179486/575 [========================>.....] - ETA: 0s - loss: 0.0175570/575 [============================>.] - ETA: 0s - loss: 0.0170575/575 [==============================] - 0s 761us/step - loss: 0.0170 - val_loss: 0.0054
[2024-11-18T17:57:29.383+0000] {process_utils.py:190} INFO - Epoch 3/10
[2024-11-18T17:57:29.804+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0133 80/575 [===>..........................] - ETA: 0s - loss: 0.0143164/575 [=======>......................] - ETA: 0s - loss: 0.0140246/575 [===========>..................] - ETA: 0s - loss: 0.0137329/575 [================>.............] - ETA: 0s - loss: 0.0135413/575 [====================>.........] - ETA: 0s - loss: 0.0134496/575 [========================>.....] - ETA: 0s - loss: 0.0131575/575 [==============================] - 0s 731us/step - loss: 0.0129 - val_loss: 0.0047
[2024-11-18T17:57:29.805+0000] {process_utils.py:190} INFO - Epoch 4/10
[2024-11-18T17:57:30.230+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0122 86/575 [===>..........................] - ETA: 0s - loss: 0.0112169/575 [=======>......................] - ETA: 0s - loss: 0.0112253/575 [============>.................] - ETA: 0s - loss: 0.0110337/575 [================>.............] - ETA: 0s - loss: 0.0110416/575 [====================>.........] - ETA: 0s - loss: 0.0108500/575 [=========================>....] - ETA: 0s - loss: 0.0107575/575 [==============================] - 0s 739us/step - loss: 0.0106 - val_loss: 0.0039
[2024-11-18T17:57:30.230+0000] {process_utils.py:190} INFO - Epoch 5/10
[2024-11-18T17:57:30.649+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0091 85/575 [===>..........................] - ETA: 0s - loss: 0.0098169/575 [=======>......................] - ETA: 0s - loss: 0.0095254/575 [============>.................] - ETA: 0s - loss: 0.0093340/575 [================>.............] - ETA: 0s - loss: 0.0092424/575 [=====================>........] - ETA: 0s - loss: 0.0091510/575 [=========================>....] - ETA: 0s - loss: 0.0091575/575 [==============================] - 0s 728us/step - loss: 0.0090 - val_loss: 0.0033
[2024-11-18T17:57:30.649+0000] {process_utils.py:190} INFO - Epoch 6/10
[2024-11-18T17:57:31.072+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0073 84/575 [===>..........................] - ETA: 0s - loss: 0.0085168/575 [=======>......................] - ETA: 0s - loss: 0.0084252/575 [============>.................] - ETA: 0s - loss: 0.0083336/575 [================>.............] - ETA: 0s - loss: 0.0083421/575 [====================>.........] - ETA: 0s - loss: 0.0081504/575 [=========================>....] - ETA: 0s - loss: 0.0080575/575 [==============================] - 0s 735us/step - loss: 0.0080 - val_loss: 0.0029
[2024-11-18T17:57:31.072+0000] {process_utils.py:190} INFO - Epoch 7/10
[2024-11-18T17:57:31.490+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0078 86/575 [===>..........................] - ETA: 0s - loss: 0.0077169/575 [=======>......................] - ETA: 0s - loss: 0.0077256/575 [============>.................] - ETA: 0s - loss: 0.0077336/575 [================>.............] - ETA: 0s - loss: 0.0076422/575 [=====================>........] - ETA: 0s - loss: 0.0076506/575 [=========================>....] - ETA: 0s - loss: 0.0075575/575 [==============================] - 0s 727us/step - loss: 0.0075 - val_loss: 0.0027
[2024-11-18T17:57:31.490+0000] {process_utils.py:190} INFO - Epoch 8/10
[2024-11-18T17:57:31.909+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0062 82/575 [===>..........................] - ETA: 0s - loss: 0.0074169/575 [=======>......................] - ETA: 0s - loss: 0.0073253/575 [============>.................] - ETA: 0s - loss: 0.0073340/575 [================>.............] - ETA: 0s - loss: 0.0072426/575 [=====================>........] - ETA: 0s - loss: 0.0072509/575 [=========================>....] - ETA: 0s - loss: 0.0072575/575 [==============================] - 0s 729us/step - loss: 0.0072 - val_loss: 0.0026
[2024-11-18T17:57:31.910+0000] {process_utils.py:190} INFO - Epoch 9/10
[2024-11-18T17:57:32.333+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0087 82/575 [===>..........................] - ETA: 0s - loss: 0.0070168/575 [=======>......................] - ETA: 0s - loss: 0.0071253/575 [============>.................] - ETA: 0s - loss: 0.0070335/575 [================>.............] - ETA: 0s - loss: 0.0070419/575 [====================>.........] - ETA: 0s - loss: 0.0070496/575 [========================>.....] - ETA: 0s - loss: 0.0070575/575 [==============================] - 0s 736us/step - loss: 0.0070 - val_loss: 0.0027
[2024-11-18T17:57:32.333+0000] {process_utils.py:190} INFO - Epoch 10/10
[2024-11-18T17:57:32.770+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0074 84/575 [===>..........................] - ETA: 0s - loss: 0.0068159/575 [=======>......................] - ETA: 0s - loss: 0.0067233/575 [===========>..................] - ETA: 0s - loss: 0.0068318/575 [===============>..............] - ETA: 0s - loss: 0.0068398/575 [===================>..........] - ETA: 0s - loss: 0.0068480/575 [========================>.....] - ETA: 0s - loss: 0.0068563/575 [============================>.] - ETA: 0s - loss: 0.0068575/575 [==============================] - 0s 760us/step - loss: 0.0068 - val_loss: 0.0024
[2024-11-18T17:57:32.786+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-11-18T17:57:32.786+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callf2yd6r4v/script.py", line 89, in <module>
[2024-11-18T17:57:32.786+0000] {process_utils.py:190} INFO -     res = train_embedding_model(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-18T17:57:32.786+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callf2yd6r4v/script.py", line 72, in train_embedding_model
[2024-11-18T17:57:32.786+0000] {process_utils.py:190} INFO -     model.save(model_buffer, save_format='tf')
[2024-11-18T17:57:32.787+0000] {process_utils.py:190} INFO -   File "/tmp/venvzt0n4jx1/lib/python3.8/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
[2024-11-18T17:57:32.787+0000] {process_utils.py:190} INFO -     raise e.with_traceback(filtered_tb) from None
[2024-11-18T17:57:32.787+0000] {process_utils.py:190} INFO -   File "/tmp/venvzt0n4jx1/lib/python3.8/site-packages/keras/src/saving/legacy/saving_utils.py", line 368, in is_hdf5_filepath
[2024-11-18T17:57:32.787+0000] {process_utils.py:190} INFO -     filepath.endswith(".h5")
[2024-11-18T17:57:32.787+0000] {process_utils.py:190} INFO - AttributeError: '_io.BytesIO' object has no attribute 'endswith'
[2024-11-18T17:57:33.643+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
'_io.BytesIO' object has no attribute 'endswith'
[2024-11-18T17:57:33.645+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_recommender_dag_v3, task_id=train_embedding_model, execution_date=20241118T175707, start_date=20241118T175708, end_date=20241118T175733
[2024-11-18T17:57:33.652+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 57 for task train_embedding_model (Process returned non-zero exit status 1.
'_io.BytesIO' object has no attribute 'endswith'; 1812)
[2024-11-18T17:57:33.695+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-18T17:57:33.704+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
