[2024-11-18T17:35:34.093+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_recommender_dag_v3.train_embedding_model manual__2024-11-18T17:30:12.719699+00:00 [queued]>
[2024-11-18T17:35:34.098+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_recommender_dag_v3.train_embedding_model manual__2024-11-18T17:30:12.719699+00:00 [queued]>
[2024-11-18T17:35:34.098+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-11-18T17:35:34.105+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_embedding_model> on 2024-11-18 17:30:12.719699+00:00
[2024-11-18T17:35:34.108+0000] {standard_task_runner.py:60} INFO - Started process 1424 to run task
[2024-11-18T17:35:34.109+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_recommender_dag_v3', 'train_embedding_model', 'manual__2024-11-18T17:30:12.719699+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/music_process.py', '--cfg-path', '/tmp/tmp_wdwya76']
[2024-11-18T17:35:34.110+0000] {standard_task_runner.py:88} INFO - Job 41: Subtask train_embedding_model
[2024-11-18T17:35:34.137+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_recommender_dag_v3.train_embedding_model manual__2024-11-18T17:30:12.719699+00:00 [running]> on host 98017b53a184
[2024-11-18T17:35:34.179+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_recommender_dag_v3' AIRFLOW_CTX_TASK_ID='train_embedding_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T17:30:12.719699+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T17:30:12.719699+00:00'
[2024-11-18T17:35:34.180+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvol07uxyc --system-site-packages --python=python
[2024-11-18T17:35:34.183+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T17:35:34.536+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 120ms
[2024-11-18T17:35:34.537+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvol07uxyc, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T17:35:34.537+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T17:35:34.537+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-11-18T17:35:34.537+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T17:35:34.554+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvol07uxyc/bin/pip install -r /tmp/venvol07uxyc/requirements.txt
[2024-11-18T17:35:34.558+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T17:35:35.499+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venvol07uxyc/requirements.txt (line 1))
[2024-11-18T17:35:35.500+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T17:35:35.543+0000] {process_utils.py:190} INFO - Collecting mlflow==2.10.2 (from -r /tmp/venvol07uxyc/requirements.txt (line 2))
[2024-11-18T17:35:35.544+0000] {process_utils.py:190} INFO -   Using cached mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
[2024-11-18T17:35:35.545+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvol07uxyc/requirements.txt (line 3)) (2.0.3)
[2024-11-18T17:35:35.647+0000] {process_utils.py:190} INFO - Collecting tensorflow==2.13.0 (from -r /tmp/venvol07uxyc/requirements.txt (line 4))
[2024-11-18T17:35:35.648+0000] {process_utils.py:190} INFO -   Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
[2024-11-18T17:35:36.047+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venvol07uxyc/requirements.txt (line 1))
[2024-11-18T17:35:36.048+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T17:35:36.049+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venvol07uxyc/requirements.txt (line 1)) (0.10.0)
[2024-11-18T17:35:36.070+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venvol07uxyc/requirements.txt (line 1))
[2024-11-18T17:35:36.071+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T17:35:36.122+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (8.1.7)
[2024-11-18T17:35:36.123+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (3.1.0)
[2024-11-18T17:35:36.140+0000] {process_utils.py:190} INFO - Collecting entrypoints<1 (from mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2))
[2024-11-18T17:35:36.141+0000] {process_utils.py:190} INFO -   Using cached entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
[2024-11-18T17:35:36.142+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=2.1.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (3.1.43)
[2024-11-18T17:35:36.142+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (6.0.1)
[2024-11-18T17:35:36.143+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<5,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (4.25.2)
[2024-11-18T17:35:36.143+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz<2024 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T17:35:36.144+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (2.31.0)
[2024-11-18T17:35:36.144+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (23.2)
[2024-11-18T17:35:36.145+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (6.11.0)
[2024-11-18T17:35:36.145+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (0.4.4)
[2024-11-18T17:35:36.146+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (1.13.1)
[2024-11-18T17:35:36.147+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (7.0.0)
[2024-11-18T17:35:36.147+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (2.2.5)
[2024-11-18T17:35:36.148+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (1.24.4)
[2024-11-18T17:35:36.148+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (1.10.1)
[2024-11-18T17:35:36.163+0000] {process_utils.py:190} INFO - Collecting querystring-parser<2 (from mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2))
[2024-11-18T17:35:36.165+0000] {process_utils.py:190} INFO -   Using cached querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
[2024-11-18T17:35:36.165+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (1.4.51)
[2024-11-18T17:35:36.166+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (1.3.2)
[2024-11-18T17:35:36.166+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow<16,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (14.0.2)
[2024-11-18T17:35:36.167+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (3.5.2)
[2024-11-18T17:35:36.168+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (3.7.5)
[2024-11-18T17:35:36.168+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<22 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (21.2.0)
[2024-11-18T17:35:36.170+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (3.1.3)
[2024-11-18T17:35:36.222+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvol07uxyc/requirements.txt (line 3)) (2.8.2)
[2024-11-18T17:35:36.222+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvol07uxyc/requirements.txt (line 3)) (2023.4)
[2024-11-18T17:35:36.256+0000] {process_utils.py:190} INFO - Collecting absl-py>=1.0.0 (from tensorflow==2.13.0->-r /tmp/venvol07uxyc/requirements.txt (line 4))
[2024-11-18T17:35:36.257+0000] {process_utils.py:190} INFO -   Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
[2024-11-18T17:35:36.274+0000] {process_utils.py:190} INFO - Collecting astunparse>=1.6.0 (from tensorflow==2.13.0->-r /tmp/venvol07uxyc/requirements.txt (line 4))
[2024-11-18T17:35:36.276+0000] {process_utils.py:190} INFO -   Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
[2024-11-18T17:35:36.294+0000] {process_utils.py:190} INFO - Collecting flatbuffers>=23.1.21 (from tensorflow==2.13.0->-r /tmp/venvol07uxyc/requirements.txt (line 4))
[2024-11-18T17:35:36.295+0000] {process_utils.py:190} INFO -   Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
[2024-11-18T17:35:36.315+0000] {process_utils.py:190} INFO - Collecting gast<=0.4.0,>=0.2.1 (from tensorflow==2.13.0->-r /tmp/venvol07uxyc/requirements.txt (line 4))
[2024-11-18T17:35:36.317+0000] {process_utils.py:190} INFO -   Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
[2024-11-18T17:35:36.334+0000] {process_utils.py:190} INFO - Collecting google-pasta>=0.1.1 (from tensorflow==2.13.0->-r /tmp/venvol07uxyc/requirements.txt (line 4))
[2024-11-18T17:35:36.335+0000] {process_utils.py:190} INFO -   Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
[2024-11-18T17:35:36.336+0000] {process_utils.py:190} INFO - Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvol07uxyc/requirements.txt (line 4)) (1.60.0)
[2024-11-18T17:35:36.378+0000] {process_utils.py:190} INFO - Collecting h5py>=2.9.0 (from tensorflow==2.13.0->-r /tmp/venvol07uxyc/requirements.txt (line 4))
[2024-11-18T17:35:36.379+0000] {process_utils.py:190} INFO -   Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
[2024-11-18T17:35:36.406+0000] {process_utils.py:190} INFO - Collecting keras<2.14,>=2.13.1 (from tensorflow==2.13.0->-r /tmp/venvol07uxyc/requirements.txt (line 4))
[2024-11-18T17:35:36.408+0000] {process_utils.py:190} INFO -   Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
[2024-11-18T17:35:36.431+0000] {process_utils.py:190} INFO - Collecting libclang>=13.0.0 (from tensorflow==2.13.0->-r /tmp/venvol07uxyc/requirements.txt (line 4))
[2024-11-18T17:35:36.433+0000] {process_utils.py:190} INFO -   Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
[2024-11-18T17:35:36.585+0000] {process_utils.py:190} INFO - Collecting numpy<2 (from mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2))
[2024-11-18T17:35:36.587+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-11-18T17:35:36.603+0000] {process_utils.py:190} INFO - Collecting opt-einsum>=2.3.2 (from tensorflow==2.13.0->-r /tmp/venvol07uxyc/requirements.txt (line 4))
[2024-11-18T17:35:36.604+0000] {process_utils.py:190} INFO -   Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
[2024-11-18T17:35:36.605+0000] {process_utils.py:190} INFO - Requirement already satisfied: setuptools in /tmp/venvol07uxyc/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvol07uxyc/requirements.txt (line 4)) (69.0.2)
[2024-11-18T17:35:36.605+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.12.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvol07uxyc/requirements.txt (line 4)) (1.16.0)
[2024-11-18T17:35:36.635+0000] {process_utils.py:190} INFO - Collecting tensorboard<2.14,>=2.13 (from tensorflow==2.13.0->-r /tmp/venvol07uxyc/requirements.txt (line 4))
[2024-11-18T17:35:36.637+0000] {process_utils.py:190} INFO -   Using cached tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T17:35:36.659+0000] {process_utils.py:190} INFO - Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow==2.13.0->-r /tmp/venvol07uxyc/requirements.txt (line 4))
[2024-11-18T17:35:36.661+0000] {process_utils.py:190} INFO -   Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
[2024-11-18T17:35:36.661+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.1.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvol07uxyc/requirements.txt (line 4)) (2.4.0)
[2024-11-18T17:35:36.687+0000] {process_utils.py:190} INFO - Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow==2.13.0->-r /tmp/venvol07uxyc/requirements.txt (line 4))
[2024-11-18T17:35:36.688+0000] {process_utils.py:190} INFO -   Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
[2024-11-18T17:35:36.689+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt>=1.11.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvol07uxyc/requirements.txt (line 4)) (1.16.0)
[2024-11-18T17:35:36.744+0000] {process_utils.py:190} INFO - Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow==2.13.0->-r /tmp/venvol07uxyc/requirements.txt (line 4))
[2024-11-18T17:35:36.746+0000] {process_utils.py:190} INFO -   Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
[2024-11-18T17:35:36.752+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (1.3.0)
[2024-11-18T17:35:36.756+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (5.13.0)
[2024-11-18T17:35:36.759+0000] {process_utils.py:190} INFO - Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venvol07uxyc/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow==2.13.0->-r /tmp/venvol07uxyc/requirements.txt (line 4)) (0.42.0)
[2024-11-18T17:35:36.764+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venvol07uxyc/requirements.txt (line 1)) (1.26.18)
[2024-11-18T17:35:36.779+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (2.2.3)
[2024-11-18T17:35:36.779+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (2.1.2)
[2024-11-18T17:35:36.796+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (4.0.11)
[2024-11-18T17:35:36.833+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (3.17.0)
[2024-11-18T17:35:36.836+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (2.1.3)
[2024-11-18T17:35:36.858+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (1.1.1)
[2024-11-18T17:35:36.859+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (0.12.1)
[2024-11-18T17:35:36.859+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (4.54.1)
[2024-11-18T17:35:36.860+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (1.4.7)
[2024-11-18T17:35:36.872+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (10.4.0)
[2024-11-18T17:35:36.872+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (3.1.1)
[2024-11-18T17:35:36.920+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (3.3.2)
[2024-11-18T17:35:36.921+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (3.6)
[2024-11-18T17:35:36.921+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (2023.11.17)
[2024-11-18T17:35:37.047+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (1.4.2)
[2024-11-18T17:35:37.048+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (3.5.0)
[2024-11-18T17:35:37.124+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (3.0.3)
[2024-11-18T17:35:37.142+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth<3,>=1.6.3 in /home/***/.local/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvol07uxyc/requirements.txt (line 4)) (2.26.2)
[2024-11-18T17:35:37.162+0000] {process_utils.py:190} INFO - Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvol07uxyc/requirements.txt (line 4))
[2024-11-18T17:35:37.163+0000] {process_utils.py:190} INFO -   Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
[2024-11-18T17:35:37.195+0000] {process_utils.py:190} INFO - Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvol07uxyc/requirements.txt (line 4))
[2024-11-18T17:35:37.196+0000] {process_utils.py:190} INFO -   Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
[2024-11-18T17:35:37.331+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvol07uxyc/requirements.txt (line 2)) (5.0.1)
[2024-11-18T17:35:37.342+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvol07uxyc/requirements.txt (line 4)) (5.3.2)
[2024-11-18T17:35:37.342+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvol07uxyc/requirements.txt (line 4)) (0.3.0)
[2024-11-18T17:35:37.342+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvol07uxyc/requirements.txt (line 4)) (4.9)
[2024-11-18T17:35:37.349+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvol07uxyc/requirements.txt (line 4)) (1.3.1)
[2024-11-18T17:35:37.485+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvol07uxyc/requirements.txt (line 4)) (0.5.1)
[2024-11-18T17:35:37.493+0000] {process_utils.py:190} INFO - Requirement already satisfied: oauthlib>=3.0.0 in /home/***/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvol07uxyc/requirements.txt (line 4)) (3.2.2)
[2024-11-18T17:35:37.524+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T17:35:37.525+0000] {process_utils.py:190} INFO - Using cached mlflow-2.10.2-py3-none-any.whl (19.5 MB)
[2024-11-18T17:35:37.542+0000] {process_utils.py:190} INFO - Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
[2024-11-18T17:35:38.014+0000] {process_utils.py:190} INFO - Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
[2024-11-18T17:35:38.016+0000] {process_utils.py:190} INFO - Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
[2024-11-18T17:35:38.018+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T17:35:38.034+0000] {process_utils.py:190} INFO - Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
[2024-11-18T17:35:38.036+0000] {process_utils.py:190} INFO - Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
[2024-11-18T17:35:38.037+0000] {process_utils.py:190} INFO - Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
[2024-11-18T17:35:38.038+0000] {process_utils.py:190} INFO - Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
[2024-11-18T17:35:38.039+0000] {process_utils.py:190} INFO - Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
[2024-11-18T17:35:38.046+0000] {process_utils.py:190} INFO - Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)
[2024-11-18T17:35:38.049+0000] {process_utils.py:190} INFO - Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
[2024-11-18T17:35:38.076+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-11-18T17:35:38.094+0000] {process_utils.py:190} INFO - Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
[2024-11-18T17:35:38.096+0000] {process_utils.py:190} INFO - Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
[2024-11-18T17:35:38.097+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T17:35:38.098+0000] {process_utils.py:190} INFO - Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
[2024-11-18T17:35:38.105+0000] {process_utils.py:190} INFO - Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
[2024-11-18T17:35:38.107+0000] {process_utils.py:190} INFO - Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
[2024-11-18T17:35:38.111+0000] {process_utils.py:190} INFO - Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[2024-11-18T17:35:38.112+0000] {process_utils.py:190} INFO - Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
[2024-11-18T17:35:38.113+0000] {process_utils.py:190} INFO - Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
[2024-11-18T17:35:40.265+0000] {process_utils.py:190} INFO - Installing collected packages: libclang, flatbuffers, typing-extensions, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, querystring-parser, opt-einsum, numpy, keras, google-pasta, gast, entrypoints, astunparse, absl-py, h5py, botocore, s3transfer, google-auth-oauthlib, tensorboard, mlflow, boto3, tensorflow
[2024-11-18T17:35:40.541+0000] {process_utils.py:190} INFO -   Attempting uninstall: typing-extensions
[2024-11-18T17:35:40.543+0000] {process_utils.py:190} INFO -     Found existing installation: typing_extensions 4.9.0
[2024-11-18T17:35:40.543+0000] {process_utils.py:190} INFO -     Not uninstalling typing-extensions at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvol07uxyc
[2024-11-18T17:35:40.544+0000] {process_utils.py:190} INFO -     Can't uninstall 'typing_extensions'. No files were found to uninstall.
[2024-11-18T17:35:40.820+0000] {process_utils.py:190} INFO -   Attempting uninstall: numpy
[2024-11-18T17:35:40.821+0000] {process_utils.py:190} INFO -     Found existing installation: numpy 1.24.4
[2024-11-18T17:35:40.822+0000] {process_utils.py:190} INFO -     Not uninstalling numpy at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvol07uxyc
[2024-11-18T17:35:40.822+0000] {process_utils.py:190} INFO -     Can't uninstall 'numpy'. No files were found to uninstall.
[2024-11-18T17:35:42.509+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T17:35:42.510+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T17:35:42.510+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvol07uxyc
[2024-11-18T17:35:42.510+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T17:35:42.908+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T17:35:42.909+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T17:35:42.910+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvol07uxyc
[2024-11-18T17:35:42.910+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T17:35:42.931+0000] {process_utils.py:190} INFO -   Attempting uninstall: google-auth-oauthlib
[2024-11-18T17:35:42.932+0000] {process_utils.py:190} INFO -     Found existing installation: google-auth-oauthlib 1.2.0
[2024-11-18T17:35:42.932+0000] {process_utils.py:190} INFO -     Not uninstalling google-auth-oauthlib at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvol07uxyc
[2024-11-18T17:35:42.933+0000] {process_utils.py:190} INFO -     Can't uninstall 'google-auth-oauthlib'. No files were found to uninstall.
[2024-11-18T17:35:43.137+0000] {process_utils.py:190} INFO -   Attempting uninstall: mlflow
[2024-11-18T17:35:43.139+0000] {process_utils.py:190} INFO -     Found existing installation: mlflow 2.17.0
[2024-11-18T17:35:43.139+0000] {process_utils.py:190} INFO -     Not uninstalling mlflow at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvol07uxyc
[2024-11-18T17:35:43.140+0000] {process_utils.py:190} INFO -     Can't uninstall 'mlflow'. No files were found to uninstall.
[2024-11-18T17:35:43.699+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T17:35:43.700+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T17:35:43.701+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvol07uxyc
[2024-11-18T17:35:43.701+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T17:35:50.796+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T17:35:50.797+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T17:35:50.799+0000] {process_utils.py:190} INFO - azure-core 1.29.6 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:35:50.799+0000] {process_utils.py:190} INFO - azure-mgmt-keyvault 10.3.1 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:35:50.800+0000] {process_utils.py:190} INFO - azure-mgmt-network 27.0.0 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:35:50.800+0000] {process_utils.py:190} INFO - graphene 3.4 requires typing-extensions<5,>=4.7.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:35:50.801+0000] {process_utils.py:190} INFO - pydantic 2.5.3 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:35:50.801+0000] {process_utils.py:190} INFO - pydantic-core 2.14.6 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:35:50.802+0000] {process_utils.py:190} INFO - Successfully installed absl-py-2.1.0 astunparse-1.6.3 boto3-1.28.0 botocore-1.31.85 entrypoints-0.4 flatbuffers-24.3.25 gast-0.4.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 h5py-3.11.0 keras-2.13.1 libclang-18.1.1 mlflow-2.10.2 numpy-1.24.3 opt-einsum-3.4.0 querystring-parser-1.2.4 s3transfer-0.6.2 tensorboard-2.13.0 tensorboard-data-server-0.7.2 tensorflow-2.13.0 tensorflow-estimator-2.13.0 tensorflow-io-gcs-filesystem-0.34.0 typing-extensions-4.5.0
[2024-11-18T17:35:50.875+0000] {process_utils.py:190} INFO - 
[2024-11-18T17:35:50.876+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.3.1
[2024-11-18T17:35:50.876+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T17:35:51.116+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvol07uxyc/bin/python /tmp/venv-callhv35wemm/script.py /tmp/venv-callhv35wemm/script.in /tmp/venv-callhv35wemm/script.out /tmp/venv-callhv35wemm/string_args.txt /tmp/venv-callhv35wemm/termination.log
[2024-11-18T17:35:51.120+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T17:35:52.124+0000] {process_utils.py:190} INFO - 2024-11-18 17:35:52.124336: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-11-18T17:35:52.125+0000] {process_utils.py:190} INFO - 2024-11-18 17:35:52.125399: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T17:35:52.147+0000] {process_utils.py:190} INFO - 2024-11-18 17:35:52.147052: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T17:35:52.147+0000] {process_utils.py:190} INFO - 2024-11-18 17:35:52.147327: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-11-18T17:35:52.148+0000] {process_utils.py:190} INFO - To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-11-18T17:35:52.662+0000] {process_utils.py:190} INFO - 2024-11-18 17:35:52.661926: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-11-18T17:35:53.642+0000] {process_utils.py:190} INFO - Epoch 1/10
[2024-11-18T17:35:54.494+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 2:46 - loss: 0.3267 56/575 [=>............................] - ETA: 0s - loss: 0.1408  116/575 [=====>........................] - ETA: 0s - loss: 0.1015188/575 [========>.....................] - ETA: 0s - loss: 0.0791261/575 [============>.................] - ETA: 0s - loss: 0.0656338/575 [================>.............] - ETA: 0s - loss: 0.0565410/575 [====================>.........] - ETA: 0s - loss: 0.0507481/575 [========================>.....] - ETA: 0s - loss: 0.0464554/575 [===========================>..] - ETA: 0s - loss: 0.0429575/575 [==============================] - 1s 977us/step - loss: 0.0421 - val_loss: 0.0068
[2024-11-18T17:35:54.494+0000] {process_utils.py:190} INFO - Epoch 2/10
[2024-11-18T17:35:54.952+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0200 75/575 [==>...........................] - ETA: 0s - loss: 0.0181149/575 [======>.......................] - ETA: 0s - loss: 0.0176225/575 [==========>...................] - ETA: 0s - loss: 0.0173305/575 [==============>...............] - ETA: 0s - loss: 0.0170384/575 [===================>..........] - ETA: 0s - loss: 0.0166457/575 [======================>.......] - ETA: 0s - loss: 0.0163537/575 [===========================>..] - ETA: 0s - loss: 0.0159575/575 [==============================] - 0s 796us/step - loss: 0.0157 - val_loss: 0.0051
[2024-11-18T17:35:54.952+0000] {process_utils.py:190} INFO - Epoch 3/10
[2024-11-18T17:35:55.485+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0131 74/575 [==>...........................] - ETA: 0s - loss: 0.0127147/575 [======>.......................] - ETA: 0s - loss: 0.0128218/575 [==========>...................] - ETA: 0s - loss: 0.0125290/575 [==============>...............] - ETA: 0s - loss: 0.0124365/575 [==================>...........] - ETA: 0s - loss: 0.0123446/575 [======================>.......] - ETA: 0s - loss: 0.0120531/575 [==========================>...] - ETA: 0s - loss: 0.0119575/575 [==============================] - 1s 927us/step - loss: 0.0118 - val_loss: 0.0044
[2024-11-18T17:35:55.486+0000] {process_utils.py:190} INFO - Epoch 4/10
[2024-11-18T17:35:55.923+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 1s - loss: 0.0102 84/575 [===>..........................] - ETA: 0s - loss: 0.0108174/575 [========>.....................] - ETA: 0s - loss: 0.0105248/575 [===========>..................] - ETA: 0s - loss: 0.0105329/575 [================>.............] - ETA: 0s - loss: 0.0104416/575 [====================>.........] - ETA: 0s - loss: 0.0103502/575 [=========================>....] - ETA: 0s - loss: 0.0101575/575 [==============================] - 0s 757us/step - loss: 0.0100 - val_loss: 0.0037
[2024-11-18T17:35:55.923+0000] {process_utils.py:190} INFO - Epoch 5/10
[2024-11-18T17:35:56.439+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0104 76/575 [==>...........................] - ETA: 0s - loss: 0.0093158/575 [=======>......................] - ETA: 0s - loss: 0.0093238/575 [===========>..................] - ETA: 0s - loss: 0.0092317/575 [===============>..............] - ETA: 0s - loss: 0.0091395/575 [===================>..........] - ETA: 0s - loss: 0.0091475/575 [=======================>......] - ETA: 0s - loss: 0.0090556/575 [============================>.] - ETA: 0s - loss: 0.0090575/575 [==============================] - 1s 897us/step - loss: 0.0090 - val_loss: 0.0034
[2024-11-18T17:35:56.440+0000] {process_utils.py:190} INFO - Epoch 6/10
[2024-11-18T17:35:56.901+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0086 80/575 [===>..........................] - ETA: 0s - loss: 0.0085145/575 [======>.......................] - ETA: 0s - loss: 0.0084219/575 [==========>...................] - ETA: 0s - loss: 0.0085295/575 [==============>...............] - ETA: 0s - loss: 0.0085372/575 [==================>...........] - ETA: 0s - loss: 0.0084451/575 [======================>.......] - ETA: 0s - loss: 0.0083513/575 [=========================>....] - ETA: 0s - loss: 0.0083575/575 [==============================] - 0s 801us/step - loss: 0.0082 - val_loss: 0.0031
[2024-11-18T17:35:56.901+0000] {process_utils.py:190} INFO - Epoch 7/10
[2024-11-18T17:35:57.359+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0091 85/575 [===>..........................] - ETA: 0s - loss: 0.0081168/575 [=======>......................] - ETA: 0s - loss: 0.0080250/575 [============>.................] - ETA: 0s - loss: 0.0079326/575 [================>.............] - ETA: 0s - loss: 0.0079402/575 [===================>..........] - ETA: 0s - loss: 0.0078475/575 [=======================>......] - ETA: 0s - loss: 0.0078547/575 [===========================>..] - ETA: 0s - loss: 0.0078575/575 [==============================] - 0s 797us/step - loss: 0.0078 - val_loss: 0.0030
[2024-11-18T17:35:57.360+0000] {process_utils.py:190} INFO - Epoch 8/10
[2024-11-18T17:35:57.813+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0066 78/575 [===>..........................] - ETA: 0s - loss: 0.0076156/575 [=======>......................] - ETA: 0s - loss: 0.0073233/575 [===========>..................] - ETA: 0s - loss: 0.0074307/575 [===============>..............] - ETA: 0s - loss: 0.0074385/575 [===================>..........] - ETA: 0s - loss: 0.0073465/575 [=======================>......] - ETA: 0s - loss: 0.0073548/575 [===========================>..] - ETA: 0s - loss: 0.0073575/575 [==============================] - 0s 789us/step - loss: 0.0072 - val_loss: 0.0025
[2024-11-18T17:35:57.813+0000] {process_utils.py:190} INFO - Epoch 9/10
[2024-11-18T17:35:58.259+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0073 76/575 [==>...........................] - ETA: 0s - loss: 0.0071150/575 [======>.......................] - ETA: 0s - loss: 0.0070234/575 [===========>..................] - ETA: 0s - loss: 0.0070312/575 [===============>..............] - ETA: 0s - loss: 0.0070397/575 [===================>..........] - ETA: 0s - loss: 0.0070477/575 [=======================>......] - ETA: 0s - loss: 0.0070556/575 [============================>.] - ETA: 0s - loss: 0.0070575/575 [==============================] - 0s 774us/step - loss: 0.0070 - val_loss: 0.0024
[2024-11-18T17:35:58.259+0000] {process_utils.py:190} INFO - Epoch 10/10
[2024-11-18T17:35:58.702+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0063 79/575 [===>..........................] - ETA: 0s - loss: 0.0072162/575 [=======>......................] - ETA: 0s - loss: 0.0070246/575 [===========>..................] - ETA: 0s - loss: 0.0069324/575 [===============>..............] - ETA: 0s - loss: 0.0069407/575 [====================>.........] - ETA: 0s - loss: 0.0069490/575 [========================>.....] - ETA: 0s - loss: 0.0068566/575 [============================>.] - ETA: 0s - loss: 0.0068575/575 [==============================] - 0s 771us/step - loss: 0.0068 - val_loss: 0.0022
[2024-11-18T17:35:58.713+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-11-18T17:35:58.714+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callhv35wemm/script.py", line 75, in <module>
[2024-11-18T17:35:58.714+0000] {process_utils.py:190} INFO -     res = train_embedding_model(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-18T17:35:58.714+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callhv35wemm/script.py", line 70, in train_embedding_model
[2024-11-18T17:35:58.715+0000] {process_utils.py:190} INFO -     mlflow.keras.log_model(model, artifact_path="model", registered_model_name="spotify_embedding_model")
[2024-11-18T17:35:58.715+0000] {process_utils.py:190} INFO - AttributeError: module 'mlflow' has no attribute 'keras'
[2024-11-18T17:35:59.521+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
module 'mlflow' has no attribute 'keras'
[2024-11-18T17:35:59.523+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=spotify_recommender_dag_v3, task_id=train_embedding_model, execution_date=20241118T173012, start_date=20241118T173534, end_date=20241118T173559
[2024-11-18T17:35:59.535+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 41 for task train_embedding_model (Process returned non-zero exit status 1.
module 'mlflow' has no attribute 'keras'; 1424)
[2024-11-18T17:35:59.574+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-18T17:35:59.587+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
