[2024-11-18T18:33:14.365+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.evaluate_champion scheduled__2024-11-17T00:00:00+00:00 [queued]>
[2024-11-18T18:33:14.369+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.evaluate_champion scheduled__2024-11-17T00:00:00+00:00 [queued]>
[2024-11-18T18:33:14.369+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-11-18T18:33:14.377+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): evaluate_champion> on 2024-11-17 00:00:00+00:00
[2024-11-18T18:33:14.380+0000] {standard_task_runner.py:60} INFO - Started process 18246 to run task
[2024-11-18T18:33:14.382+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_retrain_challenge_model_v3', 'evaluate_champion', 'scheduled__2024-11-17T00:00:00+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/retrain_music_model.py', '--cfg-path', '/tmp/tmpxmda998o']
[2024-11-18T18:33:14.383+0000] {standard_task_runner.py:88} INFO - Job 96: Subtask evaluate_champion
[2024-11-18T18:33:14.409+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_retrain_challenge_model_v3.evaluate_champion scheduled__2024-11-17T00:00:00+00:00 [running]> on host 98017b53a184
[2024-11-18T18:33:14.447+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_retrain_challenge_model_v3' AIRFLOW_CTX_TASK_ID='evaluate_champion' AIRFLOW_CTX_EXECUTION_DATE='2024-11-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-17T00:00:00+00:00'
[2024-11-18T18:33:14.448+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvy7kqvf2g --system-site-packages --python=python
[2024-11-18T18:33:14.452+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:33:14.823+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 154ms
[2024-11-18T18:33:14.824+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvy7kqvf2g, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T18:33:14.824+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T18:33:14.824+0000] {process_utils.py:190} INFO -     added seed packages: pip==24.2, setuptools==75.2.0, wheel==0.44.0
[2024-11-18T18:33:14.825+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T18:33:14.843+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvy7kqvf2g/bin/pip install -r /tmp/venvy7kqvf2g/requirements.txt
[2024-11-18T18:33:14.847+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:33:15.724+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venvy7kqvf2g/requirements.txt (line 1))
[2024-11-18T18:33:15.726+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T18:33:15.759+0000] {process_utils.py:190} INFO - Collecting mlflow==2.10.2 (from -r /tmp/venvy7kqvf2g/requirements.txt (line 2))
[2024-11-18T18:33:15.761+0000] {process_utils.py:190} INFO -   Using cached mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
[2024-11-18T18:33:15.768+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvy7kqvf2g/requirements.txt (line 3)) (2.0.3)
[2024-11-18T18:33:15.768+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn==1.3.2 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvy7kqvf2g/requirements.txt (line 4)) (1.3.2)
[2024-11-18T18:33:15.852+0000] {process_utils.py:190} INFO - Collecting tensorflow==2.13.0 (from -r /tmp/venvy7kqvf2g/requirements.txt (line 5))
[2024-11-18T18:33:15.854+0000] {process_utils.py:190} INFO -   Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
[2024-11-18T18:33:16.279+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 1))
[2024-11-18T18:33:16.281+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T18:33:16.282+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 1)) (0.10.0)
[2024-11-18T18:33:16.307+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 1))
[2024-11-18T18:33:16.309+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:33:16.313+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (8.1.7)
[2024-11-18T18:33:16.313+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (3.1.0)
[2024-11-18T18:33:16.326+0000] {process_utils.py:190} INFO - Collecting entrypoints<1 (from mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2))
[2024-11-18T18:33:16.328+0000] {process_utils.py:190} INFO -   Using cached entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
[2024-11-18T18:33:16.329+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=2.1.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (3.1.43)
[2024-11-18T18:33:16.329+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (6.0.1)
[2024-11-18T18:33:16.329+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<5,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (4.25.2)
[2024-11-18T18:33:16.330+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz<2024 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T18:33:16.330+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (2.31.0)
[2024-11-18T18:33:16.330+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (23.2)
[2024-11-18T18:33:16.331+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (6.11.0)
[2024-11-18T18:33:16.331+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (0.4.4)
[2024-11-18T18:33:16.331+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (1.13.1)
[2024-11-18T18:33:16.332+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (7.0.0)
[2024-11-18T18:33:16.332+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (2.2.5)
[2024-11-18T18:33:16.332+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (1.24.4)
[2024-11-18T18:33:16.332+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (1.10.1)
[2024-11-18T18:33:16.343+0000] {process_utils.py:190} INFO - Collecting querystring-parser<2 (from mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2))
[2024-11-18T18:33:16.344+0000] {process_utils.py:190} INFO -   Using cached querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
[2024-11-18T18:33:16.345+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (1.4.51)
[2024-11-18T18:33:16.345+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow<16,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (14.0.2)
[2024-11-18T18:33:16.346+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (3.5.2)
[2024-11-18T18:33:16.346+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (3.7.5)
[2024-11-18T18:33:16.346+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<22 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (21.2.0)
[2024-11-18T18:33:16.347+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (3.1.3)
[2024-11-18T18:33:16.371+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvy7kqvf2g/requirements.txt (line 3)) (2.8.2)
[2024-11-18T18:33:16.372+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvy7kqvf2g/requirements.txt (line 3)) (2023.4)
[2024-11-18T18:33:16.377+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 4)) (1.4.2)
[2024-11-18T18:33:16.378+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 4)) (3.5.0)
[2024-11-18T18:33:16.395+0000] {process_utils.py:190} INFO - Collecting absl-py>=1.0.0 (from tensorflow==2.13.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 5))
[2024-11-18T18:33:16.396+0000] {process_utils.py:190} INFO -   Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
[2024-11-18T18:33:16.409+0000] {process_utils.py:190} INFO - Collecting astunparse>=1.6.0 (from tensorflow==2.13.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 5))
[2024-11-18T18:33:16.411+0000] {process_utils.py:190} INFO -   Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
[2024-11-18T18:33:16.425+0000] {process_utils.py:190} INFO - Collecting flatbuffers>=23.1.21 (from tensorflow==2.13.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 5))
[2024-11-18T18:33:16.427+0000] {process_utils.py:190} INFO -   Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
[2024-11-18T18:33:16.443+0000] {process_utils.py:190} INFO - Collecting gast<=0.4.0,>=0.2.1 (from tensorflow==2.13.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 5))
[2024-11-18T18:33:16.445+0000] {process_utils.py:190} INFO -   Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
[2024-11-18T18:33:16.458+0000] {process_utils.py:190} INFO - Collecting google-pasta>=0.1.1 (from tensorflow==2.13.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 5))
[2024-11-18T18:33:16.459+0000] {process_utils.py:190} INFO -   Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
[2024-11-18T18:33:16.460+0000] {process_utils.py:190} INFO - Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 5)) (1.60.0)
[2024-11-18T18:33:16.504+0000] {process_utils.py:190} INFO - Collecting h5py>=2.9.0 (from tensorflow==2.13.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 5))
[2024-11-18T18:33:16.506+0000] {process_utils.py:190} INFO -   Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
[2024-11-18T18:33:16.532+0000] {process_utils.py:190} INFO - Collecting keras<2.14,>=2.13.1 (from tensorflow==2.13.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 5))
[2024-11-18T18:33:16.533+0000] {process_utils.py:190} INFO -   Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
[2024-11-18T18:33:16.552+0000] {process_utils.py:190} INFO - Collecting libclang>=13.0.0 (from tensorflow==2.13.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 5))
[2024-11-18T18:33:16.554+0000] {process_utils.py:190} INFO -   Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
[2024-11-18T18:33:16.754+0000] {process_utils.py:190} INFO - Collecting numpy<2 (from mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2))
[2024-11-18T18:33:16.756+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-11-18T18:33:16.771+0000] {process_utils.py:190} INFO - Collecting opt-einsum>=2.3.2 (from tensorflow==2.13.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 5))
[2024-11-18T18:33:16.773+0000] {process_utils.py:190} INFO -   Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
[2024-11-18T18:33:16.774+0000] {process_utils.py:190} INFO - Requirement already satisfied: setuptools in /tmp/venvy7kqvf2g/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 5)) (75.2.0)
[2024-11-18T18:33:16.774+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.12.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:33:16.801+0000] {process_utils.py:190} INFO - Collecting tensorboard<2.14,>=2.13 (from tensorflow==2.13.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 5))
[2024-11-18T18:33:16.803+0000] {process_utils.py:190} INFO -   Using cached tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:33:16.822+0000] {process_utils.py:190} INFO - Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow==2.13.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 5))
[2024-11-18T18:33:16.823+0000] {process_utils.py:190} INFO -   Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
[2024-11-18T18:33:16.824+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.1.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 5)) (2.4.0)
[2024-11-18T18:33:17.000+0000] {process_utils.py:190} INFO - Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow==2.13.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 5))
[2024-11-18T18:33:17.001+0000] {process_utils.py:190} INFO -   Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
[2024-11-18T18:33:17.002+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt>=1.11.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:33:17.032+0000] {process_utils.py:190} INFO - Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow==2.13.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 5))
[2024-11-18T18:33:17.033+0000] {process_utils.py:190} INFO -   Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
[2024-11-18T18:33:17.038+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (1.3.0)
[2024-11-18T18:33:17.041+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (5.13.0)
[2024-11-18T18:33:17.042+0000] {process_utils.py:190} INFO - Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venvy7kqvf2g/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow==2.13.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 5)) (0.44.0)
[2024-11-18T18:33:17.044+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 1)) (1.26.18)
[2024-11-18T18:33:17.050+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (2.2.3)
[2024-11-18T18:33:17.050+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (2.1.2)
[2024-11-18T18:33:17.055+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (4.0.11)
[2024-11-18T18:33:17.062+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (3.17.0)
[2024-11-18T18:33:17.063+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (2.1.3)
[2024-11-18T18:33:17.071+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (1.1.1)
[2024-11-18T18:33:17.071+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (0.12.1)
[2024-11-18T18:33:17.071+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (4.54.1)
[2024-11-18T18:33:17.071+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (1.4.7)
[2024-11-18T18:33:17.079+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (10.4.0)
[2024-11-18T18:33:17.079+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (3.1.1)
[2024-11-18T18:33:17.098+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (3.3.2)
[2024-11-18T18:33:17.098+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (3.6)
[2024-11-18T18:33:17.099+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (2023.11.17)
[2024-11-18T18:33:17.320+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (3.0.3)
[2024-11-18T18:33:17.326+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth<3,>=1.6.3 in /home/***/.local/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 5)) (2.26.2)
[2024-11-18T18:33:17.341+0000] {process_utils.py:190} INFO - Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 5))
[2024-11-18T18:33:17.343+0000] {process_utils.py:190} INFO -   Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
[2024-11-18T18:33:17.367+0000] {process_utils.py:190} INFO - Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 5))
[2024-11-18T18:33:17.369+0000] {process_utils.py:190} INFO -   Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
[2024-11-18T18:33:17.416+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvy7kqvf2g/requirements.txt (line 2)) (5.0.1)
[2024-11-18T18:33:17.419+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 5)) (5.3.2)
[2024-11-18T18:33:17.420+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 5)) (0.3.0)
[2024-11-18T18:33:17.420+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 5)) (4.9)
[2024-11-18T18:33:17.421+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 5)) (1.3.1)
[2024-11-18T18:33:17.448+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 5)) (0.5.1)
[2024-11-18T18:33:17.450+0000] {process_utils.py:190} INFO - Requirement already satisfied: oauthlib>=3.0.0 in /home/***/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvy7kqvf2g/requirements.txt (line 5)) (3.2.2)
[2024-11-18T18:33:17.457+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T18:33:17.459+0000] {process_utils.py:190} INFO - Using cached mlflow-2.10.2-py3-none-any.whl (19.5 MB)
[2024-11-18T18:33:17.469+0000] {process_utils.py:190} INFO - Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
[2024-11-18T18:33:17.692+0000] {process_utils.py:190} INFO - Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
[2024-11-18T18:33:17.693+0000] {process_utils.py:190} INFO - Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
[2024-11-18T18:33:17.694+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T18:33:17.700+0000] {process_utils.py:190} INFO - Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
[2024-11-18T18:33:17.701+0000] {process_utils.py:190} INFO - Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
[2024-11-18T18:33:17.702+0000] {process_utils.py:190} INFO - Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
[2024-11-18T18:33:17.704+0000] {process_utils.py:190} INFO - Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
[2024-11-18T18:33:17.705+0000] {process_utils.py:190} INFO - Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
[2024-11-18T18:33:17.708+0000] {process_utils.py:190} INFO - Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)
[2024-11-18T18:33:17.709+0000] {process_utils.py:190} INFO - Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
[2024-11-18T18:33:17.721+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-11-18T18:33:17.731+0000] {process_utils.py:190} INFO - Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
[2024-11-18T18:33:17.732+0000] {process_utils.py:190} INFO - Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
[2024-11-18T18:33:17.733+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T18:33:17.734+0000] {process_utils.py:190} INFO - Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
[2024-11-18T18:33:17.738+0000] {process_utils.py:190} INFO - Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
[2024-11-18T18:33:17.739+0000] {process_utils.py:190} INFO - Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
[2024-11-18T18:33:17.741+0000] {process_utils.py:190} INFO - Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[2024-11-18T18:33:17.742+0000] {process_utils.py:190} INFO - Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
[2024-11-18T18:33:17.743+0000] {process_utils.py:190} INFO - Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
[2024-11-18T18:33:18.947+0000] {process_utils.py:190} INFO - Installing collected packages: libclang, flatbuffers, typing-extensions, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, querystring-parser, opt-einsum, numpy, keras, google-pasta, gast, entrypoints, astunparse, absl-py, h5py, botocore, s3transfer, google-auth-oauthlib, tensorboard, mlflow, boto3, tensorflow
[2024-11-18T18:33:19.177+0000] {process_utils.py:190} INFO -   Attempting uninstall: typing-extensions
[2024-11-18T18:33:19.178+0000] {process_utils.py:190} INFO -     Found existing installation: typing_extensions 4.9.0
[2024-11-18T18:33:19.179+0000] {process_utils.py:190} INFO -     Not uninstalling typing-extensions at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvy7kqvf2g
[2024-11-18T18:33:19.179+0000] {process_utils.py:190} INFO -     Can't uninstall 'typing_extensions'. No files were found to uninstall.
[2024-11-18T18:33:19.432+0000] {process_utils.py:190} INFO -   Attempting uninstall: numpy
[2024-11-18T18:33:19.433+0000] {process_utils.py:190} INFO -     Found existing installation: numpy 1.24.4
[2024-11-18T18:33:19.433+0000] {process_utils.py:190} INFO -     Not uninstalling numpy at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvy7kqvf2g
[2024-11-18T18:33:19.434+0000] {process_utils.py:190} INFO -     Can't uninstall 'numpy'. No files were found to uninstall.
[2024-11-18T18:33:21.016+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T18:33:21.017+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T18:33:21.017+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvy7kqvf2g
[2024-11-18T18:33:21.017+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T18:33:21.412+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T18:33:21.414+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T18:33:21.415+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvy7kqvf2g
[2024-11-18T18:33:21.415+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T18:33:21.436+0000] {process_utils.py:190} INFO -   Attempting uninstall: google-auth-oauthlib
[2024-11-18T18:33:21.437+0000] {process_utils.py:190} INFO -     Found existing installation: google-auth-oauthlib 1.2.0
[2024-11-18T18:33:21.437+0000] {process_utils.py:190} INFO -     Not uninstalling google-auth-oauthlib at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvy7kqvf2g
[2024-11-18T18:33:21.438+0000] {process_utils.py:190} INFO -     Can't uninstall 'google-auth-oauthlib'. No files were found to uninstall.
[2024-11-18T18:33:21.633+0000] {process_utils.py:190} INFO -   Attempting uninstall: mlflow
[2024-11-18T18:33:21.635+0000] {process_utils.py:190} INFO -     Found existing installation: mlflow 2.17.0
[2024-11-18T18:33:21.635+0000] {process_utils.py:190} INFO -     Not uninstalling mlflow at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvy7kqvf2g
[2024-11-18T18:33:21.636+0000] {process_utils.py:190} INFO -     Can't uninstall 'mlflow'. No files were found to uninstall.
[2024-11-18T18:33:22.188+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T18:33:22.188+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T18:33:22.189+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvy7kqvf2g
[2024-11-18T18:33:22.189+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T18:33:29.184+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T18:33:29.185+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T18:33:29.186+0000] {process_utils.py:190} INFO - azure-core 1.29.6 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:33:29.187+0000] {process_utils.py:190} INFO - azure-mgmt-keyvault 10.3.1 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:33:29.189+0000] {process_utils.py:190} INFO - azure-mgmt-network 27.0.0 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:33:29.189+0000] {process_utils.py:190} INFO - graphene 3.4 requires typing-extensions<5,>=4.7.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:33:29.190+0000] {process_utils.py:190} INFO - pydantic 2.5.3 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:33:29.190+0000] {process_utils.py:190} INFO - pydantic-core 2.14.6 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:33:29.190+0000] {process_utils.py:190} INFO - Successfully installed absl-py-2.1.0 astunparse-1.6.3 boto3-1.28.0 botocore-1.31.85 entrypoints-0.4 flatbuffers-24.3.25 gast-0.4.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 h5py-3.11.0 keras-2.13.1 libclang-18.1.1 mlflow-2.10.2 numpy-1.24.3 opt-einsum-3.4.0 querystring-parser-1.2.4 s3transfer-0.6.2 tensorboard-2.13.0 tensorboard-data-server-0.7.2 tensorflow-2.13.0 tensorflow-estimator-2.13.0 tensorflow-io-gcs-filesystem-0.34.0 typing-extensions-4.5.0
[2024-11-18T18:33:29.250+0000] {process_utils.py:190} INFO - 
[2024-11-18T18:33:29.251+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 24.2 -> 24.3.1
[2024-11-18T18:33:29.251+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T18:33:29.420+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvy7kqvf2g/bin/python /tmp/venv-callkdutx8k1/script.py /tmp/venv-callkdutx8k1/script.in /tmp/venv-callkdutx8k1/script.out /tmp/venv-callkdutx8k1/string_args.txt /tmp/venv-callkdutx8k1/termination.log
[2024-11-18T18:33:29.424+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:33:30.335+0000] {process_utils.py:190} INFO - 2024-11-18 18:33:30.335089: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-11-18T18:33:30.336+0000] {process_utils.py:190} INFO - 2024-11-18 18:33:30.336163: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T18:33:30.357+0000] {process_utils.py:190} INFO - 2024-11-18 18:33:30.357450: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T18:33:30.358+0000] {process_utils.py:190} INFO - 2024-11-18 18:33:30.357707: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-11-18T18:33:30.358+0000] {process_utils.py:190} INFO - To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-11-18T18:33:30.863+0000] {process_utils.py:190} INFO - 2024-11-18 18:33:30.863682: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-11-18T18:33:31.794+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-11-18T18:33:31.795+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callkdutx8k1/script.py", line 95, in <module>
[2024-11-18T18:33:31.795+0000] {process_utils.py:190} INFO -     res = evaluate_champion(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-18T18:33:31.795+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callkdutx8k1/script.py", line 63, in evaluate_champion
[2024-11-18T18:33:31.795+0000] {process_utils.py:190} INFO -     challenger_model = tf.keras.models.load_model("/models/challenger_model.h5")
[2024-11-18T18:33:31.795+0000] {process_utils.py:190} INFO -   File "/tmp/venvy7kqvf2g/lib/python3.8/site-packages/keras/src/saving/saving_api.py", line 238, in load_model
[2024-11-18T18:33:31.796+0000] {process_utils.py:190} INFO -     return legacy_sm_saving_lib.load_model(
[2024-11-18T18:33:31.796+0000] {process_utils.py:190} INFO -   File "/tmp/venvy7kqvf2g/lib/python3.8/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
[2024-11-18T18:33:31.796+0000] {process_utils.py:190} INFO -     raise e.with_traceback(filtered_tb) from None
[2024-11-18T18:33:31.796+0000] {process_utils.py:190} INFO -   File "/tmp/venvy7kqvf2g/lib/python3.8/site-packages/keras/src/saving/legacy/save.py", line 234, in load_model
[2024-11-18T18:33:31.797+0000] {process_utils.py:190} INFO -     raise IOError(
[2024-11-18T18:33:31.797+0000] {process_utils.py:190} INFO - OSError: No file or directory found at /models/challenger_model.h5
[2024-11-18T18:33:32.602+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
No file or directory found at /models/challenger_model.h5
[2024-11-18T18:33:32.604+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_retrain_challenge_model_v3, task_id=evaluate_champion, execution_date=20241117T000000, start_date=20241118T183314, end_date=20241118T183332
[2024-11-18T18:33:32.615+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 96 for task evaluate_champion (Process returned non-zero exit status 1.
No file or directory found at /models/challenger_model.h5; 18246)
[2024-11-18T18:33:32.634+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-18T18:33:32.643+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-18T18:44:08.373+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.evaluate_champion scheduled__2024-11-17T00:00:00+00:00 [queued]>
[2024-11-18T18:44:08.378+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.evaluate_champion scheduled__2024-11-17T00:00:00+00:00 [queued]>
[2024-11-18T18:44:08.378+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-11-18T18:44:08.387+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): evaluate_champion> on 2024-11-17 00:00:00+00:00
[2024-11-18T18:44:08.390+0000] {standard_task_runner.py:60} INFO - Started process 22978 to run task
[2024-11-18T18:44:08.391+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_retrain_challenge_model_v3', 'evaluate_champion', 'scheduled__2024-11-17T00:00:00+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/retrain_music_model.py', '--cfg-path', '/tmp/tmpflkoo750']
[2024-11-18T18:44:08.392+0000] {standard_task_runner.py:88} INFO - Job 107: Subtask evaluate_champion
[2024-11-18T18:44:08.418+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_retrain_challenge_model_v3.evaluate_champion scheduled__2024-11-17T00:00:00+00:00 [running]> on host 98017b53a184
[2024-11-18T18:44:08.457+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_retrain_challenge_model_v3' AIRFLOW_CTX_TASK_ID='evaluate_champion' AIRFLOW_CTX_EXECUTION_DATE='2024-11-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-17T00:00:00+00:00'
[2024-11-18T18:44:08.458+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venviqupxdpr --system-site-packages --python=python
[2024-11-18T18:44:08.462+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:44:08.844+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 166ms
[2024-11-18T18:44:08.845+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venviqupxdpr, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T18:44:08.845+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T18:44:08.846+0000] {process_utils.py:190} INFO -     added seed packages: pip==24.2, setuptools==75.2.0, wheel==0.44.0
[2024-11-18T18:44:08.846+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T18:44:08.862+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venviqupxdpr/bin/pip install -r /tmp/venviqupxdpr/requirements.txt
[2024-11-18T18:44:08.866+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:44:09.710+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venviqupxdpr/requirements.txt (line 1))
[2024-11-18T18:44:09.712+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T18:44:09.799+0000] {process_utils.py:190} INFO - Collecting mlflow==2.10.2 (from -r /tmp/venviqupxdpr/requirements.txt (line 2))
[2024-11-18T18:44:09.800+0000] {process_utils.py:190} INFO -   Using cached mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
[2024-11-18T18:44:09.808+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venviqupxdpr/requirements.txt (line 3)) (2.0.3)
[2024-11-18T18:44:09.808+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn==1.3.2 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venviqupxdpr/requirements.txt (line 4)) (1.3.2)
[2024-11-18T18:44:09.892+0000] {process_utils.py:190} INFO - Collecting tensorflow==2.13.0 (from -r /tmp/venviqupxdpr/requirements.txt (line 5))
[2024-11-18T18:44:09.893+0000] {process_utils.py:190} INFO -   Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
[2024-11-18T18:44:10.345+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venviqupxdpr/requirements.txt (line 1))
[2024-11-18T18:44:10.347+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T18:44:10.348+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venviqupxdpr/requirements.txt (line 1)) (0.10.0)
[2024-11-18T18:44:10.427+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venviqupxdpr/requirements.txt (line 1))
[2024-11-18T18:44:10.428+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:44:10.432+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (8.1.7)
[2024-11-18T18:44:10.432+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (3.1.0)
[2024-11-18T18:44:10.443+0000] {process_utils.py:190} INFO - Collecting entrypoints<1 (from mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2))
[2024-11-18T18:44:10.444+0000] {process_utils.py:190} INFO -   Using cached entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
[2024-11-18T18:44:10.445+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=2.1.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (3.1.43)
[2024-11-18T18:44:10.445+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (6.0.1)
[2024-11-18T18:44:10.446+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<5,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (4.25.2)
[2024-11-18T18:44:10.446+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz<2024 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T18:44:10.446+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (2.31.0)
[2024-11-18T18:44:10.446+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (23.2)
[2024-11-18T18:44:10.447+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (6.11.0)
[2024-11-18T18:44:10.447+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (0.4.4)
[2024-11-18T18:44:10.447+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (1.13.1)
[2024-11-18T18:44:10.448+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (7.0.0)
[2024-11-18T18:44:10.448+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (2.2.5)
[2024-11-18T18:44:10.448+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (1.24.4)
[2024-11-18T18:44:10.449+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (1.10.1)
[2024-11-18T18:44:10.458+0000] {process_utils.py:190} INFO - Collecting querystring-parser<2 (from mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2))
[2024-11-18T18:44:10.459+0000] {process_utils.py:190} INFO -   Using cached querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
[2024-11-18T18:44:10.460+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (1.4.51)
[2024-11-18T18:44:10.460+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow<16,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (14.0.2)
[2024-11-18T18:44:10.461+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (3.5.2)
[2024-11-18T18:44:10.461+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (3.7.5)
[2024-11-18T18:44:10.462+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<22 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (21.2.0)
[2024-11-18T18:44:10.462+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (3.1.3)
[2024-11-18T18:44:10.484+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venviqupxdpr/requirements.txt (line 3)) (2.8.2)
[2024-11-18T18:44:10.484+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venviqupxdpr/requirements.txt (line 3)) (2023.4)
[2024-11-18T18:44:10.490+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venviqupxdpr/requirements.txt (line 4)) (1.4.2)
[2024-11-18T18:44:10.490+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venviqupxdpr/requirements.txt (line 4)) (3.5.0)
[2024-11-18T18:44:10.507+0000] {process_utils.py:190} INFO - Collecting absl-py>=1.0.0 (from tensorflow==2.13.0->-r /tmp/venviqupxdpr/requirements.txt (line 5))
[2024-11-18T18:44:10.508+0000] {process_utils.py:190} INFO -   Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
[2024-11-18T18:44:10.519+0000] {process_utils.py:190} INFO - Collecting astunparse>=1.6.0 (from tensorflow==2.13.0->-r /tmp/venviqupxdpr/requirements.txt (line 5))
[2024-11-18T18:44:10.520+0000] {process_utils.py:190} INFO -   Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
[2024-11-18T18:44:10.534+0000] {process_utils.py:190} INFO - Collecting flatbuffers>=23.1.21 (from tensorflow==2.13.0->-r /tmp/venviqupxdpr/requirements.txt (line 5))
[2024-11-18T18:44:10.535+0000] {process_utils.py:190} INFO -   Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
[2024-11-18T18:44:10.551+0000] {process_utils.py:190} INFO - Collecting gast<=0.4.0,>=0.2.1 (from tensorflow==2.13.0->-r /tmp/venviqupxdpr/requirements.txt (line 5))
[2024-11-18T18:44:10.552+0000] {process_utils.py:190} INFO -   Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
[2024-11-18T18:44:10.565+0000] {process_utils.py:190} INFO - Collecting google-pasta>=0.1.1 (from tensorflow==2.13.0->-r /tmp/venviqupxdpr/requirements.txt (line 5))
[2024-11-18T18:44:10.566+0000] {process_utils.py:190} INFO -   Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
[2024-11-18T18:44:10.567+0000] {process_utils.py:190} INFO - Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venviqupxdpr/requirements.txt (line 5)) (1.60.0)
[2024-11-18T18:44:10.603+0000] {process_utils.py:190} INFO - Collecting h5py>=2.9.0 (from tensorflow==2.13.0->-r /tmp/venviqupxdpr/requirements.txt (line 5))
[2024-11-18T18:44:10.605+0000] {process_utils.py:190} INFO -   Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
[2024-11-18T18:44:10.628+0000] {process_utils.py:190} INFO - Collecting keras<2.14,>=2.13.1 (from tensorflow==2.13.0->-r /tmp/venviqupxdpr/requirements.txt (line 5))
[2024-11-18T18:44:10.629+0000] {process_utils.py:190} INFO -   Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
[2024-11-18T18:44:10.646+0000] {process_utils.py:190} INFO - Collecting libclang>=13.0.0 (from tensorflow==2.13.0->-r /tmp/venviqupxdpr/requirements.txt (line 5))
[2024-11-18T18:44:10.647+0000] {process_utils.py:190} INFO -   Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
[2024-11-18T18:44:10.815+0000] {process_utils.py:190} INFO - Collecting numpy<2 (from mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2))
[2024-11-18T18:44:10.816+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-11-18T18:44:10.828+0000] {process_utils.py:190} INFO - Collecting opt-einsum>=2.3.2 (from tensorflow==2.13.0->-r /tmp/venviqupxdpr/requirements.txt (line 5))
[2024-11-18T18:44:10.829+0000] {process_utils.py:190} INFO -   Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
[2024-11-18T18:44:10.830+0000] {process_utils.py:190} INFO - Requirement already satisfied: setuptools in /tmp/venviqupxdpr/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venviqupxdpr/requirements.txt (line 5)) (75.2.0)
[2024-11-18T18:44:10.831+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.12.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venviqupxdpr/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:44:10.850+0000] {process_utils.py:190} INFO - Collecting tensorboard<2.14,>=2.13 (from tensorflow==2.13.0->-r /tmp/venviqupxdpr/requirements.txt (line 5))
[2024-11-18T18:44:10.852+0000] {process_utils.py:190} INFO -   Using cached tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:44:10.867+0000] {process_utils.py:190} INFO - Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow==2.13.0->-r /tmp/venviqupxdpr/requirements.txt (line 5))
[2024-11-18T18:44:10.869+0000] {process_utils.py:190} INFO -   Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
[2024-11-18T18:44:10.869+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.1.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venviqupxdpr/requirements.txt (line 5)) (2.4.0)
[2024-11-18T18:44:10.889+0000] {process_utils.py:190} INFO - Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow==2.13.0->-r /tmp/venviqupxdpr/requirements.txt (line 5))
[2024-11-18T18:44:10.890+0000] {process_utils.py:190} INFO -   Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
[2024-11-18T18:44:10.891+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt>=1.11.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venviqupxdpr/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:44:10.920+0000] {process_utils.py:190} INFO - Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow==2.13.0->-r /tmp/venviqupxdpr/requirements.txt (line 5))
[2024-11-18T18:44:10.921+0000] {process_utils.py:190} INFO -   Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
[2024-11-18T18:44:10.925+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (1.3.0)
[2024-11-18T18:44:10.929+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (5.13.0)
[2024-11-18T18:44:10.930+0000] {process_utils.py:190} INFO - Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venviqupxdpr/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow==2.13.0->-r /tmp/venviqupxdpr/requirements.txt (line 5)) (0.44.0)
[2024-11-18T18:44:10.932+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venviqupxdpr/requirements.txt (line 1)) (1.26.18)
[2024-11-18T18:44:10.938+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (2.2.3)
[2024-11-18T18:44:10.939+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (2.1.2)
[2024-11-18T18:44:10.944+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (4.0.11)
[2024-11-18T18:44:10.951+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (3.17.0)
[2024-11-18T18:44:10.953+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (2.1.3)
[2024-11-18T18:44:10.961+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (1.1.1)
[2024-11-18T18:44:10.961+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (0.12.1)
[2024-11-18T18:44:10.961+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (4.54.1)
[2024-11-18T18:44:10.962+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (1.4.7)
[2024-11-18T18:44:10.973+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (10.4.0)
[2024-11-18T18:44:10.975+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (3.1.1)
[2024-11-18T18:44:10.996+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (3.3.2)
[2024-11-18T18:44:10.996+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (3.6)
[2024-11-18T18:44:10.996+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (2023.11.17)
[2024-11-18T18:44:11.217+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (3.0.3)
[2024-11-18T18:44:11.222+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth<3,>=1.6.3 in /home/***/.local/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venviqupxdpr/requirements.txt (line 5)) (2.26.2)
[2024-11-18T18:44:11.238+0000] {process_utils.py:190} INFO - Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venviqupxdpr/requirements.txt (line 5))
[2024-11-18T18:44:11.239+0000] {process_utils.py:190} INFO -   Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
[2024-11-18T18:44:11.265+0000] {process_utils.py:190} INFO - Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venviqupxdpr/requirements.txt (line 5))
[2024-11-18T18:44:11.266+0000] {process_utils.py:190} INFO -   Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
[2024-11-18T18:44:11.316+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venviqupxdpr/requirements.txt (line 2)) (5.0.1)
[2024-11-18T18:44:11.319+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venviqupxdpr/requirements.txt (line 5)) (5.3.2)
[2024-11-18T18:44:11.319+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venviqupxdpr/requirements.txt (line 5)) (0.3.0)
[2024-11-18T18:44:11.320+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venviqupxdpr/requirements.txt (line 5)) (4.9)
[2024-11-18T18:44:11.321+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venviqupxdpr/requirements.txt (line 5)) (1.3.1)
[2024-11-18T18:44:11.348+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venviqupxdpr/requirements.txt (line 5)) (0.5.1)
[2024-11-18T18:44:11.350+0000] {process_utils.py:190} INFO - Requirement already satisfied: oauthlib>=3.0.0 in /home/***/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venviqupxdpr/requirements.txt (line 5)) (3.2.2)
[2024-11-18T18:44:11.358+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T18:44:11.359+0000] {process_utils.py:190} INFO - Using cached mlflow-2.10.2-py3-none-any.whl (19.5 MB)
[2024-11-18T18:44:11.366+0000] {process_utils.py:190} INFO - Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
[2024-11-18T18:44:11.543+0000] {process_utils.py:190} INFO - Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
[2024-11-18T18:44:11.544+0000] {process_utils.py:190} INFO - Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
[2024-11-18T18:44:11.546+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T18:44:11.550+0000] {process_utils.py:190} INFO - Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
[2024-11-18T18:44:11.551+0000] {process_utils.py:190} INFO - Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
[2024-11-18T18:44:11.553+0000] {process_utils.py:190} INFO - Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
[2024-11-18T18:44:11.554+0000] {process_utils.py:190} INFO - Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
[2024-11-18T18:44:11.555+0000] {process_utils.py:190} INFO - Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
[2024-11-18T18:44:11.558+0000] {process_utils.py:190} INFO - Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)
[2024-11-18T18:44:11.560+0000] {process_utils.py:190} INFO - Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
[2024-11-18T18:44:11.569+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-11-18T18:44:11.576+0000] {process_utils.py:190} INFO - Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
[2024-11-18T18:44:11.577+0000] {process_utils.py:190} INFO - Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
[2024-11-18T18:44:11.578+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T18:44:11.579+0000] {process_utils.py:190} INFO - Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
[2024-11-18T18:44:11.582+0000] {process_utils.py:190} INFO - Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
[2024-11-18T18:44:11.584+0000] {process_utils.py:190} INFO - Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
[2024-11-18T18:44:11.585+0000] {process_utils.py:190} INFO - Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[2024-11-18T18:44:11.587+0000] {process_utils.py:190} INFO - Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
[2024-11-18T18:44:11.588+0000] {process_utils.py:190} INFO - Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
[2024-11-18T18:44:12.799+0000] {process_utils.py:190} INFO - Installing collected packages: libclang, flatbuffers, typing-extensions, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, querystring-parser, opt-einsum, numpy, keras, google-pasta, gast, entrypoints, astunparse, absl-py, h5py, botocore, s3transfer, google-auth-oauthlib, tensorboard, mlflow, boto3, tensorflow
[2024-11-18T18:44:13.067+0000] {process_utils.py:190} INFO -   Attempting uninstall: typing-extensions
[2024-11-18T18:44:13.068+0000] {process_utils.py:190} INFO -     Found existing installation: typing_extensions 4.9.0
[2024-11-18T18:44:13.069+0000] {process_utils.py:190} INFO -     Not uninstalling typing-extensions at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venviqupxdpr
[2024-11-18T18:44:13.069+0000] {process_utils.py:190} INFO -     Can't uninstall 'typing_extensions'. No files were found to uninstall.
[2024-11-18T18:44:13.339+0000] {process_utils.py:190} INFO -   Attempting uninstall: numpy
[2024-11-18T18:44:13.340+0000] {process_utils.py:190} INFO -     Found existing installation: numpy 1.24.4
[2024-11-18T18:44:13.340+0000] {process_utils.py:190} INFO -     Not uninstalling numpy at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venviqupxdpr
[2024-11-18T18:44:13.341+0000] {process_utils.py:190} INFO -     Can't uninstall 'numpy'. No files were found to uninstall.
[2024-11-18T18:44:14.956+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T18:44:14.957+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T18:44:14.957+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venviqupxdpr
[2024-11-18T18:44:14.958+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T18:44:15.335+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T18:44:15.336+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T18:44:15.337+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venviqupxdpr
[2024-11-18T18:44:15.337+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T18:44:15.357+0000] {process_utils.py:190} INFO -   Attempting uninstall: google-auth-oauthlib
[2024-11-18T18:44:15.358+0000] {process_utils.py:190} INFO -     Found existing installation: google-auth-oauthlib 1.2.0
[2024-11-18T18:44:15.358+0000] {process_utils.py:190} INFO -     Not uninstalling google-auth-oauthlib at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venviqupxdpr
[2024-11-18T18:44:15.359+0000] {process_utils.py:190} INFO -     Can't uninstall 'google-auth-oauthlib'. No files were found to uninstall.
[2024-11-18T18:44:15.550+0000] {process_utils.py:190} INFO -   Attempting uninstall: mlflow
[2024-11-18T18:44:15.552+0000] {process_utils.py:190} INFO -     Found existing installation: mlflow 2.17.0
[2024-11-18T18:44:15.552+0000] {process_utils.py:190} INFO -     Not uninstalling mlflow at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venviqupxdpr
[2024-11-18T18:44:15.552+0000] {process_utils.py:190} INFO -     Can't uninstall 'mlflow'. No files were found to uninstall.
[2024-11-18T18:44:16.084+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T18:44:16.085+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T18:44:16.085+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venviqupxdpr
[2024-11-18T18:44:16.086+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T18:44:23.046+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T18:44:23.047+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T18:44:23.047+0000] {process_utils.py:190} INFO - azure-core 1.29.6 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:44:23.048+0000] {process_utils.py:190} INFO - azure-mgmt-keyvault 10.3.1 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:44:23.048+0000] {process_utils.py:190} INFO - azure-mgmt-network 27.0.0 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:44:23.048+0000] {process_utils.py:190} INFO - graphene 3.4 requires typing-extensions<5,>=4.7.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:44:23.048+0000] {process_utils.py:190} INFO - pydantic 2.5.3 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:44:23.049+0000] {process_utils.py:190} INFO - pydantic-core 2.14.6 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:44:23.049+0000] {process_utils.py:190} INFO - Successfully installed absl-py-2.1.0 astunparse-1.6.3 boto3-1.28.0 botocore-1.31.85 entrypoints-0.4 flatbuffers-24.3.25 gast-0.4.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 h5py-3.11.0 keras-2.13.1 libclang-18.1.1 mlflow-2.10.2 numpy-1.24.3 opt-einsum-3.4.0 querystring-parser-1.2.4 s3transfer-0.6.2 tensorboard-2.13.0 tensorboard-data-server-0.7.2 tensorflow-2.13.0 tensorflow-estimator-2.13.0 tensorflow-io-gcs-filesystem-0.34.0 typing-extensions-4.5.0
[2024-11-18T18:44:23.113+0000] {process_utils.py:190} INFO - 
[2024-11-18T18:44:23.113+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 24.2 -> 24.3.1
[2024-11-18T18:44:23.114+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T18:44:23.299+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venviqupxdpr/bin/python /tmp/venv-callyj_sa3nb/script.py /tmp/venv-callyj_sa3nb/script.in /tmp/venv-callyj_sa3nb/script.out /tmp/venv-callyj_sa3nb/string_args.txt /tmp/venv-callyj_sa3nb/termination.log
[2024-11-18T18:44:23.303+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:44:24.257+0000] {process_utils.py:190} INFO - 2024-11-18 18:44:24.257669: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-11-18T18:44:24.258+0000] {process_utils.py:190} INFO - 2024-11-18 18:44:24.258823: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T18:44:24.281+0000] {process_utils.py:190} INFO - 2024-11-18 18:44:24.281333: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T18:44:24.282+0000] {process_utils.py:190} INFO - 2024-11-18 18:44:24.281689: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-11-18T18:44:24.282+0000] {process_utils.py:190} INFO - To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-11-18T18:44:24.791+0000] {process_utils.py:190} INFO - 2024-11-18 18:44:24.791805: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-11-18T18:44:26.061+0000] {process_utils.py:190} INFO -   1/308 [..............................] - ETA: 17s 94/308 [========>.....................] - ETA: 0s 197/308 [==================>...........] - ETA: 0s299/308 [============================>.] - ETA: 0s308/308 [==============================] - 0s 507us/step
[2024-11-18T18:44:26.315+0000] {process_utils.py:190} INFO -   1/308 [..............................] - ETA: 10s100/308 [========>.....................] - ETA: 0s 205/308 [==================>...........] - ETA: 0s307/308 [============================>.] - ETA: 0s308/308 [==============================] - 0s 491us/step
[2024-11-18T18:44:26.456+0000] {process_utils.py:190} INFO - Promoting challenger to champion.
[2024-11-18T18:44:26.457+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-11-18T18:44:26.457+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callyj_sa3nb/script.py", line 95, in <module>
[2024-11-18T18:44:26.457+0000] {process_utils.py:190} INFO -     res = evaluate_champion(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-18T18:44:26.458+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callyj_sa3nb/script.py", line 87, in evaluate_champion
[2024-11-18T18:44:26.458+0000] {process_utils.py:190} INFO -     client.set_registered_model_alias("spotify_model_prod", "champion", model_data.version)
[2024-11-18T18:44:26.458+0000] {process_utils.py:190} INFO - NameError: name 'model_data' is not defined
[2024-11-18T18:44:27.340+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
name 'model_data' is not defined
[2024-11-18T18:44:27.343+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_retrain_challenge_model_v3, task_id=evaluate_champion, execution_date=20241117T000000, start_date=20241118T184408, end_date=20241118T184427
[2024-11-18T18:44:27.351+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 107 for task evaluate_champion (Process returned non-zero exit status 1.
name 'model_data' is not defined; 22978)
[2024-11-18T18:44:27.366+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-18T18:44:27.375+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
