[2024-11-18T18:12:21.472+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model scheduled__2024-11-17T00:00:00+00:00 [queued]>
[2024-11-18T18:12:21.476+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model scheduled__2024-11-17T00:00:00+00:00 [queued]>
[2024-11-18T18:12:21.476+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-11-18T18:12:21.484+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_challenger_model> on 2024-11-17 00:00:00+00:00
[2024-11-18T18:12:21.486+0000] {standard_task_runner.py:60} INFO - Started process 5712 to run task
[2024-11-18T18:12:21.488+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_retrain_challenge_model_v3', 'train_challenger_model', 'scheduled__2024-11-17T00:00:00+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/retrain_music_model.py', '--cfg-path', '/tmp/tmpx4iscz5x']
[2024-11-18T18:12:21.489+0000] {standard_task_runner.py:88} INFO - Job 75: Subtask train_challenger_model
[2024-11-18T18:12:21.513+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model scheduled__2024-11-17T00:00:00+00:00 [running]> on host 98017b53a184
[2024-11-18T18:12:21.550+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_retrain_challenge_model_v3' AIRFLOW_CTX_TASK_ID='train_challenger_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-17T00:00:00+00:00'
[2024-11-18T18:12:21.551+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvf5is3cn6 --system-site-packages --python=python
[2024-11-18T18:12:21.554+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:12:21.886+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 116ms
[2024-11-18T18:12:21.887+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvf5is3cn6, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T18:12:21.887+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T18:12:21.887+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-11-18T18:12:21.887+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T18:12:21.904+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvf5is3cn6/bin/pip install -r /tmp/venvf5is3cn6/requirements.txt
[2024-11-18T18:12:21.908+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:12:22.840+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venvf5is3cn6/requirements.txt (line 1))
[2024-11-18T18:12:22.841+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T18:12:22.884+0000] {process_utils.py:190} INFO - Collecting mlflow==2.10.2 (from -r /tmp/venvf5is3cn6/requirements.txt (line 2))
[2024-11-18T18:12:22.886+0000] {process_utils.py:190} INFO -   Using cached mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
[2024-11-18T18:12:22.887+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvf5is3cn6/requirements.txt (line 3)) (2.0.3)
[2024-11-18T18:12:22.887+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn==1.3.2 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvf5is3cn6/requirements.txt (line 4)) (1.3.2)
[2024-11-18T18:12:22.987+0000] {process_utils.py:190} INFO - Collecting tensorflow==2.13.0 (from -r /tmp/venvf5is3cn6/requirements.txt (line 5))
[2024-11-18T18:12:22.989+0000] {process_utils.py:190} INFO -   Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
[2024-11-18T18:12:23.387+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venvf5is3cn6/requirements.txt (line 1))
[2024-11-18T18:12:23.388+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T18:12:23.389+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venvf5is3cn6/requirements.txt (line 1)) (0.10.0)
[2024-11-18T18:12:23.426+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venvf5is3cn6/requirements.txt (line 1))
[2024-11-18T18:12:23.428+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:12:23.478+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (8.1.7)
[2024-11-18T18:12:23.479+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (3.1.0)
[2024-11-18T18:12:23.495+0000] {process_utils.py:190} INFO - Collecting entrypoints<1 (from mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2))
[2024-11-18T18:12:23.496+0000] {process_utils.py:190} INFO -   Using cached entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
[2024-11-18T18:12:23.497+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=2.1.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (3.1.43)
[2024-11-18T18:12:23.497+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (6.0.1)
[2024-11-18T18:12:23.497+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<5,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (4.25.2)
[2024-11-18T18:12:23.498+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz<2024 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T18:12:23.498+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (2.31.0)
[2024-11-18T18:12:23.499+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (23.2)
[2024-11-18T18:12:23.499+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (6.11.0)
[2024-11-18T18:12:23.499+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (0.4.4)
[2024-11-18T18:12:23.500+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (1.13.1)
[2024-11-18T18:12:23.501+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (7.0.0)
[2024-11-18T18:12:23.501+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (2.2.5)
[2024-11-18T18:12:23.501+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (1.24.4)
[2024-11-18T18:12:23.502+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (1.10.1)
[2024-11-18T18:12:23.518+0000] {process_utils.py:190} INFO - Collecting querystring-parser<2 (from mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2))
[2024-11-18T18:12:23.519+0000] {process_utils.py:190} INFO -   Using cached querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
[2024-11-18T18:12:23.520+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (1.4.51)
[2024-11-18T18:12:23.520+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow<16,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (14.0.2)
[2024-11-18T18:12:23.520+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (3.5.2)
[2024-11-18T18:12:23.521+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (3.7.5)
[2024-11-18T18:12:23.522+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<22 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (21.2.0)
[2024-11-18T18:12:23.523+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (3.1.3)
[2024-11-18T18:12:23.576+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvf5is3cn6/requirements.txt (line 3)) (2.8.2)
[2024-11-18T18:12:23.577+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvf5is3cn6/requirements.txt (line 3)) (2023.4)
[2024-11-18T18:12:23.597+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvf5is3cn6/requirements.txt (line 4)) (1.4.2)
[2024-11-18T18:12:23.598+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvf5is3cn6/requirements.txt (line 4)) (3.5.0)
[2024-11-18T18:12:23.632+0000] {process_utils.py:190} INFO - Collecting absl-py>=1.0.0 (from tensorflow==2.13.0->-r /tmp/venvf5is3cn6/requirements.txt (line 5))
[2024-11-18T18:12:23.633+0000] {process_utils.py:190} INFO -   Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
[2024-11-18T18:12:23.650+0000] {process_utils.py:190} INFO - Collecting astunparse>=1.6.0 (from tensorflow==2.13.0->-r /tmp/venvf5is3cn6/requirements.txt (line 5))
[2024-11-18T18:12:23.651+0000] {process_utils.py:190} INFO -   Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
[2024-11-18T18:12:23.668+0000] {process_utils.py:190} INFO - Collecting flatbuffers>=23.1.21 (from tensorflow==2.13.0->-r /tmp/venvf5is3cn6/requirements.txt (line 5))
[2024-11-18T18:12:23.669+0000] {process_utils.py:190} INFO -   Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
[2024-11-18T18:12:23.689+0000] {process_utils.py:190} INFO - Collecting gast<=0.4.0,>=0.2.1 (from tensorflow==2.13.0->-r /tmp/venvf5is3cn6/requirements.txt (line 5))
[2024-11-18T18:12:23.690+0000] {process_utils.py:190} INFO -   Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
[2024-11-18T18:12:23.710+0000] {process_utils.py:190} INFO - Collecting google-pasta>=0.1.1 (from tensorflow==2.13.0->-r /tmp/venvf5is3cn6/requirements.txt (line 5))
[2024-11-18T18:12:23.711+0000] {process_utils.py:190} INFO -   Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
[2024-11-18T18:12:23.712+0000] {process_utils.py:190} INFO - Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvf5is3cn6/requirements.txt (line 5)) (1.60.0)
[2024-11-18T18:12:23.753+0000] {process_utils.py:190} INFO - Collecting h5py>=2.9.0 (from tensorflow==2.13.0->-r /tmp/venvf5is3cn6/requirements.txt (line 5))
[2024-11-18T18:12:23.754+0000] {process_utils.py:190} INFO -   Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
[2024-11-18T18:12:23.779+0000] {process_utils.py:190} INFO - Collecting keras<2.14,>=2.13.1 (from tensorflow==2.13.0->-r /tmp/venvf5is3cn6/requirements.txt (line 5))
[2024-11-18T18:12:23.781+0000] {process_utils.py:190} INFO -   Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
[2024-11-18T18:12:23.802+0000] {process_utils.py:190} INFO - Collecting libclang>=13.0.0 (from tensorflow==2.13.0->-r /tmp/venvf5is3cn6/requirements.txt (line 5))
[2024-11-18T18:12:23.803+0000] {process_utils.py:190} INFO -   Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
[2024-11-18T18:12:23.956+0000] {process_utils.py:190} INFO - Collecting numpy<2 (from mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2))
[2024-11-18T18:12:23.957+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-11-18T18:12:23.975+0000] {process_utils.py:190} INFO - Collecting opt-einsum>=2.3.2 (from tensorflow==2.13.0->-r /tmp/venvf5is3cn6/requirements.txt (line 5))
[2024-11-18T18:12:23.976+0000] {process_utils.py:190} INFO -   Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
[2024-11-18T18:12:23.977+0000] {process_utils.py:190} INFO - Requirement already satisfied: setuptools in /tmp/venvf5is3cn6/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvf5is3cn6/requirements.txt (line 5)) (69.0.2)
[2024-11-18T18:12:23.978+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.12.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvf5is3cn6/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:12:24.003+0000] {process_utils.py:190} INFO - Collecting tensorboard<2.14,>=2.13 (from tensorflow==2.13.0->-r /tmp/venvf5is3cn6/requirements.txt (line 5))
[2024-11-18T18:12:24.004+0000] {process_utils.py:190} INFO -   Using cached tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:12:24.024+0000] {process_utils.py:190} INFO - Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow==2.13.0->-r /tmp/venvf5is3cn6/requirements.txt (line 5))
[2024-11-18T18:12:24.025+0000] {process_utils.py:190} INFO -   Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
[2024-11-18T18:12:24.026+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.1.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvf5is3cn6/requirements.txt (line 5)) (2.4.0)
[2024-11-18T18:12:24.052+0000] {process_utils.py:190} INFO - Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow==2.13.0->-r /tmp/venvf5is3cn6/requirements.txt (line 5))
[2024-11-18T18:12:24.053+0000] {process_utils.py:190} INFO -   Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
[2024-11-18T18:12:24.054+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt>=1.11.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvf5is3cn6/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:12:24.109+0000] {process_utils.py:190} INFO - Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow==2.13.0->-r /tmp/venvf5is3cn6/requirements.txt (line 5))
[2024-11-18T18:12:24.111+0000] {process_utils.py:190} INFO -   Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
[2024-11-18T18:12:24.118+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (1.3.0)
[2024-11-18T18:12:24.122+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (5.13.0)
[2024-11-18T18:12:24.125+0000] {process_utils.py:190} INFO - Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venvf5is3cn6/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow==2.13.0->-r /tmp/venvf5is3cn6/requirements.txt (line 5)) (0.42.0)
[2024-11-18T18:12:24.130+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venvf5is3cn6/requirements.txt (line 1)) (1.26.18)
[2024-11-18T18:12:24.145+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (2.2.3)
[2024-11-18T18:12:24.145+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (2.1.2)
[2024-11-18T18:12:24.162+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (4.0.11)
[2024-11-18T18:12:24.187+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (3.17.0)
[2024-11-18T18:12:24.190+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (2.1.3)
[2024-11-18T18:12:24.214+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (1.1.1)
[2024-11-18T18:12:24.214+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (0.12.1)
[2024-11-18T18:12:24.215+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (4.54.1)
[2024-11-18T18:12:24.215+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (1.4.7)
[2024-11-18T18:12:24.224+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (10.4.0)
[2024-11-18T18:12:24.224+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (3.1.1)
[2024-11-18T18:12:24.267+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (3.3.2)
[2024-11-18T18:12:24.267+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (3.6)
[2024-11-18T18:12:24.268+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (2023.11.17)
[2024-11-18T18:12:24.457+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (3.0.3)
[2024-11-18T18:12:24.475+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth<3,>=1.6.3 in /home/***/.local/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvf5is3cn6/requirements.txt (line 5)) (2.26.2)
[2024-11-18T18:12:24.498+0000] {process_utils.py:190} INFO - Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvf5is3cn6/requirements.txt (line 5))
[2024-11-18T18:12:24.499+0000] {process_utils.py:190} INFO -   Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
[2024-11-18T18:12:24.528+0000] {process_utils.py:190} INFO - Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvf5is3cn6/requirements.txt (line 5))
[2024-11-18T18:12:24.529+0000] {process_utils.py:190} INFO -   Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
[2024-11-18T18:12:24.670+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvf5is3cn6/requirements.txt (line 2)) (5.0.1)
[2024-11-18T18:12:24.680+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvf5is3cn6/requirements.txt (line 5)) (5.3.2)
[2024-11-18T18:12:24.681+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvf5is3cn6/requirements.txt (line 5)) (0.3.0)
[2024-11-18T18:12:24.681+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvf5is3cn6/requirements.txt (line 5)) (4.9)
[2024-11-18T18:12:24.687+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvf5is3cn6/requirements.txt (line 5)) (1.3.1)
[2024-11-18T18:12:24.813+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvf5is3cn6/requirements.txt (line 5)) (0.5.1)
[2024-11-18T18:12:24.820+0000] {process_utils.py:190} INFO - Requirement already satisfied: oauthlib>=3.0.0 in /home/***/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvf5is3cn6/requirements.txt (line 5)) (3.2.2)
[2024-11-18T18:12:24.853+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T18:12:24.854+0000] {process_utils.py:190} INFO - Using cached mlflow-2.10.2-py3-none-any.whl (19.5 MB)
[2024-11-18T18:12:24.873+0000] {process_utils.py:190} INFO - Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
[2024-11-18T18:12:25.351+0000] {process_utils.py:190} INFO - Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
[2024-11-18T18:12:25.355+0000] {process_utils.py:190} INFO - Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
[2024-11-18T18:12:25.356+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T18:12:25.365+0000] {process_utils.py:190} INFO - Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
[2024-11-18T18:12:25.366+0000] {process_utils.py:190} INFO - Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
[2024-11-18T18:12:25.367+0000] {process_utils.py:190} INFO - Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
[2024-11-18T18:12:25.369+0000] {process_utils.py:190} INFO - Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
[2024-11-18T18:12:25.371+0000] {process_utils.py:190} INFO - Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
[2024-11-18T18:12:25.375+0000] {process_utils.py:190} INFO - Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)
[2024-11-18T18:12:25.377+0000] {process_utils.py:190} INFO - Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
[2024-11-18T18:12:25.401+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-11-18T18:12:25.418+0000] {process_utils.py:190} INFO - Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
[2024-11-18T18:12:25.419+0000] {process_utils.py:190} INFO - Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
[2024-11-18T18:12:25.420+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T18:12:25.421+0000] {process_utils.py:190} INFO - Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
[2024-11-18T18:12:25.428+0000] {process_utils.py:190} INFO - Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
[2024-11-18T18:12:25.429+0000] {process_utils.py:190} INFO - Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
[2024-11-18T18:12:25.433+0000] {process_utils.py:190} INFO - Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[2024-11-18T18:12:25.434+0000] {process_utils.py:190} INFO - Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
[2024-11-18T18:12:25.435+0000] {process_utils.py:190} INFO - Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
[2024-11-18T18:12:27.518+0000] {process_utils.py:190} INFO - Installing collected packages: libclang, flatbuffers, typing-extensions, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, querystring-parser, opt-einsum, numpy, keras, google-pasta, gast, entrypoints, astunparse, absl-py, h5py, botocore, s3transfer, google-auth-oauthlib, tensorboard, mlflow, boto3, tensorflow
[2024-11-18T18:12:27.769+0000] {process_utils.py:190} INFO -   Attempting uninstall: typing-extensions
[2024-11-18T18:12:27.770+0000] {process_utils.py:190} INFO -     Found existing installation: typing_extensions 4.9.0
[2024-11-18T18:12:27.770+0000] {process_utils.py:190} INFO -     Not uninstalling typing-extensions at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvf5is3cn6
[2024-11-18T18:12:27.771+0000] {process_utils.py:190} INFO -     Can't uninstall 'typing_extensions'. No files were found to uninstall.
[2024-11-18T18:12:28.032+0000] {process_utils.py:190} INFO -   Attempting uninstall: numpy
[2024-11-18T18:12:28.034+0000] {process_utils.py:190} INFO -     Found existing installation: numpy 1.24.4
[2024-11-18T18:12:28.034+0000] {process_utils.py:190} INFO -     Not uninstalling numpy at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvf5is3cn6
[2024-11-18T18:12:28.034+0000] {process_utils.py:190} INFO -     Can't uninstall 'numpy'. No files were found to uninstall.
[2024-11-18T18:12:29.710+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T18:12:29.711+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T18:12:29.711+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvf5is3cn6
[2024-11-18T18:12:29.711+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T18:12:30.168+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T18:12:30.169+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T18:12:30.170+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvf5is3cn6
[2024-11-18T18:12:30.170+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T18:12:30.194+0000] {process_utils.py:190} INFO -   Attempting uninstall: google-auth-oauthlib
[2024-11-18T18:12:30.195+0000] {process_utils.py:190} INFO -     Found existing installation: google-auth-oauthlib 1.2.0
[2024-11-18T18:12:30.195+0000] {process_utils.py:190} INFO -     Not uninstalling google-auth-oauthlib at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvf5is3cn6
[2024-11-18T18:12:30.195+0000] {process_utils.py:190} INFO -     Can't uninstall 'google-auth-oauthlib'. No files were found to uninstall.
[2024-11-18T18:12:30.422+0000] {process_utils.py:190} INFO -   Attempting uninstall: mlflow
[2024-11-18T18:12:30.424+0000] {process_utils.py:190} INFO -     Found existing installation: mlflow 2.17.0
[2024-11-18T18:12:30.424+0000] {process_utils.py:190} INFO -     Not uninstalling mlflow at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvf5is3cn6
[2024-11-18T18:12:30.424+0000] {process_utils.py:190} INFO -     Can't uninstall 'mlflow'. No files were found to uninstall.
[2024-11-18T18:12:31.043+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T18:12:31.043+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T18:12:31.044+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvf5is3cn6
[2024-11-18T18:12:31.044+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T18:12:38.403+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T18:12:38.404+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T18:12:38.405+0000] {process_utils.py:190} INFO - azure-core 1.29.6 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:12:38.405+0000] {process_utils.py:190} INFO - azure-mgmt-keyvault 10.3.1 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:12:38.405+0000] {process_utils.py:190} INFO - azure-mgmt-network 27.0.0 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:12:38.406+0000] {process_utils.py:190} INFO - graphene 3.4 requires typing-extensions<5,>=4.7.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:12:38.406+0000] {process_utils.py:190} INFO - pydantic 2.5.3 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:12:38.407+0000] {process_utils.py:190} INFO - pydantic-core 2.14.6 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:12:38.407+0000] {process_utils.py:190} INFO - Successfully installed absl-py-2.1.0 astunparse-1.6.3 boto3-1.28.0 botocore-1.31.85 entrypoints-0.4 flatbuffers-24.3.25 gast-0.4.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 h5py-3.11.0 keras-2.13.1 libclang-18.1.1 mlflow-2.10.2 numpy-1.24.3 opt-einsum-3.4.0 querystring-parser-1.2.4 s3transfer-0.6.2 tensorboard-2.13.0 tensorboard-data-server-0.7.2 tensorflow-2.13.0 tensorflow-estimator-2.13.0 tensorflow-io-gcs-filesystem-0.34.0 typing-extensions-4.5.0
[2024-11-18T18:12:38.483+0000] {process_utils.py:190} INFO - 
[2024-11-18T18:12:38.483+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.3.1
[2024-11-18T18:12:38.483+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T18:12:38.705+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvf5is3cn6/bin/python /tmp/venv-calll15wi2m0/script.py /tmp/venv-calll15wi2m0/script.in /tmp/venv-calll15wi2m0/script.out /tmp/venv-calll15wi2m0/string_args.txt /tmp/venv-calll15wi2m0/termination.log
[2024-11-18T18:12:38.709+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:12:39.687+0000] {process_utils.py:190} INFO - 2024-11-18 18:12:39.686862: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-11-18T18:12:39.687+0000] {process_utils.py:190} INFO - 2024-11-18 18:12:39.687890: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T18:12:39.709+0000] {process_utils.py:190} INFO - 2024-11-18 18:12:39.709170: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T18:12:39.709+0000] {process_utils.py:190} INFO - 2024-11-18 18:12:39.709432: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-11-18T18:12:39.710+0000] {process_utils.py:190} INFO - To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-11-18T18:12:40.208+0000] {process_utils.py:190} INFO - 2024-11-18 18:12:40.208351: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-11-18T18:12:41.260+0000] {process_utils.py:190} INFO - Epoch 1/10
[2024-11-18T18:12:42.194+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 3:30 - loss: 0.3716 50/575 [=>............................] - ETA: 0s - loss: 0.1404  100/575 [====>.........................] - ETA: 0s - loss: 0.1018170/575 [=======>......................] - ETA: 0s - loss: 0.0785247/575 [===========>..................] - ETA: 0s - loss: 0.0657330/575 [================>.............] - ETA: 0s - loss: 0.0566403/575 [====================>.........] - ETA: 0s - loss: 0.0510479/575 [=======================>......] - ETA: 0s - loss: 0.0468558/575 [============================>.] - ETA: 0s - loss: 0.0433575/575 [==============================] - 1s 989us/step - loss: 0.0426 - val_loss: 0.0073
[2024-11-18T18:12:42.195+0000] {process_utils.py:190} INFO - Epoch 2/10
[2024-11-18T18:12:42.648+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0228 83/575 [===>..........................] - ETA: 0s - loss: 0.0191159/575 [=======>......................] - ETA: 0s - loss: 0.0184234/575 [===========>..................] - ETA: 0s - loss: 0.0179313/575 [===============>..............] - ETA: 0s - loss: 0.0174390/575 [===================>..........] - ETA: 0s - loss: 0.0168467/575 [=======================>......] - ETA: 0s - loss: 0.0164543/575 [===========================>..] - ETA: 0s - loss: 0.0159575/575 [==============================] - 0s 789us/step - loss: 0.0158 - val_loss: 0.0047
[2024-11-18T18:12:42.648+0000] {process_utils.py:190} INFO - Epoch 3/10
[2024-11-18T18:12:43.104+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0117 76/575 [==>...........................] - ETA: 0s - loss: 0.0128150/575 [======>.......................] - ETA: 0s - loss: 0.0125226/575 [==========>...................] - ETA: 0s - loss: 0.0122306/575 [==============>...............] - ETA: 0s - loss: 0.0119387/575 [===================>..........] - ETA: 0s - loss: 0.0118460/575 [=======================>......] - ETA: 0s - loss: 0.0117535/575 [==========================>...] - ETA: 0s - loss: 0.0115575/575 [==============================] - 0s 793us/step - loss: 0.0115 - val_loss: 0.0044
[2024-11-18T18:12:43.105+0000] {process_utils.py:190} INFO - Epoch 4/10
[2024-11-18T18:12:43.536+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0112 76/575 [==>...........................] - ETA: 0s - loss: 0.0099151/575 [======>.......................] - ETA: 0s - loss: 0.0099229/575 [==========>...................] - ETA: 0s - loss: 0.0098314/575 [===============>..............] - ETA: 0s - loss: 0.0098400/575 [===================>..........] - ETA: 0s - loss: 0.0097482/575 [========================>.....] - ETA: 0s - loss: 0.0096571/575 [============================>.] - ETA: 0s - loss: 0.0094575/575 [==============================] - 0s 750us/step - loss: 0.0094 - val_loss: 0.0033
[2024-11-18T18:12:43.536+0000] {process_utils.py:190} INFO - Epoch 5/10
[2024-11-18T18:12:43.996+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0077 84/575 [===>..........................] - ETA: 0s - loss: 0.0088156/575 [=======>......................] - ETA: 0s - loss: 0.0088214/575 [==========>...................] - ETA: 0s - loss: 0.0087297/575 [==============>...............] - ETA: 0s - loss: 0.0086378/575 [==================>...........] - ETA: 0s - loss: 0.0085450/575 [======================>.......] - ETA: 0s - loss: 0.0084536/575 [==========================>...] - ETA: 0s - loss: 0.0083575/575 [==============================] - 0s 799us/step - loss: 0.0083 - val_loss: 0.0028
[2024-11-18T18:12:43.996+0000] {process_utils.py:190} INFO - Epoch 6/10
[2024-11-18T18:12:44.445+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0099 73/575 [==>...........................] - ETA: 0s - loss: 0.0080149/575 [======>.......................] - ETA: 0s - loss: 0.0077233/575 [===========>..................] - ETA: 0s - loss: 0.0076311/575 [===============>..............] - ETA: 0s - loss: 0.0076384/575 [===================>..........] - ETA: 0s - loss: 0.0075460/575 [=======================>......] - ETA: 0s - loss: 0.0075539/575 [===========================>..] - ETA: 0s - loss: 0.0075575/575 [==============================] - 0s 781us/step - loss: 0.0075 - val_loss: 0.0025
[2024-11-18T18:12:44.446+0000] {process_utils.py:190} INFO - Epoch 7/10
[2024-11-18T18:12:44.912+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0072 82/575 [===>..........................] - ETA: 0s - loss: 0.0075165/575 [=======>......................] - ETA: 0s - loss: 0.0074242/575 [===========>..................] - ETA: 0s - loss: 0.0074319/575 [===============>..............] - ETA: 0s - loss: 0.0073393/575 [===================>..........] - ETA: 0s - loss: 0.0073468/575 [=======================>......] - ETA: 0s - loss: 0.0073544/575 [===========================>..] - ETA: 0s - loss: 0.0072575/575 [==============================] - 0s 812us/step - loss: 0.0072 - val_loss: 0.0025
[2024-11-18T18:12:44.913+0000] {process_utils.py:190} INFO - Epoch 8/10
[2024-11-18T18:12:45.359+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0073 78/575 [===>..........................] - ETA: 0s - loss: 0.0072154/575 [=======>......................] - ETA: 0s - loss: 0.0071238/575 [===========>..................] - ETA: 0s - loss: 0.0070318/575 [===============>..............] - ETA: 0s - loss: 0.0069399/575 [===================>..........] - ETA: 0s - loss: 0.0069473/575 [=======================>......] - ETA: 0s - loss: 0.0069552/575 [===========================>..] - ETA: 0s - loss: 0.0069575/575 [==============================] - 0s 775us/step - loss: 0.0069 - val_loss: 0.0026
[2024-11-18T18:12:45.359+0000] {process_utils.py:190} INFO - Epoch 9/10
[2024-11-18T18:12:45.827+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0068 80/575 [===>..........................] - ETA: 0s - loss: 0.0067158/575 [=======>......................] - ETA: 0s - loss: 0.0067235/575 [===========>..................] - ETA: 0s - loss: 0.0068315/575 [===============>..............] - ETA: 0s - loss: 0.0068400/575 [===================>..........] - ETA: 0s - loss: 0.0068479/575 [=======================>......] - ETA: 0s - loss: 0.0069555/575 [===========================>..] - ETA: 0s - loss: 0.0069575/575 [==============================] - 0s 814us/step - loss: 0.0069 - val_loss: 0.0024
[2024-11-18T18:12:45.828+0000] {process_utils.py:190} INFO - Epoch 10/10
[2024-11-18T18:12:46.254+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0074 89/575 [===>..........................] - ETA: 0s - loss: 0.0066176/575 [========>.....................] - ETA: 0s - loss: 0.0066253/575 [============>.................] - ETA: 0s - loss: 0.0066332/575 [================>.............] - ETA: 0s - loss: 0.0066414/575 [====================>.........] - ETA: 0s - loss: 0.0066500/575 [=========================>....] - ETA: 0s - loss: 0.0066575/575 [==============================] - 0s 741us/step - loss: 0.0066 - val_loss: 0.0022
[2024-11-18T18:12:46.643+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 29s106/719 [===>..........................] - ETA: 0s 215/719 [=======>......................] - ETA: 0s333/719 [============>.................] - ETA: 0s445/719 [=================>............] - ETA: 0s550/719 [=====================>........] - ETA: 0s655/719 [==========================>...] - ETA: 0s719/719 [==============================] - 0s 458us/step
[2024-11-18T18:12:47.199+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 7s114/719 [===>..........................] - ETA: 0s217/719 [========>.....................] - ETA: 0s318/719 [============>.................] - ETA: 0s421/719 [================>.............] - ETA: 0s533/719 [=====================>........] - ETA: 0s643/719 [=========================>....] - ETA: 0s719/719 [==============================] - 0s 470us/step
[2024-11-18T18:12:47.288+0000] {process_utils.py:190} INFO - /tmp/venvf5is3cn6/lib/python3.8/site-packages/keras/src/engine/training.py:3000 UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
[2024-11-18T18:12:47.299+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-11-18T18:12:47.300+0000] {process_utils.py:190} INFO -   File "/tmp/venv-calll15wi2m0/script.py", line 96, in <module>
[2024-11-18T18:12:47.300+0000] {process_utils.py:190} INFO -     res = train_challenger_model(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-18T18:12:47.300+0000] {process_utils.py:190} INFO -   File "/tmp/venv-calll15wi2m0/script.py", line 82, in train_challenger_model
[2024-11-18T18:12:47.301+0000] {process_utils.py:190} INFO -     model.save(model_path)
[2024-11-18T18:12:47.301+0000] {process_utils.py:190} INFO -   File "/tmp/venvf5is3cn6/lib/python3.8/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
[2024-11-18T18:12:47.301+0000] {process_utils.py:190} INFO -     raise e.with_traceback(filtered_tb) from None
[2024-11-18T18:12:47.301+0000] {process_utils.py:190} INFO -   File "/tmp/venvf5is3cn6/lib/python3.8/site-packages/tensorflow/python/lib/io/file_io.py", line 513, in recursive_create_dir_v2
[2024-11-18T18:12:47.301+0000] {process_utils.py:190} INFO -     _pywrap_file_io.RecursivelyCreateDir(compat.path_to_bytes(path))
[2024-11-18T18:12:47.302+0000] {process_utils.py:190} INFO - tensorflow.python.framework.errors_impl.PermissionDeniedError: /models; Permission denied
[2024-11-18T18:12:48.194+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
/models; Permission denied
[2024-11-18T18:12:48.196+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=spotify_retrain_challenge_model_v3, task_id=train_challenger_model, execution_date=20241117T000000, start_date=20241118T181221, end_date=20241118T181248
[2024-11-18T18:12:48.203+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 75 for task train_challenger_model (Process returned non-zero exit status 1.
/models; Permission denied; 5712)
[2024-11-18T18:12:48.235+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-18T18:12:48.246+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
