[2024-11-18T21:29:42.893+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T21:29:42.203655+00:00 [queued]>
[2024-11-18T21:29:42.898+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T21:29:42.203655+00:00 [queued]>
[2024-11-18T21:29:42.898+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-11-18T21:29:42.905+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_challenger_model> on 2024-11-18 21:29:42.203655+00:00
[2024-11-18T21:29:42.908+0000] {standard_task_runner.py:60} INFO - Started process 5386 to run task
[2024-11-18T21:29:42.910+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_retrain_challenge_model_v3', 'train_challenger_model', 'manual__2024-11-18T21:29:42.203655+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/retrain_music_model.py', '--cfg-path', '/tmp/tmpog074m0u']
[2024-11-18T21:29:42.911+0000] {standard_task_runner.py:88} INFO - Job 134: Subtask train_challenger_model
[2024-11-18T21:29:42.935+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T21:29:42.203655+00:00 [running]> on host 46787693bc19
[2024-11-18T21:29:42.975+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_retrain_challenge_model_v3' AIRFLOW_CTX_TASK_ID='train_challenger_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T21:29:42.203655+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T21:29:42.203655+00:00'
[2024-11-18T21:29:42.976+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvmj8w36qj --system-site-packages --python=python
[2024-11-18T21:29:42.980+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T21:29:43.303+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 113ms
[2024-11-18T21:29:43.304+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvmj8w36qj, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T21:29:43.304+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T21:29:43.304+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-11-18T21:29:43.304+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T21:29:43.321+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvmj8w36qj/bin/pip install -r /tmp/venvmj8w36qj/requirements.txt
[2024-11-18T21:29:43.325+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T21:29:44.253+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venvmj8w36qj/requirements.txt (line 1))
[2024-11-18T21:29:44.254+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T21:29:44.294+0000] {process_utils.py:190} INFO - Collecting mlflow==2.10.2 (from -r /tmp/venvmj8w36qj/requirements.txt (line 2))
[2024-11-18T21:29:44.295+0000] {process_utils.py:190} INFO -   Using cached mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
[2024-11-18T21:29:44.296+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvmj8w36qj/requirements.txt (line 3)) (2.0.3)
[2024-11-18T21:29:44.296+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn==1.3.2 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvmj8w36qj/requirements.txt (line 4)) (1.3.2)
[2024-11-18T21:29:44.393+0000] {process_utils.py:190} INFO - Collecting tensorflow==2.13.0 (from -r /tmp/venvmj8w36qj/requirements.txt (line 5))
[2024-11-18T21:29:44.395+0000] {process_utils.py:190} INFO -   Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
[2024-11-18T21:29:44.817+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venvmj8w36qj/requirements.txt (line 1))
[2024-11-18T21:29:44.818+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T21:29:44.819+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venvmj8w36qj/requirements.txt (line 1)) (0.10.0)
[2024-11-18T21:29:44.848+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venvmj8w36qj/requirements.txt (line 1))
[2024-11-18T21:29:44.849+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T21:29:44.899+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (8.1.7)
[2024-11-18T21:29:44.899+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (3.1.0)
[2024-11-18T21:29:44.917+0000] {process_utils.py:190} INFO - Collecting entrypoints<1 (from mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2))
[2024-11-18T21:29:44.918+0000] {process_utils.py:190} INFO -   Using cached entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
[2024-11-18T21:29:44.919+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=2.1.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (3.1.43)
[2024-11-18T21:29:44.919+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (6.0.1)
[2024-11-18T21:29:44.919+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<5,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (4.25.2)
[2024-11-18T21:29:44.920+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz<2024 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T21:29:44.920+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (2.31.0)
[2024-11-18T21:29:44.921+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (23.2)
[2024-11-18T21:29:44.921+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (6.11.0)
[2024-11-18T21:29:44.921+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (0.4.4)
[2024-11-18T21:29:44.922+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (1.13.1)
[2024-11-18T21:29:44.923+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (7.0.0)
[2024-11-18T21:29:44.923+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (2.2.5)
[2024-11-18T21:29:44.923+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (1.24.4)
[2024-11-18T21:29:44.924+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (1.10.1)
[2024-11-18T21:29:44.938+0000] {process_utils.py:190} INFO - Collecting querystring-parser<2 (from mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2))
[2024-11-18T21:29:44.939+0000] {process_utils.py:190} INFO -   Using cached querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
[2024-11-18T21:29:44.940+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (1.4.51)
[2024-11-18T21:29:44.941+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow<16,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (14.0.2)
[2024-11-18T21:29:44.941+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (3.5.2)
[2024-11-18T21:29:44.942+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (3.7.5)
[2024-11-18T21:29:44.942+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<22 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (21.2.0)
[2024-11-18T21:29:44.943+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (3.1.3)
[2024-11-18T21:29:44.996+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvmj8w36qj/requirements.txt (line 3)) (2.8.2)
[2024-11-18T21:29:44.996+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvmj8w36qj/requirements.txt (line 3)) (2023.4)
[2024-11-18T21:29:45.017+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvmj8w36qj/requirements.txt (line 4)) (1.4.2)
[2024-11-18T21:29:45.017+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvmj8w36qj/requirements.txt (line 4)) (3.5.0)
[2024-11-18T21:29:45.052+0000] {process_utils.py:190} INFO - Collecting absl-py>=1.0.0 (from tensorflow==2.13.0->-r /tmp/venvmj8w36qj/requirements.txt (line 5))
[2024-11-18T21:29:45.053+0000] {process_utils.py:190} INFO -   Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
[2024-11-18T21:29:45.070+0000] {process_utils.py:190} INFO - Collecting astunparse>=1.6.0 (from tensorflow==2.13.0->-r /tmp/venvmj8w36qj/requirements.txt (line 5))
[2024-11-18T21:29:45.071+0000] {process_utils.py:190} INFO -   Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
[2024-11-18T21:29:45.088+0000] {process_utils.py:190} INFO - Collecting flatbuffers>=23.1.21 (from tensorflow==2.13.0->-r /tmp/venvmj8w36qj/requirements.txt (line 5))
[2024-11-18T21:29:45.089+0000] {process_utils.py:190} INFO -   Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
[2024-11-18T21:29:45.109+0000] {process_utils.py:190} INFO - Collecting gast<=0.4.0,>=0.2.1 (from tensorflow==2.13.0->-r /tmp/venvmj8w36qj/requirements.txt (line 5))
[2024-11-18T21:29:45.110+0000] {process_utils.py:190} INFO -   Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
[2024-11-18T21:29:45.128+0000] {process_utils.py:190} INFO - Collecting google-pasta>=0.1.1 (from tensorflow==2.13.0->-r /tmp/venvmj8w36qj/requirements.txt (line 5))
[2024-11-18T21:29:45.129+0000] {process_utils.py:190} INFO -   Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
[2024-11-18T21:29:45.130+0000] {process_utils.py:190} INFO - Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvmj8w36qj/requirements.txt (line 5)) (1.60.0)
[2024-11-18T21:29:45.170+0000] {process_utils.py:190} INFO - Collecting h5py>=2.9.0 (from tensorflow==2.13.0->-r /tmp/venvmj8w36qj/requirements.txt (line 5))
[2024-11-18T21:29:45.171+0000] {process_utils.py:190} INFO -   Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
[2024-11-18T21:29:45.199+0000] {process_utils.py:190} INFO - Collecting keras<2.14,>=2.13.1 (from tensorflow==2.13.0->-r /tmp/venvmj8w36qj/requirements.txt (line 5))
[2024-11-18T21:29:45.200+0000] {process_utils.py:190} INFO -   Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
[2024-11-18T21:29:45.220+0000] {process_utils.py:190} INFO - Collecting libclang>=13.0.0 (from tensorflow==2.13.0->-r /tmp/venvmj8w36qj/requirements.txt (line 5))
[2024-11-18T21:29:45.222+0000] {process_utils.py:190} INFO -   Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
[2024-11-18T21:29:45.375+0000] {process_utils.py:190} INFO - Collecting numpy<2 (from mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2))
[2024-11-18T21:29:45.377+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-11-18T21:29:45.393+0000] {process_utils.py:190} INFO - Collecting opt-einsum>=2.3.2 (from tensorflow==2.13.0->-r /tmp/venvmj8w36qj/requirements.txt (line 5))
[2024-11-18T21:29:45.394+0000] {process_utils.py:190} INFO -   Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
[2024-11-18T21:29:45.395+0000] {process_utils.py:190} INFO - Requirement already satisfied: setuptools in /tmp/venvmj8w36qj/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvmj8w36qj/requirements.txt (line 5)) (69.0.2)
[2024-11-18T21:29:45.395+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.12.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvmj8w36qj/requirements.txt (line 5)) (1.16.0)
[2024-11-18T21:29:45.421+0000] {process_utils.py:190} INFO - Collecting tensorboard<2.14,>=2.13 (from tensorflow==2.13.0->-r /tmp/venvmj8w36qj/requirements.txt (line 5))
[2024-11-18T21:29:45.423+0000] {process_utils.py:190} INFO -   Using cached tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T21:29:45.442+0000] {process_utils.py:190} INFO - Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow==2.13.0->-r /tmp/venvmj8w36qj/requirements.txt (line 5))
[2024-11-18T21:29:45.444+0000] {process_utils.py:190} INFO -   Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
[2024-11-18T21:29:45.445+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.1.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvmj8w36qj/requirements.txt (line 5)) (2.4.0)
[2024-11-18T21:29:45.468+0000] {process_utils.py:190} INFO - Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow==2.13.0->-r /tmp/venvmj8w36qj/requirements.txt (line 5))
[2024-11-18T21:29:45.470+0000] {process_utils.py:190} INFO -   Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
[2024-11-18T21:29:45.471+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt>=1.11.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvmj8w36qj/requirements.txt (line 5)) (1.16.0)
[2024-11-18T21:29:45.526+0000] {process_utils.py:190} INFO - Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow==2.13.0->-r /tmp/venvmj8w36qj/requirements.txt (line 5))
[2024-11-18T21:29:45.527+0000] {process_utils.py:190} INFO -   Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
[2024-11-18T21:29:45.534+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (1.3.0)
[2024-11-18T21:29:45.538+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (5.13.0)
[2024-11-18T21:29:45.540+0000] {process_utils.py:190} INFO - Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venvmj8w36qj/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow==2.13.0->-r /tmp/venvmj8w36qj/requirements.txt (line 5)) (0.42.0)
[2024-11-18T21:29:45.545+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venvmj8w36qj/requirements.txt (line 1)) (1.26.18)
[2024-11-18T21:29:45.559+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (2.2.3)
[2024-11-18T21:29:45.560+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (2.1.2)
[2024-11-18T21:29:45.578+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (4.0.11)
[2024-11-18T21:29:45.604+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (3.17.0)
[2024-11-18T21:29:45.607+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (2.1.3)
[2024-11-18T21:29:45.630+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (1.1.1)
[2024-11-18T21:29:45.631+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (0.12.1)
[2024-11-18T21:29:45.631+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (4.54.1)
[2024-11-18T21:29:45.632+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (1.4.7)
[2024-11-18T21:29:45.640+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (10.4.0)
[2024-11-18T21:29:45.641+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (3.1.1)
[2024-11-18T21:29:45.683+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (3.3.2)
[2024-11-18T21:29:45.683+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (3.6)
[2024-11-18T21:29:45.684+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (2023.11.17)
[2024-11-18T21:29:45.921+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (3.0.3)
[2024-11-18T21:29:45.938+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth<3,>=1.6.3 in /home/***/.local/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvmj8w36qj/requirements.txt (line 5)) (2.26.2)
[2024-11-18T21:29:45.960+0000] {process_utils.py:190} INFO - Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvmj8w36qj/requirements.txt (line 5))
[2024-11-18T21:29:45.961+0000] {process_utils.py:190} INFO -   Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
[2024-11-18T21:29:45.990+0000] {process_utils.py:190} INFO - Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvmj8w36qj/requirements.txt (line 5))
[2024-11-18T21:29:45.991+0000] {process_utils.py:190} INFO -   Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
[2024-11-18T21:29:46.132+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvmj8w36qj/requirements.txt (line 2)) (5.0.1)
[2024-11-18T21:29:46.142+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvmj8w36qj/requirements.txt (line 5)) (5.3.2)
[2024-11-18T21:29:46.143+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvmj8w36qj/requirements.txt (line 5)) (0.3.0)
[2024-11-18T21:29:46.143+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvmj8w36qj/requirements.txt (line 5)) (4.9)
[2024-11-18T21:29:46.150+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvmj8w36qj/requirements.txt (line 5)) (1.3.1)
[2024-11-18T21:29:46.278+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvmj8w36qj/requirements.txt (line 5)) (0.5.1)
[2024-11-18T21:29:46.285+0000] {process_utils.py:190} INFO - Requirement already satisfied: oauthlib>=3.0.0 in /home/***/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvmj8w36qj/requirements.txt (line 5)) (3.2.2)
[2024-11-18T21:29:46.317+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T21:29:46.318+0000] {process_utils.py:190} INFO - Using cached mlflow-2.10.2-py3-none-any.whl (19.5 MB)
[2024-11-18T21:29:46.336+0000] {process_utils.py:190} INFO - Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
[2024-11-18T21:29:46.820+0000] {process_utils.py:190} INFO - Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
[2024-11-18T21:29:46.822+0000] {process_utils.py:190} INFO - Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
[2024-11-18T21:29:46.823+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T21:29:46.835+0000] {process_utils.py:190} INFO - Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
[2024-11-18T21:29:46.836+0000] {process_utils.py:190} INFO - Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
[2024-11-18T21:29:46.837+0000] {process_utils.py:190} INFO - Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
[2024-11-18T21:29:46.838+0000] {process_utils.py:190} INFO - Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
[2024-11-18T21:29:46.839+0000] {process_utils.py:190} INFO - Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
[2024-11-18T21:29:46.846+0000] {process_utils.py:190} INFO - Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)
[2024-11-18T21:29:46.848+0000] {process_utils.py:190} INFO - Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
[2024-11-18T21:29:46.872+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-11-18T21:29:46.889+0000] {process_utils.py:190} INFO - Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
[2024-11-18T21:29:46.890+0000] {process_utils.py:190} INFO - Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
[2024-11-18T21:29:46.891+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T21:29:46.892+0000] {process_utils.py:190} INFO - Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
[2024-11-18T21:29:46.899+0000] {process_utils.py:190} INFO - Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
[2024-11-18T21:29:46.900+0000] {process_utils.py:190} INFO - Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
[2024-11-18T21:29:46.904+0000] {process_utils.py:190} INFO - Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[2024-11-18T21:29:46.905+0000] {process_utils.py:190} INFO - Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
[2024-11-18T21:29:46.906+0000] {process_utils.py:190} INFO - Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
[2024-11-18T21:29:48.987+0000] {process_utils.py:190} INFO - Installing collected packages: libclang, flatbuffers, typing-extensions, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, querystring-parser, opt-einsum, numpy, keras, google-pasta, gast, entrypoints, astunparse, absl-py, h5py, botocore, s3transfer, google-auth-oauthlib, tensorboard, mlflow, boto3, tensorflow
[2024-11-18T21:29:49.250+0000] {process_utils.py:190} INFO -   Attempting uninstall: typing-extensions
[2024-11-18T21:29:49.252+0000] {process_utils.py:190} INFO -     Found existing installation: typing_extensions 4.9.0
[2024-11-18T21:29:49.252+0000] {process_utils.py:190} INFO -     Not uninstalling typing-extensions at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvmj8w36qj
[2024-11-18T21:29:49.252+0000] {process_utils.py:190} INFO -     Can't uninstall 'typing_extensions'. No files were found to uninstall.
[2024-11-18T21:29:49.516+0000] {process_utils.py:190} INFO -   Attempting uninstall: numpy
[2024-11-18T21:29:49.517+0000] {process_utils.py:190} INFO -     Found existing installation: numpy 1.24.4
[2024-11-18T21:29:49.517+0000] {process_utils.py:190} INFO -     Not uninstalling numpy at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvmj8w36qj
[2024-11-18T21:29:49.518+0000] {process_utils.py:190} INFO -     Can't uninstall 'numpy'. No files were found to uninstall.
[2024-11-18T21:29:51.241+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T21:29:51.242+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T21:29:51.242+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvmj8w36qj
[2024-11-18T21:29:51.243+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T21:29:51.643+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T21:29:51.644+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T21:29:51.644+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvmj8w36qj
[2024-11-18T21:29:51.644+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T21:29:51.666+0000] {process_utils.py:190} INFO -   Attempting uninstall: google-auth-oauthlib
[2024-11-18T21:29:51.667+0000] {process_utils.py:190} INFO -     Found existing installation: google-auth-oauthlib 1.2.0
[2024-11-18T21:29:51.667+0000] {process_utils.py:190} INFO -     Not uninstalling google-auth-oauthlib at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvmj8w36qj
[2024-11-18T21:29:51.667+0000] {process_utils.py:190} INFO -     Can't uninstall 'google-auth-oauthlib'. No files were found to uninstall.
[2024-11-18T21:29:51.869+0000] {process_utils.py:190} INFO -   Attempting uninstall: mlflow
[2024-11-18T21:29:51.871+0000] {process_utils.py:190} INFO -     Found existing installation: mlflow 2.17.0
[2024-11-18T21:29:51.871+0000] {process_utils.py:190} INFO -     Not uninstalling mlflow at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvmj8w36qj
[2024-11-18T21:29:51.872+0000] {process_utils.py:190} INFO -     Can't uninstall 'mlflow'. No files were found to uninstall.
[2024-11-18T21:29:52.410+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T21:29:52.411+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T21:29:52.413+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvmj8w36qj
[2024-11-18T21:29:52.414+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T21:29:59.470+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T21:29:59.470+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T21:29:59.471+0000] {process_utils.py:190} INFO - azure-core 1.29.6 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:29:59.471+0000] {process_utils.py:190} INFO - azure-mgmt-keyvault 10.3.1 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:29:59.471+0000] {process_utils.py:190} INFO - azure-mgmt-network 27.0.0 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:29:59.472+0000] {process_utils.py:190} INFO - graphene 3.4 requires typing-extensions<5,>=4.7.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:29:59.472+0000] {process_utils.py:190} INFO - pydantic 2.5.3 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:29:59.472+0000] {process_utils.py:190} INFO - pydantic-core 2.14.6 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:29:59.473+0000] {process_utils.py:190} INFO - Successfully installed absl-py-2.1.0 astunparse-1.6.3 boto3-1.28.0 botocore-1.31.85 entrypoints-0.4 flatbuffers-24.3.25 gast-0.4.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 h5py-3.11.0 keras-2.13.1 libclang-18.1.1 mlflow-2.10.2 numpy-1.24.3 opt-einsum-3.4.0 querystring-parser-1.2.4 s3transfer-0.6.2 tensorboard-2.13.0 tensorboard-data-server-0.7.2 tensorflow-2.13.0 tensorflow-estimator-2.13.0 tensorflow-io-gcs-filesystem-0.34.0 typing-extensions-4.5.0
[2024-11-18T21:29:59.548+0000] {process_utils.py:190} INFO - 
[2024-11-18T21:29:59.549+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.3.1
[2024-11-18T21:29:59.549+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T21:29:59.737+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvmj8w36qj/bin/python /tmp/venv-calll6u2hcre/script.py /tmp/venv-calll6u2hcre/script.in /tmp/venv-calll6u2hcre/script.out /tmp/venv-calll6u2hcre/string_args.txt /tmp/venv-calll6u2hcre/termination.log
[2024-11-18T21:29:59.740+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T21:30:00.721+0000] {process_utils.py:190} INFO - 2024-11-18 21:30:00.721697: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-11-18T21:30:00.722+0000] {process_utils.py:190} INFO - 2024-11-18 21:30:00.722858: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T21:30:00.744+0000] {process_utils.py:190} INFO - 2024-11-18 21:30:00.743921: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T21:30:00.744+0000] {process_utils.py:190} INFO - 2024-11-18 21:30:00.744173: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-11-18T21:30:00.744+0000] {process_utils.py:190} INFO - To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-11-18T21:30:01.244+0000] {process_utils.py:190} INFO - 2024-11-18 21:30:01.244862: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-11-18T21:30:02.271+0000] {process_utils.py:190} INFO - Error loading data_info/song_embeddings.json from MinIO: Expecting value: line 1 column 1 (char 0)
[2024-11-18T21:30:02.272+0000] {process_utils.py:190} INFO - No existing embeddings found, initializing a new array.
[2024-11-18T21:30:02.272+0000] {process_utils.py:190} INFO - Epoch 1/10
[2024-11-18T21:30:03.138+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 3:27 - loss: 0.4108 56/575 [=>............................] - ETA: 0s - loss: 0.1404  124/575 [=====>........................] - ETA: 0s - loss: 0.0952208/575 [=========>....................] - ETA: 0s - loss: 0.0731295/575 [==============>...............] - ETA: 0s - loss: 0.0611383/575 [==================>...........] - ETA: 0s - loss: 0.0533467/575 [=======================>......] - ETA: 0s - loss: 0.0481551/575 [===========================>..] - ETA: 0s - loss: 0.0441575/575 [==============================] - 1s 882us/step - loss: 0.0431 - val_loss: 0.0079
[2024-11-18T21:30:03.139+0000] {process_utils.py:190} INFO - Epoch 2/10
[2024-11-18T21:30:03.552+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0180 83/575 [===>..........................] - ETA: 0s - loss: 0.0200168/575 [=======>......................] - ETA: 0s - loss: 0.0189255/575 [============>.................] - ETA: 0s - loss: 0.0183342/575 [================>.............] - ETA: 0s - loss: 0.0178429/575 [=====================>........] - ETA: 0s - loss: 0.0173512/575 [=========================>....] - ETA: 0s - loss: 0.0168575/575 [==============================] - 0s 719us/step - loss: 0.0165 - val_loss: 0.0054
[2024-11-18T21:30:03.553+0000] {process_utils.py:190} INFO - Epoch 3/10
[2024-11-18T21:30:03.982+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0159 86/575 [===>..........................] - ETA: 0s - loss: 0.0139174/575 [========>.....................] - ETA: 0s - loss: 0.0134251/575 [============>.................] - ETA: 0s - loss: 0.0131329/575 [================>.............] - ETA: 0s - loss: 0.0128411/575 [====================>.........] - ETA: 0s - loss: 0.0125492/575 [========================>.....] - ETA: 0s - loss: 0.0123575/575 [==============================] - ETA: 0s - loss: 0.0121575/575 [==============================] - 0s 746us/step - loss: 0.0121 - val_loss: 0.0045
[2024-11-18T21:30:03.982+0000] {process_utils.py:190} INFO - Epoch 4/10
[2024-11-18T21:30:04.389+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0102 84/575 [===>..........................] - ETA: 0s - loss: 0.0105170/575 [=======>......................] - ETA: 0s - loss: 0.0102257/575 [============>.................] - ETA: 0s - loss: 0.0101346/575 [=================>............] - ETA: 0s - loss: 0.0100434/575 [=====================>........] - ETA: 0s - loss: 0.0098521/575 [==========================>...] - ETA: 0s - loss: 0.0097575/575 [==============================] - 0s 708us/step - loss: 0.0097 - val_loss: 0.0037
[2024-11-18T21:30:04.390+0000] {process_utils.py:190} INFO - Epoch 5/10
[2024-11-18T21:30:04.797+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0089 87/575 [===>..........................] - ETA: 0s - loss: 0.0091176/575 [========>.....................] - ETA: 0s - loss: 0.0087266/575 [============>.................] - ETA: 0s - loss: 0.0086354/575 [=================>............] - ETA: 0s - loss: 0.0086439/575 [=====================>........] - ETA: 0s - loss: 0.0085524/575 [==========================>...] - ETA: 0s - loss: 0.0084575/575 [==============================] - 0s 709us/step - loss: 0.0084 - val_loss: 0.0030
[2024-11-18T21:30:04.797+0000] {process_utils.py:190} INFO - Epoch 6/10
[2024-11-18T21:30:05.209+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0080 85/575 [===>..........................] - ETA: 0s - loss: 0.0079170/575 [=======>......................] - ETA: 0s - loss: 0.0078258/575 [============>.................] - ETA: 0s - loss: 0.0078340/575 [================>.............] - ETA: 0s - loss: 0.0077424/575 [=====================>........] - ETA: 0s - loss: 0.0077509/575 [=========================>....] - ETA: 0s - loss: 0.0077575/575 [==============================] - 0s 716us/step - loss: 0.0076 - val_loss: 0.0028
[2024-11-18T21:30:05.210+0000] {process_utils.py:190} INFO - Epoch 7/10
[2024-11-18T21:30:05.626+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0062 86/575 [===>..........................] - ETA: 0s - loss: 0.0074173/575 [========>.....................] - ETA: 0s - loss: 0.0074255/575 [============>.................] - ETA: 0s - loss: 0.0074340/575 [================>.............] - ETA: 0s - loss: 0.0073422/575 [=====================>........] - ETA: 0s - loss: 0.0073511/575 [=========================>....] - ETA: 0s - loss: 0.0073575/575 [==============================] - 0s 725us/step - loss: 0.0073 - val_loss: 0.0025
[2024-11-18T21:30:05.627+0000] {process_utils.py:190} INFO - Epoch 8/10
[2024-11-18T21:30:06.036+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0077 86/575 [===>..........................] - ETA: 0s - loss: 0.0068174/575 [========>.....................] - ETA: 0s - loss: 0.0070263/575 [============>.................] - ETA: 0s - loss: 0.0071353/575 [=================>............] - ETA: 0s - loss: 0.0071441/575 [======================>.......] - ETA: 0s - loss: 0.0071522/575 [==========================>...] - ETA: 0s - loss: 0.0070575/575 [==============================] - 0s 711us/step - loss: 0.0070 - val_loss: 0.0024
[2024-11-18T21:30:06.036+0000] {process_utils.py:190} INFO - Epoch 9/10
[2024-11-18T21:30:06.450+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0074 89/575 [===>..........................] - ETA: 0s - loss: 0.0067178/575 [========>.....................] - ETA: 0s - loss: 0.0068260/575 [============>.................] - ETA: 0s - loss: 0.0068348/575 [=================>............] - ETA: 0s - loss: 0.0068434/575 [=====================>........] - ETA: 0s - loss: 0.0068520/575 [==========================>...] - ETA: 0s - loss: 0.0068575/575 [==============================] - 0s 719us/step - loss: 0.0068 - val_loss: 0.0025
[2024-11-18T21:30:06.450+0000] {process_utils.py:190} INFO - Epoch 10/10
[2024-11-18T21:30:06.890+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0083 78/575 [===>..........................] - ETA: 0s - loss: 0.0069157/575 [=======>......................] - ETA: 0s - loss: 0.0068239/575 [===========>..................] - ETA: 0s - loss: 0.0068317/575 [===============>..............] - ETA: 0s - loss: 0.0068400/575 [===================>..........] - ETA: 0s - loss: 0.0067476/575 [=======================>......] - ETA: 0s - loss: 0.0067553/575 [===========================>..] - ETA: 0s - loss: 0.0067575/575 [==============================] - 0s 765us/step - loss: 0.0067 - val_loss: 0.0024
[2024-11-18T21:30:07.262+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 28s110/719 [===>..........................] - ETA: 0s 224/719 [========>.....................] - ETA: 0s344/719 [=============>................] - ETA: 0s459/719 [==================>...........] - ETA: 0s575/719 [======================>.......] - ETA: 0s691/719 [===========================>..] - ETA: 0s719/719 [==============================] - 0s 436us/step
[2024-11-18T21:30:07.362+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-11-18T21:30:07.362+0000] {process_utils.py:190} INFO -   File "/tmp/venv-calll6u2hcre/script.py", line 142, in <module>
[2024-11-18T21:30:07.363+0000] {process_utils.py:190} INFO -     res = train_challenger_model(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-18T21:30:07.363+0000] {process_utils.py:190} INFO -   File "/tmp/venv-calll6u2hcre/script.py", line 112, in train_challenger_model
[2024-11-18T21:30:07.363+0000] {process_utils.py:190} INFO -     updated_embeddings = np.concatenate((embeddings, new_embeddings), axis=0)
[2024-11-18T21:30:07.363+0000] {process_utils.py:190} INFO -   File "<__array_function__ internals>", line 200, in concatenate
[2024-11-18T21:30:07.364+0000] {process_utils.py:190} INFO - ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 32 and the array at index 1 has size 11
[2024-11-18T21:30:08.201+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 32 and the array at index 1 has size 11
[2024-11-18T21:30:08.203+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_retrain_challenge_model_v3, task_id=train_challenger_model, execution_date=20241118T212942, start_date=20241118T212942, end_date=20241118T213008
[2024-11-18T21:30:08.209+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 134 for task train_challenger_model (Process returned non-zero exit status 1.
all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 32 and the array at index 1 has size 11; 5386)
[2024-11-18T21:30:08.245+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-18T21:30:08.261+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
