[2024-11-18T17:35:12.927+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_recommender_dag_v3.train_embedding_model manual__2024-11-18T17:35:12.582627+00:00 [queued]>
[2024-11-18T17:35:12.933+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_recommender_dag_v3.train_embedding_model manual__2024-11-18T17:35:12.582627+00:00 [queued]>
[2024-11-18T17:35:12.933+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-11-18T17:35:12.941+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_embedding_model> on 2024-11-18 17:35:12.582627+00:00
[2024-11-18T17:35:12.942+0000] {standard_task_runner.py:60} INFO - Started process 926 to run task
[2024-11-18T17:35:12.944+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_recommender_dag_v3', 'train_embedding_model', 'manual__2024-11-18T17:35:12.582627+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/music_process.py', '--cfg-path', '/tmp/tmpc1kiluof']
[2024-11-18T17:35:12.945+0000] {standard_task_runner.py:88} INFO - Job 38: Subtask train_embedding_model
[2024-11-18T17:35:12.976+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_recommender_dag_v3.train_embedding_model manual__2024-11-18T17:35:12.582627+00:00 [running]> on host 98017b53a184
[2024-11-18T17:35:13.019+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_recommender_dag_v3' AIRFLOW_CTX_TASK_ID='train_embedding_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T17:35:12.582627+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T17:35:12.582627+00:00'
[2024-11-18T17:35:13.021+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv8opcsl2k --system-site-packages --python=python
[2024-11-18T17:35:13.024+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T17:35:13.347+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 115ms
[2024-11-18T17:35:13.347+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venv8opcsl2k, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T17:35:13.348+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T17:35:13.348+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-11-18T17:35:13.348+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T17:35:13.363+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv8opcsl2k/bin/pip install -r /tmp/venv8opcsl2k/requirements.txt
[2024-11-18T17:35:13.367+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T17:35:14.286+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venv8opcsl2k/requirements.txt (line 1))
[2024-11-18T17:35:14.288+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T17:35:14.324+0000] {process_utils.py:190} INFO - Collecting mlflow==2.10.2 (from -r /tmp/venv8opcsl2k/requirements.txt (line 2))
[2024-11-18T17:35:14.325+0000] {process_utils.py:190} INFO -   Using cached mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
[2024-11-18T17:35:14.326+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv8opcsl2k/requirements.txt (line 3)) (2.0.3)
[2024-11-18T17:35:14.425+0000] {process_utils.py:190} INFO - Collecting tensorflow==2.13.0 (from -r /tmp/venv8opcsl2k/requirements.txt (line 4))
[2024-11-18T17:35:14.426+0000] {process_utils.py:190} INFO -   Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
[2024-11-18T17:35:14.815+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venv8opcsl2k/requirements.txt (line 1))
[2024-11-18T17:35:14.816+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T17:35:14.817+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venv8opcsl2k/requirements.txt (line 1)) (0.10.0)
[2024-11-18T17:35:14.840+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venv8opcsl2k/requirements.txt (line 1))
[2024-11-18T17:35:14.841+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T17:35:14.888+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (8.1.7)
[2024-11-18T17:35:14.888+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (3.1.0)
[2024-11-18T17:35:14.905+0000] {process_utils.py:190} INFO - Collecting entrypoints<1 (from mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2))
[2024-11-18T17:35:14.907+0000] {process_utils.py:190} INFO -   Using cached entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
[2024-11-18T17:35:14.907+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=2.1.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (3.1.43)
[2024-11-18T17:35:14.908+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (6.0.1)
[2024-11-18T17:35:14.908+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<5,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (4.25.2)
[2024-11-18T17:35:14.909+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz<2024 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T17:35:14.909+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (2.31.0)
[2024-11-18T17:35:14.910+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (23.2)
[2024-11-18T17:35:14.910+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (6.11.0)
[2024-11-18T17:35:14.910+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (0.4.4)
[2024-11-18T17:35:14.911+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (1.13.1)
[2024-11-18T17:35:14.911+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (7.0.0)
[2024-11-18T17:35:14.912+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (2.2.5)
[2024-11-18T17:35:14.912+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (1.24.4)
[2024-11-18T17:35:14.913+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (1.10.1)
[2024-11-18T17:35:14.928+0000] {process_utils.py:190} INFO - Collecting querystring-parser<2 (from mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2))
[2024-11-18T17:35:14.929+0000] {process_utils.py:190} INFO -   Using cached querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
[2024-11-18T17:35:14.930+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (1.4.51)
[2024-11-18T17:35:14.930+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (1.3.2)
[2024-11-18T17:35:14.931+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow<16,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (14.0.2)
[2024-11-18T17:35:14.931+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (3.5.2)
[2024-11-18T17:35:14.931+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (3.7.5)
[2024-11-18T17:35:14.932+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<22 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (21.2.0)
[2024-11-18T17:35:14.933+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (3.1.3)
[2024-11-18T17:35:14.985+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venv8opcsl2k/requirements.txt (line 3)) (2.8.2)
[2024-11-18T17:35:14.985+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venv8opcsl2k/requirements.txt (line 3)) (2023.4)
[2024-11-18T17:35:15.018+0000] {process_utils.py:190} INFO - Collecting absl-py>=1.0.0 (from tensorflow==2.13.0->-r /tmp/venv8opcsl2k/requirements.txt (line 4))
[2024-11-18T17:35:15.019+0000] {process_utils.py:190} INFO -   Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
[2024-11-18T17:35:15.035+0000] {process_utils.py:190} INFO - Collecting astunparse>=1.6.0 (from tensorflow==2.13.0->-r /tmp/venv8opcsl2k/requirements.txt (line 4))
[2024-11-18T17:35:15.036+0000] {process_utils.py:190} INFO -   Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
[2024-11-18T17:35:15.053+0000] {process_utils.py:190} INFO - Collecting flatbuffers>=23.1.21 (from tensorflow==2.13.0->-r /tmp/venv8opcsl2k/requirements.txt (line 4))
[2024-11-18T17:35:15.054+0000] {process_utils.py:190} INFO -   Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
[2024-11-18T17:35:15.074+0000] {process_utils.py:190} INFO - Collecting gast<=0.4.0,>=0.2.1 (from tensorflow==2.13.0->-r /tmp/venv8opcsl2k/requirements.txt (line 4))
[2024-11-18T17:35:15.075+0000] {process_utils.py:190} INFO -   Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
[2024-11-18T17:35:15.093+0000] {process_utils.py:190} INFO - Collecting google-pasta>=0.1.1 (from tensorflow==2.13.0->-r /tmp/venv8opcsl2k/requirements.txt (line 4))
[2024-11-18T17:35:15.094+0000] {process_utils.py:190} INFO -   Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
[2024-11-18T17:35:15.095+0000] {process_utils.py:190} INFO - Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv8opcsl2k/requirements.txt (line 4)) (1.60.0)
[2024-11-18T17:35:15.137+0000] {process_utils.py:190} INFO - Collecting h5py>=2.9.0 (from tensorflow==2.13.0->-r /tmp/venv8opcsl2k/requirements.txt (line 4))
[2024-11-18T17:35:15.138+0000] {process_utils.py:190} INFO -   Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
[2024-11-18T17:35:15.164+0000] {process_utils.py:190} INFO - Collecting keras<2.14,>=2.13.1 (from tensorflow==2.13.0->-r /tmp/venv8opcsl2k/requirements.txt (line 4))
[2024-11-18T17:35:15.165+0000] {process_utils.py:190} INFO -   Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
[2024-11-18T17:35:15.185+0000] {process_utils.py:190} INFO - Collecting libclang>=13.0.0 (from tensorflow==2.13.0->-r /tmp/venv8opcsl2k/requirements.txt (line 4))
[2024-11-18T17:35:15.186+0000] {process_utils.py:190} INFO -   Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
[2024-11-18T17:35:15.333+0000] {process_utils.py:190} INFO - Collecting numpy<2 (from mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2))
[2024-11-18T17:35:15.335+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-11-18T17:35:15.353+0000] {process_utils.py:190} INFO - Collecting opt-einsum>=2.3.2 (from tensorflow==2.13.0->-r /tmp/venv8opcsl2k/requirements.txt (line 4))
[2024-11-18T17:35:15.354+0000] {process_utils.py:190} INFO -   Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
[2024-11-18T17:35:15.355+0000] {process_utils.py:190} INFO - Requirement already satisfied: setuptools in /tmp/venv8opcsl2k/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv8opcsl2k/requirements.txt (line 4)) (69.0.2)
[2024-11-18T17:35:15.356+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.12.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv8opcsl2k/requirements.txt (line 4)) (1.16.0)
[2024-11-18T17:35:15.382+0000] {process_utils.py:190} INFO - Collecting tensorboard<2.14,>=2.13 (from tensorflow==2.13.0->-r /tmp/venv8opcsl2k/requirements.txt (line 4))
[2024-11-18T17:35:15.383+0000] {process_utils.py:190} INFO -   Using cached tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T17:35:15.403+0000] {process_utils.py:190} INFO - Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow==2.13.0->-r /tmp/venv8opcsl2k/requirements.txt (line 4))
[2024-11-18T17:35:15.405+0000] {process_utils.py:190} INFO -   Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
[2024-11-18T17:35:15.406+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.1.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv8opcsl2k/requirements.txt (line 4)) (2.4.0)
[2024-11-18T17:35:15.429+0000] {process_utils.py:190} INFO - Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow==2.13.0->-r /tmp/venv8opcsl2k/requirements.txt (line 4))
[2024-11-18T17:35:15.430+0000] {process_utils.py:190} INFO -   Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
[2024-11-18T17:35:15.431+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt>=1.11.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv8opcsl2k/requirements.txt (line 4)) (1.16.0)
[2024-11-18T17:35:15.485+0000] {process_utils.py:190} INFO - Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow==2.13.0->-r /tmp/venv8opcsl2k/requirements.txt (line 4))
[2024-11-18T17:35:15.486+0000] {process_utils.py:190} INFO -   Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
[2024-11-18T17:35:15.493+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (1.3.0)
[2024-11-18T17:35:15.497+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (5.13.0)
[2024-11-18T17:35:15.499+0000] {process_utils.py:190} INFO - Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venv8opcsl2k/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow==2.13.0->-r /tmp/venv8opcsl2k/requirements.txt (line 4)) (0.42.0)
[2024-11-18T17:35:15.505+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venv8opcsl2k/requirements.txt (line 1)) (1.26.18)
[2024-11-18T17:35:15.519+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (2.2.3)
[2024-11-18T17:35:15.519+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (2.1.2)
[2024-11-18T17:35:15.536+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (4.0.11)
[2024-11-18T17:35:15.570+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (3.17.0)
[2024-11-18T17:35:15.573+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (2.1.3)
[2024-11-18T17:35:15.594+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (1.1.1)
[2024-11-18T17:35:15.595+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (0.12.1)
[2024-11-18T17:35:15.595+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (4.54.1)
[2024-11-18T17:35:15.596+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (1.4.7)
[2024-11-18T17:35:15.604+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (10.4.0)
[2024-11-18T17:35:15.605+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (3.1.1)
[2024-11-18T17:35:15.647+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (3.3.2)
[2024-11-18T17:35:15.647+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (3.6)
[2024-11-18T17:35:15.648+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (2023.11.17)
[2024-11-18T17:35:15.786+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (1.4.2)
[2024-11-18T17:35:15.787+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (3.5.0)
[2024-11-18T17:35:15.865+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (3.0.3)
[2024-11-18T17:35:15.883+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth<3,>=1.6.3 in /home/***/.local/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv8opcsl2k/requirements.txt (line 4)) (2.26.2)
[2024-11-18T17:35:15.903+0000] {process_utils.py:190} INFO - Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv8opcsl2k/requirements.txt (line 4))
[2024-11-18T17:35:15.904+0000] {process_utils.py:190} INFO -   Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
[2024-11-18T17:35:15.938+0000] {process_utils.py:190} INFO - Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv8opcsl2k/requirements.txt (line 4))
[2024-11-18T17:35:15.940+0000] {process_utils.py:190} INFO -   Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
[2024-11-18T17:35:16.081+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venv8opcsl2k/requirements.txt (line 2)) (5.0.1)
[2024-11-18T17:35:16.092+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv8opcsl2k/requirements.txt (line 4)) (5.3.2)
[2024-11-18T17:35:16.092+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv8opcsl2k/requirements.txt (line 4)) (0.3.0)
[2024-11-18T17:35:16.093+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv8opcsl2k/requirements.txt (line 4)) (4.9)
[2024-11-18T17:35:16.100+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv8opcsl2k/requirements.txt (line 4)) (1.3.1)
[2024-11-18T17:35:16.234+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv8opcsl2k/requirements.txt (line 4)) (0.5.1)
[2024-11-18T17:35:16.242+0000] {process_utils.py:190} INFO - Requirement already satisfied: oauthlib>=3.0.0 in /home/***/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv8opcsl2k/requirements.txt (line 4)) (3.2.2)
[2024-11-18T17:35:16.275+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T17:35:16.276+0000] {process_utils.py:190} INFO - Using cached mlflow-2.10.2-py3-none-any.whl (19.5 MB)
[2024-11-18T17:35:16.296+0000] {process_utils.py:190} INFO - Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
[2024-11-18T17:35:16.760+0000] {process_utils.py:190} INFO - Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
[2024-11-18T17:35:16.761+0000] {process_utils.py:190} INFO - Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
[2024-11-18T17:35:16.762+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T17:35:16.774+0000] {process_utils.py:190} INFO - Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
[2024-11-18T17:35:16.775+0000] {process_utils.py:190} INFO - Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
[2024-11-18T17:35:16.777+0000] {process_utils.py:190} INFO - Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
[2024-11-18T17:35:16.778+0000] {process_utils.py:190} INFO - Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
[2024-11-18T17:35:16.779+0000] {process_utils.py:190} INFO - Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
[2024-11-18T17:35:16.785+0000] {process_utils.py:190} INFO - Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)
[2024-11-18T17:35:16.788+0000] {process_utils.py:190} INFO - Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
[2024-11-18T17:35:16.813+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-11-18T17:35:16.830+0000] {process_utils.py:190} INFO - Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
[2024-11-18T17:35:16.832+0000] {process_utils.py:190} INFO - Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
[2024-11-18T17:35:16.833+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T17:35:16.836+0000] {process_utils.py:190} INFO - Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
[2024-11-18T17:35:16.840+0000] {process_utils.py:190} INFO - Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
[2024-11-18T17:35:16.842+0000] {process_utils.py:190} INFO - Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
[2024-11-18T17:35:16.845+0000] {process_utils.py:190} INFO - Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[2024-11-18T17:35:16.847+0000] {process_utils.py:190} INFO - Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
[2024-11-18T17:35:16.848+0000] {process_utils.py:190} INFO - Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
[2024-11-18T17:35:18.989+0000] {process_utils.py:190} INFO - Installing collected packages: libclang, flatbuffers, typing-extensions, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, querystring-parser, opt-einsum, numpy, keras, google-pasta, gast, entrypoints, astunparse, absl-py, h5py, botocore, s3transfer, google-auth-oauthlib, tensorboard, mlflow, boto3, tensorflow
[2024-11-18T17:35:19.237+0000] {process_utils.py:190} INFO -   Attempting uninstall: typing-extensions
[2024-11-18T17:35:19.239+0000] {process_utils.py:190} INFO -     Found existing installation: typing_extensions 4.9.0
[2024-11-18T17:35:19.239+0000] {process_utils.py:190} INFO -     Not uninstalling typing-extensions at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv8opcsl2k
[2024-11-18T17:35:19.239+0000] {process_utils.py:190} INFO -     Can't uninstall 'typing_extensions'. No files were found to uninstall.
[2024-11-18T17:35:19.508+0000] {process_utils.py:190} INFO -   Attempting uninstall: numpy
[2024-11-18T17:35:19.510+0000] {process_utils.py:190} INFO -     Found existing installation: numpy 1.24.4
[2024-11-18T17:35:19.510+0000] {process_utils.py:190} INFO -     Not uninstalling numpy at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv8opcsl2k
[2024-11-18T17:35:19.510+0000] {process_utils.py:190} INFO -     Can't uninstall 'numpy'. No files were found to uninstall.
[2024-11-18T17:35:21.221+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T17:35:21.222+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T17:35:21.222+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv8opcsl2k
[2024-11-18T17:35:21.222+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T17:35:21.641+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T17:35:21.643+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T17:35:21.643+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv8opcsl2k
[2024-11-18T17:35:21.643+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T17:35:21.665+0000] {process_utils.py:190} INFO -   Attempting uninstall: google-auth-oauthlib
[2024-11-18T17:35:21.666+0000] {process_utils.py:190} INFO -     Found existing installation: google-auth-oauthlib 1.2.0
[2024-11-18T17:35:21.667+0000] {process_utils.py:190} INFO -     Not uninstalling google-auth-oauthlib at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv8opcsl2k
[2024-11-18T17:35:21.667+0000] {process_utils.py:190} INFO -     Can't uninstall 'google-auth-oauthlib'. No files were found to uninstall.
[2024-11-18T17:35:21.868+0000] {process_utils.py:190} INFO -   Attempting uninstall: mlflow
[2024-11-18T17:35:21.869+0000] {process_utils.py:190} INFO -     Found existing installation: mlflow 2.17.0
[2024-11-18T17:35:21.870+0000] {process_utils.py:190} INFO -     Not uninstalling mlflow at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv8opcsl2k
[2024-11-18T17:35:21.870+0000] {process_utils.py:190} INFO -     Can't uninstall 'mlflow'. No files were found to uninstall.
[2024-11-18T17:35:22.430+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T17:35:22.431+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T17:35:22.432+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv8opcsl2k
[2024-11-18T17:35:22.432+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T17:35:29.759+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T17:35:29.760+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T17:35:29.762+0000] {process_utils.py:190} INFO - azure-core 1.29.6 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:35:29.762+0000] {process_utils.py:190} INFO - azure-mgmt-keyvault 10.3.1 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:35:29.763+0000] {process_utils.py:190} INFO - azure-mgmt-network 27.0.0 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:35:29.763+0000] {process_utils.py:190} INFO - graphene 3.4 requires typing-extensions<5,>=4.7.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:35:29.764+0000] {process_utils.py:190} INFO - pydantic 2.5.3 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:35:29.764+0000] {process_utils.py:190} INFO - pydantic-core 2.14.6 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:35:29.765+0000] {process_utils.py:190} INFO - Successfully installed absl-py-2.1.0 astunparse-1.6.3 boto3-1.28.0 botocore-1.31.85 entrypoints-0.4 flatbuffers-24.3.25 gast-0.4.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 h5py-3.11.0 keras-2.13.1 libclang-18.1.1 mlflow-2.10.2 numpy-1.24.3 opt-einsum-3.4.0 querystring-parser-1.2.4 s3transfer-0.6.2 tensorboard-2.13.0 tensorboard-data-server-0.7.2 tensorflow-2.13.0 tensorflow-estimator-2.13.0 tensorflow-io-gcs-filesystem-0.34.0 typing-extensions-4.5.0
[2024-11-18T17:35:29.836+0000] {process_utils.py:190} INFO - 
[2024-11-18T17:35:29.837+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.3.1
[2024-11-18T17:35:29.838+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T17:35:30.049+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv8opcsl2k/bin/python /tmp/venv-callht6i9csd/script.py /tmp/venv-callht6i9csd/script.in /tmp/venv-callht6i9csd/script.out /tmp/venv-callht6i9csd/string_args.txt /tmp/venv-callht6i9csd/termination.log
[2024-11-18T17:35:30.052+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T17:35:31.027+0000] {process_utils.py:190} INFO - 2024-11-18 17:35:31.027329: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-11-18T17:35:31.028+0000] {process_utils.py:190} INFO - 2024-11-18 17:35:31.028359: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T17:35:31.048+0000] {process_utils.py:190} INFO - 2024-11-18 17:35:31.048684: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T17:35:31.049+0000] {process_utils.py:190} INFO - 2024-11-18 17:35:31.048929: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-11-18T17:35:31.049+0000] {process_utils.py:190} INFO - To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-11-18T17:35:31.555+0000] {process_utils.py:190} INFO - 2024-11-18 17:35:31.555021: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-11-18T17:35:32.746+0000] {process_utils.py:190} INFO - Epoch 1/10
[2024-11-18T17:35:33.586+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 2:46 - loss: 0.3187 49/575 [=>............................] - ETA: 0s - loss: 0.1465  105/575 [====>.........................] - ETA: 0s - loss: 0.1031184/575 [========>.....................] - ETA: 0s - loss: 0.0779262/575 [============>.................] - ETA: 0s - loss: 0.0647343/575 [================>.............] - ETA: 0s - loss: 0.0561416/575 [====================>.........] - ETA: 0s - loss: 0.0507491/575 [========================>.....] - ETA: 0s - loss: 0.0463566/575 [============================>.] - ETA: 0s - loss: 0.0430575/575 [==============================] - 1s 959us/step - loss: 0.0426 - val_loss: 0.0071
[2024-11-18T17:35:33.587+0000] {process_utils.py:190} INFO - Epoch 2/10
[2024-11-18T17:35:34.086+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0195 80/575 [===>..........................] - ETA: 0s - loss: 0.0195160/575 [=======>......................] - ETA: 0s - loss: 0.0185239/575 [===========>..................] - ETA: 0s - loss: 0.0178319/575 [===============>..............] - ETA: 0s - loss: 0.0172400/575 [===================>..........] - ETA: 0s - loss: 0.0167482/575 [========================>.....] - ETA: 0s - loss: 0.0162535/575 [==========================>...] - ETA: 0s - loss: 0.0159572/575 [============================>.] - ETA: 0s - loss: 0.0157575/575 [==============================] - 0s 869us/step - loss: 0.0157 - val_loss: 0.0047
[2024-11-18T17:35:34.087+0000] {process_utils.py:190} INFO - Epoch 3/10
[2024-11-18T17:35:34.661+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0140 77/575 [===>..........................] - ETA: 0s - loss: 0.0125146/575 [======>.......................] - ETA: 0s - loss: 0.0125226/575 [==========>...................] - ETA: 0s - loss: 0.0123297/575 [==============>...............] - ETA: 0s - loss: 0.0122344/575 [================>.............] - ETA: 0s - loss: 0.0120400/575 [===================>..........] - ETA: 0s - loss: 0.0119472/575 [=======================>......] - ETA: 0s - loss: 0.0117549/575 [===========================>..] - ETA: 0s - loss: 0.0115575/575 [==============================] - 1s 999us/step - loss: 0.0115 - val_loss: 0.0043
[2024-11-18T17:35:34.662+0000] {process_utils.py:190} INFO - Epoch 4/10
[2024-11-18T17:35:35.117+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0095 76/575 [==>...........................] - ETA: 0s - loss: 0.0101154/575 [=======>......................] - ETA: 0s - loss: 0.0099230/575 [===========>..................] - ETA: 0s - loss: 0.0098308/575 [===============>..............] - ETA: 0s - loss: 0.0097387/575 [===================>..........] - ETA: 0s - loss: 0.0096467/575 [=======================>......] - ETA: 0s - loss: 0.0096543/575 [===========================>..] - ETA: 0s - loss: 0.0095575/575 [==============================] - 0s 790us/step - loss: 0.0095 - val_loss: 0.0038
[2024-11-18T17:35:35.117+0000] {process_utils.py:190} INFO - Epoch 5/10
[2024-11-18T17:35:35.560+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0085 78/575 [===>..........................] - ETA: 0s - loss: 0.0094158/575 [=======>......................] - ETA: 0s - loss: 0.0091235/575 [===========>..................] - ETA: 0s - loss: 0.0090314/575 [===============>..............] - ETA: 0s - loss: 0.0089394/575 [===================>..........] - ETA: 0s - loss: 0.0088472/575 [=======================>......] - ETA: 0s - loss: 0.0087554/575 [===========================>..] - ETA: 0s - loss: 0.0087575/575 [==============================] - 0s 770us/step - loss: 0.0087 - val_loss: 0.0032
[2024-11-18T17:35:35.560+0000] {process_utils.py:190} INFO - Epoch 6/10
[2024-11-18T17:35:36.001+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0085 81/575 [===>..........................] - ETA: 0s - loss: 0.0082161/575 [=======>......................] - ETA: 0s - loss: 0.0081240/575 [===========>..................] - ETA: 0s - loss: 0.0080321/575 [===============>..............] - ETA: 0s - loss: 0.0080401/575 [===================>..........] - ETA: 0s - loss: 0.0079482/575 [========================>.....] - ETA: 0s - loss: 0.0079553/575 [===========================>..] - ETA: 0s - loss: 0.0079575/575 [==============================] - 0s 766us/step - loss: 0.0078 - val_loss: 0.0028
[2024-11-18T17:35:36.001+0000] {process_utils.py:190} INFO - Epoch 7/10
[2024-11-18T17:35:36.439+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0068 84/575 [===>..........................] - ETA: 0s - loss: 0.0075168/575 [=======>......................] - ETA: 0s - loss: 0.0076249/575 [===========>..................] - ETA: 0s - loss: 0.0075327/575 [================>.............] - ETA: 0s - loss: 0.0075408/575 [====================>.........] - ETA: 0s - loss: 0.0074488/575 [========================>.....] - ETA: 0s - loss: 0.0073567/575 [============================>.] - ETA: 0s - loss: 0.0073575/575 [==============================] - 0s 762us/step - loss: 0.0073 - val_loss: 0.0026
[2024-11-18T17:35:36.440+0000] {process_utils.py:190} INFO - Epoch 8/10
[2024-11-18T17:35:36.883+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0051 84/575 [===>..........................] - ETA: 0s - loss: 0.0072169/575 [=======>......................] - ETA: 0s - loss: 0.0072249/575 [===========>..................] - ETA: 0s - loss: 0.0071319/575 [===============>..............] - ETA: 0s - loss: 0.0071393/575 [===================>..........] - ETA: 0s - loss: 0.0071469/575 [=======================>......] - ETA: 0s - loss: 0.0071550/575 [===========================>..] - ETA: 0s - loss: 0.0070575/575 [==============================] - 0s 771us/step - loss: 0.0070 - val_loss: 0.0027
[2024-11-18T17:35:36.883+0000] {process_utils.py:190} INFO - Epoch 9/10
[2024-11-18T17:35:37.317+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0056 77/575 [===>..........................] - ETA: 0s - loss: 0.0070158/575 [=======>......................] - ETA: 0s - loss: 0.0069240/575 [===========>..................] - ETA: 0s - loss: 0.0070322/575 [===============>..............] - ETA: 0s - loss: 0.0069403/575 [====================>.........] - ETA: 0s - loss: 0.0068479/575 [=======================>......] - ETA: 0s - loss: 0.0069559/575 [============================>.] - ETA: 0s - loss: 0.0068575/575 [==============================] - 0s 754us/step - loss: 0.0068 - val_loss: 0.0026
[2024-11-18T17:35:37.317+0000] {process_utils.py:190} INFO - Epoch 10/10
[2024-11-18T17:35:37.746+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0051 85/575 [===>..........................] - ETA: 0s - loss: 0.0066167/575 [=======>......................] - ETA: 0s - loss: 0.0066247/575 [===========>..................] - ETA: 0s - loss: 0.0067328/575 [================>.............] - ETA: 0s - loss: 0.0067412/575 [====================>.........] - ETA: 0s - loss: 0.0067494/575 [========================>.....] - ETA: 0s - loss: 0.0067575/575 [==============================] - ETA: 0s - loss: 0.0067575/575 [==============================] - 0s 745us/step - loss: 0.0067 - val_loss: 0.0021
[2024-11-18T17:35:37.767+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-11-18T17:35:37.767+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callht6i9csd/script.py", line 75, in <module>
[2024-11-18T17:35:37.767+0000] {process_utils.py:190} INFO -     res = train_embedding_model(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-18T17:35:37.767+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callht6i9csd/script.py", line 70, in train_embedding_model
[2024-11-18T17:35:37.768+0000] {process_utils.py:190} INFO -     mlflow.keras.log_model(model, artifact_path="model", registered_model_name="spotify_embedding_model")
[2024-11-18T17:35:37.768+0000] {process_utils.py:190} INFO - AttributeError: module 'mlflow' has no attribute 'keras'
[2024-11-18T17:35:38.613+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
module 'mlflow' has no attribute 'keras'
[2024-11-18T17:35:38.615+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_recommender_dag_v3, task_id=train_embedding_model, execution_date=20241118T173512, start_date=20241118T173512, end_date=20241118T173538
[2024-11-18T17:35:38.621+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 38 for task train_embedding_model (Process returned non-zero exit status 1.
module 'mlflow' has no attribute 'keras'; 926)
[2024-11-18T17:35:38.651+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-18T17:35:38.660+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
