[2024-11-18T17:51:58.262+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_recommender_dag_v3.train_embedding_model manual__2024-11-18T17:46:31.072006+00:00 [queued]>
[2024-11-18T17:51:58.267+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_recommender_dag_v3.train_embedding_model manual__2024-11-18T17:46:31.072006+00:00 [queued]>
[2024-11-18T17:51:58.267+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-11-18T17:51:58.273+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_embedding_model> on 2024-11-18 17:46:31.072006+00:00
[2024-11-18T17:51:58.275+0000] {standard_task_runner.py:60} INFO - Started process 262 to run task
[2024-11-18T17:51:58.277+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_recommender_dag_v3', 'train_embedding_model', 'manual__2024-11-18T17:46:31.072006+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/music_process.py', '--cfg-path', '/tmp/tmp3wvap9p9']
[2024-11-18T17:51:58.278+0000] {standard_task_runner.py:88} INFO - Job 53: Subtask train_embedding_model
[2024-11-18T17:51:58.305+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_recommender_dag_v3.train_embedding_model manual__2024-11-18T17:46:31.072006+00:00 [running]> on host 98017b53a184
[2024-11-18T17:51:58.341+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_recommender_dag_v3' AIRFLOW_CTX_TASK_ID='train_embedding_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T17:46:31.072006+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T17:46:31.072006+00:00'
[2024-11-18T17:51:58.344+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvn513hq2y --system-site-packages --python=python
[2024-11-18T17:51:58.347+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T17:51:58.671+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 115ms
[2024-11-18T17:51:58.671+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvn513hq2y, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T17:51:58.671+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T17:51:58.672+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-11-18T17:51:58.672+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T17:51:58.688+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvn513hq2y/bin/pip install -r /tmp/venvn513hq2y/requirements.txt
[2024-11-18T17:51:58.692+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T17:51:59.631+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venvn513hq2y/requirements.txt (line 1))
[2024-11-18T17:51:59.633+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T17:51:59.684+0000] {process_utils.py:190} INFO - Collecting mlflow==2.10.2 (from -r /tmp/venvn513hq2y/requirements.txt (line 2))
[2024-11-18T17:51:59.685+0000] {process_utils.py:190} INFO -   Using cached mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
[2024-11-18T17:51:59.686+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvn513hq2y/requirements.txt (line 3)) (2.0.3)
[2024-11-18T17:51:59.791+0000] {process_utils.py:190} INFO - Collecting tensorflow==2.13.0 (from -r /tmp/venvn513hq2y/requirements.txt (line 4))
[2024-11-18T17:51:59.793+0000] {process_utils.py:190} INFO -   Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
[2024-11-18T17:52:00.187+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venvn513hq2y/requirements.txt (line 1))
[2024-11-18T17:52:00.188+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T17:52:00.189+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venvn513hq2y/requirements.txt (line 1)) (0.10.0)
[2024-11-18T17:52:00.212+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venvn513hq2y/requirements.txt (line 1))
[2024-11-18T17:52:00.213+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T17:52:00.263+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (8.1.7)
[2024-11-18T17:52:00.264+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (3.1.0)
[2024-11-18T17:52:00.279+0000] {process_utils.py:190} INFO - Collecting entrypoints<1 (from mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2))
[2024-11-18T17:52:00.280+0000] {process_utils.py:190} INFO -   Using cached entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
[2024-11-18T17:52:00.281+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=2.1.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (3.1.43)
[2024-11-18T17:52:00.281+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (6.0.1)
[2024-11-18T17:52:00.282+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<5,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (4.25.2)
[2024-11-18T17:52:00.282+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz<2024 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T17:52:00.282+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (2.31.0)
[2024-11-18T17:52:00.283+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (23.2)
[2024-11-18T17:52:00.283+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (6.11.0)
[2024-11-18T17:52:00.284+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (0.4.4)
[2024-11-18T17:52:00.284+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (1.13.1)
[2024-11-18T17:52:00.285+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (7.0.0)
[2024-11-18T17:52:00.285+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (2.2.5)
[2024-11-18T17:52:00.285+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (1.24.4)
[2024-11-18T17:52:00.286+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (1.10.1)
[2024-11-18T17:52:00.302+0000] {process_utils.py:190} INFO - Collecting querystring-parser<2 (from mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2))
[2024-11-18T17:52:00.303+0000] {process_utils.py:190} INFO -   Using cached querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
[2024-11-18T17:52:00.304+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (1.4.51)
[2024-11-18T17:52:00.304+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (1.3.2)
[2024-11-18T17:52:00.304+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow<16,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (14.0.2)
[2024-11-18T17:52:00.305+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (3.5.2)
[2024-11-18T17:52:00.305+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (3.7.5)
[2024-11-18T17:52:00.306+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<22 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (21.2.0)
[2024-11-18T17:52:00.307+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (3.1.3)
[2024-11-18T17:52:00.363+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvn513hq2y/requirements.txt (line 3)) (2.8.2)
[2024-11-18T17:52:00.364+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvn513hq2y/requirements.txt (line 3)) (2023.4)
[2024-11-18T17:52:00.397+0000] {process_utils.py:190} INFO - Collecting absl-py>=1.0.0 (from tensorflow==2.13.0->-r /tmp/venvn513hq2y/requirements.txt (line 4))
[2024-11-18T17:52:00.398+0000] {process_utils.py:190} INFO -   Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
[2024-11-18T17:52:00.416+0000] {process_utils.py:190} INFO - Collecting astunparse>=1.6.0 (from tensorflow==2.13.0->-r /tmp/venvn513hq2y/requirements.txt (line 4))
[2024-11-18T17:52:00.417+0000] {process_utils.py:190} INFO -   Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
[2024-11-18T17:52:00.436+0000] {process_utils.py:190} INFO - Collecting flatbuffers>=23.1.21 (from tensorflow==2.13.0->-r /tmp/venvn513hq2y/requirements.txt (line 4))
[2024-11-18T17:52:00.438+0000] {process_utils.py:190} INFO -   Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
[2024-11-18T17:52:00.460+0000] {process_utils.py:190} INFO - Collecting gast<=0.4.0,>=0.2.1 (from tensorflow==2.13.0->-r /tmp/venvn513hq2y/requirements.txt (line 4))
[2024-11-18T17:52:00.461+0000] {process_utils.py:190} INFO -   Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
[2024-11-18T17:52:00.479+0000] {process_utils.py:190} INFO - Collecting google-pasta>=0.1.1 (from tensorflow==2.13.0->-r /tmp/venvn513hq2y/requirements.txt (line 4))
[2024-11-18T17:52:00.480+0000] {process_utils.py:190} INFO -   Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
[2024-11-18T17:52:00.481+0000] {process_utils.py:190} INFO - Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvn513hq2y/requirements.txt (line 4)) (1.60.0)
[2024-11-18T17:52:00.668+0000] {process_utils.py:190} INFO - Collecting h5py>=2.9.0 (from tensorflow==2.13.0->-r /tmp/venvn513hq2y/requirements.txt (line 4))
[2024-11-18T17:52:00.669+0000] {process_utils.py:190} INFO -   Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
[2024-11-18T17:52:00.695+0000] {process_utils.py:190} INFO - Collecting keras<2.14,>=2.13.1 (from tensorflow==2.13.0->-r /tmp/venvn513hq2y/requirements.txt (line 4))
[2024-11-18T17:52:00.696+0000] {process_utils.py:190} INFO -   Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
[2024-11-18T17:52:00.717+0000] {process_utils.py:190} INFO - Collecting libclang>=13.0.0 (from tensorflow==2.13.0->-r /tmp/venvn513hq2y/requirements.txt (line 4))
[2024-11-18T17:52:00.718+0000] {process_utils.py:190} INFO -   Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
[2024-11-18T17:52:00.870+0000] {process_utils.py:190} INFO - Collecting numpy<2 (from mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2))
[2024-11-18T17:52:00.871+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-11-18T17:52:00.889+0000] {process_utils.py:190} INFO - Collecting opt-einsum>=2.3.2 (from tensorflow==2.13.0->-r /tmp/venvn513hq2y/requirements.txt (line 4))
[2024-11-18T17:52:00.891+0000] {process_utils.py:190} INFO -   Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
[2024-11-18T17:52:00.892+0000] {process_utils.py:190} INFO - Requirement already satisfied: setuptools in /tmp/venvn513hq2y/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvn513hq2y/requirements.txt (line 4)) (69.0.2)
[2024-11-18T17:52:00.892+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.12.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvn513hq2y/requirements.txt (line 4)) (1.16.0)
[2024-11-18T17:52:00.916+0000] {process_utils.py:190} INFO - Collecting tensorboard<2.14,>=2.13 (from tensorflow==2.13.0->-r /tmp/venvn513hq2y/requirements.txt (line 4))
[2024-11-18T17:52:00.918+0000] {process_utils.py:190} INFO -   Using cached tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T17:52:00.936+0000] {process_utils.py:190} INFO - Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow==2.13.0->-r /tmp/venvn513hq2y/requirements.txt (line 4))
[2024-11-18T17:52:00.938+0000] {process_utils.py:190} INFO -   Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
[2024-11-18T17:52:00.938+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.1.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvn513hq2y/requirements.txt (line 4)) (2.4.0)
[2024-11-18T17:52:00.962+0000] {process_utils.py:190} INFO - Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow==2.13.0->-r /tmp/venvn513hq2y/requirements.txt (line 4))
[2024-11-18T17:52:00.964+0000] {process_utils.py:190} INFO -   Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
[2024-11-18T17:52:00.965+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt>=1.11.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvn513hq2y/requirements.txt (line 4)) (1.16.0)
[2024-11-18T17:52:01.020+0000] {process_utils.py:190} INFO - Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow==2.13.0->-r /tmp/venvn513hq2y/requirements.txt (line 4))
[2024-11-18T17:52:01.022+0000] {process_utils.py:190} INFO -   Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
[2024-11-18T17:52:01.029+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (1.3.0)
[2024-11-18T17:52:01.033+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (5.13.0)
[2024-11-18T17:52:01.036+0000] {process_utils.py:190} INFO - Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venvn513hq2y/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow==2.13.0->-r /tmp/venvn513hq2y/requirements.txt (line 4)) (0.42.0)
[2024-11-18T17:52:01.041+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venvn513hq2y/requirements.txt (line 1)) (1.26.18)
[2024-11-18T17:52:01.055+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (2.2.3)
[2024-11-18T17:52:01.056+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (2.1.2)
[2024-11-18T17:52:01.072+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (4.0.11)
[2024-11-18T17:52:01.109+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (3.17.0)
[2024-11-18T17:52:01.112+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (2.1.3)
[2024-11-18T17:52:01.135+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (1.1.1)
[2024-11-18T17:52:01.136+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (0.12.1)
[2024-11-18T17:52:01.136+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (4.54.1)
[2024-11-18T17:52:01.137+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (1.4.7)
[2024-11-18T17:52:01.147+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (10.4.0)
[2024-11-18T17:52:01.148+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (3.1.1)
[2024-11-18T17:52:01.193+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (3.3.2)
[2024-11-18T17:52:01.193+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (3.6)
[2024-11-18T17:52:01.194+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (2023.11.17)
[2024-11-18T17:52:01.328+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (1.4.2)
[2024-11-18T17:52:01.328+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (3.5.0)
[2024-11-18T17:52:01.408+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (3.0.3)
[2024-11-18T17:52:01.426+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth<3,>=1.6.3 in /home/***/.local/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvn513hq2y/requirements.txt (line 4)) (2.26.2)
[2024-11-18T17:52:01.446+0000] {process_utils.py:190} INFO - Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvn513hq2y/requirements.txt (line 4))
[2024-11-18T17:52:01.447+0000] {process_utils.py:190} INFO -   Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
[2024-11-18T17:52:01.482+0000] {process_utils.py:190} INFO - Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvn513hq2y/requirements.txt (line 4))
[2024-11-18T17:52:01.483+0000] {process_utils.py:190} INFO -   Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
[2024-11-18T17:52:01.622+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvn513hq2y/requirements.txt (line 2)) (5.0.1)
[2024-11-18T17:52:01.634+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvn513hq2y/requirements.txt (line 4)) (5.3.2)
[2024-11-18T17:52:01.635+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvn513hq2y/requirements.txt (line 4)) (0.3.0)
[2024-11-18T17:52:01.635+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvn513hq2y/requirements.txt (line 4)) (4.9)
[2024-11-18T17:52:01.642+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvn513hq2y/requirements.txt (line 4)) (1.3.1)
[2024-11-18T17:52:01.783+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvn513hq2y/requirements.txt (line 4)) (0.5.1)
[2024-11-18T17:52:01.790+0000] {process_utils.py:190} INFO - Requirement already satisfied: oauthlib>=3.0.0 in /home/***/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvn513hq2y/requirements.txt (line 4)) (3.2.2)
[2024-11-18T17:52:01.823+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T17:52:01.824+0000] {process_utils.py:190} INFO - Using cached mlflow-2.10.2-py3-none-any.whl (19.5 MB)
[2024-11-18T17:52:01.845+0000] {process_utils.py:190} INFO - Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
[2024-11-18T17:52:02.360+0000] {process_utils.py:190} INFO - Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
[2024-11-18T17:52:02.362+0000] {process_utils.py:190} INFO - Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
[2024-11-18T17:52:02.363+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T17:52:02.375+0000] {process_utils.py:190} INFO - Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
[2024-11-18T17:52:02.376+0000] {process_utils.py:190} INFO - Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
[2024-11-18T17:52:02.378+0000] {process_utils.py:190} INFO - Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
[2024-11-18T17:52:02.379+0000] {process_utils.py:190} INFO - Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
[2024-11-18T17:52:02.380+0000] {process_utils.py:190} INFO - Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
[2024-11-18T17:52:02.387+0000] {process_utils.py:190} INFO - Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)
[2024-11-18T17:52:02.390+0000] {process_utils.py:190} INFO - Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
[2024-11-18T17:52:02.415+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-11-18T17:52:02.434+0000] {process_utils.py:190} INFO - Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
[2024-11-18T17:52:02.435+0000] {process_utils.py:190} INFO - Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
[2024-11-18T17:52:02.436+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T17:52:02.437+0000] {process_utils.py:190} INFO - Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
[2024-11-18T17:52:02.444+0000] {process_utils.py:190} INFO - Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
[2024-11-18T17:52:02.445+0000] {process_utils.py:190} INFO - Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
[2024-11-18T17:52:02.449+0000] {process_utils.py:190} INFO - Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[2024-11-18T17:52:02.450+0000] {process_utils.py:190} INFO - Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
[2024-11-18T17:52:02.451+0000] {process_utils.py:190} INFO - Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
[2024-11-18T17:52:04.561+0000] {process_utils.py:190} INFO - Installing collected packages: libclang, flatbuffers, typing-extensions, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, querystring-parser, opt-einsum, numpy, keras, google-pasta, gast, entrypoints, astunparse, absl-py, h5py, botocore, s3transfer, google-auth-oauthlib, tensorboard, mlflow, boto3, tensorflow
[2024-11-18T17:52:04.807+0000] {process_utils.py:190} INFO -   Attempting uninstall: typing-extensions
[2024-11-18T17:52:04.808+0000] {process_utils.py:190} INFO -     Found existing installation: typing_extensions 4.9.0
[2024-11-18T17:52:04.809+0000] {process_utils.py:190} INFO -     Not uninstalling typing-extensions at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvn513hq2y
[2024-11-18T17:52:04.809+0000] {process_utils.py:190} INFO -     Can't uninstall 'typing_extensions'. No files were found to uninstall.
[2024-11-18T17:52:05.070+0000] {process_utils.py:190} INFO -   Attempting uninstall: numpy
[2024-11-18T17:52:05.071+0000] {process_utils.py:190} INFO -     Found existing installation: numpy 1.24.4
[2024-11-18T17:52:05.071+0000] {process_utils.py:190} INFO -     Not uninstalling numpy at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvn513hq2y
[2024-11-18T17:52:05.072+0000] {process_utils.py:190} INFO -     Can't uninstall 'numpy'. No files were found to uninstall.
[2024-11-18T17:52:06.730+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T17:52:06.731+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T17:52:06.731+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvn513hq2y
[2024-11-18T17:52:06.732+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T17:52:07.142+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T17:52:07.143+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T17:52:07.143+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvn513hq2y
[2024-11-18T17:52:07.144+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T17:52:07.165+0000] {process_utils.py:190} INFO -   Attempting uninstall: google-auth-oauthlib
[2024-11-18T17:52:07.165+0000] {process_utils.py:190} INFO -     Found existing installation: google-auth-oauthlib 1.2.0
[2024-11-18T17:52:07.166+0000] {process_utils.py:190} INFO -     Not uninstalling google-auth-oauthlib at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvn513hq2y
[2024-11-18T17:52:07.166+0000] {process_utils.py:190} INFO -     Can't uninstall 'google-auth-oauthlib'. No files were found to uninstall.
[2024-11-18T17:52:07.363+0000] {process_utils.py:190} INFO -   Attempting uninstall: mlflow
[2024-11-18T17:52:07.364+0000] {process_utils.py:190} INFO -     Found existing installation: mlflow 2.17.0
[2024-11-18T17:52:07.365+0000] {process_utils.py:190} INFO -     Not uninstalling mlflow at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvn513hq2y
[2024-11-18T17:52:07.365+0000] {process_utils.py:190} INFO -     Can't uninstall 'mlflow'. No files were found to uninstall.
[2024-11-18T17:52:07.926+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T17:52:07.926+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T17:52:07.927+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvn513hq2y
[2024-11-18T17:52:07.927+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T17:52:15.132+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T17:52:15.133+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T17:52:15.133+0000] {process_utils.py:190} INFO - azure-core 1.29.6 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:52:15.133+0000] {process_utils.py:190} INFO - azure-mgmt-keyvault 10.3.1 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:52:15.134+0000] {process_utils.py:190} INFO - azure-mgmt-network 27.0.0 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:52:15.134+0000] {process_utils.py:190} INFO - graphene 3.4 requires typing-extensions<5,>=4.7.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:52:15.134+0000] {process_utils.py:190} INFO - pydantic 2.5.3 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:52:15.134+0000] {process_utils.py:190} INFO - pydantic-core 2.14.6 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T17:52:15.135+0000] {process_utils.py:190} INFO - Successfully installed absl-py-2.1.0 astunparse-1.6.3 boto3-1.28.0 botocore-1.31.85 entrypoints-0.4 flatbuffers-24.3.25 gast-0.4.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 h5py-3.11.0 keras-2.13.1 libclang-18.1.1 mlflow-2.10.2 numpy-1.24.3 opt-einsum-3.4.0 querystring-parser-1.2.4 s3transfer-0.6.2 tensorboard-2.13.0 tensorboard-data-server-0.7.2 tensorflow-2.13.0 tensorflow-estimator-2.13.0 tensorflow-io-gcs-filesystem-0.34.0 typing-extensions-4.5.0
[2024-11-18T17:52:15.212+0000] {process_utils.py:190} INFO - 
[2024-11-18T17:52:15.213+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.3.1
[2024-11-18T17:52:15.214+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T17:52:15.412+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvn513hq2y/bin/python /tmp/venv-callnm9xa_qy/script.py /tmp/venv-callnm9xa_qy/script.in /tmp/venv-callnm9xa_qy/script.out /tmp/venv-callnm9xa_qy/string_args.txt /tmp/venv-callnm9xa_qy/termination.log
[2024-11-18T17:52:15.416+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T17:52:16.371+0000] {process_utils.py:190} INFO - 2024-11-18 17:52:16.371339: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-11-18T17:52:16.372+0000] {process_utils.py:190} INFO - 2024-11-18 17:52:16.372679: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T17:52:16.393+0000] {process_utils.py:190} INFO - 2024-11-18 17:52:16.392967: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T17:52:16.393+0000] {process_utils.py:190} INFO - 2024-11-18 17:52:16.393223: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-11-18T17:52:16.393+0000] {process_utils.py:190} INFO - To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-11-18T17:52:16.881+0000] {process_utils.py:190} INFO - 2024-11-18 17:52:16.881135: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-11-18T17:52:18.362+0000] {process_utils.py:190} INFO - Epoch 1/10
[2024-11-18T17:52:19.237+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 3:19 - loss: 0.3544 49/575 [=>............................] - ETA: 0s - loss: 0.1728  100/575 [====>.........................] - ETA: 0s - loss: 0.1276176/575 [========>.....................] - ETA: 0s - loss: 0.0961267/575 [============>.................] - ETA: 0s - loss: 0.0764351/575 [=================>............] - ETA: 0s - loss: 0.0656433/575 [=====================>........] - ETA: 0s - loss: 0.0583519/575 [==========================>...] - ETA: 0s - loss: 0.0526575/575 [==============================] - 1s 917us/step - loss: 0.0496 - val_loss: 0.0081
[2024-11-18T17:52:19.237+0000] {process_utils.py:190} INFO - Epoch 2/10
[2024-11-18T17:52:19.661+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0190 84/575 [===>..........................] - ETA: 0s - loss: 0.0193166/575 [=======>......................] - ETA: 0s - loss: 0.0186251/575 [============>.................] - ETA: 0s - loss: 0.0179337/575 [================>.............] - ETA: 0s - loss: 0.0174416/575 [====================>.........] - ETA: 0s - loss: 0.0168499/575 [=========================>....] - ETA: 0s - loss: 0.0164575/575 [==============================] - 0s 737us/step - loss: 0.0160 - val_loss: 0.0058
[2024-11-18T17:52:19.661+0000] {process_utils.py:190} INFO - Epoch 3/10
[2024-11-18T17:52:20.091+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0109 83/575 [===>..........................] - ETA: 0s - loss: 0.0132165/575 [=======>......................] - ETA: 0s - loss: 0.0131246/575 [===========>..................] - ETA: 0s - loss: 0.0128327/575 [================>.............] - ETA: 0s - loss: 0.0126409/575 [====================>.........] - ETA: 0s - loss: 0.0124491/575 [========================>.....] - ETA: 0s - loss: 0.0122569/575 [============================>.] - ETA: 0s - loss: 0.0121575/575 [==============================] - 0s 747us/step - loss: 0.0121 - val_loss: 0.0040
[2024-11-18T17:52:20.092+0000] {process_utils.py:190} INFO - Epoch 4/10
[2024-11-18T17:52:20.525+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0089 82/575 [===>..........................] - ETA: 0s - loss: 0.0110163/575 [=======>......................] - ETA: 0s - loss: 0.0108243/575 [===========>..................] - ETA: 0s - loss: 0.0108325/575 [===============>..............] - ETA: 0s - loss: 0.0106404/575 [====================>.........] - ETA: 0s - loss: 0.0106488/575 [========================>.....] - ETA: 0s - loss: 0.0105566/575 [============================>.] - ETA: 0s - loss: 0.0104575/575 [==============================] - 0s 753us/step - loss: 0.0104 - val_loss: 0.0039
[2024-11-18T17:52:20.525+0000] {process_utils.py:190} INFO - Epoch 5/10
[2024-11-18T17:52:20.963+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0089 85/575 [===>..........................] - ETA: 0s - loss: 0.0095165/575 [=======>......................] - ETA: 0s - loss: 0.0095244/575 [===========>..................] - ETA: 0s - loss: 0.0095318/575 [===============>..............] - ETA: 0s - loss: 0.0094403/575 [====================>.........] - ETA: 0s - loss: 0.0093483/575 [========================>.....] - ETA: 0s - loss: 0.0092564/575 [============================>.] - ETA: 0s - loss: 0.0092575/575 [==============================] - 0s 761us/step - loss: 0.0092 - val_loss: 0.0038
[2024-11-18T17:52:20.963+0000] {process_utils.py:190} INFO - Epoch 6/10
[2024-11-18T17:52:21.387+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0092 86/575 [===>..........................] - ETA: 0s - loss: 0.0086169/575 [=======>......................] - ETA: 0s - loss: 0.0085251/575 [============>.................] - ETA: 0s - loss: 0.0085333/575 [================>.............] - ETA: 0s - loss: 0.0086417/575 [====================>.........] - ETA: 0s - loss: 0.0085499/575 [=========================>....] - ETA: 0s - loss: 0.0085575/575 [==============================] - 0s 736us/step - loss: 0.0085 - val_loss: 0.0032
[2024-11-18T17:52:21.387+0000] {process_utils.py:190} INFO - Epoch 7/10
[2024-11-18T17:52:21.820+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0074 70/575 [==>...........................] - ETA: 0s - loss: 0.0079152/575 [======>.......................] - ETA: 0s - loss: 0.0079237/575 [===========>..................] - ETA: 0s - loss: 0.0080318/575 [===============>..............] - ETA: 0s - loss: 0.0079401/575 [===================>..........] - ETA: 0s - loss: 0.0079484/575 [========================>.....] - ETA: 0s - loss: 0.0079566/575 [============================>.] - ETA: 0s - loss: 0.0079575/575 [==============================] - 0s 752us/step - loss: 0.0079 - val_loss: 0.0031
[2024-11-18T17:52:21.820+0000] {process_utils.py:190} INFO - Epoch 8/10
[2024-11-18T17:52:22.250+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0083 82/575 [===>..........................] - ETA: 0s - loss: 0.0075164/575 [=======>......................] - ETA: 0s - loss: 0.0073243/575 [===========>..................] - ETA: 0s - loss: 0.0074325/575 [===============>..............] - ETA: 0s - loss: 0.0074407/575 [====================>.........] - ETA: 0s - loss: 0.0073491/575 [========================>.....] - ETA: 0s - loss: 0.0073571/575 [============================>.] - ETA: 0s - loss: 0.0073575/575 [==============================] - 0s 748us/step - loss: 0.0073 - val_loss: 0.0027
[2024-11-18T17:52:22.251+0000] {process_utils.py:190} INFO - Epoch 9/10
[2024-11-18T17:52:22.677+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0062 81/575 [===>..........................] - ETA: 0s - loss: 0.0069163/575 [=======>......................] - ETA: 0s - loss: 0.0069245/575 [===========>..................] - ETA: 0s - loss: 0.0070326/575 [================>.............] - ETA: 0s - loss: 0.0070406/575 [====================>.........] - ETA: 0s - loss: 0.0070493/575 [========================>.....] - ETA: 0s - loss: 0.0069575/575 [==============================] - 0s 742us/step - loss: 0.0069 - val_loss: 0.0023
[2024-11-18T17:52:22.678+0000] {process_utils.py:190} INFO - Epoch 10/10
[2024-11-18T17:52:23.099+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0051 83/575 [===>..........................] - ETA: 0s - loss: 0.0070165/575 [=======>......................] - ETA: 0s - loss: 0.0069248/575 [===========>..................] - ETA: 0s - loss: 0.0069326/575 [================>.............] - ETA: 0s - loss: 0.0068410/575 [====================>.........] - ETA: 0s - loss: 0.0068491/575 [========================>.....] - ETA: 0s - loss: 0.0068575/575 [==============================] - 0s 733us/step - loss: 0.0068 - val_loss: 0.0025
[2024-11-18T17:52:23.114+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-11-18T17:52:23.115+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callnm9xa_qy/script.py", line 89, in <module>
[2024-11-18T17:52:23.115+0000] {process_utils.py:190} INFO -     res = train_embedding_model(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-18T17:52:23.115+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callnm9xa_qy/script.py", line 76, in train_embedding_model
[2024-11-18T17:52:23.115+0000] {process_utils.py:190} INFO -     os.makedirs(model_path, exist_ok=True)
[2024-11-18T17:52:23.116+0000] {process_utils.py:190} INFO -   File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
[2024-11-18T17:52:23.116+0000] {process_utils.py:190} INFO -     mkdir(name, mode)
[2024-11-18T17:52:23.116+0000] {process_utils.py:190} INFO - PermissionError: [Errno 13] Permission denied: '/models'
[2024-11-18T17:52:23.929+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
[Errno 13] Permission denied: '/models'
[2024-11-18T17:52:23.931+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=spotify_recommender_dag_v3, task_id=train_embedding_model, execution_date=20241118T174631, start_date=20241118T175158, end_date=20241118T175223
[2024-11-18T17:52:23.938+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 53 for task train_embedding_model (Process returned non-zero exit status 1.
[Errno 13] Permission denied: '/models'; 262)
[2024-11-18T17:52:23.985+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-18T17:52:23.994+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
