[2024-11-18T18:18:00.047+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:17:59.060229+00:00 [queued]>
[2024-11-18T18:18:00.051+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:17:59.060229+00:00 [queued]>
[2024-11-18T18:18:00.052+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-11-18T18:18:00.059+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_challenger_model> on 2024-11-18 18:17:59.060229+00:00
[2024-11-18T18:18:00.061+0000] {standard_task_runner.py:60} INFO - Started process 8924 to run task
[2024-11-18T18:18:00.062+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_retrain_challenge_model_v3', 'train_challenger_model', 'manual__2024-11-18T18:17:59.060229+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/retrain_music_model.py', '--cfg-path', '/tmp/tmp5hhhxe2j']
[2024-11-18T18:18:00.063+0000] {standard_task_runner.py:88} INFO - Job 79: Subtask train_challenger_model
[2024-11-18T18:18:00.088+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:17:59.060229+00:00 [running]> on host 98017b53a184
[2024-11-18T18:18:00.126+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_retrain_challenge_model_v3' AIRFLOW_CTX_TASK_ID='train_challenger_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T18:17:59.060229+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T18:17:59.060229+00:00'
[2024-11-18T18:18:00.127+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvpefvkyss --system-site-packages --python=python
[2024-11-18T18:18:00.131+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:18:00.458+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 115ms
[2024-11-18T18:18:00.459+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvpefvkyss, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T18:18:00.459+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T18:18:00.459+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-11-18T18:18:00.459+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T18:18:00.476+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvpefvkyss/bin/pip install -r /tmp/venvpefvkyss/requirements.txt
[2024-11-18T18:18:00.480+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:18:01.413+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venvpefvkyss/requirements.txt (line 1))
[2024-11-18T18:18:01.414+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T18:18:01.453+0000] {process_utils.py:190} INFO - Collecting mlflow==2.10.2 (from -r /tmp/venvpefvkyss/requirements.txt (line 2))
[2024-11-18T18:18:01.454+0000] {process_utils.py:190} INFO -   Using cached mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
[2024-11-18T18:18:01.455+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvpefvkyss/requirements.txt (line 3)) (2.0.3)
[2024-11-18T18:18:01.456+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn==1.3.2 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvpefvkyss/requirements.txt (line 4)) (1.3.2)
[2024-11-18T18:18:01.556+0000] {process_utils.py:190} INFO - Collecting tensorflow==2.13.0 (from -r /tmp/venvpefvkyss/requirements.txt (line 5))
[2024-11-18T18:18:01.558+0000] {process_utils.py:190} INFO -   Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
[2024-11-18T18:18:01.953+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venvpefvkyss/requirements.txt (line 1))
[2024-11-18T18:18:01.955+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T18:18:01.956+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venvpefvkyss/requirements.txt (line 1)) (0.10.0)
[2024-11-18T18:18:01.978+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venvpefvkyss/requirements.txt (line 1))
[2024-11-18T18:18:01.979+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:18:02.032+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (8.1.7)
[2024-11-18T18:18:02.032+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (3.1.0)
[2024-11-18T18:18:02.048+0000] {process_utils.py:190} INFO - Collecting entrypoints<1 (from mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2))
[2024-11-18T18:18:02.049+0000] {process_utils.py:190} INFO -   Using cached entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
[2024-11-18T18:18:02.050+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=2.1.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (3.1.43)
[2024-11-18T18:18:02.050+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (6.0.1)
[2024-11-18T18:18:02.050+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<5,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (4.25.2)
[2024-11-18T18:18:02.051+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz<2024 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T18:18:02.051+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (2.31.0)
[2024-11-18T18:18:02.052+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (23.2)
[2024-11-18T18:18:02.052+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (6.11.0)
[2024-11-18T18:18:02.052+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (0.4.4)
[2024-11-18T18:18:02.053+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (1.13.1)
[2024-11-18T18:18:02.054+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (7.0.0)
[2024-11-18T18:18:02.054+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (2.2.5)
[2024-11-18T18:18:02.054+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (1.24.4)
[2024-11-18T18:18:02.055+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (1.10.1)
[2024-11-18T18:18:02.070+0000] {process_utils.py:190} INFO - Collecting querystring-parser<2 (from mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2))
[2024-11-18T18:18:02.072+0000] {process_utils.py:190} INFO -   Using cached querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
[2024-11-18T18:18:02.072+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (1.4.51)
[2024-11-18T18:18:02.073+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow<16,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (14.0.2)
[2024-11-18T18:18:02.073+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (3.5.2)
[2024-11-18T18:18:02.074+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (3.7.5)
[2024-11-18T18:18:02.074+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<22 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (21.2.0)
[2024-11-18T18:18:02.075+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (3.1.3)
[2024-11-18T18:18:02.128+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvpefvkyss/requirements.txt (line 3)) (2.8.2)
[2024-11-18T18:18:02.129+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvpefvkyss/requirements.txt (line 3)) (2023.4)
[2024-11-18T18:18:02.150+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvpefvkyss/requirements.txt (line 4)) (1.4.2)
[2024-11-18T18:18:02.150+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvpefvkyss/requirements.txt (line 4)) (3.5.0)
[2024-11-18T18:18:02.183+0000] {process_utils.py:190} INFO - Collecting absl-py>=1.0.0 (from tensorflow==2.13.0->-r /tmp/venvpefvkyss/requirements.txt (line 5))
[2024-11-18T18:18:02.185+0000] {process_utils.py:190} INFO -   Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
[2024-11-18T18:18:02.208+0000] {process_utils.py:190} INFO - Collecting astunparse>=1.6.0 (from tensorflow==2.13.0->-r /tmp/venvpefvkyss/requirements.txt (line 5))
[2024-11-18T18:18:02.210+0000] {process_utils.py:190} INFO -   Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
[2024-11-18T18:18:02.227+0000] {process_utils.py:190} INFO - Collecting flatbuffers>=23.1.21 (from tensorflow==2.13.0->-r /tmp/venvpefvkyss/requirements.txt (line 5))
[2024-11-18T18:18:02.229+0000] {process_utils.py:190} INFO -   Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
[2024-11-18T18:18:02.249+0000] {process_utils.py:190} INFO - Collecting gast<=0.4.0,>=0.2.1 (from tensorflow==2.13.0->-r /tmp/venvpefvkyss/requirements.txt (line 5))
[2024-11-18T18:18:02.251+0000] {process_utils.py:190} INFO -   Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
[2024-11-18T18:18:02.268+0000] {process_utils.py:190} INFO - Collecting google-pasta>=0.1.1 (from tensorflow==2.13.0->-r /tmp/venvpefvkyss/requirements.txt (line 5))
[2024-11-18T18:18:02.269+0000] {process_utils.py:190} INFO -   Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
[2024-11-18T18:18:02.270+0000] {process_utils.py:190} INFO - Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvpefvkyss/requirements.txt (line 5)) (1.60.0)
[2024-11-18T18:18:02.310+0000] {process_utils.py:190} INFO - Collecting h5py>=2.9.0 (from tensorflow==2.13.0->-r /tmp/venvpefvkyss/requirements.txt (line 5))
[2024-11-18T18:18:02.311+0000] {process_utils.py:190} INFO -   Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
[2024-11-18T18:18:02.338+0000] {process_utils.py:190} INFO - Collecting keras<2.14,>=2.13.1 (from tensorflow==2.13.0->-r /tmp/venvpefvkyss/requirements.txt (line 5))
[2024-11-18T18:18:02.340+0000] {process_utils.py:190} INFO -   Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
[2024-11-18T18:18:02.362+0000] {process_utils.py:190} INFO - Collecting libclang>=13.0.0 (from tensorflow==2.13.0->-r /tmp/venvpefvkyss/requirements.txt (line 5))
[2024-11-18T18:18:02.364+0000] {process_utils.py:190} INFO -   Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
[2024-11-18T18:18:02.517+0000] {process_utils.py:190} INFO - Collecting numpy<2 (from mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2))
[2024-11-18T18:18:02.518+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-11-18T18:18:02.535+0000] {process_utils.py:190} INFO - Collecting opt-einsum>=2.3.2 (from tensorflow==2.13.0->-r /tmp/venvpefvkyss/requirements.txt (line 5))
[2024-11-18T18:18:02.537+0000] {process_utils.py:190} INFO -   Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
[2024-11-18T18:18:02.538+0000] {process_utils.py:190} INFO - Requirement already satisfied: setuptools in /tmp/venvpefvkyss/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvpefvkyss/requirements.txt (line 5)) (69.0.2)
[2024-11-18T18:18:02.539+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.12.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvpefvkyss/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:18:02.563+0000] {process_utils.py:190} INFO - Collecting tensorboard<2.14,>=2.13 (from tensorflow==2.13.0->-r /tmp/venvpefvkyss/requirements.txt (line 5))
[2024-11-18T18:18:02.564+0000] {process_utils.py:190} INFO -   Using cached tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:18:02.582+0000] {process_utils.py:190} INFO - Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow==2.13.0->-r /tmp/venvpefvkyss/requirements.txt (line 5))
[2024-11-18T18:18:02.584+0000] {process_utils.py:190} INFO -   Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
[2024-11-18T18:18:02.584+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.1.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvpefvkyss/requirements.txt (line 5)) (2.4.0)
[2024-11-18T18:18:02.628+0000] {process_utils.py:190} INFO - Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow==2.13.0->-r /tmp/venvpefvkyss/requirements.txt (line 5))
[2024-11-18T18:18:02.630+0000] {process_utils.py:190} INFO -   Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
[2024-11-18T18:18:02.631+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt>=1.11.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvpefvkyss/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:18:02.661+0000] {process_utils.py:190} INFO - Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow==2.13.0->-r /tmp/venvpefvkyss/requirements.txt (line 5))
[2024-11-18T18:18:02.663+0000] {process_utils.py:190} INFO -   Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
[2024-11-18T18:18:02.670+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (1.3.0)
[2024-11-18T18:18:02.674+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (5.13.0)
[2024-11-18T18:18:02.677+0000] {process_utils.py:190} INFO - Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venvpefvkyss/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow==2.13.0->-r /tmp/venvpefvkyss/requirements.txt (line 5)) (0.42.0)
[2024-11-18T18:18:02.682+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venvpefvkyss/requirements.txt (line 1)) (1.26.18)
[2024-11-18T18:18:02.697+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (2.2.3)
[2024-11-18T18:18:02.698+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (2.1.2)
[2024-11-18T18:18:02.714+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (4.0.11)
[2024-11-18T18:18:02.738+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (3.17.0)
[2024-11-18T18:18:02.742+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (2.1.3)
[2024-11-18T18:18:02.766+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (1.1.1)
[2024-11-18T18:18:02.766+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (0.12.1)
[2024-11-18T18:18:02.767+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (4.54.1)
[2024-11-18T18:18:02.767+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (1.4.7)
[2024-11-18T18:18:02.777+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (10.4.0)
[2024-11-18T18:18:02.777+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (3.1.1)
[2024-11-18T18:18:02.825+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (3.3.2)
[2024-11-18T18:18:02.825+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (3.6)
[2024-11-18T18:18:02.826+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (2023.11.17)
[2024-11-18T18:18:03.081+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (3.0.3)
[2024-11-18T18:18:03.098+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth<3,>=1.6.3 in /home/***/.local/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvpefvkyss/requirements.txt (line 5)) (2.26.2)
[2024-11-18T18:18:03.120+0000] {process_utils.py:190} INFO - Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvpefvkyss/requirements.txt (line 5))
[2024-11-18T18:18:03.121+0000] {process_utils.py:190} INFO -   Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
[2024-11-18T18:18:03.156+0000] {process_utils.py:190} INFO - Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvpefvkyss/requirements.txt (line 5))
[2024-11-18T18:18:03.158+0000] {process_utils.py:190} INFO -   Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
[2024-11-18T18:18:03.304+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvpefvkyss/requirements.txt (line 2)) (5.0.1)
[2024-11-18T18:18:03.314+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvpefvkyss/requirements.txt (line 5)) (5.3.2)
[2024-11-18T18:18:03.315+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvpefvkyss/requirements.txt (line 5)) (0.3.0)
[2024-11-18T18:18:03.315+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvpefvkyss/requirements.txt (line 5)) (4.9)
[2024-11-18T18:18:03.322+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvpefvkyss/requirements.txt (line 5)) (1.3.1)
[2024-11-18T18:18:03.450+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvpefvkyss/requirements.txt (line 5)) (0.5.1)
[2024-11-18T18:18:03.457+0000] {process_utils.py:190} INFO - Requirement already satisfied: oauthlib>=3.0.0 in /home/***/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvpefvkyss/requirements.txt (line 5)) (3.2.2)
[2024-11-18T18:18:03.492+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T18:18:03.493+0000] {process_utils.py:190} INFO - Using cached mlflow-2.10.2-py3-none-any.whl (19.5 MB)
[2024-11-18T18:18:03.511+0000] {process_utils.py:190} INFO - Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
[2024-11-18T18:18:03.979+0000] {process_utils.py:190} INFO - Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
[2024-11-18T18:18:03.981+0000] {process_utils.py:190} INFO - Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
[2024-11-18T18:18:03.981+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T18:18:03.993+0000] {process_utils.py:190} INFO - Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
[2024-11-18T18:18:03.994+0000] {process_utils.py:190} INFO - Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
[2024-11-18T18:18:03.995+0000] {process_utils.py:190} INFO - Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
[2024-11-18T18:18:03.996+0000] {process_utils.py:190} INFO - Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
[2024-11-18T18:18:03.997+0000] {process_utils.py:190} INFO - Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
[2024-11-18T18:18:04.003+0000] {process_utils.py:190} INFO - Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)
[2024-11-18T18:18:04.006+0000] {process_utils.py:190} INFO - Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
[2024-11-18T18:18:04.030+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-11-18T18:18:04.047+0000] {process_utils.py:190} INFO - Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
[2024-11-18T18:18:04.048+0000] {process_utils.py:190} INFO - Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
[2024-11-18T18:18:04.049+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T18:18:04.050+0000] {process_utils.py:190} INFO - Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
[2024-11-18T18:18:04.057+0000] {process_utils.py:190} INFO - Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
[2024-11-18T18:18:04.058+0000] {process_utils.py:190} INFO - Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
[2024-11-18T18:18:04.061+0000] {process_utils.py:190} INFO - Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[2024-11-18T18:18:04.062+0000] {process_utils.py:190} INFO - Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
[2024-11-18T18:18:04.063+0000] {process_utils.py:190} INFO - Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
[2024-11-18T18:18:06.179+0000] {process_utils.py:190} INFO - Installing collected packages: libclang, flatbuffers, typing-extensions, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, querystring-parser, opt-einsum, numpy, keras, google-pasta, gast, entrypoints, astunparse, absl-py, h5py, botocore, s3transfer, google-auth-oauthlib, tensorboard, mlflow, boto3, tensorflow
[2024-11-18T18:18:06.427+0000] {process_utils.py:190} INFO -   Attempting uninstall: typing-extensions
[2024-11-18T18:18:06.428+0000] {process_utils.py:190} INFO -     Found existing installation: typing_extensions 4.9.0
[2024-11-18T18:18:06.428+0000] {process_utils.py:190} INFO -     Not uninstalling typing-extensions at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvpefvkyss
[2024-11-18T18:18:06.429+0000] {process_utils.py:190} INFO -     Can't uninstall 'typing_extensions'. No files were found to uninstall.
[2024-11-18T18:18:06.686+0000] {process_utils.py:190} INFO -   Attempting uninstall: numpy
[2024-11-18T18:18:06.688+0000] {process_utils.py:190} INFO -     Found existing installation: numpy 1.24.4
[2024-11-18T18:18:06.688+0000] {process_utils.py:190} INFO -     Not uninstalling numpy at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvpefvkyss
[2024-11-18T18:18:06.688+0000] {process_utils.py:190} INFO -     Can't uninstall 'numpy'. No files were found to uninstall.
[2024-11-18T18:18:08.358+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T18:18:08.359+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T18:18:08.359+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvpefvkyss
[2024-11-18T18:18:08.360+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T18:18:08.762+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T18:18:08.763+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T18:18:08.763+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvpefvkyss
[2024-11-18T18:18:08.764+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T18:18:08.785+0000] {process_utils.py:190} INFO -   Attempting uninstall: google-auth-oauthlib
[2024-11-18T18:18:08.787+0000] {process_utils.py:190} INFO -     Found existing installation: google-auth-oauthlib 1.2.0
[2024-11-18T18:18:08.787+0000] {process_utils.py:190} INFO -     Not uninstalling google-auth-oauthlib at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvpefvkyss
[2024-11-18T18:18:08.787+0000] {process_utils.py:190} INFO -     Can't uninstall 'google-auth-oauthlib'. No files were found to uninstall.
[2024-11-18T18:18:08.987+0000] {process_utils.py:190} INFO -   Attempting uninstall: mlflow
[2024-11-18T18:18:08.989+0000] {process_utils.py:190} INFO -     Found existing installation: mlflow 2.17.0
[2024-11-18T18:18:08.989+0000] {process_utils.py:190} INFO -     Not uninstalling mlflow at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvpefvkyss
[2024-11-18T18:18:08.990+0000] {process_utils.py:190} INFO -     Can't uninstall 'mlflow'. No files were found to uninstall.
[2024-11-18T18:18:09.554+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T18:18:09.555+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T18:18:09.555+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvpefvkyss
[2024-11-18T18:18:09.556+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T18:18:16.794+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T18:18:16.794+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T18:18:16.795+0000] {process_utils.py:190} INFO - azure-core 1.29.6 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:18:16.795+0000] {process_utils.py:190} INFO - azure-mgmt-keyvault 10.3.1 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:18:16.795+0000] {process_utils.py:190} INFO - azure-mgmt-network 27.0.0 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:18:16.796+0000] {process_utils.py:190} INFO - graphene 3.4 requires typing-extensions<5,>=4.7.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:18:16.796+0000] {process_utils.py:190} INFO - pydantic 2.5.3 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:18:16.796+0000] {process_utils.py:190} INFO - pydantic-core 2.14.6 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:18:16.797+0000] {process_utils.py:190} INFO - Successfully installed absl-py-2.1.0 astunparse-1.6.3 boto3-1.28.0 botocore-1.31.85 entrypoints-0.4 flatbuffers-24.3.25 gast-0.4.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 h5py-3.11.0 keras-2.13.1 libclang-18.1.1 mlflow-2.10.2 numpy-1.24.3 opt-einsum-3.4.0 querystring-parser-1.2.4 s3transfer-0.6.2 tensorboard-2.13.0 tensorboard-data-server-0.7.2 tensorflow-2.13.0 tensorflow-estimator-2.13.0 tensorflow-io-gcs-filesystem-0.34.0 typing-extensions-4.5.0
[2024-11-18T18:18:16.873+0000] {process_utils.py:190} INFO - 
[2024-11-18T18:18:16.873+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.3.1
[2024-11-18T18:18:16.874+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T18:18:17.059+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvpefvkyss/bin/python /tmp/venv-callz02g7nys/script.py /tmp/venv-callz02g7nys/script.in /tmp/venv-callz02g7nys/script.out /tmp/venv-callz02g7nys/string_args.txt /tmp/venv-callz02g7nys/termination.log
[2024-11-18T18:18:17.063+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:18:18.022+0000] {process_utils.py:190} INFO - 2024-11-18 18:18:18.022079: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-11-18T18:18:18.023+0000] {process_utils.py:190} INFO - 2024-11-18 18:18:18.023158: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T18:18:18.044+0000] {process_utils.py:190} INFO - 2024-11-18 18:18:18.044816: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T18:18:18.045+0000] {process_utils.py:190} INFO - 2024-11-18 18:18:18.045088: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-11-18T18:18:18.045+0000] {process_utils.py:190} INFO - To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-11-18T18:18:18.544+0000] {process_utils.py:190} INFO - 2024-11-18 18:18:18.544282: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-11-18T18:18:19.580+0000] {process_utils.py:190} INFO - Epoch 1/10
[2024-11-18T18:18:20.474+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 3:27 - loss: 0.2606 56/575 [=>............................] - ETA: 0s - loss: 0.1132  121/575 [=====>........................] - ETA: 0s - loss: 0.0828201/575 [=========>....................] - ETA: 0s - loss: 0.0660279/575 [=============>................] - ETA: 0s - loss: 0.0562357/575 [=================>............] - ETA: 0s - loss: 0.0495435/575 [=====================>........] - ETA: 0s - loss: 0.0447519/575 [==========================>...] - ETA: 0s - loss: 0.0407575/575 [==============================] - 1s 928us/step - loss: 0.0386 - val_loss: 0.0061
[2024-11-18T18:18:20.475+0000] {process_utils.py:190} INFO - Epoch 2/10
[2024-11-18T18:18:20.931+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0166 78/575 [===>..........................] - ETA: 0s - loss: 0.0174145/575 [======>.......................] - ETA: 0s - loss: 0.0170223/575 [==========>...................] - ETA: 0s - loss: 0.0163304/575 [==============>...............] - ETA: 0s - loss: 0.0159382/575 [==================>...........] - ETA: 0s - loss: 0.0153459/575 [======================>.......] - ETA: 0s - loss: 0.0149534/575 [==========================>...] - ETA: 0s - loss: 0.0145575/575 [==============================] - 0s 794us/step - loss: 0.0142 - val_loss: 0.0042
[2024-11-18T18:18:20.932+0000] {process_utils.py:190} INFO - Epoch 3/10
[2024-11-18T18:18:21.387+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0103 79/575 [===>..........................] - ETA: 0s - loss: 0.0110159/575 [=======>......................] - ETA: 0s - loss: 0.0108236/575 [===========>..................] - ETA: 0s - loss: 0.0106315/575 [===============>..............] - ETA: 0s - loss: 0.0105394/575 [===================>..........] - ETA: 0s - loss: 0.0103473/575 [=======================>......] - ETA: 0s - loss: 0.0102543/575 [===========================>..] - ETA: 0s - loss: 0.0101575/575 [==============================] - 0s 792us/step - loss: 0.0100 - val_loss: 0.0034
[2024-11-18T18:18:21.388+0000] {process_utils.py:190} INFO - Epoch 4/10
[2024-11-18T18:18:21.825+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0093 83/575 [===>..........................] - ETA: 0s - loss: 0.0090162/575 [=======>......................] - ETA: 0s - loss: 0.0090242/575 [===========>..................] - ETA: 0s - loss: 0.0089321/575 [===============>..............] - ETA: 0s - loss: 0.0088401/575 [===================>..........] - ETA: 0s - loss: 0.0087481/575 [========================>.....] - ETA: 0s - loss: 0.0086560/575 [============================>.] - ETA: 0s - loss: 0.0085575/575 [==============================] - 0s 760us/step - loss: 0.0084 - val_loss: 0.0030
[2024-11-18T18:18:21.825+0000] {process_utils.py:190} INFO - Epoch 5/10
[2024-11-18T18:18:22.258+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0059 71/575 [==>...........................] - ETA: 0s - loss: 0.0077159/575 [=======>......................] - ETA: 0s - loss: 0.0076244/575 [===========>..................] - ETA: 0s - loss: 0.0077324/575 [===============>..............] - ETA: 0s - loss: 0.0077399/575 [===================>..........] - ETA: 0s - loss: 0.0076480/575 [========================>.....] - ETA: 0s - loss: 0.0076567/575 [============================>.] - ETA: 0s - loss: 0.0075575/575 [==============================] - 0s 753us/step - loss: 0.0075 - val_loss: 0.0030
[2024-11-18T18:18:22.258+0000] {process_utils.py:190} INFO - Epoch 6/10
[2024-11-18T18:18:22.712+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0076 81/575 [===>..........................] - ETA: 0s - loss: 0.0074160/575 [=======>......................] - ETA: 0s - loss: 0.0072234/575 [===========>..................] - ETA: 0s - loss: 0.0072314/575 [===============>..............] - ETA: 0s - loss: 0.0072398/575 [===================>..........] - ETA: 0s - loss: 0.0072470/575 [=======================>......] - ETA: 0s - loss: 0.0071544/575 [===========================>..] - ETA: 0s - loss: 0.0071575/575 [==============================] - 0s 789us/step - loss: 0.0071 - val_loss: 0.0025
[2024-11-18T18:18:22.713+0000] {process_utils.py:190} INFO - Epoch 7/10
[2024-11-18T18:18:23.165+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0064 80/575 [===>..........................] - ETA: 0s - loss: 0.0070157/575 [=======>......................] - ETA: 0s - loss: 0.0068235/575 [===========>..................] - ETA: 0s - loss: 0.0067316/575 [===============>..............] - ETA: 0s - loss: 0.0068387/575 [===================>..........] - ETA: 0s - loss: 0.0068464/575 [=======================>......] - ETA: 0s - loss: 0.0068540/575 [===========================>..] - ETA: 0s - loss: 0.0068575/575 [==============================] - 0s 786us/step - loss: 0.0068 - val_loss: 0.0024
[2024-11-18T18:18:23.167+0000] {process_utils.py:190} INFO - Epoch 8/10
[2024-11-18T18:18:23.608+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0050 92/575 [===>..........................] - ETA: 0s - loss: 0.0067174/575 [========>.....................] - ETA: 0s - loss: 0.0067254/575 [============>.................] - ETA: 0s - loss: 0.0067334/575 [================>.............] - ETA: 0s - loss: 0.0067409/575 [====================>.........] - ETA: 0s - loss: 0.0067486/575 [========================>.....] - ETA: 0s - loss: 0.0067564/575 [============================>.] - ETA: 0s - loss: 0.0067575/575 [==============================] - 0s 770us/step - loss: 0.0067 - val_loss: 0.0024
[2024-11-18T18:18:23.609+0000] {process_utils.py:190} INFO - Epoch 9/10
[2024-11-18T18:18:24.052+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0083 80/575 [===>..........................] - ETA: 0s - loss: 0.0064160/575 [=======>......................] - ETA: 0s - loss: 0.0064234/575 [===========>..................] - ETA: 0s - loss: 0.0065311/575 [===============>..............] - ETA: 0s - loss: 0.0065391/575 [===================>..........] - ETA: 0s - loss: 0.0065470/575 [=======================>......] - ETA: 0s - loss: 0.0064551/575 [===========================>..] - ETA: 0s - loss: 0.0064575/575 [==============================] - 0s 770us/step - loss: 0.0064 - val_loss: 0.0021
[2024-11-18T18:18:24.052+0000] {process_utils.py:190} INFO - Epoch 10/10
[2024-11-18T18:18:24.500+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0075 79/575 [===>..........................] - ETA: 0s - loss: 0.0064159/575 [=======>......................] - ETA: 0s - loss: 0.0064237/575 [===========>..................] - ETA: 0s - loss: 0.0064315/575 [===============>..............] - ETA: 0s - loss: 0.0064396/575 [===================>..........] - ETA: 0s - loss: 0.0063474/575 [=======================>......] - ETA: 0s - loss: 0.0063553/575 [===========================>..] - ETA: 0s - loss: 0.0063575/575 [==============================] - 0s 779us/step - loss: 0.0063 - val_loss: 0.0021
[2024-11-18T18:18:24.882+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 28s108/719 [===>..........................] - ETA: 0s 221/719 [========>.....................] - ETA: 0s333/719 [============>.................] - ETA: 0s446/719 [=================>............] - ETA: 0s564/719 [======================>.......] - ETA: 0s669/719 [==========================>...] - ETA: 0s719/719 [==============================] - 0s 449us/step
[2024-11-18T18:18:25.443+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 8s102/719 [===>..........................] - ETA: 0s222/719 [========>.....................] - ETA: 0s329/719 [============>.................] - ETA: 0s440/719 [=================>............] - ETA: 0s548/719 [=====================>........] - ETA: 0s657/719 [==========================>...] - ETA: 0s719/719 [==============================] - 0s 461us/step
[2024-11-18T18:18:25.537+0000] {process_utils.py:190} INFO - /tmp/venvpefvkyss/lib/python3.8/site-packages/keras/src/engine/training.py:3000 UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
[2024-11-18T18:18:25.558+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-11-18T18:18:25.559+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callz02g7nys/script.py", line 96, in <module>
[2024-11-18T18:18:25.559+0000] {process_utils.py:190} INFO -     res = train_challenger_model(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-18T18:18:25.559+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callz02g7nys/script.py", line 83, in train_challenger_model
[2024-11-18T18:18:25.560+0000] {process_utils.py:190} INFO -     mlflow.keras.log_model(model, artifact_path="model", registered_model_name="spotify_model_prod")
[2024-11-18T18:18:25.560+0000] {process_utils.py:190} INFO - AttributeError: module 'mlflow' has no attribute 'keras'
[2024-11-18T18:18:26.440+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
module 'mlflow' has no attribute 'keras'
[2024-11-18T18:18:26.442+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_retrain_challenge_model_v3, task_id=train_challenger_model, execution_date=20241118T181759, start_date=20241118T181800, end_date=20241118T181826
[2024-11-18T18:18:26.454+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 79 for task train_challenger_model (Process returned non-zero exit status 1.
module 'mlflow' has no attribute 'keras'; 8924)
[2024-11-18T18:18:26.493+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-18T18:18:26.508+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
