[2024-11-18T18:23:27.127+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:17:59.060229+00:00 [queued]>
[2024-11-18T18:23:27.132+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:17:59.060229+00:00 [queued]>
[2024-11-18T18:23:27.132+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-11-18T18:23:27.140+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_challenger_model> on 2024-11-18 18:17:59.060229+00:00
[2024-11-18T18:23:27.143+0000] {standard_task_runner.py:60} INFO - Started process 11659 to run task
[2024-11-18T18:23:27.144+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_retrain_challenge_model_v3', 'train_challenger_model', 'manual__2024-11-18T18:17:59.060229+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/retrain_music_model.py', '--cfg-path', '/tmp/tmpprt6w86h']
[2024-11-18T18:23:27.145+0000] {standard_task_runner.py:88} INFO - Job 83: Subtask train_challenger_model
[2024-11-18T18:23:27.170+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:17:59.060229+00:00 [running]> on host 98017b53a184
[2024-11-18T18:23:27.207+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_retrain_challenge_model_v3' AIRFLOW_CTX_TASK_ID='train_challenger_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T18:17:59.060229+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T18:17:59.060229+00:00'
[2024-11-18T18:23:27.208+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvo0vccq4d --system-site-packages --python=python
[2024-11-18T18:23:27.212+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:23:27.539+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 117ms
[2024-11-18T18:23:27.539+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvo0vccq4d, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T18:23:27.540+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T18:23:27.540+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-11-18T18:23:27.541+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T18:23:27.559+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvo0vccq4d/bin/pip install -r /tmp/venvo0vccq4d/requirements.txt
[2024-11-18T18:23:27.563+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:23:28.512+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venvo0vccq4d/requirements.txt (line 1))
[2024-11-18T18:23:28.514+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T18:23:28.604+0000] {process_utils.py:190} INFO - Collecting mlflow==2.10.2 (from -r /tmp/venvo0vccq4d/requirements.txt (line 2))
[2024-11-18T18:23:28.606+0000] {process_utils.py:190} INFO -   Using cached mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
[2024-11-18T18:23:28.607+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvo0vccq4d/requirements.txt (line 3)) (2.0.3)
[2024-11-18T18:23:28.607+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn==1.3.2 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvo0vccq4d/requirements.txt (line 4)) (1.3.2)
[2024-11-18T18:23:28.712+0000] {process_utils.py:190} INFO - Collecting tensorflow==2.13.0 (from -r /tmp/venvo0vccq4d/requirements.txt (line 5))
[2024-11-18T18:23:28.714+0000] {process_utils.py:190} INFO -   Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
[2024-11-18T18:23:29.109+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venvo0vccq4d/requirements.txt (line 1))
[2024-11-18T18:23:29.111+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T18:23:29.112+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venvo0vccq4d/requirements.txt (line 1)) (0.10.0)
[2024-11-18T18:23:29.135+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venvo0vccq4d/requirements.txt (line 1))
[2024-11-18T18:23:29.137+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:23:29.191+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (8.1.7)
[2024-11-18T18:23:29.192+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (3.1.0)
[2024-11-18T18:23:29.208+0000] {process_utils.py:190} INFO - Collecting entrypoints<1 (from mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2))
[2024-11-18T18:23:29.210+0000] {process_utils.py:190} INFO -   Using cached entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
[2024-11-18T18:23:29.210+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=2.1.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (3.1.43)
[2024-11-18T18:23:29.211+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (6.0.1)
[2024-11-18T18:23:29.211+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<5,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (4.25.2)
[2024-11-18T18:23:29.212+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz<2024 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T18:23:29.212+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (2.31.0)
[2024-11-18T18:23:29.213+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (23.2)
[2024-11-18T18:23:29.213+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (6.11.0)
[2024-11-18T18:23:29.214+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (0.4.4)
[2024-11-18T18:23:29.214+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (1.13.1)
[2024-11-18T18:23:29.215+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (7.0.0)
[2024-11-18T18:23:29.215+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (2.2.5)
[2024-11-18T18:23:29.216+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (1.24.4)
[2024-11-18T18:23:29.216+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (1.10.1)
[2024-11-18T18:23:29.232+0000] {process_utils.py:190} INFO - Collecting querystring-parser<2 (from mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2))
[2024-11-18T18:23:29.234+0000] {process_utils.py:190} INFO -   Using cached querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
[2024-11-18T18:23:29.234+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (1.4.51)
[2024-11-18T18:23:29.235+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow<16,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (14.0.2)
[2024-11-18T18:23:29.235+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (3.5.2)
[2024-11-18T18:23:29.236+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (3.7.5)
[2024-11-18T18:23:29.237+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<22 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (21.2.0)
[2024-11-18T18:23:29.237+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (3.1.3)
[2024-11-18T18:23:29.290+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvo0vccq4d/requirements.txt (line 3)) (2.8.2)
[2024-11-18T18:23:29.291+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvo0vccq4d/requirements.txt (line 3)) (2023.4)
[2024-11-18T18:23:29.312+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvo0vccq4d/requirements.txt (line 4)) (1.4.2)
[2024-11-18T18:23:29.313+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvo0vccq4d/requirements.txt (line 4)) (3.5.0)
[2024-11-18T18:23:29.347+0000] {process_utils.py:190} INFO - Collecting absl-py>=1.0.0 (from tensorflow==2.13.0->-r /tmp/venvo0vccq4d/requirements.txt (line 5))
[2024-11-18T18:23:29.348+0000] {process_utils.py:190} INFO -   Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
[2024-11-18T18:23:29.365+0000] {process_utils.py:190} INFO - Collecting astunparse>=1.6.0 (from tensorflow==2.13.0->-r /tmp/venvo0vccq4d/requirements.txt (line 5))
[2024-11-18T18:23:29.366+0000] {process_utils.py:190} INFO -   Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
[2024-11-18T18:23:29.384+0000] {process_utils.py:190} INFO - Collecting flatbuffers>=23.1.21 (from tensorflow==2.13.0->-r /tmp/venvo0vccq4d/requirements.txt (line 5))
[2024-11-18T18:23:29.385+0000] {process_utils.py:190} INFO -   Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
[2024-11-18T18:23:29.406+0000] {process_utils.py:190} INFO - Collecting gast<=0.4.0,>=0.2.1 (from tensorflow==2.13.0->-r /tmp/venvo0vccq4d/requirements.txt (line 5))
[2024-11-18T18:23:29.407+0000] {process_utils.py:190} INFO -   Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
[2024-11-18T18:23:29.424+0000] {process_utils.py:190} INFO - Collecting google-pasta>=0.1.1 (from tensorflow==2.13.0->-r /tmp/venvo0vccq4d/requirements.txt (line 5))
[2024-11-18T18:23:29.425+0000] {process_utils.py:190} INFO -   Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
[2024-11-18T18:23:29.426+0000] {process_utils.py:190} INFO - Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvo0vccq4d/requirements.txt (line 5)) (1.60.0)
[2024-11-18T18:23:29.471+0000] {process_utils.py:190} INFO - Collecting h5py>=2.9.0 (from tensorflow==2.13.0->-r /tmp/venvo0vccq4d/requirements.txt (line 5))
[2024-11-18T18:23:29.473+0000] {process_utils.py:190} INFO -   Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
[2024-11-18T18:23:29.499+0000] {process_utils.py:190} INFO - Collecting keras<2.14,>=2.13.1 (from tensorflow==2.13.0->-r /tmp/venvo0vccq4d/requirements.txt (line 5))
[2024-11-18T18:23:29.500+0000] {process_utils.py:190} INFO -   Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
[2024-11-18T18:23:29.522+0000] {process_utils.py:190} INFO - Collecting libclang>=13.0.0 (from tensorflow==2.13.0->-r /tmp/venvo0vccq4d/requirements.txt (line 5))
[2024-11-18T18:23:29.524+0000] {process_utils.py:190} INFO -   Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
[2024-11-18T18:23:29.676+0000] {process_utils.py:190} INFO - Collecting numpy<2 (from mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2))
[2024-11-18T18:23:29.677+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-11-18T18:23:29.697+0000] {process_utils.py:190} INFO - Collecting opt-einsum>=2.3.2 (from tensorflow==2.13.0->-r /tmp/venvo0vccq4d/requirements.txt (line 5))
[2024-11-18T18:23:29.698+0000] {process_utils.py:190} INFO -   Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
[2024-11-18T18:23:29.699+0000] {process_utils.py:190} INFO - Requirement already satisfied: setuptools in /tmp/venvo0vccq4d/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvo0vccq4d/requirements.txt (line 5)) (69.0.2)
[2024-11-18T18:23:29.699+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.12.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvo0vccq4d/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:23:29.724+0000] {process_utils.py:190} INFO - Collecting tensorboard<2.14,>=2.13 (from tensorflow==2.13.0->-r /tmp/venvo0vccq4d/requirements.txt (line 5))
[2024-11-18T18:23:29.726+0000] {process_utils.py:190} INFO -   Using cached tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:23:29.745+0000] {process_utils.py:190} INFO - Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow==2.13.0->-r /tmp/venvo0vccq4d/requirements.txt (line 5))
[2024-11-18T18:23:29.747+0000] {process_utils.py:190} INFO -   Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
[2024-11-18T18:23:29.748+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.1.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvo0vccq4d/requirements.txt (line 5)) (2.4.0)
[2024-11-18T18:23:29.772+0000] {process_utils.py:190} INFO - Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow==2.13.0->-r /tmp/venvo0vccq4d/requirements.txt (line 5))
[2024-11-18T18:23:29.773+0000] {process_utils.py:190} INFO -   Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
[2024-11-18T18:23:29.774+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt>=1.11.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvo0vccq4d/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:23:29.828+0000] {process_utils.py:190} INFO - Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow==2.13.0->-r /tmp/venvo0vccq4d/requirements.txt (line 5))
[2024-11-18T18:23:29.829+0000] {process_utils.py:190} INFO -   Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
[2024-11-18T18:23:29.837+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (1.3.0)
[2024-11-18T18:23:29.841+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (5.13.0)
[2024-11-18T18:23:29.844+0000] {process_utils.py:190} INFO - Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venvo0vccq4d/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow==2.13.0->-r /tmp/venvo0vccq4d/requirements.txt (line 5)) (0.42.0)
[2024-11-18T18:23:29.849+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venvo0vccq4d/requirements.txt (line 1)) (1.26.18)
[2024-11-18T18:23:29.863+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (2.2.3)
[2024-11-18T18:23:29.863+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (2.1.2)
[2024-11-18T18:23:29.881+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (4.0.11)
[2024-11-18T18:23:29.908+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (3.17.0)
[2024-11-18T18:23:29.912+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (2.1.3)
[2024-11-18T18:23:29.936+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (1.1.1)
[2024-11-18T18:23:29.936+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (0.12.1)
[2024-11-18T18:23:29.937+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (4.54.1)
[2024-11-18T18:23:29.937+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (1.4.7)
[2024-11-18T18:23:29.947+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (10.4.0)
[2024-11-18T18:23:29.948+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (3.1.1)
[2024-11-18T18:23:29.994+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (3.3.2)
[2024-11-18T18:23:29.994+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (3.6)
[2024-11-18T18:23:29.995+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (2023.11.17)
[2024-11-18T18:23:30.179+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (3.0.3)
[2024-11-18T18:23:30.199+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth<3,>=1.6.3 in /home/***/.local/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvo0vccq4d/requirements.txt (line 5)) (2.26.2)
[2024-11-18T18:23:30.221+0000] {process_utils.py:190} INFO - Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvo0vccq4d/requirements.txt (line 5))
[2024-11-18T18:23:30.222+0000] {process_utils.py:190} INFO -   Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
[2024-11-18T18:23:30.254+0000] {process_utils.py:190} INFO - Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvo0vccq4d/requirements.txt (line 5))
[2024-11-18T18:23:30.256+0000] {process_utils.py:190} INFO -   Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
[2024-11-18T18:23:30.395+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvo0vccq4d/requirements.txt (line 2)) (5.0.1)
[2024-11-18T18:23:30.405+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvo0vccq4d/requirements.txt (line 5)) (5.3.2)
[2024-11-18T18:23:30.407+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvo0vccq4d/requirements.txt (line 5)) (0.3.0)
[2024-11-18T18:23:30.412+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvo0vccq4d/requirements.txt (line 5)) (4.9)
[2024-11-18T18:23:30.415+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvo0vccq4d/requirements.txt (line 5)) (1.3.1)
[2024-11-18T18:23:30.542+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvo0vccq4d/requirements.txt (line 5)) (0.5.1)
[2024-11-18T18:23:30.549+0000] {process_utils.py:190} INFO - Requirement already satisfied: oauthlib>=3.0.0 in /home/***/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvo0vccq4d/requirements.txt (line 5)) (3.2.2)
[2024-11-18T18:23:30.582+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T18:23:30.584+0000] {process_utils.py:190} INFO - Using cached mlflow-2.10.2-py3-none-any.whl (19.5 MB)
[2024-11-18T18:23:30.603+0000] {process_utils.py:190} INFO - Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
[2024-11-18T18:23:31.077+0000] {process_utils.py:190} INFO - Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
[2024-11-18T18:23:31.081+0000] {process_utils.py:190} INFO - Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
[2024-11-18T18:23:31.083+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T18:23:31.095+0000] {process_utils.py:190} INFO - Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
[2024-11-18T18:23:31.096+0000] {process_utils.py:190} INFO - Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
[2024-11-18T18:23:31.097+0000] {process_utils.py:190} INFO - Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
[2024-11-18T18:23:31.099+0000] {process_utils.py:190} INFO - Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
[2024-11-18T18:23:31.100+0000] {process_utils.py:190} INFO - Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
[2024-11-18T18:23:31.106+0000] {process_utils.py:190} INFO - Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)
[2024-11-18T18:23:31.109+0000] {process_utils.py:190} INFO - Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
[2024-11-18T18:23:31.133+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-11-18T18:23:31.150+0000] {process_utils.py:190} INFO - Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
[2024-11-18T18:23:31.151+0000] {process_utils.py:190} INFO - Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
[2024-11-18T18:23:31.152+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T18:23:31.153+0000] {process_utils.py:190} INFO - Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
[2024-11-18T18:23:31.160+0000] {process_utils.py:190} INFO - Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
[2024-11-18T18:23:31.161+0000] {process_utils.py:190} INFO - Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
[2024-11-18T18:23:31.164+0000] {process_utils.py:190} INFO - Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[2024-11-18T18:23:31.165+0000] {process_utils.py:190} INFO - Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
[2024-11-18T18:23:31.166+0000] {process_utils.py:190} INFO - Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
[2024-11-18T18:23:33.317+0000] {process_utils.py:190} INFO - Installing collected packages: libclang, flatbuffers, typing-extensions, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, querystring-parser, opt-einsum, numpy, keras, google-pasta, gast, entrypoints, astunparse, absl-py, h5py, botocore, s3transfer, google-auth-oauthlib, tensorboard, mlflow, boto3, tensorflow
[2024-11-18T18:23:33.561+0000] {process_utils.py:190} INFO -   Attempting uninstall: typing-extensions
[2024-11-18T18:23:33.562+0000] {process_utils.py:190} INFO -     Found existing installation: typing_extensions 4.9.0
[2024-11-18T18:23:33.562+0000] {process_utils.py:190} INFO -     Not uninstalling typing-extensions at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvo0vccq4d
[2024-11-18T18:23:33.563+0000] {process_utils.py:190} INFO -     Can't uninstall 'typing_extensions'. No files were found to uninstall.
[2024-11-18T18:23:33.835+0000] {process_utils.py:190} INFO -   Attempting uninstall: numpy
[2024-11-18T18:23:33.837+0000] {process_utils.py:190} INFO -     Found existing installation: numpy 1.24.4
[2024-11-18T18:23:33.837+0000] {process_utils.py:190} INFO -     Not uninstalling numpy at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvo0vccq4d
[2024-11-18T18:23:33.837+0000] {process_utils.py:190} INFO -     Can't uninstall 'numpy'. No files were found to uninstall.
[2024-11-18T18:23:35.527+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T18:23:35.528+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T18:23:35.528+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvo0vccq4d
[2024-11-18T18:23:35.529+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T18:23:35.957+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T18:23:35.958+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T18:23:35.958+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvo0vccq4d
[2024-11-18T18:23:35.959+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T18:23:35.981+0000] {process_utils.py:190} INFO -   Attempting uninstall: google-auth-oauthlib
[2024-11-18T18:23:35.982+0000] {process_utils.py:190} INFO -     Found existing installation: google-auth-oauthlib 1.2.0
[2024-11-18T18:23:35.983+0000] {process_utils.py:190} INFO -     Not uninstalling google-auth-oauthlib at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvo0vccq4d
[2024-11-18T18:23:35.983+0000] {process_utils.py:190} INFO -     Can't uninstall 'google-auth-oauthlib'. No files were found to uninstall.
[2024-11-18T18:23:36.185+0000] {process_utils.py:190} INFO -   Attempting uninstall: mlflow
[2024-11-18T18:23:36.186+0000] {process_utils.py:190} INFO -     Found existing installation: mlflow 2.17.0
[2024-11-18T18:23:36.187+0000] {process_utils.py:190} INFO -     Not uninstalling mlflow at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvo0vccq4d
[2024-11-18T18:23:36.187+0000] {process_utils.py:190} INFO -     Can't uninstall 'mlflow'. No files were found to uninstall.
[2024-11-18T18:23:36.790+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T18:23:36.791+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T18:23:36.791+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvo0vccq4d
[2024-11-18T18:23:36.791+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T18:23:44.002+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T18:23:44.002+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T18:23:44.003+0000] {process_utils.py:190} INFO - azure-core 1.29.6 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:23:44.003+0000] {process_utils.py:190} INFO - azure-mgmt-keyvault 10.3.1 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:23:44.003+0000] {process_utils.py:190} INFO - azure-mgmt-network 27.0.0 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:23:44.004+0000] {process_utils.py:190} INFO - graphene 3.4 requires typing-extensions<5,>=4.7.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:23:44.004+0000] {process_utils.py:190} INFO - pydantic 2.5.3 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:23:44.004+0000] {process_utils.py:190} INFO - pydantic-core 2.14.6 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:23:44.004+0000] {process_utils.py:190} INFO - Successfully installed absl-py-2.1.0 astunparse-1.6.3 boto3-1.28.0 botocore-1.31.85 entrypoints-0.4 flatbuffers-24.3.25 gast-0.4.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 h5py-3.11.0 keras-2.13.1 libclang-18.1.1 mlflow-2.10.2 numpy-1.24.3 opt-einsum-3.4.0 querystring-parser-1.2.4 s3transfer-0.6.2 tensorboard-2.13.0 tensorboard-data-server-0.7.2 tensorflow-2.13.0 tensorflow-estimator-2.13.0 tensorflow-io-gcs-filesystem-0.34.0 typing-extensions-4.5.0
[2024-11-18T18:23:44.092+0000] {process_utils.py:190} INFO - 
[2024-11-18T18:23:44.092+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.3.1
[2024-11-18T18:23:44.093+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T18:23:44.294+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvo0vccq4d/bin/python /tmp/venv-callhsmn_395/script.py /tmp/venv-callhsmn_395/script.in /tmp/venv-callhsmn_395/script.out /tmp/venv-callhsmn_395/string_args.txt /tmp/venv-callhsmn_395/termination.log
[2024-11-18T18:23:44.298+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:23:45.249+0000] {process_utils.py:190} INFO - 2024-11-18 18:23:45.248973: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-11-18T18:23:45.250+0000] {process_utils.py:190} INFO - 2024-11-18 18:23:45.250228: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T18:23:45.271+0000] {process_utils.py:190} INFO - 2024-11-18 18:23:45.271375: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T18:23:45.271+0000] {process_utils.py:190} INFO - 2024-11-18 18:23:45.271626: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-11-18T18:23:45.272+0000] {process_utils.py:190} INFO - To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-11-18T18:23:45.782+0000] {process_utils.py:190} INFO - 2024-11-18 18:23:45.782575: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-11-18T18:23:46.821+0000] {process_utils.py:190} INFO - Epoch 1/10
[2024-11-18T18:23:47.734+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 3:32 - loss: 0.4950 52/575 [=>............................] - ETA: 0s - loss: 0.2167  108/575 [====>.........................] - ETA: 0s - loss: 0.1484186/575 [========>.....................] - ETA: 0s - loss: 0.1101268/575 [============>.................] - ETA: 0s - loss: 0.0896353/575 [=================>............] - ETA: 0s - loss: 0.0767433/575 [=====================>........] - ETA: 0s - loss: 0.0682511/575 [=========================>....] - ETA: 0s - loss: 0.0619575/575 [==============================] - 1s 944us/step - loss: 0.0576 - val_loss: 0.0086
[2024-11-18T18:23:47.734+0000] {process_utils.py:190} INFO - Epoch 2/10
[2024-11-18T18:23:48.170+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0235 83/575 [===>..........................] - ETA: 0s - loss: 0.0215166/575 [=======>......................] - ETA: 0s - loss: 0.0205247/575 [===========>..................] - ETA: 0s - loss: 0.0197328/575 [================>.............] - ETA: 0s - loss: 0.0189408/575 [====================>.........] - ETA: 0s - loss: 0.0184491/575 [========================>.....] - ETA: 0s - loss: 0.0178574/575 [============================>.] - ETA: 0s - loss: 0.0172575/575 [==============================] - 0s 757us/step - loss: 0.0172 - val_loss: 0.0055
[2024-11-18T18:23:48.170+0000] {process_utils.py:190} INFO - Epoch 3/10
[2024-11-18T18:23:48.614+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0129 79/575 [===>..........................] - ETA: 0s - loss: 0.0136157/575 [=======>......................] - ETA: 0s - loss: 0.0134238/575 [===========>..................] - ETA: 0s - loss: 0.0132315/575 [===============>..............] - ETA: 0s - loss: 0.0130394/575 [===================>..........] - ETA: 0s - loss: 0.0127476/575 [=======================>......] - ETA: 0s - loss: 0.0126558/575 [============================>.] - ETA: 0s - loss: 0.0124575/575 [==============================] - 0s 772us/step - loss: 0.0123 - val_loss: 0.0046
[2024-11-18T18:23:48.615+0000] {process_utils.py:190} INFO - Epoch 4/10
[2024-11-18T18:23:49.050+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0133 87/575 [===>..........................] - ETA: 0s - loss: 0.0112171/575 [=======>......................] - ETA: 0s - loss: 0.0110245/575 [===========>..................] - ETA: 0s - loss: 0.0109320/575 [===============>..............] - ETA: 0s - loss: 0.0107404/575 [====================>.........] - ETA: 0s - loss: 0.0105489/575 [========================>.....] - ETA: 0s - loss: 0.0104573/575 [============================>.] - ETA: 0s - loss: 0.0103575/575 [==============================] - 0s 758us/step - loss: 0.0103 - val_loss: 0.0037
[2024-11-18T18:23:49.051+0000] {process_utils.py:190} INFO - Epoch 5/10
[2024-11-18T18:23:49.476+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0114 82/575 [===>..........................] - ETA: 0s - loss: 0.0092169/575 [=======>......................] - ETA: 0s - loss: 0.0091254/575 [============>.................] - ETA: 0s - loss: 0.0091334/575 [================>.............] - ETA: 0s - loss: 0.0090410/575 [====================>.........] - ETA: 0s - loss: 0.0090490/575 [========================>.....] - ETA: 0s - loss: 0.0089575/575 [==============================] - 0s 738us/step - loss: 0.0089 - val_loss: 0.0033
[2024-11-18T18:23:49.476+0000] {process_utils.py:190} INFO - Epoch 6/10
[2024-11-18T18:23:49.910+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0077 85/575 [===>..........................] - ETA: 0s - loss: 0.0083170/575 [=======>......................] - ETA: 0s - loss: 0.0084252/575 [============>.................] - ETA: 0s - loss: 0.0083335/575 [================>.............] - ETA: 0s - loss: 0.0082413/575 [====================>.........] - ETA: 0s - loss: 0.0082493/575 [========================>.....] - ETA: 0s - loss: 0.0081569/575 [============================>.] - ETA: 0s - loss: 0.0080575/575 [==============================] - 0s 755us/step - loss: 0.0080 - val_loss: 0.0031
[2024-11-18T18:23:49.911+0000] {process_utils.py:190} INFO - Epoch 7/10
[2024-11-18T18:23:50.424+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0082 80/575 [===>..........................] - ETA: 0s - loss: 0.0081161/575 [=======>......................] - ETA: 0s - loss: 0.0078243/575 [===========>..................] - ETA: 0s - loss: 0.0077320/575 [===============>..............] - ETA: 0s - loss: 0.0077397/575 [===================>..........] - ETA: 0s - loss: 0.0077478/575 [=======================>......] - ETA: 0s - loss: 0.0077561/575 [============================>.] - ETA: 0s - loss: 0.0077575/575 [==============================] - 1s 893us/step - loss: 0.0077 - val_loss: 0.0028
[2024-11-18T18:23:50.424+0000] {process_utils.py:190} INFO - Epoch 8/10
[2024-11-18T18:23:50.869+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0076 77/575 [===>..........................] - ETA: 0s - loss: 0.0072156/575 [=======>......................] - ETA: 0s - loss: 0.0073242/575 [===========>..................] - ETA: 0s - loss: 0.0072319/575 [===============>..............] - ETA: 0s - loss: 0.0072401/575 [===================>..........] - ETA: 0s - loss: 0.0072480/575 [========================>.....] - ETA: 0s - loss: 0.0073557/575 [============================>.] - ETA: 0s - loss: 0.0073575/575 [==============================] - 0s 772us/step - loss: 0.0073 - val_loss: 0.0026
[2024-11-18T18:23:50.869+0000] {process_utils.py:190} INFO - Epoch 9/10
[2024-11-18T18:23:51.307+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0055 81/575 [===>..........................] - ETA: 0s - loss: 0.0071162/575 [=======>......................] - ETA: 0s - loss: 0.0070239/575 [===========>..................] - ETA: 0s - loss: 0.0071314/575 [===============>..............] - ETA: 0s - loss: 0.0071398/575 [===================>..........] - ETA: 0s - loss: 0.0071483/575 [========================>.....] - ETA: 0s - loss: 0.0072564/575 [============================>.] - ETA: 0s - loss: 0.0071575/575 [==============================] - 0s 761us/step - loss: 0.0071 - val_loss: 0.0025
[2024-11-18T18:23:51.307+0000] {process_utils.py:190} INFO - Epoch 10/10
[2024-11-18T18:23:51.749+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0082 87/575 [===>..........................] - ETA: 0s - loss: 0.0071170/575 [=======>......................] - ETA: 0s - loss: 0.0071258/575 [============>.................] - ETA: 0s - loss: 0.0071335/575 [================>.............] - ETA: 0s - loss: 0.0071412/575 [====================>.........] - ETA: 0s - loss: 0.0070485/575 [========================>.....] - ETA: 0s - loss: 0.0070562/575 [============================>.] - ETA: 0s - loss: 0.0070575/575 [==============================] - 0s 768us/step - loss: 0.0070 - val_loss: 0.0024
[2024-11-18T18:23:52.135+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 29s104/719 [===>..........................] - ETA: 0s 212/719 [=======>......................] - ETA: 0s320/719 [============>.................] - ETA: 0s430/719 [================>.............] - ETA: 0s554/719 [======================>.......] - ETA: 0s666/719 [==========================>...] - ETA: 0s719/719 [==============================] - 0s 454us/step
[2024-11-18T18:23:52.743+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 7s114/719 [===>..........................] - ETA: 0s219/719 [========>.....................] - ETA: 0s327/719 [============>.................] - ETA: 0s432/719 [=================>............] - ETA: 0s544/719 [=====================>........] - ETA: 0s662/719 [==========================>...] - ETA: 0s719/719 [==============================] - 0s 455us/step
[2024-11-18T18:23:52.829+0000] {process_utils.py:190} INFO - /tmp/venvo0vccq4d/lib/python3.8/site-packages/keras/src/engine/training.py:3000 UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
[2024-11-18T18:23:52.857+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-11-18T18:23:52.858+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callhsmn_395/script.py", line 101, in <module>
[2024-11-18T18:23:52.858+0000] {process_utils.py:190} INFO -     res = train_challenger_model(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-18T18:23:52.858+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callhsmn_395/script.py", line 84, in train_challenger_model
[2024-11-18T18:23:52.858+0000] {process_utils.py:190} INFO -     mlflow.tensorflow.log_model(
[2024-11-18T18:23:52.859+0000] {process_utils.py:190} INFO - TypeError: log_model() got an unexpected keyword argument 'tf_saved_model_dir'
[2024-11-18T18:23:53.715+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
log_model() got an unexpected keyword argument 'tf_saved_model_dir'
[2024-11-18T18:23:53.717+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=spotify_retrain_challenge_model_v3, task_id=train_challenger_model, execution_date=20241118T181759, start_date=20241118T182327, end_date=20241118T182353
[2024-11-18T18:23:53.724+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 83 for task train_challenger_model (Process returned non-zero exit status 1.
log_model() got an unexpected keyword argument 'tf_saved_model_dir'; 11659)
[2024-11-18T18:23:53.733+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-18T18:23:53.745+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
