[2024-11-18T18:37:44.326+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.evaluate_champion manual__2024-11-18T18:37:15.025333+00:00 [queued]>
[2024-11-18T18:37:44.331+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.evaluate_champion manual__2024-11-18T18:37:15.025333+00:00 [queued]>
[2024-11-18T18:37:44.331+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-11-18T18:37:44.338+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): evaluate_champion> on 2024-11-18 18:37:15.025333+00:00
[2024-11-18T18:37:44.341+0000] {standard_task_runner.py:60} INFO - Started process 20262 to run task
[2024-11-18T18:37:44.343+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_retrain_challenge_model_v3', 'evaluate_champion', 'manual__2024-11-18T18:37:15.025333+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/retrain_music_model.py', '--cfg-path', '/tmp/tmpnxejdf5x']
[2024-11-18T18:37:44.344+0000] {standard_task_runner.py:88} INFO - Job 100: Subtask evaluate_champion
[2024-11-18T18:37:44.369+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_retrain_challenge_model_v3.evaluate_champion manual__2024-11-18T18:37:15.025333+00:00 [running]> on host 98017b53a184
[2024-11-18T18:37:44.406+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_retrain_challenge_model_v3' AIRFLOW_CTX_TASK_ID='evaluate_champion' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T18:37:15.025333+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T18:37:15.025333+00:00'
[2024-11-18T18:37:44.408+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvytwot105 --system-site-packages --python=python
[2024-11-18T18:37:44.412+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:37:44.778+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 152ms
[2024-11-18T18:37:44.778+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvytwot105, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T18:37:44.779+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T18:37:44.779+0000] {process_utils.py:190} INFO -     added seed packages: pip==24.2, setuptools==75.2.0, wheel==0.44.0
[2024-11-18T18:37:44.779+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T18:37:44.798+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvytwot105/bin/pip install -r /tmp/venvytwot105/requirements.txt
[2024-11-18T18:37:44.802+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:37:45.654+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venvytwot105/requirements.txt (line 1))
[2024-11-18T18:37:45.655+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T18:37:45.692+0000] {process_utils.py:190} INFO - Collecting mlflow==2.10.2 (from -r /tmp/venvytwot105/requirements.txt (line 2))
[2024-11-18T18:37:45.693+0000] {process_utils.py:190} INFO -   Using cached mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
[2024-11-18T18:37:45.701+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvytwot105/requirements.txt (line 3)) (2.0.3)
[2024-11-18T18:37:45.701+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn==1.3.2 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvytwot105/requirements.txt (line 4)) (1.3.2)
[2024-11-18T18:37:45.788+0000] {process_utils.py:190} INFO - Collecting tensorflow==2.13.0 (from -r /tmp/venvytwot105/requirements.txt (line 5))
[2024-11-18T18:37:45.790+0000] {process_utils.py:190} INFO -   Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
[2024-11-18T18:37:46.190+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venvytwot105/requirements.txt (line 1))
[2024-11-18T18:37:46.192+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T18:37:46.193+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venvytwot105/requirements.txt (line 1)) (0.10.0)
[2024-11-18T18:37:46.232+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venvytwot105/requirements.txt (line 1))
[2024-11-18T18:37:46.234+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:37:46.237+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (8.1.7)
[2024-11-18T18:37:46.237+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (3.1.0)
[2024-11-18T18:37:46.252+0000] {process_utils.py:190} INFO - Collecting entrypoints<1 (from mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2))
[2024-11-18T18:37:46.253+0000] {process_utils.py:190} INFO -   Using cached entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
[2024-11-18T18:37:46.254+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=2.1.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (3.1.43)
[2024-11-18T18:37:46.254+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (6.0.1)
[2024-11-18T18:37:46.254+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<5,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (4.25.2)
[2024-11-18T18:37:46.255+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz<2024 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T18:37:46.255+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (2.31.0)
[2024-11-18T18:37:46.255+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (23.2)
[2024-11-18T18:37:46.256+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (6.11.0)
[2024-11-18T18:37:46.256+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (0.4.4)
[2024-11-18T18:37:46.256+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (1.13.1)
[2024-11-18T18:37:46.257+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (7.0.0)
[2024-11-18T18:37:46.257+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (2.2.5)
[2024-11-18T18:37:46.258+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (1.24.4)
[2024-11-18T18:37:46.258+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (1.10.1)
[2024-11-18T18:37:46.274+0000] {process_utils.py:190} INFO - Collecting querystring-parser<2 (from mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2))
[2024-11-18T18:37:46.275+0000] {process_utils.py:190} INFO -   Using cached querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
[2024-11-18T18:37:46.276+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (1.4.51)
[2024-11-18T18:37:46.276+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow<16,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (14.0.2)
[2024-11-18T18:37:46.276+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (3.5.2)
[2024-11-18T18:37:46.277+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (3.7.5)
[2024-11-18T18:37:46.277+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<22 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (21.2.0)
[2024-11-18T18:37:46.277+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (3.1.3)
[2024-11-18T18:37:46.305+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvytwot105/requirements.txt (line 3)) (2.8.2)
[2024-11-18T18:37:46.353+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvytwot105/requirements.txt (line 3)) (2023.4)
[2024-11-18T18:37:46.353+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvytwot105/requirements.txt (line 4)) (1.4.2)
[2024-11-18T18:37:46.354+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvytwot105/requirements.txt (line 4)) (3.5.0)
[2024-11-18T18:37:46.354+0000] {process_utils.py:190} INFO - Collecting absl-py>=1.0.0 (from tensorflow==2.13.0->-r /tmp/venvytwot105/requirements.txt (line 5))
[2024-11-18T18:37:46.355+0000] {process_utils.py:190} INFO -   Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
[2024-11-18T18:37:46.371+0000] {process_utils.py:190} INFO - Collecting astunparse>=1.6.0 (from tensorflow==2.13.0->-r /tmp/venvytwot105/requirements.txt (line 5))
[2024-11-18T18:37:46.372+0000] {process_utils.py:190} INFO -   Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
[2024-11-18T18:37:46.391+0000] {process_utils.py:190} INFO - Collecting flatbuffers>=23.1.21 (from tensorflow==2.13.0->-r /tmp/venvytwot105/requirements.txt (line 5))
[2024-11-18T18:37:46.392+0000] {process_utils.py:190} INFO -   Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
[2024-11-18T18:37:46.413+0000] {process_utils.py:190} INFO - Collecting gast<=0.4.0,>=0.2.1 (from tensorflow==2.13.0->-r /tmp/venvytwot105/requirements.txt (line 5))
[2024-11-18T18:37:46.415+0000] {process_utils.py:190} INFO -   Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
[2024-11-18T18:37:46.431+0000] {process_utils.py:190} INFO - Collecting google-pasta>=0.1.1 (from tensorflow==2.13.0->-r /tmp/venvytwot105/requirements.txt (line 5))
[2024-11-18T18:37:46.432+0000] {process_utils.py:190} INFO -   Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
[2024-11-18T18:37:46.433+0000] {process_utils.py:190} INFO - Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvytwot105/requirements.txt (line 5)) (1.60.0)
[2024-11-18T18:37:46.476+0000] {process_utils.py:190} INFO - Collecting h5py>=2.9.0 (from tensorflow==2.13.0->-r /tmp/venvytwot105/requirements.txt (line 5))
[2024-11-18T18:37:46.478+0000] {process_utils.py:190} INFO -   Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
[2024-11-18T18:37:46.504+0000] {process_utils.py:190} INFO - Collecting keras<2.14,>=2.13.1 (from tensorflow==2.13.0->-r /tmp/venvytwot105/requirements.txt (line 5))
[2024-11-18T18:37:46.506+0000] {process_utils.py:190} INFO -   Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
[2024-11-18T18:37:46.526+0000] {process_utils.py:190} INFO - Collecting libclang>=13.0.0 (from tensorflow==2.13.0->-r /tmp/venvytwot105/requirements.txt (line 5))
[2024-11-18T18:37:46.527+0000] {process_utils.py:190} INFO -   Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
[2024-11-18T18:37:46.699+0000] {process_utils.py:190} INFO - Collecting numpy<2 (from mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2))
[2024-11-18T18:37:46.701+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-11-18T18:37:46.719+0000] {process_utils.py:190} INFO - Collecting opt-einsum>=2.3.2 (from tensorflow==2.13.0->-r /tmp/venvytwot105/requirements.txt (line 5))
[2024-11-18T18:37:46.720+0000] {process_utils.py:190} INFO -   Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
[2024-11-18T18:37:46.721+0000] {process_utils.py:190} INFO - Requirement already satisfied: setuptools in /tmp/venvytwot105/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvytwot105/requirements.txt (line 5)) (75.2.0)
[2024-11-18T18:37:46.722+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.12.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvytwot105/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:37:46.747+0000] {process_utils.py:190} INFO - Collecting tensorboard<2.14,>=2.13 (from tensorflow==2.13.0->-r /tmp/venvytwot105/requirements.txt (line 5))
[2024-11-18T18:37:46.749+0000] {process_utils.py:190} INFO -   Using cached tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:37:46.769+0000] {process_utils.py:190} INFO - Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow==2.13.0->-r /tmp/venvytwot105/requirements.txt (line 5))
[2024-11-18T18:37:46.770+0000] {process_utils.py:190} INFO -   Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
[2024-11-18T18:37:46.771+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.1.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvytwot105/requirements.txt (line 5)) (2.4.0)
[2024-11-18T18:37:46.795+0000] {process_utils.py:190} INFO - Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow==2.13.0->-r /tmp/venvytwot105/requirements.txt (line 5))
[2024-11-18T18:37:46.796+0000] {process_utils.py:190} INFO -   Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
[2024-11-18T18:37:46.797+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt>=1.11.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvytwot105/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:37:46.829+0000] {process_utils.py:190} INFO - Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow==2.13.0->-r /tmp/venvytwot105/requirements.txt (line 5))
[2024-11-18T18:37:46.830+0000] {process_utils.py:190} INFO -   Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
[2024-11-18T18:37:46.834+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (1.3.0)
[2024-11-18T18:37:46.837+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (5.13.0)
[2024-11-18T18:37:46.839+0000] {process_utils.py:190} INFO - Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venvytwot105/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow==2.13.0->-r /tmp/venvytwot105/requirements.txt (line 5)) (0.44.0)
[2024-11-18T18:37:46.840+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venvytwot105/requirements.txt (line 1)) (1.26.18)
[2024-11-18T18:37:46.846+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (2.2.3)
[2024-11-18T18:37:46.847+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (2.1.2)
[2024-11-18T18:37:46.852+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (4.0.11)
[2024-11-18T18:37:46.860+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (3.17.0)
[2024-11-18T18:37:46.862+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (2.1.3)
[2024-11-18T18:37:46.869+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (1.1.1)
[2024-11-18T18:37:46.869+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (0.12.1)
[2024-11-18T18:37:46.870+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (4.54.1)
[2024-11-18T18:37:46.870+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (1.4.7)
[2024-11-18T18:37:46.879+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (10.4.0)
[2024-11-18T18:37:46.880+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (3.1.1)
[2024-11-18T18:37:46.900+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (3.3.2)
[2024-11-18T18:37:46.900+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (3.6)
[2024-11-18T18:37:46.900+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (2023.11.17)
[2024-11-18T18:37:47.116+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (3.0.3)
[2024-11-18T18:37:47.122+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth<3,>=1.6.3 in /home/***/.local/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvytwot105/requirements.txt (line 5)) (2.26.2)
[2024-11-18T18:37:47.146+0000] {process_utils.py:190} INFO - Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvytwot105/requirements.txt (line 5))
[2024-11-18T18:37:47.147+0000] {process_utils.py:190} INFO -   Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
[2024-11-18T18:37:47.179+0000] {process_utils.py:190} INFO - Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvytwot105/requirements.txt (line 5))
[2024-11-18T18:37:47.181+0000] {process_utils.py:190} INFO -   Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
[2024-11-18T18:37:47.229+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvytwot105/requirements.txt (line 2)) (5.0.1)
[2024-11-18T18:37:47.232+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvytwot105/requirements.txt (line 5)) (5.3.2)
[2024-11-18T18:37:47.232+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvytwot105/requirements.txt (line 5)) (0.3.0)
[2024-11-18T18:37:47.232+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvytwot105/requirements.txt (line 5)) (4.9)
[2024-11-18T18:37:47.234+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvytwot105/requirements.txt (line 5)) (1.3.1)
[2024-11-18T18:37:47.262+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvytwot105/requirements.txt (line 5)) (0.5.1)
[2024-11-18T18:37:47.264+0000] {process_utils.py:190} INFO - Requirement already satisfied: oauthlib>=3.0.0 in /home/***/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvytwot105/requirements.txt (line 5)) (3.2.2)
[2024-11-18T18:37:47.271+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T18:37:47.272+0000] {process_utils.py:190} INFO - Using cached mlflow-2.10.2-py3-none-any.whl (19.5 MB)
[2024-11-18T18:37:47.282+0000] {process_utils.py:190} INFO - Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
[2024-11-18T18:37:47.466+0000] {process_utils.py:190} INFO - Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
[2024-11-18T18:37:47.467+0000] {process_utils.py:190} INFO - Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
[2024-11-18T18:37:47.468+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T18:37:47.474+0000] {process_utils.py:190} INFO - Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
[2024-11-18T18:37:47.475+0000] {process_utils.py:190} INFO - Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
[2024-11-18T18:37:47.476+0000] {process_utils.py:190} INFO - Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
[2024-11-18T18:37:47.477+0000] {process_utils.py:190} INFO - Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
[2024-11-18T18:37:47.479+0000] {process_utils.py:190} INFO - Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
[2024-11-18T18:37:47.482+0000] {process_utils.py:190} INFO - Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)
[2024-11-18T18:37:47.483+0000] {process_utils.py:190} INFO - Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
[2024-11-18T18:37:47.493+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-11-18T18:37:47.501+0000] {process_utils.py:190} INFO - Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
[2024-11-18T18:37:47.502+0000] {process_utils.py:190} INFO - Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
[2024-11-18T18:37:47.503+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T18:37:47.504+0000] {process_utils.py:190} INFO - Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
[2024-11-18T18:37:47.508+0000] {process_utils.py:190} INFO - Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
[2024-11-18T18:37:47.509+0000] {process_utils.py:190} INFO - Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
[2024-11-18T18:37:47.511+0000] {process_utils.py:190} INFO - Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[2024-11-18T18:37:47.512+0000] {process_utils.py:190} INFO - Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
[2024-11-18T18:37:47.513+0000] {process_utils.py:190} INFO - Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
[2024-11-18T18:37:48.734+0000] {process_utils.py:190} INFO - Installing collected packages: libclang, flatbuffers, typing-extensions, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, querystring-parser, opt-einsum, numpy, keras, google-pasta, gast, entrypoints, astunparse, absl-py, h5py, botocore, s3transfer, google-auth-oauthlib, tensorboard, mlflow, boto3, tensorflow
[2024-11-18T18:37:48.967+0000] {process_utils.py:190} INFO -   Attempting uninstall: typing-extensions
[2024-11-18T18:37:48.969+0000] {process_utils.py:190} INFO -     Found existing installation: typing_extensions 4.9.0
[2024-11-18T18:37:48.969+0000] {process_utils.py:190} INFO -     Not uninstalling typing-extensions at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvytwot105
[2024-11-18T18:37:48.970+0000] {process_utils.py:190} INFO -     Can't uninstall 'typing_extensions'. No files were found to uninstall.
[2024-11-18T18:37:49.229+0000] {process_utils.py:190} INFO -   Attempting uninstall: numpy
[2024-11-18T18:37:49.231+0000] {process_utils.py:190} INFO -     Found existing installation: numpy 1.24.4
[2024-11-18T18:37:49.231+0000] {process_utils.py:190} INFO -     Not uninstalling numpy at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvytwot105
[2024-11-18T18:37:49.231+0000] {process_utils.py:190} INFO -     Can't uninstall 'numpy'. No files were found to uninstall.
[2024-11-18T18:37:50.827+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T18:37:50.828+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T18:37:50.828+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvytwot105
[2024-11-18T18:37:50.828+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T18:37:51.212+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T18:37:51.214+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T18:37:51.214+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvytwot105
[2024-11-18T18:37:51.215+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T18:37:51.236+0000] {process_utils.py:190} INFO -   Attempting uninstall: google-auth-oauthlib
[2024-11-18T18:37:51.237+0000] {process_utils.py:190} INFO -     Found existing installation: google-auth-oauthlib 1.2.0
[2024-11-18T18:37:51.238+0000] {process_utils.py:190} INFO -     Not uninstalling google-auth-oauthlib at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvytwot105
[2024-11-18T18:37:51.238+0000] {process_utils.py:190} INFO -     Can't uninstall 'google-auth-oauthlib'. No files were found to uninstall.
[2024-11-18T18:37:51.428+0000] {process_utils.py:190} INFO -   Attempting uninstall: mlflow
[2024-11-18T18:37:51.430+0000] {process_utils.py:190} INFO -     Found existing installation: mlflow 2.17.0
[2024-11-18T18:37:51.430+0000] {process_utils.py:190} INFO -     Not uninstalling mlflow at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvytwot105
[2024-11-18T18:37:51.430+0000] {process_utils.py:190} INFO -     Can't uninstall 'mlflow'. No files were found to uninstall.
[2024-11-18T18:37:51.951+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T18:37:51.952+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T18:37:51.952+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvytwot105
[2024-11-18T18:37:51.953+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T18:37:58.772+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T18:37:58.772+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T18:37:58.773+0000] {process_utils.py:190} INFO - azure-core 1.29.6 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:37:58.773+0000] {process_utils.py:190} INFO - azure-mgmt-keyvault 10.3.1 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:37:58.773+0000] {process_utils.py:190} INFO - azure-mgmt-network 27.0.0 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:37:58.773+0000] {process_utils.py:190} INFO - graphene 3.4 requires typing-extensions<5,>=4.7.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:37:58.773+0000] {process_utils.py:190} INFO - pydantic 2.5.3 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:37:58.774+0000] {process_utils.py:190} INFO - pydantic-core 2.14.6 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:37:58.774+0000] {process_utils.py:190} INFO - Successfully installed absl-py-2.1.0 astunparse-1.6.3 boto3-1.28.0 botocore-1.31.85 entrypoints-0.4 flatbuffers-24.3.25 gast-0.4.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 h5py-3.11.0 keras-2.13.1 libclang-18.1.1 mlflow-2.10.2 numpy-1.24.3 opt-einsum-3.4.0 querystring-parser-1.2.4 s3transfer-0.6.2 tensorboard-2.13.0 tensorboard-data-server-0.7.2 tensorflow-2.13.0 tensorflow-estimator-2.13.0 tensorflow-io-gcs-filesystem-0.34.0 typing-extensions-4.5.0
[2024-11-18T18:37:58.839+0000] {process_utils.py:190} INFO - 
[2024-11-18T18:37:58.839+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 24.2 -> 24.3.1
[2024-11-18T18:37:58.839+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T18:37:59.008+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvytwot105/bin/python /tmp/venv-call5ker9hen/script.py /tmp/venv-call5ker9hen/script.in /tmp/venv-call5ker9hen/script.out /tmp/venv-call5ker9hen/string_args.txt /tmp/venv-call5ker9hen/termination.log
[2024-11-18T18:37:59.012+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:37:59.960+0000] {process_utils.py:190} INFO - 2024-11-18 18:37:59.960610: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-11-18T18:37:59.961+0000] {process_utils.py:190} INFO - 2024-11-18 18:37:59.961651: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T18:37:59.984+0000] {process_utils.py:190} INFO - 2024-11-18 18:37:59.984210: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T18:37:59.984+0000] {process_utils.py:190} INFO - 2024-11-18 18:37:59.984486: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-11-18T18:37:59.984+0000] {process_utils.py:190} INFO - To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-11-18T18:38:00.488+0000] {process_utils.py:190} INFO - 2024-11-18 18:38:00.488343: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-11-18T18:38:01.540+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-11-18T18:38:01.540+0000] {process_utils.py:190} INFO -   File "/tmp/venv-call5ker9hen/script.py", line 95, in <module>
[2024-11-18T18:38:01.540+0000] {process_utils.py:190} INFO -     res = evaluate_champion(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-18T18:38:01.540+0000] {process_utils.py:190} INFO -   File "/tmp/venv-call5ker9hen/script.py", line 66, in evaluate_champion
[2024-11-18T18:38:01.541+0000] {process_utils.py:190} INFO -     model_data = client.get_model_version_by_alias("spotify_model_prod", "champion")
[2024-11-18T18:38:01.541+0000] {process_utils.py:190} INFO -   File "/tmp/venvytwot105/lib/python3.8/site-packages/mlflow/tracking/client.py", line 3745, in get_model_version_by_alias
[2024-11-18T18:38:01.541+0000] {process_utils.py:190} INFO -     return self._get_registry_client().get_model_version_by_alias(name, alias)
[2024-11-18T18:38:01.541+0000] {process_utils.py:190} INFO -   File "/tmp/venvytwot105/lib/python3.8/site-packages/mlflow/tracking/_model_registry/client.py", line 366, in get_model_version_by_alias
[2024-11-18T18:38:01.541+0000] {process_utils.py:190} INFO -     return self.store.get_model_version_by_alias(name, alias)
[2024-11-18T18:38:01.541+0000] {process_utils.py:190} INFO -   File "/tmp/venvytwot105/lib/python3.8/site-packages/mlflow/store/model_registry/rest_store.py", line 400, in get_model_version_by_alias
[2024-11-18T18:38:01.542+0000] {process_utils.py:190} INFO -     response_proto = self._call_endpoint(GetModelVersionByAlias, req_body)
[2024-11-18T18:38:01.542+0000] {process_utils.py:190} INFO -   File "/tmp/venvytwot105/lib/python3.8/site-packages/mlflow/store/model_registry/base_rest_store.py", line 44, in _call_endpoint
[2024-11-18T18:38:01.542+0000] {process_utils.py:190} INFO -     return call_endpoint(
[2024-11-18T18:38:01.542+0000] {process_utils.py:190} INFO -   File "/tmp/venvytwot105/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 220, in call_endpoint
[2024-11-18T18:38:01.542+0000] {process_utils.py:190} INFO -     response = verify_rest_response(response, endpoint)
[2024-11-18T18:38:01.542+0000] {process_utils.py:190} INFO -   File "/tmp/venvytwot105/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 152, in verify_rest_response
[2024-11-18T18:38:01.542+0000] {process_utils.py:190} INFO -     raise RestException(json.loads(response.text))
[2024-11-18T18:38:01.543+0000] {process_utils.py:190} INFO - mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Registered model alias champion not found.
[2024-11-18T18:38:02.327+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
INVALID_PARAMETER_VALUE: Registered model alias champion not found.
[2024-11-18T18:38:02.329+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_retrain_challenge_model_v3, task_id=evaluate_champion, execution_date=20241118T183715, start_date=20241118T183744, end_date=20241118T183802
[2024-11-18T18:38:02.348+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 100 for task evaluate_champion (Process returned non-zero exit status 1.
INVALID_PARAMETER_VALUE: Registered model alias champion not found.; 20262)
[2024-11-18T18:38:02.352+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-18T18:38:02.360+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
