[2024-11-18T18:25:18.159+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:25:17.182075+00:00 [queued]>
[2024-11-18T18:25:18.164+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:25:17.182075+00:00 [queued]>
[2024-11-18T18:25:18.164+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-11-18T18:25:18.171+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_challenger_model> on 2024-11-18 18:25:17.182075+00:00
[2024-11-18T18:25:18.174+0000] {standard_task_runner.py:60} INFO - Started process 12379 to run task
[2024-11-18T18:25:18.175+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_retrain_challenge_model_v3', 'train_challenger_model', 'manual__2024-11-18T18:25:17.182075+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/retrain_music_model.py', '--cfg-path', '/tmp/tmpx02z8ur2']
[2024-11-18T18:25:18.176+0000] {standard_task_runner.py:88} INFO - Job 84: Subtask train_challenger_model
[2024-11-18T18:25:18.201+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:25:17.182075+00:00 [running]> on host 98017b53a184
[2024-11-18T18:25:18.238+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_retrain_challenge_model_v3' AIRFLOW_CTX_TASK_ID='train_challenger_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T18:25:17.182075+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T18:25:17.182075+00:00'
[2024-11-18T18:25:18.239+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvsfc63u3x --system-site-packages --python=python
[2024-11-18T18:25:18.243+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:25:18.565+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 114ms
[2024-11-18T18:25:18.566+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvsfc63u3x, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T18:25:18.566+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T18:25:18.566+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-11-18T18:25:18.567+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T18:25:18.584+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvsfc63u3x/bin/pip install -r /tmp/venvsfc63u3x/requirements.txt
[2024-11-18T18:25:18.587+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:25:19.526+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venvsfc63u3x/requirements.txt (line 1))
[2024-11-18T18:25:19.528+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T18:25:19.592+0000] {process_utils.py:190} INFO - Collecting mlflow==2.10.2 (from -r /tmp/venvsfc63u3x/requirements.txt (line 2))
[2024-11-18T18:25:19.593+0000] {process_utils.py:190} INFO -   Using cached mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
[2024-11-18T18:25:19.594+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvsfc63u3x/requirements.txt (line 3)) (2.0.3)
[2024-11-18T18:25:19.595+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn==1.3.2 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvsfc63u3x/requirements.txt (line 4)) (1.3.2)
[2024-11-18T18:25:19.698+0000] {process_utils.py:190} INFO - Collecting tensorflow==2.13.0 (from -r /tmp/venvsfc63u3x/requirements.txt (line 5))
[2024-11-18T18:25:19.700+0000] {process_utils.py:190} INFO -   Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
[2024-11-18T18:25:20.130+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venvsfc63u3x/requirements.txt (line 1))
[2024-11-18T18:25:20.131+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T18:25:20.132+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venvsfc63u3x/requirements.txt (line 1)) (0.10.0)
[2024-11-18T18:25:20.159+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venvsfc63u3x/requirements.txt (line 1))
[2024-11-18T18:25:20.160+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:25:20.211+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (8.1.7)
[2024-11-18T18:25:20.212+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (3.1.0)
[2024-11-18T18:25:20.228+0000] {process_utils.py:190} INFO - Collecting entrypoints<1 (from mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2))
[2024-11-18T18:25:20.229+0000] {process_utils.py:190} INFO -   Using cached entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
[2024-11-18T18:25:20.230+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=2.1.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (3.1.43)
[2024-11-18T18:25:20.231+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (6.0.1)
[2024-11-18T18:25:20.231+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<5,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (4.25.2)
[2024-11-18T18:25:20.231+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz<2024 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T18:25:20.232+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (2.31.0)
[2024-11-18T18:25:20.232+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (23.2)
[2024-11-18T18:25:20.233+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (6.11.0)
[2024-11-18T18:25:20.233+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (0.4.4)
[2024-11-18T18:25:20.234+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (1.13.1)
[2024-11-18T18:25:20.235+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (7.0.0)
[2024-11-18T18:25:20.235+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (2.2.5)
[2024-11-18T18:25:20.236+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (1.24.4)
[2024-11-18T18:25:20.236+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (1.10.1)
[2024-11-18T18:25:20.252+0000] {process_utils.py:190} INFO - Collecting querystring-parser<2 (from mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2))
[2024-11-18T18:25:20.253+0000] {process_utils.py:190} INFO -   Using cached querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
[2024-11-18T18:25:20.254+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (1.4.51)
[2024-11-18T18:25:20.255+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow<16,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (14.0.2)
[2024-11-18T18:25:20.255+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (3.5.2)
[2024-11-18T18:25:20.255+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (3.7.5)
[2024-11-18T18:25:20.256+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<22 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (21.2.0)
[2024-11-18T18:25:20.257+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (3.1.3)
[2024-11-18T18:25:20.311+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvsfc63u3x/requirements.txt (line 3)) (2.8.2)
[2024-11-18T18:25:20.311+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvsfc63u3x/requirements.txt (line 3)) (2023.4)
[2024-11-18T18:25:20.332+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvsfc63u3x/requirements.txt (line 4)) (1.4.2)
[2024-11-18T18:25:20.332+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvsfc63u3x/requirements.txt (line 4)) (3.5.0)
[2024-11-18T18:25:20.364+0000] {process_utils.py:190} INFO - Collecting absl-py>=1.0.0 (from tensorflow==2.13.0->-r /tmp/venvsfc63u3x/requirements.txt (line 5))
[2024-11-18T18:25:20.365+0000] {process_utils.py:190} INFO -   Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
[2024-11-18T18:25:20.381+0000] {process_utils.py:190} INFO - Collecting astunparse>=1.6.0 (from tensorflow==2.13.0->-r /tmp/venvsfc63u3x/requirements.txt (line 5))
[2024-11-18T18:25:20.383+0000] {process_utils.py:190} INFO -   Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
[2024-11-18T18:25:20.401+0000] {process_utils.py:190} INFO - Collecting flatbuffers>=23.1.21 (from tensorflow==2.13.0->-r /tmp/venvsfc63u3x/requirements.txt (line 5))
[2024-11-18T18:25:20.403+0000] {process_utils.py:190} INFO -   Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
[2024-11-18T18:25:20.425+0000] {process_utils.py:190} INFO - Collecting gast<=0.4.0,>=0.2.1 (from tensorflow==2.13.0->-r /tmp/venvsfc63u3x/requirements.txt (line 5))
[2024-11-18T18:25:20.426+0000] {process_utils.py:190} INFO -   Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
[2024-11-18T18:25:20.443+0000] {process_utils.py:190} INFO - Collecting google-pasta>=0.1.1 (from tensorflow==2.13.0->-r /tmp/venvsfc63u3x/requirements.txt (line 5))
[2024-11-18T18:25:20.445+0000] {process_utils.py:190} INFO -   Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
[2024-11-18T18:25:20.445+0000] {process_utils.py:190} INFO - Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvsfc63u3x/requirements.txt (line 5)) (1.60.0)
[2024-11-18T18:25:20.487+0000] {process_utils.py:190} INFO - Collecting h5py>=2.9.0 (from tensorflow==2.13.0->-r /tmp/venvsfc63u3x/requirements.txt (line 5))
[2024-11-18T18:25:20.489+0000] {process_utils.py:190} INFO -   Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
[2024-11-18T18:25:20.516+0000] {process_utils.py:190} INFO - Collecting keras<2.14,>=2.13.1 (from tensorflow==2.13.0->-r /tmp/venvsfc63u3x/requirements.txt (line 5))
[2024-11-18T18:25:20.517+0000] {process_utils.py:190} INFO -   Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
[2024-11-18T18:25:20.537+0000] {process_utils.py:190} INFO - Collecting libclang>=13.0.0 (from tensorflow==2.13.0->-r /tmp/venvsfc63u3x/requirements.txt (line 5))
[2024-11-18T18:25:20.538+0000] {process_utils.py:190} INFO -   Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
[2024-11-18T18:25:20.692+0000] {process_utils.py:190} INFO - Collecting numpy<2 (from mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2))
[2024-11-18T18:25:20.693+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-11-18T18:25:20.710+0000] {process_utils.py:190} INFO - Collecting opt-einsum>=2.3.2 (from tensorflow==2.13.0->-r /tmp/venvsfc63u3x/requirements.txt (line 5))
[2024-11-18T18:25:20.711+0000] {process_utils.py:190} INFO -   Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
[2024-11-18T18:25:20.712+0000] {process_utils.py:190} INFO - Requirement already satisfied: setuptools in /tmp/venvsfc63u3x/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvsfc63u3x/requirements.txt (line 5)) (69.0.2)
[2024-11-18T18:25:20.713+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.12.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvsfc63u3x/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:25:20.738+0000] {process_utils.py:190} INFO - Collecting tensorboard<2.14,>=2.13 (from tensorflow==2.13.0->-r /tmp/venvsfc63u3x/requirements.txt (line 5))
[2024-11-18T18:25:20.739+0000] {process_utils.py:190} INFO -   Using cached tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:25:20.760+0000] {process_utils.py:190} INFO - Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow==2.13.0->-r /tmp/venvsfc63u3x/requirements.txt (line 5))
[2024-11-18T18:25:20.762+0000] {process_utils.py:190} INFO -   Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
[2024-11-18T18:25:20.762+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.1.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvsfc63u3x/requirements.txt (line 5)) (2.4.0)
[2024-11-18T18:25:20.807+0000] {process_utils.py:190} INFO - Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow==2.13.0->-r /tmp/venvsfc63u3x/requirements.txt (line 5))
[2024-11-18T18:25:20.809+0000] {process_utils.py:190} INFO -   Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
[2024-11-18T18:25:20.810+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt>=1.11.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvsfc63u3x/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:25:20.846+0000] {process_utils.py:190} INFO - Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow==2.13.0->-r /tmp/venvsfc63u3x/requirements.txt (line 5))
[2024-11-18T18:25:20.847+0000] {process_utils.py:190} INFO -   Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
[2024-11-18T18:25:20.857+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (1.3.0)
[2024-11-18T18:25:20.861+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (5.13.0)
[2024-11-18T18:25:20.864+0000] {process_utils.py:190} INFO - Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venvsfc63u3x/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow==2.13.0->-r /tmp/venvsfc63u3x/requirements.txt (line 5)) (0.42.0)
[2024-11-18T18:25:20.870+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venvsfc63u3x/requirements.txt (line 1)) (1.26.18)
[2024-11-18T18:25:20.885+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (2.2.3)
[2024-11-18T18:25:20.885+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (2.1.2)
[2024-11-18T18:25:20.901+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (4.0.11)
[2024-11-18T18:25:20.927+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (3.17.0)
[2024-11-18T18:25:20.931+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (2.1.3)
[2024-11-18T18:25:20.955+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (1.1.1)
[2024-11-18T18:25:20.956+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (0.12.1)
[2024-11-18T18:25:20.956+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (4.54.1)
[2024-11-18T18:25:20.956+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (1.4.7)
[2024-11-18T18:25:20.968+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (10.4.0)
[2024-11-18T18:25:20.968+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (3.1.1)
[2024-11-18T18:25:21.017+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (3.3.2)
[2024-11-18T18:25:21.017+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (3.6)
[2024-11-18T18:25:21.018+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (2023.11.17)
[2024-11-18T18:25:21.290+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (3.0.3)
[2024-11-18T18:25:21.309+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth<3,>=1.6.3 in /home/***/.local/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvsfc63u3x/requirements.txt (line 5)) (2.26.2)
[2024-11-18T18:25:21.330+0000] {process_utils.py:190} INFO - Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvsfc63u3x/requirements.txt (line 5))
[2024-11-18T18:25:21.331+0000] {process_utils.py:190} INFO -   Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
[2024-11-18T18:25:21.363+0000] {process_utils.py:190} INFO - Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvsfc63u3x/requirements.txt (line 5))
[2024-11-18T18:25:21.364+0000] {process_utils.py:190} INFO -   Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
[2024-11-18T18:25:21.512+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvsfc63u3x/requirements.txt (line 2)) (5.0.1)
[2024-11-18T18:25:21.524+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvsfc63u3x/requirements.txt (line 5)) (5.3.2)
[2024-11-18T18:25:21.524+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvsfc63u3x/requirements.txt (line 5)) (0.3.0)
[2024-11-18T18:25:21.525+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvsfc63u3x/requirements.txt (line 5)) (4.9)
[2024-11-18T18:25:21.532+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvsfc63u3x/requirements.txt (line 5)) (1.3.1)
[2024-11-18T18:25:21.658+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvsfc63u3x/requirements.txt (line 5)) (0.5.1)
[2024-11-18T18:25:21.666+0000] {process_utils.py:190} INFO - Requirement already satisfied: oauthlib>=3.0.0 in /home/***/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvsfc63u3x/requirements.txt (line 5)) (3.2.2)
[2024-11-18T18:25:21.700+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T18:25:21.702+0000] {process_utils.py:190} INFO - Using cached mlflow-2.10.2-py3-none-any.whl (19.5 MB)
[2024-11-18T18:25:21.720+0000] {process_utils.py:190} INFO - Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
[2024-11-18T18:25:22.198+0000] {process_utils.py:190} INFO - Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
[2024-11-18T18:25:22.200+0000] {process_utils.py:190} INFO - Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
[2024-11-18T18:25:22.201+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T18:25:22.213+0000] {process_utils.py:190} INFO - Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
[2024-11-18T18:25:22.214+0000] {process_utils.py:190} INFO - Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
[2024-11-18T18:25:22.215+0000] {process_utils.py:190} INFO - Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
[2024-11-18T18:25:22.216+0000] {process_utils.py:190} INFO - Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
[2024-11-18T18:25:22.217+0000] {process_utils.py:190} INFO - Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
[2024-11-18T18:25:22.223+0000] {process_utils.py:190} INFO - Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)
[2024-11-18T18:25:22.226+0000] {process_utils.py:190} INFO - Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
[2024-11-18T18:25:22.252+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-11-18T18:25:22.271+0000] {process_utils.py:190} INFO - Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
[2024-11-18T18:25:22.272+0000] {process_utils.py:190} INFO - Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
[2024-11-18T18:25:22.273+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T18:25:22.274+0000] {process_utils.py:190} INFO - Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
[2024-11-18T18:25:22.281+0000] {process_utils.py:190} INFO - Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
[2024-11-18T18:25:22.283+0000] {process_utils.py:190} INFO - Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
[2024-11-18T18:25:22.286+0000] {process_utils.py:190} INFO - Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[2024-11-18T18:25:22.287+0000] {process_utils.py:190} INFO - Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
[2024-11-18T18:25:22.288+0000] {process_utils.py:190} INFO - Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
[2024-11-18T18:25:24.447+0000] {process_utils.py:190} INFO - Installing collected packages: libclang, flatbuffers, typing-extensions, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, querystring-parser, opt-einsum, numpy, keras, google-pasta, gast, entrypoints, astunparse, absl-py, h5py, botocore, s3transfer, google-auth-oauthlib, tensorboard, mlflow, boto3, tensorflow
[2024-11-18T18:25:24.702+0000] {process_utils.py:190} INFO -   Attempting uninstall: typing-extensions
[2024-11-18T18:25:24.703+0000] {process_utils.py:190} INFO -     Found existing installation: typing_extensions 4.9.0
[2024-11-18T18:25:24.704+0000] {process_utils.py:190} INFO -     Not uninstalling typing-extensions at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvsfc63u3x
[2024-11-18T18:25:24.704+0000] {process_utils.py:190} INFO -     Can't uninstall 'typing_extensions'. No files were found to uninstall.
[2024-11-18T18:25:24.974+0000] {process_utils.py:190} INFO -   Attempting uninstall: numpy
[2024-11-18T18:25:24.975+0000] {process_utils.py:190} INFO -     Found existing installation: numpy 1.24.4
[2024-11-18T18:25:24.975+0000] {process_utils.py:190} INFO -     Not uninstalling numpy at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvsfc63u3x
[2024-11-18T18:25:24.976+0000] {process_utils.py:190} INFO -     Can't uninstall 'numpy'. No files were found to uninstall.
[2024-11-18T18:25:26.668+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T18:25:26.668+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T18:25:26.669+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvsfc63u3x
[2024-11-18T18:25:26.669+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T18:25:27.068+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T18:25:27.069+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T18:25:27.070+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvsfc63u3x
[2024-11-18T18:25:27.070+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T18:25:27.091+0000] {process_utils.py:190} INFO -   Attempting uninstall: google-auth-oauthlib
[2024-11-18T18:25:27.092+0000] {process_utils.py:190} INFO -     Found existing installation: google-auth-oauthlib 1.2.0
[2024-11-18T18:25:27.092+0000] {process_utils.py:190} INFO -     Not uninstalling google-auth-oauthlib at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvsfc63u3x
[2024-11-18T18:25:27.093+0000] {process_utils.py:190} INFO -     Can't uninstall 'google-auth-oauthlib'. No files were found to uninstall.
[2024-11-18T18:25:27.288+0000] {process_utils.py:190} INFO -   Attempting uninstall: mlflow
[2024-11-18T18:25:27.290+0000] {process_utils.py:190} INFO -     Found existing installation: mlflow 2.17.0
[2024-11-18T18:25:27.290+0000] {process_utils.py:190} INFO -     Not uninstalling mlflow at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvsfc63u3x
[2024-11-18T18:25:27.291+0000] {process_utils.py:190} INFO -     Can't uninstall 'mlflow'. No files were found to uninstall.
[2024-11-18T18:25:27.850+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T18:25:27.850+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T18:25:27.851+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvsfc63u3x
[2024-11-18T18:25:27.851+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T18:25:35.079+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T18:25:35.079+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T18:25:35.080+0000] {process_utils.py:190} INFO - azure-core 1.29.6 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:25:35.080+0000] {process_utils.py:190} INFO - azure-mgmt-keyvault 10.3.1 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:25:35.080+0000] {process_utils.py:190} INFO - azure-mgmt-network 27.0.0 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:25:35.080+0000] {process_utils.py:190} INFO - graphene 3.4 requires typing-extensions<5,>=4.7.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:25:35.080+0000] {process_utils.py:190} INFO - pydantic 2.5.3 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:25:35.081+0000] {process_utils.py:190} INFO - pydantic-core 2.14.6 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:25:35.081+0000] {process_utils.py:190} INFO - Successfully installed absl-py-2.1.0 astunparse-1.6.3 boto3-1.28.0 botocore-1.31.85 entrypoints-0.4 flatbuffers-24.3.25 gast-0.4.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 h5py-3.11.0 keras-2.13.1 libclang-18.1.1 mlflow-2.10.2 numpy-1.24.3 opt-einsum-3.4.0 querystring-parser-1.2.4 s3transfer-0.6.2 tensorboard-2.13.0 tensorboard-data-server-0.7.2 tensorflow-2.13.0 tensorflow-estimator-2.13.0 tensorflow-io-gcs-filesystem-0.34.0 typing-extensions-4.5.0
[2024-11-18T18:25:35.185+0000] {process_utils.py:190} INFO - 
[2024-11-18T18:25:35.186+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.3.1
[2024-11-18T18:25:35.186+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T18:25:35.376+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvsfc63u3x/bin/python /tmp/venv-callf5gn7ffs/script.py /tmp/venv-callf5gn7ffs/script.in /tmp/venv-callf5gn7ffs/script.out /tmp/venv-callf5gn7ffs/string_args.txt /tmp/venv-callf5gn7ffs/termination.log
[2024-11-18T18:25:35.379+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:25:36.318+0000] {process_utils.py:190} INFO - 2024-11-18 18:25:36.318703: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-11-18T18:25:36.319+0000] {process_utils.py:190} INFO - 2024-11-18 18:25:36.319761: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T18:25:36.340+0000] {process_utils.py:190} INFO - 2024-11-18 18:25:36.339998: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T18:25:36.340+0000] {process_utils.py:190} INFO - 2024-11-18 18:25:36.340258: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-11-18T18:25:36.340+0000] {process_utils.py:190} INFO - To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-11-18T18:25:36.834+0000] {process_utils.py:190} INFO - 2024-11-18 18:25:36.834225: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-11-18T18:25:37.850+0000] {process_utils.py:190} INFO - Epoch 1/10
[2024-11-18T18:25:38.760+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 3:30 - loss: 0.3783 55/575 [=>............................] - ETA: 0s - loss: 0.1663  118/575 [=====>........................] - ETA: 0s - loss: 0.1133200/575 [=========>....................] - ETA: 0s - loss: 0.0856276/575 [=============>................] - ETA: 0s - loss: 0.0713354/575 [=================>............] - ETA: 0s - loss: 0.0618430/575 [=====================>........] - ETA: 0s - loss: 0.0552507/575 [=========================>....] - ETA: 0s - loss: 0.0503575/575 [==============================] - 1s 948us/step - loss: 0.0469 - val_loss: 0.0076
[2024-11-18T18:25:38.761+0000] {process_utils.py:190} INFO - Epoch 2/10
[2024-11-18T18:25:39.205+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0203 82/575 [===>..........................] - ETA: 0s - loss: 0.0194159/575 [=======>......................] - ETA: 0s - loss: 0.0189236/575 [===========>..................] - ETA: 0s - loss: 0.0184314/575 [===============>..............] - ETA: 0s - loss: 0.0179392/575 [===================>..........] - ETA: 0s - loss: 0.0175474/575 [=======================>......] - ETA: 0s - loss: 0.0171553/575 [===========================>..] - ETA: 0s - loss: 0.0167575/575 [==============================] - 0s 773us/step - loss: 0.0166 - val_loss: 0.0050
[2024-11-18T18:25:39.206+0000] {process_utils.py:190} INFO - Epoch 3/10
[2024-11-18T18:25:39.653+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0153 89/575 [===>..........................] - ETA: 0s - loss: 0.0134172/575 [=======>......................] - ETA: 0s - loss: 0.0132251/575 [============>.................] - ETA: 0s - loss: 0.0131333/575 [================>.............] - ETA: 0s - loss: 0.0129418/575 [====================>.........] - ETA: 0s - loss: 0.0127494/575 [========================>.....] - ETA: 0s - loss: 0.0126568/575 [============================>.] - ETA: 0s - loss: 0.0125575/575 [==============================] - 0s 777us/step - loss: 0.0125 - val_loss: 0.0047
[2024-11-18T18:25:39.653+0000] {process_utils.py:190} INFO - Epoch 4/10
[2024-11-18T18:25:40.098+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0125 74/575 [==>...........................] - ETA: 0s - loss: 0.0115148/575 [======>.......................] - ETA: 0s - loss: 0.0111230/575 [===========>..................] - ETA: 0s - loss: 0.0110312/575 [===============>..............] - ETA: 0s - loss: 0.0108393/575 [===================>..........] - ETA: 0s - loss: 0.0107474/575 [=======================>......] - ETA: 0s - loss: 0.0106554/575 [===========================>..] - ETA: 0s - loss: 0.0105575/575 [==============================] - 0s 773us/step - loss: 0.0105 - val_loss: 0.0041
[2024-11-18T18:25:40.098+0000] {process_utils.py:190} INFO - Epoch 5/10
[2024-11-18T18:25:40.538+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0095 80/575 [===>..........................] - ETA: 0s - loss: 0.0100156/575 [=======>......................] - ETA: 0s - loss: 0.0097238/575 [===========>..................] - ETA: 0s - loss: 0.0096317/575 [===============>..............] - ETA: 0s - loss: 0.0095399/575 [===================>..........] - ETA: 0s - loss: 0.0094476/575 [=======================>......] - ETA: 0s - loss: 0.0093556/575 [============================>.] - ETA: 0s - loss: 0.0093575/575 [==============================] - 0s 765us/step - loss: 0.0093 - val_loss: 0.0035
[2024-11-18T18:25:40.538+0000] {process_utils.py:190} INFO - Epoch 6/10
[2024-11-18T18:25:40.974+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0068 82/575 [===>..........................] - ETA: 0s - loss: 0.0086162/575 [=======>......................] - ETA: 0s - loss: 0.0086244/575 [===========>..................] - ETA: 0s - loss: 0.0086326/575 [================>.............] - ETA: 0s - loss: 0.0085406/575 [====================>.........] - ETA: 0s - loss: 0.0085483/575 [========================>.....] - ETA: 0s - loss: 0.0084564/575 [============================>.] - ETA: 0s - loss: 0.0084575/575 [==============================] - 0s 758us/step - loss: 0.0084 - val_loss: 0.0031
[2024-11-18T18:25:40.975+0000] {process_utils.py:190} INFO - Epoch 7/10
[2024-11-18T18:25:41.417+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0072 80/575 [===>..........................] - ETA: 0s - loss: 0.0082164/575 [=======>......................] - ETA: 0s - loss: 0.0081243/575 [===========>..................] - ETA: 0s - loss: 0.0080320/575 [===============>..............] - ETA: 0s - loss: 0.0079398/575 [===================>..........] - ETA: 0s - loss: 0.0079479/575 [=======================>......] - ETA: 0s - loss: 0.0078558/575 [============================>.] - ETA: 0s - loss: 0.0078575/575 [==============================] - 0s 769us/step - loss: 0.0078 - val_loss: 0.0029
[2024-11-18T18:25:41.417+0000] {process_utils.py:190} INFO - Epoch 8/10
[2024-11-18T18:25:41.853+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0085 84/575 [===>..........................] - ETA: 0s - loss: 0.0077163/575 [=======>......................] - ETA: 0s - loss: 0.0077243/575 [===========>..................] - ETA: 0s - loss: 0.0077322/575 [===============>..............] - ETA: 0s - loss: 0.0076400/575 [===================>..........] - ETA: 0s - loss: 0.0076478/575 [=======================>......] - ETA: 0s - loss: 0.0075568/575 [============================>.] - ETA: 0s - loss: 0.0075575/575 [==============================] - 0s 757us/step - loss: 0.0075 - val_loss: 0.0029
[2024-11-18T18:25:41.853+0000] {process_utils.py:190} INFO - Epoch 9/10
[2024-11-18T18:25:42.301+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0066 83/575 [===>..........................] - ETA: 0s - loss: 0.0074167/575 [=======>......................] - ETA: 0s - loss: 0.0075244/575 [===========>..................] - ETA: 0s - loss: 0.0075324/575 [===============>..............] - ETA: 0s - loss: 0.0074403/575 [====================>.........] - ETA: 0s - loss: 0.0074488/575 [========================>.....] - ETA: 0s - loss: 0.0074559/575 [============================>.] - ETA: 0s - loss: 0.0073575/575 [==============================] - 0s 778us/step - loss: 0.0073 - val_loss: 0.0030
[2024-11-18T18:25:42.301+0000] {process_utils.py:190} INFO - Epoch 10/10
[2024-11-18T18:25:42.731+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0077 83/575 [===>..........................] - ETA: 0s - loss: 0.0072164/575 [=======>......................] - ETA: 0s - loss: 0.0071244/575 [===========>..................] - ETA: 0s - loss: 0.0070317/575 [===============>..............] - ETA: 0s - loss: 0.0070401/575 [===================>..........] - ETA: 0s - loss: 0.0070484/575 [========================>.....] - ETA: 0s - loss: 0.0069565/575 [============================>.] - ETA: 0s - loss: 0.0069575/575 [==============================] - 0s 747us/step - loss: 0.0069 - val_loss: 0.0026
[2024-11-18T18:25:43.120+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 28s103/719 [===>..........................] - ETA: 0s 210/719 [=======>......................] - ETA: 0s326/719 [============>.................] - ETA: 0s439/719 [=================>............] - ETA: 0s531/719 [=====================>........] - ETA: 0s649/719 [==========================>...] - ETA: 0s719/719 [==============================] - 0s 462us/step
[2024-11-18T18:25:43.859+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 7s103/719 [===>..........................] - ETA: 0s208/719 [=======>......................] - ETA: 0s318/719 [============>.................] - ETA: 0s426/719 [================>.............] - ETA: 0s535/719 [=====================>........] - ETA: 0s644/719 [=========================>....] - ETA: 0s719/719 [==============================] - 0s 469us/step
[2024-11-18T18:25:44.158+0000] {process_utils.py:190} INFO - 2024/11/18 18:25:44 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.
[2024-11-18T18:25:44.545+0000] {process_utils.py:190} INFO - [[34m2024-11-18T18:25:44.544+0000[0m] {[34mbuilder_impl.py:[0m804} INFO[0m - Assets written to: /tmp/tmp086s30xy/model/data/model/assets[0m
[2024-11-18T18:25:47.302+0000] {process_utils.py:190} INFO - /tmp/venvsfc63u3x/lib/python3.8/site-packages/_distutils_hack/__init__.py:33 UserWarning: Setuptools is replacing distutils.
[2024-11-18T18:25:47.325+0000] {process_utils.py:190} INFO - [[34m2024-11-18T18:25:47.325+0000[0m] {[34mcredentials.py:[0m1124} INFO[0m - Found credentials in environment variables.[0m
[2024-11-18T18:25:47.532+0000] {process_utils.py:190} INFO - Successfully registered model 'spotify_model_prod'.
[2024-11-18T18:25:47.532+0000] {process_utils.py:190} INFO - 2024/11/18 18:25:47 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: spotify_model_prod, version 1
[2024-11-18T18:25:47.541+0000] {process_utils.py:190} INFO - Created version '1' of model 'spotify_model_prod'.
[2024-11-18T18:25:47.541+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-11-18T18:25:47.542+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callf5gn7ffs/script.py", line 99, in <module>
[2024-11-18T18:25:47.542+0000] {process_utils.py:190} INFO -     res = train_challenger_model(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-18T18:25:47.542+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callf5gn7ffs/script.py", line 89, in train_challenger_model
[2024-11-18T18:25:47.542+0000] {process_utils.py:190} INFO -     s3_client.upload_file(model_path, MINIO_BUCKET, 'models/challenger_spotify_model.h5')
[2024-11-18T18:25:47.542+0000] {process_utils.py:190} INFO -   File "/tmp/venvsfc63u3x/lib/python3.8/site-packages/boto3/s3/inject.py", line 143, in upload_file
[2024-11-18T18:25:47.543+0000] {process_utils.py:190} INFO -     return transfer.upload_file(
[2024-11-18T18:25:47.543+0000] {process_utils.py:190} INFO -   File "/tmp/venvsfc63u3x/lib/python3.8/site-packages/boto3/s3/transfer.py", line 292, in upload_file
[2024-11-18T18:25:47.543+0000] {process_utils.py:190} INFO -     future.result()
[2024-11-18T18:25:47.543+0000] {process_utils.py:190} INFO -   File "/tmp/venvsfc63u3x/lib/python3.8/site-packages/s3transfer/futures.py", line 103, in result
[2024-11-18T18:25:47.543+0000] {process_utils.py:190} INFO -     return self._coordinator.result()
[2024-11-18T18:25:47.543+0000] {process_utils.py:190} INFO -   File "/tmp/venvsfc63u3x/lib/python3.8/site-packages/s3transfer/futures.py", line 266, in result
[2024-11-18T18:25:47.543+0000] {process_utils.py:190} INFO -     raise self._exception
[2024-11-18T18:25:47.544+0000] {process_utils.py:190} INFO -   File "/tmp/venvsfc63u3x/lib/python3.8/site-packages/s3transfer/tasks.py", line 269, in _main
[2024-11-18T18:25:47.544+0000] {process_utils.py:190} INFO -     self._submit(transfer_future=transfer_future, **kwargs)
[2024-11-18T18:25:47.544+0000] {process_utils.py:190} INFO -   File "/tmp/venvsfc63u3x/lib/python3.8/site-packages/s3transfer/upload.py", line 585, in _submit
[2024-11-18T18:25:47.544+0000] {process_utils.py:190} INFO -     upload_input_manager.provide_transfer_size(transfer_future)
[2024-11-18T18:25:47.544+0000] {process_utils.py:190} INFO -   File "/tmp/venvsfc63u3x/lib/python3.8/site-packages/s3transfer/upload.py", line 244, in provide_transfer_size
[2024-11-18T18:25:47.544+0000] {process_utils.py:190} INFO -     self._osutil.get_file_size(transfer_future.meta.call_args.fileobj)
[2024-11-18T18:25:47.544+0000] {process_utils.py:190} INFO -   File "/tmp/venvsfc63u3x/lib/python3.8/site-packages/s3transfer/utils.py", line 247, in get_file_size
[2024-11-18T18:25:47.545+0000] {process_utils.py:190} INFO -     return os.path.getsize(filename)
[2024-11-18T18:25:47.545+0000] {process_utils.py:190} INFO -   File "/usr/local/lib/python3.8/genericpath.py", line 50, in getsize
[2024-11-18T18:25:47.545+0000] {process_utils.py:190} INFO -     return os.stat(filename).st_size
[2024-11-18T18:25:47.545+0000] {process_utils.py:190} INFO - FileNotFoundError: [Errno 2] No such file or directory: 'models/challenger_spotify_model'
[2024-11-18T18:25:48.487+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
[Errno 2] No such file or directory: 'models/challenger_spotify_model'
[2024-11-18T18:25:48.490+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_retrain_challenge_model_v3, task_id=train_challenger_model, execution_date=20241118T182517, start_date=20241118T182518, end_date=20241118T182548
[2024-11-18T18:25:48.521+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 84 for task train_challenger_model (Process returned non-zero exit status 1.
[Errno 2] No such file or directory: 'models/challenger_spotify_model'; 12379)
[2024-11-18T18:25:48.557+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-18T18:25:48.568+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
