[2024-11-18T18:27:13.388+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:27:12.351051+00:00 [queued]>
[2024-11-18T18:27:13.392+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:27:12.351051+00:00 [queued]>
[2024-11-18T18:27:13.393+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-11-18T18:27:13.400+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_challenger_model> on 2024-11-18 18:27:12.351051+00:00
[2024-11-18T18:27:13.402+0000] {standard_task_runner.py:60} INFO - Started process 13912 to run task
[2024-11-18T18:27:13.404+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_retrain_challenge_model_v3', 'train_challenger_model', 'manual__2024-11-18T18:27:12.351051+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/retrain_music_model.py', '--cfg-path', '/tmp/tmp2_tgh38o']
[2024-11-18T18:27:13.406+0000] {standard_task_runner.py:88} INFO - Job 86: Subtask train_challenger_model
[2024-11-18T18:27:13.430+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:27:12.351051+00:00 [running]> on host 98017b53a184
[2024-11-18T18:27:13.469+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_retrain_challenge_model_v3' AIRFLOW_CTX_TASK_ID='train_challenger_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T18:27:12.351051+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T18:27:12.351051+00:00'
[2024-11-18T18:27:13.471+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv9s3rmzoi --system-site-packages --python=python
[2024-11-18T18:27:13.474+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:27:13.902+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 219ms
[2024-11-18T18:27:13.903+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venv9s3rmzoi, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T18:27:13.903+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T18:27:13.903+0000] {process_utils.py:190} INFO -     added seed packages: pip==24.2, setuptools==75.2.0, wheel==0.44.0
[2024-11-18T18:27:13.903+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T18:27:13.921+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv9s3rmzoi/bin/pip install -r /tmp/venv9s3rmzoi/requirements.txt
[2024-11-18T18:27:13.925+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:27:14.756+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venv9s3rmzoi/requirements.txt (line 1))
[2024-11-18T18:27:14.758+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T18:27:14.791+0000] {process_utils.py:190} INFO - Collecting mlflow==2.10.2 (from -r /tmp/venv9s3rmzoi/requirements.txt (line 2))
[2024-11-18T18:27:14.792+0000] {process_utils.py:190} INFO -   Using cached mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
[2024-11-18T18:27:14.800+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv9s3rmzoi/requirements.txt (line 3)) (2.0.3)
[2024-11-18T18:27:14.800+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn==1.3.2 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv9s3rmzoi/requirements.txt (line 4)) (1.3.2)
[2024-11-18T18:27:14.886+0000] {process_utils.py:190} INFO - Collecting tensorflow==2.13.0 (from -r /tmp/venv9s3rmzoi/requirements.txt (line 5))
[2024-11-18T18:27:14.887+0000] {process_utils.py:190} INFO -   Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
[2024-11-18T18:27:15.289+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 1))
[2024-11-18T18:27:15.291+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T18:27:15.293+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 1)) (0.10.0)
[2024-11-18T18:27:15.383+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 1))
[2024-11-18T18:27:15.385+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:27:15.387+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (8.1.7)
[2024-11-18T18:27:15.388+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (3.1.0)
[2024-11-18T18:27:15.399+0000] {process_utils.py:190} INFO - Collecting entrypoints<1 (from mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2))
[2024-11-18T18:27:15.400+0000] {process_utils.py:190} INFO -   Using cached entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
[2024-11-18T18:27:15.401+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=2.1.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (3.1.43)
[2024-11-18T18:27:15.401+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (6.0.1)
[2024-11-18T18:27:15.402+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<5,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (4.25.2)
[2024-11-18T18:27:15.402+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz<2024 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T18:27:15.402+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (2.31.0)
[2024-11-18T18:27:15.402+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (23.2)
[2024-11-18T18:27:15.403+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (6.11.0)
[2024-11-18T18:27:15.403+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (0.4.4)
[2024-11-18T18:27:15.403+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (1.13.1)
[2024-11-18T18:27:15.404+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (7.0.0)
[2024-11-18T18:27:15.404+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (2.2.5)
[2024-11-18T18:27:15.404+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (1.24.4)
[2024-11-18T18:27:15.404+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (1.10.1)
[2024-11-18T18:27:15.416+0000] {process_utils.py:190} INFO - Collecting querystring-parser<2 (from mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2))
[2024-11-18T18:27:15.417+0000] {process_utils.py:190} INFO -   Using cached querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
[2024-11-18T18:27:15.418+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (1.4.51)
[2024-11-18T18:27:15.418+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow<16,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (14.0.2)
[2024-11-18T18:27:15.419+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (3.5.2)
[2024-11-18T18:27:15.419+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (3.7.5)
[2024-11-18T18:27:15.419+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<22 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (21.2.0)
[2024-11-18T18:27:15.420+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (3.1.3)
[2024-11-18T18:27:15.443+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venv9s3rmzoi/requirements.txt (line 3)) (2.8.2)
[2024-11-18T18:27:15.443+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venv9s3rmzoi/requirements.txt (line 3)) (2023.4)
[2024-11-18T18:27:15.448+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 4)) (1.4.2)
[2024-11-18T18:27:15.449+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 4)) (3.5.0)
[2024-11-18T18:27:15.464+0000] {process_utils.py:190} INFO - Collecting absl-py>=1.0.0 (from tensorflow==2.13.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 5))
[2024-11-18T18:27:15.466+0000] {process_utils.py:190} INFO -   Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
[2024-11-18T18:27:15.477+0000] {process_utils.py:190} INFO - Collecting astunparse>=1.6.0 (from tensorflow==2.13.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 5))
[2024-11-18T18:27:15.478+0000] {process_utils.py:190} INFO -   Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
[2024-11-18T18:27:15.492+0000] {process_utils.py:190} INFO - Collecting flatbuffers>=23.1.21 (from tensorflow==2.13.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 5))
[2024-11-18T18:27:15.494+0000] {process_utils.py:190} INFO -   Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
[2024-11-18T18:27:15.511+0000] {process_utils.py:190} INFO - Collecting gast<=0.4.0,>=0.2.1 (from tensorflow==2.13.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 5))
[2024-11-18T18:27:15.512+0000] {process_utils.py:190} INFO -   Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
[2024-11-18T18:27:15.526+0000] {process_utils.py:190} INFO - Collecting google-pasta>=0.1.1 (from tensorflow==2.13.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 5))
[2024-11-18T18:27:15.527+0000] {process_utils.py:190} INFO -   Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
[2024-11-18T18:27:15.527+0000] {process_utils.py:190} INFO - Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 5)) (1.60.0)
[2024-11-18T18:27:15.565+0000] {process_utils.py:190} INFO - Collecting h5py>=2.9.0 (from tensorflow==2.13.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 5))
[2024-11-18T18:27:15.566+0000] {process_utils.py:190} INFO -   Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
[2024-11-18T18:27:15.590+0000] {process_utils.py:190} INFO - Collecting keras<2.14,>=2.13.1 (from tensorflow==2.13.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 5))
[2024-11-18T18:27:15.591+0000] {process_utils.py:190} INFO -   Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
[2024-11-18T18:27:15.607+0000] {process_utils.py:190} INFO - Collecting libclang>=13.0.0 (from tensorflow==2.13.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 5))
[2024-11-18T18:27:15.608+0000] {process_utils.py:190} INFO -   Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
[2024-11-18T18:27:15.770+0000] {process_utils.py:190} INFO - Collecting numpy<2 (from mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2))
[2024-11-18T18:27:15.772+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-11-18T18:27:15.785+0000] {process_utils.py:190} INFO - Collecting opt-einsum>=2.3.2 (from tensorflow==2.13.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 5))
[2024-11-18T18:27:15.786+0000] {process_utils.py:190} INFO -   Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
[2024-11-18T18:27:15.787+0000] {process_utils.py:190} INFO - Requirement already satisfied: setuptools in /tmp/venv9s3rmzoi/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 5)) (75.2.0)
[2024-11-18T18:27:15.788+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.12.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:27:15.808+0000] {process_utils.py:190} INFO - Collecting tensorboard<2.14,>=2.13 (from tensorflow==2.13.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 5))
[2024-11-18T18:27:15.810+0000] {process_utils.py:190} INFO -   Using cached tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:27:15.826+0000] {process_utils.py:190} INFO - Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow==2.13.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 5))
[2024-11-18T18:27:15.827+0000] {process_utils.py:190} INFO -   Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
[2024-11-18T18:27:15.828+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.1.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 5)) (2.4.0)
[2024-11-18T18:27:15.848+0000] {process_utils.py:190} INFO - Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow==2.13.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 5))
[2024-11-18T18:27:15.849+0000] {process_utils.py:190} INFO -   Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
[2024-11-18T18:27:15.850+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt>=1.11.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:27:15.879+0000] {process_utils.py:190} INFO - Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow==2.13.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 5))
[2024-11-18T18:27:15.880+0000] {process_utils.py:190} INFO -   Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
[2024-11-18T18:27:15.884+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (1.3.0)
[2024-11-18T18:27:15.887+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (5.13.0)
[2024-11-18T18:27:15.888+0000] {process_utils.py:190} INFO - Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venv9s3rmzoi/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow==2.13.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 5)) (0.44.0)
[2024-11-18T18:27:15.890+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 1)) (1.26.18)
[2024-11-18T18:27:15.896+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (2.2.3)
[2024-11-18T18:27:15.896+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (2.1.2)
[2024-11-18T18:27:15.901+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (4.0.11)
[2024-11-18T18:27:15.909+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (3.17.0)
[2024-11-18T18:27:15.910+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (2.1.3)
[2024-11-18T18:27:15.918+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (1.1.1)
[2024-11-18T18:27:15.918+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (0.12.1)
[2024-11-18T18:27:15.919+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (4.54.1)
[2024-11-18T18:27:15.919+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (1.4.7)
[2024-11-18T18:27:15.927+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (10.4.0)
[2024-11-18T18:27:15.927+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (3.1.1)
[2024-11-18T18:27:15.947+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (3.3.2)
[2024-11-18T18:27:15.947+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (3.6)
[2024-11-18T18:27:15.947+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (2023.11.17)
[2024-11-18T18:27:16.084+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (3.0.3)
[2024-11-18T18:27:16.089+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth<3,>=1.6.3 in /home/***/.local/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 5)) (2.26.2)
[2024-11-18T18:27:16.157+0000] {process_utils.py:190} INFO - Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 5))
[2024-11-18T18:27:16.159+0000] {process_utils.py:190} INFO -   Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
[2024-11-18T18:27:16.185+0000] {process_utils.py:190} INFO - Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 5))
[2024-11-18T18:27:16.186+0000] {process_utils.py:190} INFO -   Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
[2024-11-18T18:27:16.235+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venv9s3rmzoi/requirements.txt (line 2)) (5.0.1)
[2024-11-18T18:27:16.238+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 5)) (5.3.2)
[2024-11-18T18:27:16.238+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 5)) (0.3.0)
[2024-11-18T18:27:16.239+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 5)) (4.9)
[2024-11-18T18:27:16.240+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 5)) (1.3.1)
[2024-11-18T18:27:16.267+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 5)) (0.5.1)
[2024-11-18T18:27:16.268+0000] {process_utils.py:190} INFO - Requirement already satisfied: oauthlib>=3.0.0 in /home/***/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv9s3rmzoi/requirements.txt (line 5)) (3.2.2)
[2024-11-18T18:27:16.276+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T18:27:16.277+0000] {process_utils.py:190} INFO - Using cached mlflow-2.10.2-py3-none-any.whl (19.5 MB)
[2024-11-18T18:27:16.288+0000] {process_utils.py:190} INFO - Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
[2024-11-18T18:27:16.581+0000] {process_utils.py:190} INFO - Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
[2024-11-18T18:27:16.582+0000] {process_utils.py:190} INFO - Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
[2024-11-18T18:27:16.583+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T18:27:16.590+0000] {process_utils.py:190} INFO - Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
[2024-11-18T18:27:16.591+0000] {process_utils.py:190} INFO - Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
[2024-11-18T18:27:16.592+0000] {process_utils.py:190} INFO - Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
[2024-11-18T18:27:16.594+0000] {process_utils.py:190} INFO - Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
[2024-11-18T18:27:16.595+0000] {process_utils.py:190} INFO - Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
[2024-11-18T18:27:16.599+0000] {process_utils.py:190} INFO - Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)
[2024-11-18T18:27:16.601+0000] {process_utils.py:190} INFO - Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
[2024-11-18T18:27:16.618+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-11-18T18:27:16.630+0000] {process_utils.py:190} INFO - Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
[2024-11-18T18:27:16.631+0000] {process_utils.py:190} INFO - Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
[2024-11-18T18:27:16.633+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T18:27:16.634+0000] {process_utils.py:190} INFO - Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
[2024-11-18T18:27:16.638+0000] {process_utils.py:190} INFO - Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
[2024-11-18T18:27:16.640+0000] {process_utils.py:190} INFO - Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
[2024-11-18T18:27:16.642+0000] {process_utils.py:190} INFO - Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[2024-11-18T18:27:16.643+0000] {process_utils.py:190} INFO - Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
[2024-11-18T18:27:16.644+0000] {process_utils.py:190} INFO - Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
[2024-11-18T18:27:17.838+0000] {process_utils.py:190} INFO - Installing collected packages: libclang, flatbuffers, typing-extensions, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, querystring-parser, opt-einsum, numpy, keras, google-pasta, gast, entrypoints, astunparse, absl-py, h5py, botocore, s3transfer, google-auth-oauthlib, tensorboard, mlflow, boto3, tensorflow
[2024-11-18T18:27:18.168+0000] {process_utils.py:190} INFO -   Attempting uninstall: typing-extensions
[2024-11-18T18:27:18.170+0000] {process_utils.py:190} INFO -     Found existing installation: typing_extensions 4.9.0
[2024-11-18T18:27:18.170+0000] {process_utils.py:190} INFO -     Not uninstalling typing-extensions at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv9s3rmzoi
[2024-11-18T18:27:18.171+0000] {process_utils.py:190} INFO -     Can't uninstall 'typing_extensions'. No files were found to uninstall.
[2024-11-18T18:27:18.430+0000] {process_utils.py:190} INFO -   Attempting uninstall: numpy
[2024-11-18T18:27:18.431+0000] {process_utils.py:190} INFO -     Found existing installation: numpy 1.24.4
[2024-11-18T18:27:18.432+0000] {process_utils.py:190} INFO -     Not uninstalling numpy at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv9s3rmzoi
[2024-11-18T18:27:18.432+0000] {process_utils.py:190} INFO -     Can't uninstall 'numpy'. No files were found to uninstall.
[2024-11-18T18:27:20.024+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T18:27:20.025+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T18:27:20.025+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv9s3rmzoi
[2024-11-18T18:27:20.026+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T18:27:20.448+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T18:27:20.449+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T18:27:20.450+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv9s3rmzoi
[2024-11-18T18:27:20.451+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T18:27:20.472+0000] {process_utils.py:190} INFO -   Attempting uninstall: google-auth-oauthlib
[2024-11-18T18:27:20.473+0000] {process_utils.py:190} INFO -     Found existing installation: google-auth-oauthlib 1.2.0
[2024-11-18T18:27:20.473+0000] {process_utils.py:190} INFO -     Not uninstalling google-auth-oauthlib at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv9s3rmzoi
[2024-11-18T18:27:20.473+0000] {process_utils.py:190} INFO -     Can't uninstall 'google-auth-oauthlib'. No files were found to uninstall.
[2024-11-18T18:27:20.667+0000] {process_utils.py:190} INFO -   Attempting uninstall: mlflow
[2024-11-18T18:27:20.669+0000] {process_utils.py:190} INFO -     Found existing installation: mlflow 2.17.0
[2024-11-18T18:27:20.669+0000] {process_utils.py:190} INFO -     Not uninstalling mlflow at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv9s3rmzoi
[2024-11-18T18:27:20.670+0000] {process_utils.py:190} INFO -     Can't uninstall 'mlflow'. No files were found to uninstall.
[2024-11-18T18:27:21.210+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T18:27:21.211+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T18:27:21.211+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv9s3rmzoi
[2024-11-18T18:27:21.212+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T18:27:28.219+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T18:27:28.220+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T18:27:28.220+0000] {process_utils.py:190} INFO - azure-core 1.29.6 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:27:28.220+0000] {process_utils.py:190} INFO - azure-mgmt-keyvault 10.3.1 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:27:28.221+0000] {process_utils.py:190} INFO - azure-mgmt-network 27.0.0 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:27:28.221+0000] {process_utils.py:190} INFO - graphene 3.4 requires typing-extensions<5,>=4.7.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:27:28.221+0000] {process_utils.py:190} INFO - pydantic 2.5.3 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:27:28.221+0000] {process_utils.py:190} INFO - pydantic-core 2.14.6 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:27:28.222+0000] {process_utils.py:190} INFO - Successfully installed absl-py-2.1.0 astunparse-1.6.3 boto3-1.28.0 botocore-1.31.85 entrypoints-0.4 flatbuffers-24.3.25 gast-0.4.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 h5py-3.11.0 keras-2.13.1 libclang-18.1.1 mlflow-2.10.2 numpy-1.24.3 opt-einsum-3.4.0 querystring-parser-1.2.4 s3transfer-0.6.2 tensorboard-2.13.0 tensorboard-data-server-0.7.2 tensorflow-2.13.0 tensorflow-estimator-2.13.0 tensorflow-io-gcs-filesystem-0.34.0 typing-extensions-4.5.0
[2024-11-18T18:27:28.283+0000] {process_utils.py:190} INFO - 
[2024-11-18T18:27:28.284+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 24.2 -> 24.3.1
[2024-11-18T18:27:28.285+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T18:27:28.491+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv9s3rmzoi/bin/python /tmp/venv-callezsetnq8/script.py /tmp/venv-callezsetnq8/script.in /tmp/venv-callezsetnq8/script.out /tmp/venv-callezsetnq8/string_args.txt /tmp/venv-callezsetnq8/termination.log
[2024-11-18T18:27:28.495+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:27:29.475+0000] {process_utils.py:190} INFO - 2024-11-18 18:27:29.475663: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-11-18T18:27:29.476+0000] {process_utils.py:190} INFO - 2024-11-18 18:27:29.476779: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T18:27:29.497+0000] {process_utils.py:190} INFO - 2024-11-18 18:27:29.497142: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T18:27:29.497+0000] {process_utils.py:190} INFO - 2024-11-18 18:27:29.497390: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-11-18T18:27:29.497+0000] {process_utils.py:190} INFO - To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-11-18T18:27:29.993+0000] {process_utils.py:190} INFO - 2024-11-18 18:27:29.993047: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-11-18T18:27:31.055+0000] {process_utils.py:190} INFO - Epoch 1/10
[2024-11-18T18:27:31.990+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 2:46 - loss: 0.3530 48/575 [=>............................] - ETA: 0s - loss: 0.1511  100/575 [====>.........................] - ETA: 0s - loss: 0.1051176/575 [========>.....................] - ETA: 0s - loss: 0.0793253/575 [============>.................] - ETA: 0s - loss: 0.0656327/575 [================>.............] - ETA: 0s - loss: 0.0573405/575 [====================>.........] - ETA: 0s - loss: 0.0514481/575 [========================>.....] - ETA: 0s - loss: 0.0469557/575 [============================>.] - ETA: 0s - loss: 0.0435575/575 [==============================] - 1s 1ms/step - loss: 0.0428 - val_loss: 0.0086
[2024-11-18T18:27:31.990+0000] {process_utils.py:190} INFO - Epoch 2/10
[2024-11-18T18:27:32.461+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0190 76/575 [==>...........................] - ETA: 0s - loss: 0.0195149/575 [======>.......................] - ETA: 0s - loss: 0.0186222/575 [==========>...................] - ETA: 0s - loss: 0.0183294/575 [==============>...............] - ETA: 0s - loss: 0.0178366/575 [==================>...........] - ETA: 0s - loss: 0.0175439/575 [=====================>........] - ETA: 0s - loss: 0.0173516/575 [=========================>....] - ETA: 0s - loss: 0.0170575/575 [==============================] - 0s 819us/step - loss: 0.0167 - val_loss: 0.0058
[2024-11-18T18:27:32.461+0000] {process_utils.py:190} INFO - Epoch 3/10
[2024-11-18T18:27:32.933+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0141 78/575 [===>..........................] - ETA: 0s - loss: 0.0141155/575 [=======>......................] - ETA: 0s - loss: 0.0139232/575 [===========>..................] - ETA: 0s - loss: 0.0137307/575 [===============>..............] - ETA: 0s - loss: 0.0135384/575 [===================>..........] - ETA: 0s - loss: 0.0133461/575 [=======================>......] - ETA: 0s - loss: 0.0131534/575 [==========================>...] - ETA: 0s - loss: 0.0129575/575 [==============================] - 0s 820us/step - loss: 0.0128 - val_loss: 0.0046
[2024-11-18T18:27:32.933+0000] {process_utils.py:190} INFO - Epoch 4/10
[2024-11-18T18:27:33.395+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0114 77/575 [===>..........................] - ETA: 0s - loss: 0.0115156/575 [=======>......................] - ETA: 0s - loss: 0.0111232/575 [===========>..................] - ETA: 0s - loss: 0.0109310/575 [===============>..............] - ETA: 0s - loss: 0.0108387/575 [===================>..........] - ETA: 0s - loss: 0.0107461/575 [=======================>......] - ETA: 0s - loss: 0.0106537/575 [===========================>..] - ETA: 0s - loss: 0.0106575/575 [==============================] - 0s 802us/step - loss: 0.0105 - val_loss: 0.0043
[2024-11-18T18:27:33.395+0000] {process_utils.py:190} INFO - Epoch 5/10
[2024-11-18T18:27:33.860+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0072 79/575 [===>..........................] - ETA: 0s - loss: 0.0095148/575 [======>.......................] - ETA: 0s - loss: 0.0094228/575 [==========>...................] - ETA: 0s - loss: 0.0094302/575 [==============>...............] - ETA: 0s - loss: 0.0093380/575 [==================>...........] - ETA: 0s - loss: 0.0093456/575 [======================>.......] - ETA: 0s - loss: 0.0092535/575 [==========================>...] - ETA: 0s - loss: 0.0091575/575 [==============================] - 0s 808us/step - loss: 0.0091 - val_loss: 0.0035
[2024-11-18T18:27:33.860+0000] {process_utils.py:190} INFO - Epoch 6/10
[2024-11-18T18:27:34.320+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0108 76/575 [==>...........................] - ETA: 0s - loss: 0.0088152/575 [======>.......................] - ETA: 0s - loss: 0.0088228/575 [==========>...................] - ETA: 0s - loss: 0.0087303/575 [==============>...............] - ETA: 0s - loss: 0.0086379/575 [==================>...........] - ETA: 0s - loss: 0.0085456/575 [======================>.......] - ETA: 0s - loss: 0.0084530/575 [==========================>...] - ETA: 0s - loss: 0.0084575/575 [==============================] - 0s 800us/step - loss: 0.0084 - val_loss: 0.0030
[2024-11-18T18:27:34.321+0000] {process_utils.py:190} INFO - Epoch 7/10
[2024-11-18T18:27:34.789+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0064 78/575 [===>..........................] - ETA: 0s - loss: 0.0079154/575 [=======>......................] - ETA: 0s - loss: 0.0078231/575 [===========>..................] - ETA: 0s - loss: 0.0079310/575 [===============>..............] - ETA: 0s - loss: 0.0078387/575 [===================>..........] - ETA: 0s - loss: 0.0078463/575 [=======================>......] - ETA: 0s - loss: 0.0078537/575 [===========================>..] - ETA: 0s - loss: 0.0078575/575 [==============================] - 0s 815us/step - loss: 0.0078 - val_loss: 0.0030
[2024-11-18T18:27:34.790+0000] {process_utils.py:190} INFO - Epoch 8/10
[2024-11-18T18:27:35.251+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0071 74/575 [==>...........................] - ETA: 0s - loss: 0.0075152/575 [======>.......................] - ETA: 0s - loss: 0.0077230/575 [===========>..................] - ETA: 0s - loss: 0.0076305/575 [==============>...............] - ETA: 0s - loss: 0.0076381/575 [==================>...........] - ETA: 0s - loss: 0.0076458/575 [======================>.......] - ETA: 0s - loss: 0.0076534/575 [==========================>...] - ETA: 0s - loss: 0.0076575/575 [==============================] - 0s 803us/step - loss: 0.0076 - val_loss: 0.0032
[2024-11-18T18:27:35.252+0000] {process_utils.py:190} INFO - Epoch 9/10
[2024-11-18T18:27:35.712+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0084 77/575 [===>..........................] - ETA: 0s - loss: 0.0076155/575 [=======>......................] - ETA: 0s - loss: 0.0076232/575 [===========>..................] - ETA: 0s - loss: 0.0075308/575 [===============>..............] - ETA: 0s - loss: 0.0075384/575 [===================>..........] - ETA: 0s - loss: 0.0074462/575 [=======================>......] - ETA: 0s - loss: 0.0074537/575 [===========================>..] - ETA: 0s - loss: 0.0074575/575 [==============================] - 0s 800us/step - loss: 0.0074 - val_loss: 0.0027
[2024-11-18T18:27:35.712+0000] {process_utils.py:190} INFO - Epoch 10/10
[2024-11-18T18:27:36.170+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0061 77/575 [===>..........................] - ETA: 0s - loss: 0.0072153/575 [======>.......................] - ETA: 0s - loss: 0.0072226/575 [==========>...................] - ETA: 0s - loss: 0.0072303/575 [==============>...............] - ETA: 0s - loss: 0.0072381/575 [==================>...........] - ETA: 0s - loss: 0.0072457/575 [======================>.......] - ETA: 0s - loss: 0.0072537/575 [===========================>..] - ETA: 0s - loss: 0.0072575/575 [==============================] - 0s 796us/step - loss: 0.0072 - val_loss: 0.0024
[2024-11-18T18:27:36.584+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 29s 96/719 [===>..........................] - ETA: 0s 201/719 [=======>......................] - ETA: 0s303/719 [===========>..................] - ETA: 0s406/719 [===============>..............] - ETA: 0s509/719 [====================>.........] - ETA: 0s609/719 [========================>.....] - ETA: 0s715/719 [============================>.] - ETA: 0s719/719 [==============================] - 0s 493us/step
[2024-11-18T18:27:37.182+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 7s 88/719 [==>...........................] - ETA: 0s183/719 [======>.......................] - ETA: 0s292/719 [===========>..................] - ETA: 0s395/719 [===============>..............] - ETA: 0s500/719 [===================>..........] - ETA: 0s598/719 [=======================>......] - ETA: 0s692/719 [===========================>..] - ETA: 0s719/719 [==============================] - 0s 509us/step
[2024-11-18T18:27:37.255+0000] {process_utils.py:190} INFO - 2024/11/18 18:27:37 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.
[2024-11-18T18:27:37.581+0000] {process_utils.py:190} INFO - [[34m2024-11-18T18:27:37.580+0000[0m] {[34mbuilder_impl.py:[0m804} INFO[0m - Assets written to: /tmp/tmptjsse5i8/model/data/model/assets[0m
[2024-11-18T18:27:40.429+0000] {process_utils.py:190} INFO - /tmp/venv9s3rmzoi/lib/python3.8/site-packages/_distutils_hack/__init__.py:31 UserWarning: Setuptools is replacing distutils. Support for replacing an already imported distutils is deprecated. In the future, this condition will fail. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
[2024-11-18T18:27:40.469+0000] {process_utils.py:190} INFO - [[34m2024-11-18T18:27:40.469+0000[0m] {[34mcredentials.py:[0m1124} INFO[0m - Found credentials in environment variables.[0m
[2024-11-18T18:27:40.588+0000] {process_utils.py:190} INFO - Registered model 'spotify_model_prod' already exists. Creating a new version of this model...
[2024-11-18T18:27:40.589+0000] {process_utils.py:190} INFO - 2024/11/18 18:27:40 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: spotify_model_prod, version 3
[2024-11-18T18:27:40.589+0000] {process_utils.py:190} INFO - Created version '3' of model 'spotify_model_prod'.
[2024-11-18T18:27:40.589+0000] {process_utils.py:190} INFO - /tmp/venv9s3rmzoi/lib/python3.8/site-packages/keras/src/engine/training.py:3000 UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
[2024-11-18T18:27:40.612+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-11-18T18:27:40.612+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callezsetnq8/script.py", line 101, in <module>
[2024-11-18T18:27:40.613+0000] {process_utils.py:190} INFO -     res = train_challenger_model(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-18T18:27:40.615+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callezsetnq8/script.py", line 95, in train_challenger_model
[2024-11-18T18:27:40.617+0000] {process_utils.py:190} INFO -     json.dump({"embeddings": embeddings.tolist()}, f)
[2024-11-18T18:27:40.618+0000] {process_utils.py:190} INFO - NameError: name 'json' is not defined
[2024-11-18T18:27:41.573+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
name 'json' is not defined
[2024-11-18T18:27:41.575+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_retrain_challenge_model_v3, task_id=train_challenger_model, execution_date=20241118T182712, start_date=20241118T182713, end_date=20241118T182741
[2024-11-18T18:27:41.617+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 86 for task train_challenger_model (Process returned non-zero exit status 1.
name 'json' is not defined; 13912)
[2024-11-18T18:27:41.628+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-18T18:27:41.639+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
