[2024-11-18T18:32:42.119+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:27:12.351051+00:00 [queued]>
[2024-11-18T18:32:42.123+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:27:12.351051+00:00 [queued]>
[2024-11-18T18:32:42.124+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-11-18T18:32:42.131+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_challenger_model> on 2024-11-18 18:27:12.351051+00:00
[2024-11-18T18:32:42.134+0000] {standard_task_runner.py:60} INFO - Started process 17346 to run task
[2024-11-18T18:32:42.135+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_retrain_challenge_model_v3', 'train_challenger_model', 'manual__2024-11-18T18:27:12.351051+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/retrain_music_model.py', '--cfg-path', '/tmp/tmpka3zp026']
[2024-11-18T18:32:42.136+0000] {standard_task_runner.py:88} INFO - Job 92: Subtask train_challenger_model
[2024-11-18T18:32:42.162+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:27:12.351051+00:00 [running]> on host 98017b53a184
[2024-11-18T18:32:42.202+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_retrain_challenge_model_v3' AIRFLOW_CTX_TASK_ID='train_challenger_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T18:27:12.351051+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T18:27:12.351051+00:00'
[2024-11-18T18:32:42.203+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvygireiqq --system-site-packages --python=python
[2024-11-18T18:32:42.207+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:32:42.569+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 154ms
[2024-11-18T18:32:42.569+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvygireiqq, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T18:32:42.570+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T18:32:42.570+0000] {process_utils.py:190} INFO -     added seed packages: pip==24.2, setuptools==75.2.0, wheel==0.44.0
[2024-11-18T18:32:42.571+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T18:32:42.588+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvygireiqq/bin/pip install -r /tmp/venvygireiqq/requirements.txt
[2024-11-18T18:32:42.591+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:32:43.425+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venvygireiqq/requirements.txt (line 1))
[2024-11-18T18:32:43.426+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T18:32:43.460+0000] {process_utils.py:190} INFO - Collecting mlflow==2.10.2 (from -r /tmp/venvygireiqq/requirements.txt (line 2))
[2024-11-18T18:32:43.461+0000] {process_utils.py:190} INFO -   Using cached mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
[2024-11-18T18:32:43.469+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvygireiqq/requirements.txt (line 3)) (2.0.3)
[2024-11-18T18:32:43.469+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn==1.3.2 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvygireiqq/requirements.txt (line 4)) (1.3.2)
[2024-11-18T18:32:43.553+0000] {process_utils.py:190} INFO - Collecting tensorflow==2.13.0 (from -r /tmp/venvygireiqq/requirements.txt (line 5))
[2024-11-18T18:32:43.555+0000] {process_utils.py:190} INFO -   Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
[2024-11-18T18:32:43.987+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venvygireiqq/requirements.txt (line 1))
[2024-11-18T18:32:43.988+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T18:32:43.989+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venvygireiqq/requirements.txt (line 1)) (0.10.0)
[2024-11-18T18:32:44.009+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venvygireiqq/requirements.txt (line 1))
[2024-11-18T18:32:44.010+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:32:44.013+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (8.1.7)
[2024-11-18T18:32:44.013+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (3.1.0)
[2024-11-18T18:32:44.026+0000] {process_utils.py:190} INFO - Collecting entrypoints<1 (from mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2))
[2024-11-18T18:32:44.027+0000] {process_utils.py:190} INFO -   Using cached entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
[2024-11-18T18:32:44.028+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=2.1.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (3.1.43)
[2024-11-18T18:32:44.028+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (6.0.1)
[2024-11-18T18:32:44.028+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<5,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (4.25.2)
[2024-11-18T18:32:44.029+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz<2024 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T18:32:44.029+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (2.31.0)
[2024-11-18T18:32:44.029+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (23.2)
[2024-11-18T18:32:44.030+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (6.11.0)
[2024-11-18T18:32:44.030+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (0.4.4)
[2024-11-18T18:32:44.030+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (1.13.1)
[2024-11-18T18:32:44.030+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (7.0.0)
[2024-11-18T18:32:44.031+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (2.2.5)
[2024-11-18T18:32:44.031+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (1.24.4)
[2024-11-18T18:32:44.031+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (1.10.1)
[2024-11-18T18:32:44.043+0000] {process_utils.py:190} INFO - Collecting querystring-parser<2 (from mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2))
[2024-11-18T18:32:44.044+0000] {process_utils.py:190} INFO -   Using cached querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
[2024-11-18T18:32:44.045+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (1.4.51)
[2024-11-18T18:32:44.045+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow<16,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (14.0.2)
[2024-11-18T18:32:44.046+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (3.5.2)
[2024-11-18T18:32:44.046+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (3.7.5)
[2024-11-18T18:32:44.046+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<22 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (21.2.0)
[2024-11-18T18:32:44.047+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (3.1.3)
[2024-11-18T18:32:44.067+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvygireiqq/requirements.txt (line 3)) (2.8.2)
[2024-11-18T18:32:44.068+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvygireiqq/requirements.txt (line 3)) (2023.4)
[2024-11-18T18:32:44.073+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvygireiqq/requirements.txt (line 4)) (1.4.2)
[2024-11-18T18:32:44.074+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvygireiqq/requirements.txt (line 4)) (3.5.0)
[2024-11-18T18:32:44.091+0000] {process_utils.py:190} INFO - Collecting absl-py>=1.0.0 (from tensorflow==2.13.0->-r /tmp/venvygireiqq/requirements.txt (line 5))
[2024-11-18T18:32:44.092+0000] {process_utils.py:190} INFO -   Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
[2024-11-18T18:32:44.105+0000] {process_utils.py:190} INFO - Collecting astunparse>=1.6.0 (from tensorflow==2.13.0->-r /tmp/venvygireiqq/requirements.txt (line 5))
[2024-11-18T18:32:44.106+0000] {process_utils.py:190} INFO -   Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
[2024-11-18T18:32:44.121+0000] {process_utils.py:190} INFO - Collecting flatbuffers>=23.1.21 (from tensorflow==2.13.0->-r /tmp/venvygireiqq/requirements.txt (line 5))
[2024-11-18T18:32:44.122+0000] {process_utils.py:190} INFO -   Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
[2024-11-18T18:32:44.139+0000] {process_utils.py:190} INFO - Collecting gast<=0.4.0,>=0.2.1 (from tensorflow==2.13.0->-r /tmp/venvygireiqq/requirements.txt (line 5))
[2024-11-18T18:32:44.140+0000] {process_utils.py:190} INFO -   Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
[2024-11-18T18:32:44.153+0000] {process_utils.py:190} INFO - Collecting google-pasta>=0.1.1 (from tensorflow==2.13.0->-r /tmp/venvygireiqq/requirements.txt (line 5))
[2024-11-18T18:32:44.154+0000] {process_utils.py:190} INFO -   Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
[2024-11-18T18:32:44.155+0000] {process_utils.py:190} INFO - Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvygireiqq/requirements.txt (line 5)) (1.60.0)
[2024-11-18T18:32:44.191+0000] {process_utils.py:190} INFO - Collecting h5py>=2.9.0 (from tensorflow==2.13.0->-r /tmp/venvygireiqq/requirements.txt (line 5))
[2024-11-18T18:32:44.193+0000] {process_utils.py:190} INFO -   Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
[2024-11-18T18:32:44.216+0000] {process_utils.py:190} INFO - Collecting keras<2.14,>=2.13.1 (from tensorflow==2.13.0->-r /tmp/venvygireiqq/requirements.txt (line 5))
[2024-11-18T18:32:44.218+0000] {process_utils.py:190} INFO -   Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
[2024-11-18T18:32:44.237+0000] {process_utils.py:190} INFO - Collecting libclang>=13.0.0 (from tensorflow==2.13.0->-r /tmp/venvygireiqq/requirements.txt (line 5))
[2024-11-18T18:32:44.238+0000] {process_utils.py:190} INFO -   Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
[2024-11-18T18:32:44.405+0000] {process_utils.py:190} INFO - Collecting numpy<2 (from mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2))
[2024-11-18T18:32:44.407+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-11-18T18:32:44.420+0000] {process_utils.py:190} INFO - Collecting opt-einsum>=2.3.2 (from tensorflow==2.13.0->-r /tmp/venvygireiqq/requirements.txt (line 5))
[2024-11-18T18:32:44.421+0000] {process_utils.py:190} INFO -   Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
[2024-11-18T18:32:44.422+0000] {process_utils.py:190} INFO - Requirement already satisfied: setuptools in /tmp/venvygireiqq/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvygireiqq/requirements.txt (line 5)) (75.2.0)
[2024-11-18T18:32:44.423+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.12.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvygireiqq/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:32:44.445+0000] {process_utils.py:190} INFO - Collecting tensorboard<2.14,>=2.13 (from tensorflow==2.13.0->-r /tmp/venvygireiqq/requirements.txt (line 5))
[2024-11-18T18:32:44.446+0000] {process_utils.py:190} INFO -   Using cached tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:32:44.462+0000] {process_utils.py:190} INFO - Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow==2.13.0->-r /tmp/venvygireiqq/requirements.txt (line 5))
[2024-11-18T18:32:44.463+0000] {process_utils.py:190} INFO -   Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
[2024-11-18T18:32:44.464+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.1.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvygireiqq/requirements.txt (line 5)) (2.4.0)
[2024-11-18T18:32:44.482+0000] {process_utils.py:190} INFO - Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow==2.13.0->-r /tmp/venvygireiqq/requirements.txt (line 5))
[2024-11-18T18:32:44.484+0000] {process_utils.py:190} INFO -   Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
[2024-11-18T18:32:44.485+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt>=1.11.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvygireiqq/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:32:44.515+0000] {process_utils.py:190} INFO - Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow==2.13.0->-r /tmp/venvygireiqq/requirements.txt (line 5))
[2024-11-18T18:32:44.516+0000] {process_utils.py:190} INFO -   Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
[2024-11-18T18:32:44.520+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (1.3.0)
[2024-11-18T18:32:44.524+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (5.13.0)
[2024-11-18T18:32:44.525+0000] {process_utils.py:190} INFO - Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venvygireiqq/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow==2.13.0->-r /tmp/venvygireiqq/requirements.txt (line 5)) (0.44.0)
[2024-11-18T18:32:44.526+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venvygireiqq/requirements.txt (line 1)) (1.26.18)
[2024-11-18T18:32:44.532+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (2.2.3)
[2024-11-18T18:32:44.533+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (2.1.2)
[2024-11-18T18:32:44.538+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (4.0.11)
[2024-11-18T18:32:44.546+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (3.17.0)
[2024-11-18T18:32:44.547+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (2.1.3)
[2024-11-18T18:32:44.556+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (1.1.1)
[2024-11-18T18:32:44.556+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (0.12.1)
[2024-11-18T18:32:44.556+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (4.54.1)
[2024-11-18T18:32:44.556+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (1.4.7)
[2024-11-18T18:32:44.563+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (10.4.0)
[2024-11-18T18:32:44.564+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (3.1.1)
[2024-11-18T18:32:44.582+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (3.3.2)
[2024-11-18T18:32:44.582+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (3.6)
[2024-11-18T18:32:44.582+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (2023.11.17)
[2024-11-18T18:32:44.798+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (3.0.3)
[2024-11-18T18:32:44.804+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth<3,>=1.6.3 in /home/***/.local/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvygireiqq/requirements.txt (line 5)) (2.26.2)
[2024-11-18T18:32:44.821+0000] {process_utils.py:190} INFO - Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvygireiqq/requirements.txt (line 5))
[2024-11-18T18:32:44.822+0000] {process_utils.py:190} INFO -   Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
[2024-11-18T18:32:44.851+0000] {process_utils.py:190} INFO - Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvygireiqq/requirements.txt (line 5))
[2024-11-18T18:32:44.852+0000] {process_utils.py:190} INFO -   Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
[2024-11-18T18:32:44.902+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvygireiqq/requirements.txt (line 2)) (5.0.1)
[2024-11-18T18:32:44.905+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvygireiqq/requirements.txt (line 5)) (5.3.2)
[2024-11-18T18:32:44.905+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvygireiqq/requirements.txt (line 5)) (0.3.0)
[2024-11-18T18:32:44.906+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvygireiqq/requirements.txt (line 5)) (4.9)
[2024-11-18T18:32:44.907+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvygireiqq/requirements.txt (line 5)) (1.3.1)
[2024-11-18T18:32:44.935+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvygireiqq/requirements.txt (line 5)) (0.5.1)
[2024-11-18T18:32:44.937+0000] {process_utils.py:190} INFO - Requirement already satisfied: oauthlib>=3.0.0 in /home/***/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvygireiqq/requirements.txt (line 5)) (3.2.2)
[2024-11-18T18:32:44.945+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T18:32:44.946+0000] {process_utils.py:190} INFO - Using cached mlflow-2.10.2-py3-none-any.whl (19.5 MB)
[2024-11-18T18:32:44.955+0000] {process_utils.py:190} INFO - Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
[2024-11-18T18:32:45.163+0000] {process_utils.py:190} INFO - Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
[2024-11-18T18:32:45.164+0000] {process_utils.py:190} INFO - Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
[2024-11-18T18:32:45.165+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T18:32:45.171+0000] {process_utils.py:190} INFO - Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
[2024-11-18T18:32:45.173+0000] {process_utils.py:190} INFO - Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
[2024-11-18T18:32:45.174+0000] {process_utils.py:190} INFO - Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
[2024-11-18T18:32:45.175+0000] {process_utils.py:190} INFO - Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
[2024-11-18T18:32:45.176+0000] {process_utils.py:190} INFO - Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
[2024-11-18T18:32:45.179+0000] {process_utils.py:190} INFO - Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)
[2024-11-18T18:32:45.182+0000] {process_utils.py:190} INFO - Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
[2024-11-18T18:32:45.194+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-11-18T18:32:45.202+0000] {process_utils.py:190} INFO - Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
[2024-11-18T18:32:45.204+0000] {process_utils.py:190} INFO - Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
[2024-11-18T18:32:45.205+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T18:32:45.206+0000] {process_utils.py:190} INFO - Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
[2024-11-18T18:32:45.209+0000] {process_utils.py:190} INFO - Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
[2024-11-18T18:32:45.211+0000] {process_utils.py:190} INFO - Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
[2024-11-18T18:32:45.213+0000] {process_utils.py:190} INFO - Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[2024-11-18T18:32:45.214+0000] {process_utils.py:190} INFO - Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
[2024-11-18T18:32:45.215+0000] {process_utils.py:190} INFO - Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
[2024-11-18T18:32:46.421+0000] {process_utils.py:190} INFO - Installing collected packages: libclang, flatbuffers, typing-extensions, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, querystring-parser, opt-einsum, numpy, keras, google-pasta, gast, entrypoints, astunparse, absl-py, h5py, botocore, s3transfer, google-auth-oauthlib, tensorboard, mlflow, boto3, tensorflow
[2024-11-18T18:32:46.650+0000] {process_utils.py:190} INFO -   Attempting uninstall: typing-extensions
[2024-11-18T18:32:46.651+0000] {process_utils.py:190} INFO -     Found existing installation: typing_extensions 4.9.0
[2024-11-18T18:32:46.652+0000] {process_utils.py:190} INFO -     Not uninstalling typing-extensions at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvygireiqq
[2024-11-18T18:32:46.652+0000] {process_utils.py:190} INFO -     Can't uninstall 'typing_extensions'. No files were found to uninstall.
[2024-11-18T18:32:46.908+0000] {process_utils.py:190} INFO -   Attempting uninstall: numpy
[2024-11-18T18:32:46.909+0000] {process_utils.py:190} INFO -     Found existing installation: numpy 1.24.4
[2024-11-18T18:32:46.909+0000] {process_utils.py:190} INFO -     Not uninstalling numpy at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvygireiqq
[2024-11-18T18:32:46.909+0000] {process_utils.py:190} INFO -     Can't uninstall 'numpy'. No files were found to uninstall.
[2024-11-18T18:32:48.504+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T18:32:48.505+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T18:32:48.505+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvygireiqq
[2024-11-18T18:32:48.505+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T18:32:48.882+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T18:32:48.884+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T18:32:48.884+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvygireiqq
[2024-11-18T18:32:48.884+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T18:32:48.905+0000] {process_utils.py:190} INFO -   Attempting uninstall: google-auth-oauthlib
[2024-11-18T18:32:48.906+0000] {process_utils.py:190} INFO -     Found existing installation: google-auth-oauthlib 1.2.0
[2024-11-18T18:32:48.906+0000] {process_utils.py:190} INFO -     Not uninstalling google-auth-oauthlib at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvygireiqq
[2024-11-18T18:32:48.906+0000] {process_utils.py:190} INFO -     Can't uninstall 'google-auth-oauthlib'. No files were found to uninstall.
[2024-11-18T18:32:49.137+0000] {process_utils.py:190} INFO -   Attempting uninstall: mlflow
[2024-11-18T18:32:49.139+0000] {process_utils.py:190} INFO -     Found existing installation: mlflow 2.17.0
[2024-11-18T18:32:49.139+0000] {process_utils.py:190} INFO -     Not uninstalling mlflow at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvygireiqq
[2024-11-18T18:32:49.139+0000] {process_utils.py:190} INFO -     Can't uninstall 'mlflow'. No files were found to uninstall.
[2024-11-18T18:32:49.677+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T18:32:49.678+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T18:32:49.678+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvygireiqq
[2024-11-18T18:32:49.678+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T18:32:52.207+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-11-18T18:32:52.209+0000] {process_utils.py:131} INFO - Sending 15 to group 17346. PIDs of all processes in the group: [17355, 17346]
[2024-11-18T18:32:52.210+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 17346
[2024-11-18T18:32:52.211+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-18T18:32:52.215+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=17355, status='terminated', started='18:32:41') (17355) terminated with exit code None
[2024-11-18T18:32:52.422+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 714, in execute_callable
    self._prepare_venv(tmp_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 626, in _prepare_venv
    prepare_virtualenv(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/python_virtualenv.py", line 118, in prepare_virtualenv
    execute_in_subprocess(pip_cmd)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/process_utils.py", line 171, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/process_utils.py", line 189, in execute_in_subprocess_with_kwargs
    for line in iter(proc.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2452, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-11-18T18:32:52.424+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=spotify_retrain_challenge_model_v3, task_id=train_challenger_model, execution_date=20241118T182712, start_date=20241118T183242, end_date=20241118T183252
[2024-11-18T18:32:52.435+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 92 for task train_challenger_model ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(spotify_retrain_challenge_model_v3, train_challenger_model, manual__2024-11-18T18:27:12.351051+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'train_challenger_model', 'dag_id': 'spotify_retrain_challenge_model_v3', 'run_id': 'manual__2024-11-18T18:27:12.351051+00:00', 'map_index': -1, 'start_date': datetime.datetime(2024, 11, 18, 18, 32, 42, 119746, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2024, 11, 18, 18, 32, 52, 423940, tzinfo=Timezone('UTC')), 'duration': 10}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 17346)
[2024-11-18T18:32:52.468+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=17346, status='terminated', exitcode=1, started='18:32:41') (17346) terminated with exit code 1
