[2024-11-18T21:05:26.979+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T21:05:26.400981+00:00 [queued]>
[2024-11-18T21:05:26.983+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T21:05:26.400981+00:00 [queued]>
[2024-11-18T21:05:26.984+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-11-18T21:05:26.990+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_challenger_model> on 2024-11-18 21:05:26.400981+00:00
[2024-11-18T21:05:26.994+0000] {standard_task_runner.py:60} INFO - Started process 575 to run task
[2024-11-18T21:05:26.995+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_retrain_challenge_model_v3', 'train_challenger_model', 'manual__2024-11-18T21:05:26.400981+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/retrain_music_model.py', '--cfg-path', '/tmp/tmps_nnk7kb']
[2024-11-18T21:05:26.996+0000] {standard_task_runner.py:88} INFO - Job 125: Subtask train_challenger_model
[2024-11-18T21:05:27.022+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T21:05:26.400981+00:00 [running]> on host e779a152538d
[2024-11-18T21:05:27.065+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_retrain_challenge_model_v3' AIRFLOW_CTX_TASK_ID='train_challenger_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T21:05:26.400981+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T21:05:26.400981+00:00'
[2024-11-18T21:05:27.066+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvfa2zehtd --system-site-packages --python=python
[2024-11-18T21:05:27.070+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T21:05:27.402+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 121ms
[2024-11-18T21:05:27.403+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvfa2zehtd, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T21:05:27.403+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T21:05:27.403+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-11-18T21:05:27.404+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T21:05:27.421+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvfa2zehtd/bin/pip install -r /tmp/venvfa2zehtd/requirements.txt
[2024-11-18T21:05:27.427+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T21:05:28.369+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venvfa2zehtd/requirements.txt (line 1))
[2024-11-18T21:05:28.371+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T21:05:28.415+0000] {process_utils.py:190} INFO - Collecting mlflow==2.10.2 (from -r /tmp/venvfa2zehtd/requirements.txt (line 2))
[2024-11-18T21:05:28.458+0000] {process_utils.py:190} INFO -   Downloading mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
[2024-11-18T21:05:28.462+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvfa2zehtd/requirements.txt (line 3)) (2.0.3)
[2024-11-18T21:05:28.463+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn==1.3.2 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvfa2zehtd/requirements.txt (line 4)) (1.3.2)
[2024-11-18T21:05:28.584+0000] {process_utils.py:190} INFO - Collecting tensorflow==2.13.0 (from -r /tmp/venvfa2zehtd/requirements.txt (line 5))
[2024-11-18T21:05:28.593+0000] {process_utils.py:190} INFO -   Downloading tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
[2024-11-18T21:05:29.017+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venvfa2zehtd/requirements.txt (line 1))
[2024-11-18T21:05:29.018+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T21:05:29.019+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venvfa2zehtd/requirements.txt (line 1)) (0.10.0)
[2024-11-18T21:05:29.043+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venvfa2zehtd/requirements.txt (line 1))
[2024-11-18T21:05:29.044+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T21:05:29.096+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (8.1.7)
[2024-11-18T21:05:29.097+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (3.1.0)
[2024-11-18T21:05:29.114+0000] {process_utils.py:190} INFO - Collecting entrypoints<1 (from mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2))
[2024-11-18T21:05:29.121+0000] {process_utils.py:190} INFO -   Downloading entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
[2024-11-18T21:05:29.125+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=2.1.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (3.1.43)
[2024-11-18T21:05:29.125+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (6.0.1)
[2024-11-18T21:05:29.126+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<5,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (4.25.2)
[2024-11-18T21:05:29.126+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz<2024 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T21:05:29.127+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (2.31.0)
[2024-11-18T21:05:29.127+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (23.2)
[2024-11-18T21:05:29.127+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (6.11.0)
[2024-11-18T21:05:29.128+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (0.4.4)
[2024-11-18T21:05:29.128+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (1.13.1)
[2024-11-18T21:05:29.129+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (7.0.0)
[2024-11-18T21:05:29.129+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (2.2.5)
[2024-11-18T21:05:29.130+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (1.24.4)
[2024-11-18T21:05:29.130+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (1.10.1)
[2024-11-18T21:05:29.148+0000] {process_utils.py:190} INFO - Collecting querystring-parser<2 (from mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2))
[2024-11-18T21:05:29.155+0000] {process_utils.py:190} INFO -   Downloading querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
[2024-11-18T21:05:29.158+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (1.4.51)
[2024-11-18T21:05:29.159+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow<16,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (14.0.2)
[2024-11-18T21:05:29.159+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (3.5.2)
[2024-11-18T21:05:29.160+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (3.7.5)
[2024-11-18T21:05:29.160+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<22 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (21.2.0)
[2024-11-18T21:05:29.161+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (3.1.3)
[2024-11-18T21:05:29.215+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvfa2zehtd/requirements.txt (line 3)) (2.8.2)
[2024-11-18T21:05:29.215+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvfa2zehtd/requirements.txt (line 3)) (2023.4)
[2024-11-18T21:05:29.235+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvfa2zehtd/requirements.txt (line 4)) (1.4.2)
[2024-11-18T21:05:29.236+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvfa2zehtd/requirements.txt (line 4)) (3.5.0)
[2024-11-18T21:05:29.270+0000] {process_utils.py:190} INFO - Collecting absl-py>=1.0.0 (from tensorflow==2.13.0->-r /tmp/venvfa2zehtd/requirements.txt (line 5))
[2024-11-18T21:05:29.280+0000] {process_utils.py:190} INFO -   Downloading absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
[2024-11-18T21:05:29.301+0000] {process_utils.py:190} INFO - Collecting astunparse>=1.6.0 (from tensorflow==2.13.0->-r /tmp/venvfa2zehtd/requirements.txt (line 5))
[2024-11-18T21:05:29.310+0000] {process_utils.py:190} INFO -   Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
[2024-11-18T21:05:29.332+0000] {process_utils.py:190} INFO - Collecting flatbuffers>=23.1.21 (from tensorflow==2.13.0->-r /tmp/venvfa2zehtd/requirements.txt (line 5))
[2024-11-18T21:05:29.341+0000] {process_utils.py:190} INFO -   Downloading flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
[2024-11-18T21:05:29.364+0000] {process_utils.py:190} INFO - Collecting gast<=0.4.0,>=0.2.1 (from tensorflow==2.13.0->-r /tmp/venvfa2zehtd/requirements.txt (line 5))
[2024-11-18T21:05:29.373+0000] {process_utils.py:190} INFO -   Downloading gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
[2024-11-18T21:05:29.395+0000] {process_utils.py:190} INFO - Collecting google-pasta>=0.1.1 (from tensorflow==2.13.0->-r /tmp/venvfa2zehtd/requirements.txt (line 5))
[2024-11-18T21:05:29.402+0000] {process_utils.py:190} INFO -   Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
[2024-11-18T21:05:29.406+0000] {process_utils.py:190} INFO - Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvfa2zehtd/requirements.txt (line 5)) (1.60.0)
[2024-11-18T21:05:29.456+0000] {process_utils.py:190} INFO - Collecting h5py>=2.9.0 (from tensorflow==2.13.0->-r /tmp/venvfa2zehtd/requirements.txt (line 5))
[2024-11-18T21:05:29.464+0000] {process_utils.py:190} INFO -   Downloading h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
[2024-11-18T21:05:29.495+0000] {process_utils.py:190} INFO - Collecting keras<2.14,>=2.13.1 (from tensorflow==2.13.0->-r /tmp/venvfa2zehtd/requirements.txt (line 5))
[2024-11-18T21:05:29.503+0000] {process_utils.py:190} INFO -   Downloading keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
[2024-11-18T21:05:29.529+0000] {process_utils.py:190} INFO - Collecting libclang>=13.0.0 (from tensorflow==2.13.0->-r /tmp/venvfa2zehtd/requirements.txt (line 5))
[2024-11-18T21:05:29.537+0000] {process_utils.py:190} INFO -   Downloading libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
[2024-11-18T21:05:29.717+0000] {process_utils.py:190} INFO - Collecting numpy<2 (from mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2))
[2024-11-18T21:05:29.725+0000] {process_utils.py:190} INFO -   Downloading numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-11-18T21:05:29.746+0000] {process_utils.py:190} INFO - Collecting opt-einsum>=2.3.2 (from tensorflow==2.13.0->-r /tmp/venvfa2zehtd/requirements.txt (line 5))
[2024-11-18T21:05:29.755+0000] {process_utils.py:190} INFO -   Downloading opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
[2024-11-18T21:05:29.759+0000] {process_utils.py:190} INFO - Requirement already satisfied: setuptools in /tmp/venvfa2zehtd/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvfa2zehtd/requirements.txt (line 5)) (69.0.2)
[2024-11-18T21:05:29.759+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.12.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvfa2zehtd/requirements.txt (line 5)) (1.16.0)
[2024-11-18T21:05:29.786+0000] {process_utils.py:190} INFO - Collecting tensorboard<2.14,>=2.13 (from tensorflow==2.13.0->-r /tmp/venvfa2zehtd/requirements.txt (line 5))
[2024-11-18T21:05:29.795+0000] {process_utils.py:190} INFO -   Downloading tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T21:05:29.818+0000] {process_utils.py:190} INFO - Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow==2.13.0->-r /tmp/venvfa2zehtd/requirements.txt (line 5))
[2024-11-18T21:05:29.826+0000] {process_utils.py:190} INFO -   Downloading tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
[2024-11-18T21:05:29.829+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.1.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvfa2zehtd/requirements.txt (line 5)) (2.4.0)
[2024-11-18T21:05:29.852+0000] {process_utils.py:190} INFO - Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow==2.13.0->-r /tmp/venvfa2zehtd/requirements.txt (line 5))
[2024-11-18T21:05:29.860+0000] {process_utils.py:190} INFO -   Downloading typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
[2024-11-18T21:05:29.864+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt>=1.11.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvfa2zehtd/requirements.txt (line 5)) (1.16.0)
[2024-11-18T21:05:29.921+0000] {process_utils.py:190} INFO - Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow==2.13.0->-r /tmp/venvfa2zehtd/requirements.txt (line 5))
[2024-11-18T21:05:29.929+0000] {process_utils.py:190} INFO -   Downloading tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
[2024-11-18T21:05:29.940+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (1.3.0)
[2024-11-18T21:05:29.943+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (5.13.0)
[2024-11-18T21:05:29.946+0000] {process_utils.py:190} INFO - Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venvfa2zehtd/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow==2.13.0->-r /tmp/venvfa2zehtd/requirements.txt (line 5)) (0.42.0)
[2024-11-18T21:05:29.952+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venvfa2zehtd/requirements.txt (line 1)) (1.26.18)
[2024-11-18T21:05:29.966+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (2.2.3)
[2024-11-18T21:05:29.967+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (2.1.2)
[2024-11-18T21:05:29.984+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (4.0.11)
[2024-11-18T21:05:30.010+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (3.17.0)
[2024-11-18T21:05:30.014+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (2.1.3)
[2024-11-18T21:05:30.038+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (1.1.1)
[2024-11-18T21:05:30.038+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (0.12.1)
[2024-11-18T21:05:30.039+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (4.54.1)
[2024-11-18T21:05:30.039+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (1.4.7)
[2024-11-18T21:05:30.048+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (10.4.0)
[2024-11-18T21:05:30.049+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (3.1.1)
[2024-11-18T21:05:30.095+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (3.3.2)
[2024-11-18T21:05:30.095+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (3.6)
[2024-11-18T21:05:30.096+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (2023.11.17)
[2024-11-18T21:05:30.348+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (3.0.3)
[2024-11-18T21:05:30.365+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth<3,>=1.6.3 in /home/***/.local/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvfa2zehtd/requirements.txt (line 5)) (2.26.2)
[2024-11-18T21:05:30.393+0000] {process_utils.py:190} INFO - Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvfa2zehtd/requirements.txt (line 5))
[2024-11-18T21:05:30.400+0000] {process_utils.py:190} INFO -   Downloading google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
[2024-11-18T21:05:30.433+0000] {process_utils.py:190} INFO - Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvfa2zehtd/requirements.txt (line 5))
[2024-11-18T21:05:30.442+0000] {process_utils.py:190} INFO -   Downloading tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
[2024-11-18T21:05:30.590+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvfa2zehtd/requirements.txt (line 2)) (5.0.1)
[2024-11-18T21:05:30.601+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvfa2zehtd/requirements.txt (line 5)) (5.3.2)
[2024-11-18T21:05:30.601+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvfa2zehtd/requirements.txt (line 5)) (0.3.0)
[2024-11-18T21:05:30.602+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvfa2zehtd/requirements.txt (line 5)) (4.9)
[2024-11-18T21:05:30.609+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvfa2zehtd/requirements.txt (line 5)) (1.3.1)
[2024-11-18T21:05:30.741+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvfa2zehtd/requirements.txt (line 5)) (0.5.1)
[2024-11-18T21:05:30.749+0000] {process_utils.py:190} INFO - Requirement already satisfied: oauthlib>=3.0.0 in /home/***/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvfa2zehtd/requirements.txt (line 5)) (3.2.2)
[2024-11-18T21:05:30.781+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T21:05:30.788+0000] {process_utils.py:190} INFO - Downloading mlflow-2.10.2-py3-none-any.whl (19.5 MB)
[2024-11-18T21:05:32.499+0000] {process_utils.py:190} INFO -    ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 19.5/19.5 MB 11.2 MB/s eta 0:00:00
[2024-11-18T21:05:32.508+0000] {process_utils.py:190} INFO - Downloading tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
[2024-11-18T21:06:18.058+0000] {process_utils.py:190} INFO -    ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 524.1/524.1 MB 7.3 MB/s eta 0:00:00
[2024-11-18T21:06:18.066+0000] {process_utils.py:190} INFO - Downloading absl_py-2.1.0-py3-none-any.whl (133 kB)
[2024-11-18T21:06:18.081+0000] {process_utils.py:190} INFO -    ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 133.7/133.7 kB 9.9 MB/s eta 0:00:00
[2024-11-18T21:06:18.091+0000] {process_utils.py:190} INFO - Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
[2024-11-18T21:06:18.094+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T21:06:18.121+0000] {process_utils.py:190} INFO - Downloading entrypoints-0.4-py3-none-any.whl (5.3 kB)
[2024-11-18T21:06:18.130+0000] {process_utils.py:190} INFO - Downloading flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
[2024-11-18T21:06:18.143+0000] {process_utils.py:190} INFO - Downloading gast-0.4.0-py3-none-any.whl (9.8 kB)
[2024-11-18T21:06:18.156+0000] {process_utils.py:190} INFO - Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
[2024-11-18T21:06:18.164+0000] {process_utils.py:190} INFO -    ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 57.5/57.5 kB 7.7 MB/s eta 0:00:00
[2024-11-18T21:06:18.174+0000] {process_utils.py:190} INFO - Downloading h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
[2024-11-18T21:06:18.639+0000] {process_utils.py:190} INFO -    ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 5.3/5.3 MB 11.5 MB/s eta 0:00:00
[2024-11-18T21:06:18.648+0000] {process_utils.py:190} INFO - Downloading keras-2.13.1-py3-none-any.whl (1.7 MB)
[2024-11-18T21:06:18.799+0000] {process_utils.py:190} INFO -    ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 1.7/1.7 MB 11.4 MB/s eta 0:00:00
[2024-11-18T21:06:18.806+0000] {process_utils.py:190} INFO - Downloading libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
[2024-11-18T21:06:20.935+0000] {process_utils.py:190} INFO -    ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 24.5/24.5 MB 11.3 MB/s eta 0:00:00
[2024-11-18T21:06:20.945+0000] {process_utils.py:190} INFO - Downloading numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-11-18T21:06:22.451+0000] {process_utils.py:190} INFO -    ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 17.3/17.3 MB 11.4 MB/s eta 0:00:00
[2024-11-18T21:06:22.461+0000] {process_utils.py:190} INFO - Downloading opt_einsum-3.4.0-py3-none-any.whl (71 kB)
[2024-11-18T21:06:22.469+0000] {process_utils.py:190} INFO -    ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 71.9/71.9 kB 9.3 MB/s eta 0:00:00
[2024-11-18T21:06:22.478+0000] {process_utils.py:190} INFO - Downloading querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
[2024-11-18T21:06:22.482+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T21:06:22.491+0000] {process_utils.py:190} INFO - Downloading tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
[2024-11-18T21:06:23.011+0000] {process_utils.py:190} INFO -    ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 5.6/5.6 MB 10.8 MB/s eta 0:00:00
[2024-11-18T21:06:23.022+0000] {process_utils.py:190} INFO - Downloading tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
[2024-11-18T21:06:23.084+0000] {process_utils.py:190} INFO -    ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 440.8/440.8 kB 7.8 MB/s eta 0:00:00
[2024-11-18T21:06:23.093+0000] {process_utils.py:190} INFO - Downloading tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
[2024-11-18T21:06:23.363+0000] {process_utils.py:190} INFO -    ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 2.4/2.4 MB 8.9 MB/s eta 0:00:00
[2024-11-18T21:06:23.374+0000] {process_utils.py:190} INFO - Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[2024-11-18T21:06:23.386+0000] {process_utils.py:190} INFO - Downloading google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
[2024-11-18T21:06:23.398+0000] {process_utils.py:190} INFO - Downloading tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
[2024-11-18T21:06:23.989+0000] {process_utils.py:190} INFO -    ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 6.6/6.6 MB 11.2 MB/s eta 0:00:00
[2024-11-18T21:06:26.173+0000] {process_utils.py:190} INFO - Installing collected packages: libclang, flatbuffers, typing-extensions, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, querystring-parser, opt-einsum, numpy, keras, google-pasta, gast, entrypoints, astunparse, absl-py, h5py, botocore, s3transfer, google-auth-oauthlib, tensorboard, mlflow, boto3, tensorflow
[2024-11-18T21:06:26.423+0000] {process_utils.py:190} INFO -   Attempting uninstall: typing-extensions
[2024-11-18T21:06:26.425+0000] {process_utils.py:190} INFO -     Found existing installation: typing_extensions 4.9.0
[2024-11-18T21:06:26.425+0000] {process_utils.py:190} INFO -     Not uninstalling typing-extensions at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvfa2zehtd
[2024-11-18T21:06:26.426+0000] {process_utils.py:190} INFO -     Can't uninstall 'typing_extensions'. No files were found to uninstall.
[2024-11-18T21:06:26.696+0000] {process_utils.py:190} INFO -   Attempting uninstall: numpy
[2024-11-18T21:06:26.697+0000] {process_utils.py:190} INFO -     Found existing installation: numpy 1.24.4
[2024-11-18T21:06:26.697+0000] {process_utils.py:190} INFO -     Not uninstalling numpy at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvfa2zehtd
[2024-11-18T21:06:26.697+0000] {process_utils.py:190} INFO -     Can't uninstall 'numpy'. No files were found to uninstall.
[2024-11-18T21:06:28.481+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T21:06:28.482+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T21:06:28.482+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvfa2zehtd
[2024-11-18T21:06:28.482+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T21:06:28.894+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T21:06:28.895+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T21:06:28.895+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvfa2zehtd
[2024-11-18T21:06:28.896+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T21:06:28.918+0000] {process_utils.py:190} INFO -   Attempting uninstall: google-auth-oauthlib
[2024-11-18T21:06:28.919+0000] {process_utils.py:190} INFO -     Found existing installation: google-auth-oauthlib 1.2.0
[2024-11-18T21:06:28.919+0000] {process_utils.py:190} INFO -     Not uninstalling google-auth-oauthlib at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvfa2zehtd
[2024-11-18T21:06:28.919+0000] {process_utils.py:190} INFO -     Can't uninstall 'google-auth-oauthlib'. No files were found to uninstall.
[2024-11-18T21:06:29.135+0000] {process_utils.py:190} INFO -   Attempting uninstall: mlflow
[2024-11-18T21:06:29.137+0000] {process_utils.py:190} INFO -     Found existing installation: mlflow 2.17.0
[2024-11-18T21:06:29.137+0000] {process_utils.py:190} INFO -     Not uninstalling mlflow at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvfa2zehtd
[2024-11-18T21:06:29.138+0000] {process_utils.py:190} INFO -     Can't uninstall 'mlflow'. No files were found to uninstall.
[2024-11-18T21:06:29.701+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T21:06:29.702+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T21:06:29.702+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvfa2zehtd
[2024-11-18T21:06:29.703+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T21:06:36.891+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T21:06:36.891+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T21:06:36.892+0000] {process_utils.py:190} INFO - azure-core 1.29.6 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:06:36.892+0000] {process_utils.py:190} INFO - azure-mgmt-keyvault 10.3.1 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:06:36.893+0000] {process_utils.py:190} INFO - azure-mgmt-network 27.0.0 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:06:36.893+0000] {process_utils.py:190} INFO - graphene 3.4 requires typing-extensions<5,>=4.7.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:06:36.894+0000] {process_utils.py:190} INFO - pydantic 2.5.3 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:06:36.894+0000] {process_utils.py:190} INFO - pydantic-core 2.14.6 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:06:36.895+0000] {process_utils.py:190} INFO - Successfully installed absl-py-2.1.0 astunparse-1.6.3 boto3-1.28.0 botocore-1.31.85 entrypoints-0.4 flatbuffers-24.3.25 gast-0.4.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 h5py-3.11.0 keras-2.13.1 libclang-18.1.1 mlflow-2.10.2 numpy-1.24.3 opt-einsum-3.4.0 querystring-parser-1.2.4 s3transfer-0.6.2 tensorboard-2.13.0 tensorboard-data-server-0.7.2 tensorflow-2.13.0 tensorflow-estimator-2.13.0 tensorflow-io-gcs-filesystem-0.34.0 typing-extensions-4.5.0
[2024-11-18T21:06:36.969+0000] {process_utils.py:190} INFO - 
[2024-11-18T21:06:36.970+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.3.1
[2024-11-18T21:06:36.970+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T21:06:37.171+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvfa2zehtd/bin/python /tmp/venv-callod5bv0wb/script.py /tmp/venv-callod5bv0wb/script.in /tmp/venv-callod5bv0wb/script.out /tmp/venv-callod5bv0wb/string_args.txt /tmp/venv-callod5bv0wb/termination.log
[2024-11-18T21:06:37.175+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T21:06:38.203+0000] {process_utils.py:190} INFO - 2024-11-18 21:06:38.203461: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-11-18T21:06:38.204+0000] {process_utils.py:190} INFO - 2024-11-18 21:06:38.204575: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T21:06:38.227+0000] {process_utils.py:190} INFO - 2024-11-18 21:06:38.227365: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T21:06:38.227+0000] {process_utils.py:190} INFO - 2024-11-18 21:06:38.227645: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-11-18T21:06:38.228+0000] {process_utils.py:190} INFO - To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-11-18T21:06:38.815+0000] {process_utils.py:190} INFO - 2024-11-18 21:06:38.815620: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-11-18T21:06:40.023+0000] {process_utils.py:190} INFO - Epoch 1/10
[2024-11-18T21:06:40.942+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 3:40 - loss: 0.3002 48/575 [=>............................] - ETA: 0s - loss: 0.1323  106/575 [====>.........................] - ETA: 0s - loss: 0.0909187/575 [========>.....................] - ETA: 0s - loss: 0.0688271/575 [=============>................] - ETA: 0s - loss: 0.0571350/575 [=================>............] - ETA: 0s - loss: 0.0502432/575 [=====================>........] - ETA: 0s - loss: 0.0450514/575 [=========================>....] - ETA: 0s - loss: 0.0412575/575 [==============================] - 1s 932us/step - loss: 0.0389 - val_loss: 0.0067
[2024-11-18T21:06:40.942+0000] {process_utils.py:190} INFO - Epoch 2/10
[2024-11-18T21:06:41.370+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0163 84/575 [===>..........................] - ETA: 0s - loss: 0.0180168/575 [=======>......................] - ETA: 0s - loss: 0.0176249/575 [===========>..................] - ETA: 0s - loss: 0.0171334/575 [================>.............] - ETA: 0s - loss: 0.0166420/575 [====================>.........] - ETA: 0s - loss: 0.0162504/575 [=========================>....] - ETA: 0s - loss: 0.0157575/575 [==============================] - 0s 744us/step - loss: 0.0154 - val_loss: 0.0050
[2024-11-18T21:06:41.375+0000] {process_utils.py:190} INFO - Epoch 3/10
[2024-11-18T21:06:41.794+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0133 81/575 [===>..........................] - ETA: 0s - loss: 0.0122165/575 [=======>......................] - ETA: 0s - loss: 0.0122247/575 [===========>..................] - ETA: 0s - loss: 0.0121332/575 [================>.............] - ETA: 0s - loss: 0.0118419/575 [====================>.........] - ETA: 0s - loss: 0.0117503/575 [=========================>....] - ETA: 0s - loss: 0.0116575/575 [==============================] - 0s 737us/step - loss: 0.0115 - val_loss: 0.0040
[2024-11-18T21:06:41.794+0000] {process_utils.py:190} INFO - Epoch 4/10
[2024-11-18T21:06:42.210+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0091 84/575 [===>..........................] - ETA: 0s - loss: 0.0103173/575 [========>.....................] - ETA: 0s - loss: 0.0103260/575 [============>.................] - ETA: 0s - loss: 0.0103346/575 [=================>............] - ETA: 0s - loss: 0.0100430/575 [=====================>........] - ETA: 0s - loss: 0.0100514/575 [=========================>....] - ETA: 0s - loss: 0.0098575/575 [==============================] - 0s 722us/step - loss: 0.0098 - val_loss: 0.0034
[2024-11-18T21:06:42.210+0000] {process_utils.py:190} INFO - Epoch 5/10
[2024-11-18T21:06:42.645+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0088 81/575 [===>..........................] - ETA: 0s - loss: 0.0092163/575 [=======>......................] - ETA: 0s - loss: 0.0091244/575 [===========>..................] - ETA: 0s - loss: 0.0090328/575 [================>.............] - ETA: 0s - loss: 0.0088414/575 [====================>.........] - ETA: 0s - loss: 0.0087490/575 [========================>.....] - ETA: 0s - loss: 0.0086568/575 [============================>.] - ETA: 0s - loss: 0.0085575/575 [==============================] - 0s 757us/step - loss: 0.0085 - val_loss: 0.0030
[2024-11-18T21:06:42.646+0000] {process_utils.py:190} INFO - Epoch 6/10
[2024-11-18T21:06:43.092+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0063 84/575 [===>..........................] - ETA: 0s - loss: 0.0081163/575 [=======>......................] - ETA: 0s - loss: 0.0081247/575 [===========>..................] - ETA: 0s - loss: 0.0080320/575 [===============>..............] - ETA: 0s - loss: 0.0080400/575 [===================>..........] - ETA: 0s - loss: 0.0080481/575 [========================>.....] - ETA: 0s - loss: 0.0079558/575 [============================>.] - ETA: 0s - loss: 0.0079575/575 [==============================] - 0s 777us/step - loss: 0.0079 - val_loss: 0.0029
[2024-11-18T21:06:43.092+0000] {process_utils.py:190} INFO - Epoch 7/10
[2024-11-18T21:06:43.549+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0077 79/575 [===>..........................] - ETA: 0s - loss: 0.0075153/575 [======>.......................] - ETA: 0s - loss: 0.0074229/575 [==========>...................] - ETA: 0s - loss: 0.0074307/575 [===============>..............] - ETA: 0s - loss: 0.0074387/575 [===================>..........] - ETA: 0s - loss: 0.0074468/575 [=======================>......] - ETA: 0s - loss: 0.0074550/575 [===========================>..] - ETA: 0s - loss: 0.0074575/575 [==============================] - 0s 794us/step - loss: 0.0074 - val_loss: 0.0028
[2024-11-18T21:06:43.549+0000] {process_utils.py:190} INFO - Epoch 8/10
[2024-11-18T21:06:43.987+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0072 83/575 [===>..........................] - ETA: 0s - loss: 0.0074162/575 [=======>......................] - ETA: 0s - loss: 0.0074239/575 [===========>..................] - ETA: 0s - loss: 0.0073319/575 [===============>..............] - ETA: 0s - loss: 0.0073402/575 [===================>..........] - ETA: 0s - loss: 0.0073481/575 [========================>.....] - ETA: 0s - loss: 0.0072566/575 [============================>.] - ETA: 0s - loss: 0.0072575/575 [==============================] - 0s 761us/step - loss: 0.0072 - val_loss: 0.0027
[2024-11-18T21:06:43.987+0000] {process_utils.py:190} INFO - Epoch 9/10
[2024-11-18T21:06:44.439+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0092 81/575 [===>..........................] - ETA: 0s - loss: 0.0070162/575 [=======>......................] - ETA: 0s - loss: 0.0069242/575 [===========>..................] - ETA: 0s - loss: 0.0069319/575 [===============>..............] - ETA: 0s - loss: 0.0069391/575 [===================>..........] - ETA: 0s - loss: 0.0069468/575 [=======================>......] - ETA: 0s - loss: 0.0069547/575 [===========================>..] - ETA: 0s - loss: 0.0069575/575 [==============================] - 0s 785us/step - loss: 0.0069 - val_loss: 0.0025
[2024-11-18T21:06:44.439+0000] {process_utils.py:190} INFO - Epoch 10/10
[2024-11-18T21:06:44.910+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0074 78/575 [===>..........................] - ETA: 0s - loss: 0.0067156/575 [=======>......................] - ETA: 0s - loss: 0.0068232/575 [===========>..................] - ETA: 0s - loss: 0.0067306/575 [==============>...............] - ETA: 0s - loss: 0.0068379/575 [==================>...........] - ETA: 0s - loss: 0.0068453/575 [======================>.......] - ETA: 0s - loss: 0.0068522/575 [==========================>...] - ETA: 0s - loss: 0.0068575/575 [==============================] - 0s 819us/step - loss: 0.0068 - val_loss: 0.0023
[2024-11-18T21:06:45.321+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 30s 98/719 [===>..........................] - ETA: 0s 202/719 [=======>......................] - ETA: 0s318/719 [============>.................] - ETA: 0s428/719 [================>.............] - ETA: 0s526/719 [====================>.........] - ETA: 0s621/719 [========================>.....] - ETA: 0s719/719 [==============================] - 0s 487us/step
[2024-11-18T21:06:46.451+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 9s 91/719 [==>...........................] - ETA: 0s195/719 [=======>......................] - ETA: 0s300/719 [===========>..................] - ETA: 0s398/719 [===============>..............] - ETA: 0s501/719 [===================>..........] - ETA: 0s608/719 [========================>.....] - ETA: 0s710/719 [============================>.] - ETA: 0s719/719 [==============================] - 0s 495us/step
[2024-11-18T21:06:46.771+0000] {process_utils.py:190} INFO - 2024/11/18 21:06:46 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.
[2024-11-18T21:06:47.130+0000] {process_utils.py:190} INFO - [[34m2024-11-18T21:06:47.121+0000[0m] {[34mbuilder_impl.py:[0m804} INFO[0m - Assets written to: /tmp/tmp0f9t2nal/model/data/model/assets[0m
[2024-11-18T21:06:49.756+0000] {process_utils.py:190} INFO - /tmp/venvfa2zehtd/lib/python3.8/site-packages/_distutils_hack/__init__.py:33 UserWarning: Setuptools is replacing distutils.
[2024-11-18T21:06:50.027+0000] {process_utils.py:190} INFO - [[34m2024-11-18T21:06:50.027+0000[0m] {[34mcredentials.py:[0m1124} INFO[0m - Found credentials in environment variables.[0m
[2024-11-18T21:06:50.222+0000] {process_utils.py:190} INFO - Registered model 'spotify_model_prod' already exists. Creating a new version of this model...
[2024-11-18T21:06:50.223+0000] {process_utils.py:190} INFO - 2024/11/18 21:06:50 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: spotify_model_prod, version 12
[2024-11-18T21:06:50.223+0000] {process_utils.py:190} INFO - Created version '12' of model 'spotify_model_prod'.
[2024-11-18T21:06:50.224+0000] {process_utils.py:190} INFO - /tmp/venvfa2zehtd/lib/python3.8/site-packages/keras/src/engine/training.py:3000 UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
[2024-11-18T21:06:50.250+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-11-18T21:06:50.250+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callod5bv0wb/script.py", line 102, in <module>
[2024-11-18T21:06:50.250+0000] {process_utils.py:190} INFO -     res = train_challenger_model(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-18T21:06:50.251+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callod5bv0wb/script.py", line 95, in train_challenger_model
[2024-11-18T21:06:50.251+0000] {process_utils.py:190} INFO -     with open(embeddings_path, 'w') as f:
[2024-11-18T21:06:50.251+0000] {process_utils.py:190} INFO - FileNotFoundError: [Errno 2] No such file or directory: 'data_info/song_embeddings.json'
[2024-11-18T21:06:51.232+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
[Errno 2] No such file or directory: 'data_info/song_embeddings.json'
[2024-11-18T21:06:51.236+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_retrain_challenge_model_v3, task_id=train_challenger_model, execution_date=20241118T210526, start_date=20241118T210526, end_date=20241118T210651
[2024-11-18T21:06:51.244+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 125 for task train_challenger_model (Process returned non-zero exit status 1.
[Errno 2] No such file or directory: 'data_info/song_embeddings.json'; 575)
[2024-11-18T21:06:51.276+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-18T21:06:51.289+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
