[2024-11-18T18:11:20.288+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:11:19.639154+00:00 [queued]>
[2024-11-18T18:11:20.292+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:11:19.639154+00:00 [queued]>
[2024-11-18T18:11:20.293+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-11-18T18:11:20.300+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_challenger_model> on 2024-11-18 18:11:19.639154+00:00
[2024-11-18T18:11:20.303+0000] {standard_task_runner.py:60} INFO - Started process 5044 to run task
[2024-11-18T18:11:20.304+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_retrain_challenge_model_v3', 'train_challenger_model', 'manual__2024-11-18T18:11:19.639154+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/retrain_music_model.py', '--cfg-path', '/tmp/tmpe4_0dg20']
[2024-11-18T18:11:20.305+0000] {standard_task_runner.py:88} INFO - Job 73: Subtask train_challenger_model
[2024-11-18T18:11:20.330+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:11:19.639154+00:00 [running]> on host 98017b53a184
[2024-11-18T18:11:20.368+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_retrain_challenge_model_v3' AIRFLOW_CTX_TASK_ID='train_challenger_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T18:11:19.639154+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T18:11:19.639154+00:00'
[2024-11-18T18:11:20.370+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv6csr8w8j --system-site-packages --python=python
[2024-11-18T18:11:20.373+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:11:20.703+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 117ms
[2024-11-18T18:11:20.704+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venv6csr8w8j, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T18:11:20.704+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T18:11:20.704+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-11-18T18:11:20.704+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T18:11:20.721+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv6csr8w8j/bin/pip install -r /tmp/venv6csr8w8j/requirements.txt
[2024-11-18T18:11:20.725+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:11:21.676+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venv6csr8w8j/requirements.txt (line 1))
[2024-11-18T18:11:21.677+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T18:11:21.713+0000] {process_utils.py:190} INFO - Collecting mlflow==2.10.2 (from -r /tmp/venv6csr8w8j/requirements.txt (line 2))
[2024-11-18T18:11:21.714+0000] {process_utils.py:190} INFO -   Using cached mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
[2024-11-18T18:11:21.715+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv6csr8w8j/requirements.txt (line 3)) (2.0.3)
[2024-11-18T18:11:21.716+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn==1.3.2 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv6csr8w8j/requirements.txt (line 4)) (1.3.2)
[2024-11-18T18:11:21.819+0000] {process_utils.py:190} INFO - Collecting tensorflow==2.13.0 (from -r /tmp/venv6csr8w8j/requirements.txt (line 5))
[2024-11-18T18:11:21.821+0000] {process_utils.py:190} INFO -   Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
[2024-11-18T18:11:22.216+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venv6csr8w8j/requirements.txt (line 1))
[2024-11-18T18:11:22.217+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T18:11:22.218+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venv6csr8w8j/requirements.txt (line 1)) (0.10.0)
[2024-11-18T18:11:22.256+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venv6csr8w8j/requirements.txt (line 1))
[2024-11-18T18:11:22.258+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:11:22.311+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (8.1.7)
[2024-11-18T18:11:22.312+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (3.1.0)
[2024-11-18T18:11:22.327+0000] {process_utils.py:190} INFO - Collecting entrypoints<1 (from mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2))
[2024-11-18T18:11:22.328+0000] {process_utils.py:190} INFO -   Using cached entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
[2024-11-18T18:11:22.329+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=2.1.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (3.1.43)
[2024-11-18T18:11:22.330+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (6.0.1)
[2024-11-18T18:11:22.330+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<5,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (4.25.2)
[2024-11-18T18:11:22.331+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz<2024 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T18:11:22.331+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (2.31.0)
[2024-11-18T18:11:22.332+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (23.2)
[2024-11-18T18:11:22.332+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (6.11.0)
[2024-11-18T18:11:22.332+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (0.4.4)
[2024-11-18T18:11:22.333+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (1.13.1)
[2024-11-18T18:11:22.334+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (7.0.0)
[2024-11-18T18:11:22.334+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (2.2.5)
[2024-11-18T18:11:22.334+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (1.24.4)
[2024-11-18T18:11:22.335+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (1.10.1)
[2024-11-18T18:11:22.350+0000] {process_utils.py:190} INFO - Collecting querystring-parser<2 (from mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2))
[2024-11-18T18:11:22.352+0000] {process_utils.py:190} INFO -   Using cached querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
[2024-11-18T18:11:22.352+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (1.4.51)
[2024-11-18T18:11:22.353+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow<16,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (14.0.2)
[2024-11-18T18:11:22.354+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (3.5.2)
[2024-11-18T18:11:22.354+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (3.7.5)
[2024-11-18T18:11:22.355+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<22 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (21.2.0)
[2024-11-18T18:11:22.356+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (3.1.3)
[2024-11-18T18:11:22.411+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venv6csr8w8j/requirements.txt (line 3)) (2.8.2)
[2024-11-18T18:11:22.412+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venv6csr8w8j/requirements.txt (line 3)) (2023.4)
[2024-11-18T18:11:22.433+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venv6csr8w8j/requirements.txt (line 4)) (1.4.2)
[2024-11-18T18:11:22.433+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venv6csr8w8j/requirements.txt (line 4)) (3.5.0)
[2024-11-18T18:11:22.467+0000] {process_utils.py:190} INFO - Collecting absl-py>=1.0.0 (from tensorflow==2.13.0->-r /tmp/venv6csr8w8j/requirements.txt (line 5))
[2024-11-18T18:11:22.469+0000] {process_utils.py:190} INFO -   Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
[2024-11-18T18:11:22.485+0000] {process_utils.py:190} INFO - Collecting astunparse>=1.6.0 (from tensorflow==2.13.0->-r /tmp/venv6csr8w8j/requirements.txt (line 5))
[2024-11-18T18:11:22.486+0000] {process_utils.py:190} INFO -   Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
[2024-11-18T18:11:22.504+0000] {process_utils.py:190} INFO - Collecting flatbuffers>=23.1.21 (from tensorflow==2.13.0->-r /tmp/venv6csr8w8j/requirements.txt (line 5))
[2024-11-18T18:11:22.505+0000] {process_utils.py:190} INFO -   Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
[2024-11-18T18:11:22.524+0000] {process_utils.py:190} INFO - Collecting gast<=0.4.0,>=0.2.1 (from tensorflow==2.13.0->-r /tmp/venv6csr8w8j/requirements.txt (line 5))
[2024-11-18T18:11:22.525+0000] {process_utils.py:190} INFO -   Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
[2024-11-18T18:11:22.543+0000] {process_utils.py:190} INFO - Collecting google-pasta>=0.1.1 (from tensorflow==2.13.0->-r /tmp/venv6csr8w8j/requirements.txt (line 5))
[2024-11-18T18:11:22.544+0000] {process_utils.py:190} INFO -   Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
[2024-11-18T18:11:22.545+0000] {process_utils.py:190} INFO - Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv6csr8w8j/requirements.txt (line 5)) (1.60.0)
[2024-11-18T18:11:22.586+0000] {process_utils.py:190} INFO - Collecting h5py>=2.9.0 (from tensorflow==2.13.0->-r /tmp/venv6csr8w8j/requirements.txt (line 5))
[2024-11-18T18:11:22.587+0000] {process_utils.py:190} INFO -   Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
[2024-11-18T18:11:22.616+0000] {process_utils.py:190} INFO - Collecting keras<2.14,>=2.13.1 (from tensorflow==2.13.0->-r /tmp/venv6csr8w8j/requirements.txt (line 5))
[2024-11-18T18:11:22.617+0000] {process_utils.py:190} INFO -   Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
[2024-11-18T18:11:22.638+0000] {process_utils.py:190} INFO - Collecting libclang>=13.0.0 (from tensorflow==2.13.0->-r /tmp/venv6csr8w8j/requirements.txt (line 5))
[2024-11-18T18:11:22.640+0000] {process_utils.py:190} INFO -   Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
[2024-11-18T18:11:22.792+0000] {process_utils.py:190} INFO - Collecting numpy<2 (from mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2))
[2024-11-18T18:11:22.794+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-11-18T18:11:22.810+0000] {process_utils.py:190} INFO - Collecting opt-einsum>=2.3.2 (from tensorflow==2.13.0->-r /tmp/venv6csr8w8j/requirements.txt (line 5))
[2024-11-18T18:11:22.812+0000] {process_utils.py:190} INFO -   Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
[2024-11-18T18:11:22.813+0000] {process_utils.py:190} INFO - Requirement already satisfied: setuptools in /tmp/venv6csr8w8j/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv6csr8w8j/requirements.txt (line 5)) (69.0.2)
[2024-11-18T18:11:22.813+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.12.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv6csr8w8j/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:11:22.838+0000] {process_utils.py:190} INFO - Collecting tensorboard<2.14,>=2.13 (from tensorflow==2.13.0->-r /tmp/venv6csr8w8j/requirements.txt (line 5))
[2024-11-18T18:11:22.840+0000] {process_utils.py:190} INFO -   Using cached tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:11:22.858+0000] {process_utils.py:190} INFO - Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow==2.13.0->-r /tmp/venv6csr8w8j/requirements.txt (line 5))
[2024-11-18T18:11:22.859+0000] {process_utils.py:190} INFO -   Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
[2024-11-18T18:11:22.860+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.1.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv6csr8w8j/requirements.txt (line 5)) (2.4.0)
[2024-11-18T18:11:22.907+0000] {process_utils.py:190} INFO - Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow==2.13.0->-r /tmp/venv6csr8w8j/requirements.txt (line 5))
[2024-11-18T18:11:22.908+0000] {process_utils.py:190} INFO -   Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
[2024-11-18T18:11:22.909+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt>=1.11.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv6csr8w8j/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:11:22.942+0000] {process_utils.py:190} INFO - Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow==2.13.0->-r /tmp/venv6csr8w8j/requirements.txt (line 5))
[2024-11-18T18:11:22.944+0000] {process_utils.py:190} INFO -   Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
[2024-11-18T18:11:22.952+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (1.3.0)
[2024-11-18T18:11:22.956+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (5.13.0)
[2024-11-18T18:11:22.959+0000] {process_utils.py:190} INFO - Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venv6csr8w8j/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow==2.13.0->-r /tmp/venv6csr8w8j/requirements.txt (line 5)) (0.42.0)
[2024-11-18T18:11:22.964+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venv6csr8w8j/requirements.txt (line 1)) (1.26.18)
[2024-11-18T18:11:22.978+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (2.2.3)
[2024-11-18T18:11:22.979+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (2.1.2)
[2024-11-18T18:11:22.996+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (4.0.11)
[2024-11-18T18:11:23.021+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (3.17.0)
[2024-11-18T18:11:23.024+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (2.1.3)
[2024-11-18T18:11:23.048+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (1.1.1)
[2024-11-18T18:11:23.049+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (0.12.1)
[2024-11-18T18:11:23.050+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (4.54.1)
[2024-11-18T18:11:23.050+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (1.4.7)
[2024-11-18T18:11:23.061+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (10.4.0)
[2024-11-18T18:11:23.061+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (3.1.1)
[2024-11-18T18:11:23.108+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (3.3.2)
[2024-11-18T18:11:23.109+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (3.6)
[2024-11-18T18:11:23.109+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (2023.11.17)
[2024-11-18T18:11:23.295+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (3.0.3)
[2024-11-18T18:11:23.314+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth<3,>=1.6.3 in /home/***/.local/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv6csr8w8j/requirements.txt (line 5)) (2.26.2)
[2024-11-18T18:11:23.343+0000] {process_utils.py:190} INFO - Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv6csr8w8j/requirements.txt (line 5))
[2024-11-18T18:11:23.344+0000] {process_utils.py:190} INFO -   Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
[2024-11-18T18:11:23.378+0000] {process_utils.py:190} INFO - Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv6csr8w8j/requirements.txt (line 5))
[2024-11-18T18:11:23.379+0000] {process_utils.py:190} INFO -   Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
[2024-11-18T18:11:23.526+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venv6csr8w8j/requirements.txt (line 2)) (5.0.1)
[2024-11-18T18:11:23.537+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv6csr8w8j/requirements.txt (line 5)) (5.3.2)
[2024-11-18T18:11:23.537+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv6csr8w8j/requirements.txt (line 5)) (0.3.0)
[2024-11-18T18:11:23.538+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv6csr8w8j/requirements.txt (line 5)) (4.9)
[2024-11-18T18:11:23.544+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv6csr8w8j/requirements.txt (line 5)) (1.3.1)
[2024-11-18T18:11:23.674+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv6csr8w8j/requirements.txt (line 5)) (0.5.1)
[2024-11-18T18:11:23.682+0000] {process_utils.py:190} INFO - Requirement already satisfied: oauthlib>=3.0.0 in /home/***/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv6csr8w8j/requirements.txt (line 5)) (3.2.2)
[2024-11-18T18:11:23.718+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T18:11:23.720+0000] {process_utils.py:190} INFO - Using cached mlflow-2.10.2-py3-none-any.whl (19.5 MB)
[2024-11-18T18:11:23.742+0000] {process_utils.py:190} INFO - Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
[2024-11-18T18:11:24.252+0000] {process_utils.py:190} INFO - Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
[2024-11-18T18:11:24.253+0000] {process_utils.py:190} INFO - Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
[2024-11-18T18:11:24.254+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T18:11:24.268+0000] {process_utils.py:190} INFO - Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
[2024-11-18T18:11:24.269+0000] {process_utils.py:190} INFO - Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
[2024-11-18T18:11:24.270+0000] {process_utils.py:190} INFO - Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
[2024-11-18T18:11:24.271+0000] {process_utils.py:190} INFO - Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
[2024-11-18T18:11:24.272+0000] {process_utils.py:190} INFO - Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
[2024-11-18T18:11:24.279+0000] {process_utils.py:190} INFO - Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)
[2024-11-18T18:11:24.282+0000] {process_utils.py:190} INFO - Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
[2024-11-18T18:11:24.311+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-11-18T18:11:24.334+0000] {process_utils.py:190} INFO - Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
[2024-11-18T18:11:24.335+0000] {process_utils.py:190} INFO - Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
[2024-11-18T18:11:24.336+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T18:11:24.338+0000] {process_utils.py:190} INFO - Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
[2024-11-18T18:11:24.347+0000] {process_utils.py:190} INFO - Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
[2024-11-18T18:11:24.348+0000] {process_utils.py:190} INFO - Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
[2024-11-18T18:11:24.353+0000] {process_utils.py:190} INFO - Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[2024-11-18T18:11:24.354+0000] {process_utils.py:190} INFO - Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
[2024-11-18T18:11:24.355+0000] {process_utils.py:190} INFO - Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
[2024-11-18T18:11:26.495+0000] {process_utils.py:190} INFO - Installing collected packages: libclang, flatbuffers, typing-extensions, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, querystring-parser, opt-einsum, numpy, keras, google-pasta, gast, entrypoints, astunparse, absl-py, h5py, botocore, s3transfer, google-auth-oauthlib, tensorboard, mlflow, boto3, tensorflow
[2024-11-18T18:11:26.739+0000] {process_utils.py:190} INFO -   Attempting uninstall: typing-extensions
[2024-11-18T18:11:26.741+0000] {process_utils.py:190} INFO -     Found existing installation: typing_extensions 4.9.0
[2024-11-18T18:11:26.741+0000] {process_utils.py:190} INFO -     Not uninstalling typing-extensions at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv6csr8w8j
[2024-11-18T18:11:26.741+0000] {process_utils.py:190} INFO -     Can't uninstall 'typing_extensions'. No files were found to uninstall.
[2024-11-18T18:11:27.010+0000] {process_utils.py:190} INFO -   Attempting uninstall: numpy
[2024-11-18T18:11:27.011+0000] {process_utils.py:190} INFO -     Found existing installation: numpy 1.24.4
[2024-11-18T18:11:27.011+0000] {process_utils.py:190} INFO -     Not uninstalling numpy at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv6csr8w8j
[2024-11-18T18:11:27.012+0000] {process_utils.py:190} INFO -     Can't uninstall 'numpy'. No files were found to uninstall.
[2024-11-18T18:11:28.663+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T18:11:28.663+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T18:11:28.664+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv6csr8w8j
[2024-11-18T18:11:28.664+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T18:11:29.067+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T18:11:29.069+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T18:11:29.069+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv6csr8w8j
[2024-11-18T18:11:29.069+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T18:11:29.090+0000] {process_utils.py:190} INFO -   Attempting uninstall: google-auth-oauthlib
[2024-11-18T18:11:29.091+0000] {process_utils.py:190} INFO -     Found existing installation: google-auth-oauthlib 1.2.0
[2024-11-18T18:11:29.091+0000] {process_utils.py:190} INFO -     Not uninstalling google-auth-oauthlib at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv6csr8w8j
[2024-11-18T18:11:29.092+0000] {process_utils.py:190} INFO -     Can't uninstall 'google-auth-oauthlib'. No files were found to uninstall.
[2024-11-18T18:11:29.294+0000] {process_utils.py:190} INFO -   Attempting uninstall: mlflow
[2024-11-18T18:11:29.295+0000] {process_utils.py:190} INFO -     Found existing installation: mlflow 2.17.0
[2024-11-18T18:11:29.296+0000] {process_utils.py:190} INFO -     Not uninstalling mlflow at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv6csr8w8j
[2024-11-18T18:11:29.296+0000] {process_utils.py:190} INFO -     Can't uninstall 'mlflow'. No files were found to uninstall.
[2024-11-18T18:11:29.850+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T18:11:29.851+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T18:11:29.852+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv6csr8w8j
[2024-11-18T18:11:29.852+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T18:11:36.958+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T18:11:36.959+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T18:11:36.960+0000] {process_utils.py:190} INFO - azure-core 1.29.6 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:11:36.961+0000] {process_utils.py:190} INFO - azure-mgmt-keyvault 10.3.1 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:11:36.961+0000] {process_utils.py:190} INFO - azure-mgmt-network 27.0.0 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:11:36.961+0000] {process_utils.py:190} INFO - graphene 3.4 requires typing-extensions<5,>=4.7.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:11:36.962+0000] {process_utils.py:190} INFO - pydantic 2.5.3 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:11:36.962+0000] {process_utils.py:190} INFO - pydantic-core 2.14.6 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:11:36.962+0000] {process_utils.py:190} INFO - Successfully installed absl-py-2.1.0 astunparse-1.6.3 boto3-1.28.0 botocore-1.31.85 entrypoints-0.4 flatbuffers-24.3.25 gast-0.4.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 h5py-3.11.0 keras-2.13.1 libclang-18.1.1 mlflow-2.10.2 numpy-1.24.3 opt-einsum-3.4.0 querystring-parser-1.2.4 s3transfer-0.6.2 tensorboard-2.13.0 tensorboard-data-server-0.7.2 tensorflow-2.13.0 tensorflow-estimator-2.13.0 tensorflow-io-gcs-filesystem-0.34.0 typing-extensions-4.5.0
[2024-11-18T18:11:37.036+0000] {process_utils.py:190} INFO - 
[2024-11-18T18:11:37.036+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.3.1
[2024-11-18T18:11:37.037+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T18:11:37.221+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv6csr8w8j/bin/python /tmp/venv-callf1jyojln/script.py /tmp/venv-callf1jyojln/script.in /tmp/venv-callf1jyojln/script.out /tmp/venv-callf1jyojln/string_args.txt /tmp/venv-callf1jyojln/termination.log
[2024-11-18T18:11:37.225+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:11:38.191+0000] {process_utils.py:190} INFO - 2024-11-18 18:11:38.191497: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-11-18T18:11:38.192+0000] {process_utils.py:190} INFO - 2024-11-18 18:11:38.192548: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T18:11:38.213+0000] {process_utils.py:190} INFO - 2024-11-18 18:11:38.213543: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T18:11:38.214+0000] {process_utils.py:190} INFO - 2024-11-18 18:11:38.213818: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-11-18T18:11:38.214+0000] {process_utils.py:190} INFO - To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-11-18T18:11:38.705+0000] {process_utils.py:190} INFO - 2024-11-18 18:11:38.705875: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-11-18T18:11:39.758+0000] {process_utils.py:190} INFO - Epoch 1/10
[2024-11-18T18:11:40.632+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 3:28 - loss: 0.4255 57/575 [=>............................] - ETA: 0s - loss: 0.1695  127/575 [=====>........................] - ETA: 0s - loss: 0.1120209/575 [=========>....................] - ETA: 0s - loss: 0.0853290/575 [==============>...............] - ETA: 0s - loss: 0.0713375/575 [==================>...........] - ETA: 0s - loss: 0.0620460/575 [=======================>......] - ETA: 0s - loss: 0.0553543/575 [===========================>..] - ETA: 0s - loss: 0.0503575/575 [==============================] - 1s 890us/step - loss: 0.0487 - val_loss: 0.0075
[2024-11-18T18:11:40.632+0000] {process_utils.py:190} INFO - Epoch 2/10
[2024-11-18T18:11:41.072+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0242 79/575 [===>..........................] - ETA: 0s - loss: 0.0206159/575 [=======>......................] - ETA: 0s - loss: 0.0197238/575 [===========>..................] - ETA: 0s - loss: 0.0189315/575 [===============>..............] - ETA: 0s - loss: 0.0184396/575 [===================>..........] - ETA: 0s - loss: 0.0178476/575 [=======================>......] - ETA: 0s - loss: 0.0175553/575 [===========================>..] - ETA: 0s - loss: 0.0171575/575 [==============================] - 0s 765us/step - loss: 0.0170 - val_loss: 0.0058
[2024-11-18T18:11:41.072+0000] {process_utils.py:190} INFO - Epoch 3/10
[2024-11-18T18:11:41.514+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0102 69/575 [==>...........................] - ETA: 0s - loss: 0.0137152/575 [======>.......................] - ETA: 0s - loss: 0.0136238/575 [===========>..................] - ETA: 0s - loss: 0.0135316/575 [===============>..............] - ETA: 0s - loss: 0.0133397/575 [===================>..........] - ETA: 0s - loss: 0.0129478/575 [=======================>......] - ETA: 0s - loss: 0.0127558/575 [============================>.] - ETA: 0s - loss: 0.0124575/575 [==============================] - 0s 769us/step - loss: 0.0123 - val_loss: 0.0042
[2024-11-18T18:11:41.515+0000] {process_utils.py:190} INFO - Epoch 4/10
[2024-11-18T18:11:41.947+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0127 81/575 [===>..........................] - ETA: 0s - loss: 0.0105164/575 [=======>......................] - ETA: 0s - loss: 0.0102243/575 [===========>..................] - ETA: 0s - loss: 0.0100325/575 [===============>..............] - ETA: 0s - loss: 0.0099406/575 [====================>.........] - ETA: 0s - loss: 0.0098487/575 [========================>.....] - ETA: 0s - loss: 0.0097567/575 [============================>.] - ETA: 0s - loss: 0.0096575/575 [==============================] - 0s 751us/step - loss: 0.0096 - val_loss: 0.0030
[2024-11-18T18:11:41.948+0000] {process_utils.py:190} INFO - Epoch 5/10
[2024-11-18T18:11:42.390+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0080 81/575 [===>..........................] - ETA: 0s - loss: 0.0086158/575 [=======>......................] - ETA: 0s - loss: 0.0086243/575 [===========>..................] - ETA: 0s - loss: 0.0086314/575 [===============>..............] - ETA: 0s - loss: 0.0085395/575 [===================>..........] - ETA: 0s - loss: 0.0085471/575 [=======================>......] - ETA: 0s - loss: 0.0084548/575 [===========================>..] - ETA: 0s - loss: 0.0083575/575 [==============================] - 0s 770us/step - loss: 0.0083 - val_loss: 0.0031
[2024-11-18T18:11:42.391+0000] {process_utils.py:190} INFO - Epoch 6/10
[2024-11-18T18:11:42.825+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0062 84/575 [===>..........................] - ETA: 0s - loss: 0.0079164/575 [=======>......................] - ETA: 0s - loss: 0.0079244/575 [===========>..................] - ETA: 0s - loss: 0.0077321/575 [===============>..............] - ETA: 0s - loss: 0.0077402/575 [===================>..........] - ETA: 0s - loss: 0.0076482/575 [========================>.....] - ETA: 0s - loss: 0.0076562/575 [============================>.] - ETA: 0s - loss: 0.0076575/575 [==============================] - 0s 754us/step - loss: 0.0076 - val_loss: 0.0028
[2024-11-18T18:11:42.825+0000] {process_utils.py:190} INFO - Epoch 7/10
[2024-11-18T18:11:43.261+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0069 75/575 [==>...........................] - ETA: 0s - loss: 0.0074154/575 [=======>......................] - ETA: 0s - loss: 0.0073235/575 [===========>..................] - ETA: 0s - loss: 0.0072313/575 [===============>..............] - ETA: 0s - loss: 0.0072394/575 [===================>..........] - ETA: 0s - loss: 0.0073476/575 [=======================>......] - ETA: 0s - loss: 0.0072558/575 [============================>.] - ETA: 0s - loss: 0.0071575/575 [==============================] - 0s 758us/step - loss: 0.0071 - val_loss: 0.0027
[2024-11-18T18:11:43.261+0000] {process_utils.py:190} INFO - Epoch 8/10
[2024-11-18T18:11:43.694+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0057 80/575 [===>..........................] - ETA: 0s - loss: 0.0069159/575 [=======>......................] - ETA: 0s - loss: 0.0068240/575 [===========>..................] - ETA: 0s - loss: 0.0070322/575 [===============>..............] - ETA: 0s - loss: 0.0069404/575 [====================>.........] - ETA: 0s - loss: 0.0069485/575 [========================>.....] - ETA: 0s - loss: 0.0069567/575 [============================>.] - ETA: 0s - loss: 0.0069575/575 [==============================] - 0s 753us/step - loss: 0.0069 - val_loss: 0.0024
[2024-11-18T18:11:43.695+0000] {process_utils.py:190} INFO - Epoch 9/10
[2024-11-18T18:11:44.129+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0065 81/575 [===>..........................] - ETA: 0s - loss: 0.0069160/575 [=======>......................] - ETA: 0s - loss: 0.0068243/575 [===========>..................] - ETA: 0s - loss: 0.0067325/575 [===============>..............] - ETA: 0s - loss: 0.0067405/575 [====================>.........] - ETA: 0s - loss: 0.0067481/575 [========================>.....] - ETA: 0s - loss: 0.0066568/575 [============================>.] - ETA: 0s - loss: 0.0066575/575 [==============================] - 0s 756us/step - loss: 0.0067 - val_loss: 0.0022
[2024-11-18T18:11:44.129+0000] {process_utils.py:190} INFO - Epoch 10/10
[2024-11-18T18:11:44.559+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0063 80/575 [===>..........................] - ETA: 0s - loss: 0.0066168/575 [=======>......................] - ETA: 0s - loss: 0.0064248/575 [===========>..................] - ETA: 0s - loss: 0.0064329/575 [================>.............] - ETA: 0s - loss: 0.0065409/575 [====================>.........] - ETA: 0s - loss: 0.0065490/575 [========================>.....] - ETA: 0s - loss: 0.0065572/575 [============================>.] - ETA: 0s - loss: 0.0065575/575 [==============================] - 0s 746us/step - loss: 0.0065 - val_loss: 0.0020
[2024-11-18T18:11:44.933+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 29s107/719 [===>..........................] - ETA: 0s 224/719 [========>.....................] - ETA: 0s344/719 [=============>................] - ETA: 0s460/719 [==================>...........] - ETA: 0s573/719 [======================>.......] - ETA: 0s688/719 [===========================>..] - ETA: 0s719/719 [==============================] - 0s 438us/step
[2024-11-18T18:11:45.477+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 7s103/719 [===>..........................] - ETA: 0s211/719 [=======>......................] - ETA: 0s315/719 [============>.................] - ETA: 0s437/719 [=================>............] - ETA: 0s559/719 [======================>.......] - ETA: 0s669/719 [==========================>...] - ETA: 0s719/719 [==============================] - 0s 452us/step
[2024-11-18T18:11:45.567+0000] {process_utils.py:190} INFO - /tmp/venv6csr8w8j/lib/python3.8/site-packages/keras/src/engine/training.py:3000 UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
[2024-11-18T18:11:45.577+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-11-18T18:11:45.577+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callf1jyojln/script.py", line 96, in <module>
[2024-11-18T18:11:45.578+0000] {process_utils.py:190} INFO -     res = train_challenger_model(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-18T18:11:45.578+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callf1jyojln/script.py", line 82, in train_challenger_model
[2024-11-18T18:11:45.578+0000] {process_utils.py:190} INFO -     model.save(model_path)
[2024-11-18T18:11:45.578+0000] {process_utils.py:190} INFO -   File "/tmp/venv6csr8w8j/lib/python3.8/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
[2024-11-18T18:11:45.578+0000] {process_utils.py:190} INFO -     raise e.with_traceback(filtered_tb) from None
[2024-11-18T18:11:45.579+0000] {process_utils.py:190} INFO -   File "/tmp/venv6csr8w8j/lib/python3.8/site-packages/tensorflow/python/lib/io/file_io.py", line 513, in recursive_create_dir_v2
[2024-11-18T18:11:45.579+0000] {process_utils.py:190} INFO -     _pywrap_file_io.RecursivelyCreateDir(compat.path_to_bytes(path))
[2024-11-18T18:11:45.579+0000] {process_utils.py:190} INFO - tensorflow.python.framework.errors_impl.PermissionDeniedError: /models; Permission denied
[2024-11-18T18:11:46.457+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
/models; Permission denied
[2024-11-18T18:11:46.460+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_retrain_challenge_model_v3, task_id=train_challenger_model, execution_date=20241118T181119, start_date=20241118T181120, end_date=20241118T181146
[2024-11-18T18:11:46.484+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 73 for task train_challenger_model (Process returned non-zero exit status 1.
/models; Permission denied; 5044)
[2024-11-18T18:11:46.498+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-18T18:11:46.510+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
