[2024-11-18T18:16:47.593+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:11:19.639154+00:00 [queued]>
[2024-11-18T18:16:47.597+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:11:19.639154+00:00 [queued]>
[2024-11-18T18:16:47.597+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-11-18T18:16:47.605+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_challenger_model> on 2024-11-18 18:11:19.639154+00:00
[2024-11-18T18:16:47.608+0000] {standard_task_runner.py:60} INFO - Started process 8254 to run task
[2024-11-18T18:16:47.609+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_retrain_challenge_model_v3', 'train_challenger_model', 'manual__2024-11-18T18:11:19.639154+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/retrain_music_model.py', '--cfg-path', '/tmp/tmpirnw1xs1']
[2024-11-18T18:16:47.610+0000] {standard_task_runner.py:88} INFO - Job 78: Subtask train_challenger_model
[2024-11-18T18:16:47.634+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:11:19.639154+00:00 [running]> on host 98017b53a184
[2024-11-18T18:16:47.670+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_retrain_challenge_model_v3' AIRFLOW_CTX_TASK_ID='train_challenger_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T18:11:19.639154+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T18:11:19.639154+00:00'
[2024-11-18T18:16:47.671+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv1n4q6hf7 --system-site-packages --python=python
[2024-11-18T18:16:47.674+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:16:48.002+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 114ms
[2024-11-18T18:16:48.003+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venv1n4q6hf7, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T18:16:48.003+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T18:16:48.004+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-11-18T18:16:48.004+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T18:16:48.020+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv1n4q6hf7/bin/pip install -r /tmp/venv1n4q6hf7/requirements.txt
[2024-11-18T18:16:48.024+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:16:48.963+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venv1n4q6hf7/requirements.txt (line 1))
[2024-11-18T18:16:48.964+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T18:16:49.001+0000] {process_utils.py:190} INFO - Collecting mlflow==2.10.2 (from -r /tmp/venv1n4q6hf7/requirements.txt (line 2))
[2024-11-18T18:16:49.003+0000] {process_utils.py:190} INFO -   Using cached mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
[2024-11-18T18:16:49.004+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv1n4q6hf7/requirements.txt (line 3)) (2.0.3)
[2024-11-18T18:16:49.004+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn==1.3.2 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv1n4q6hf7/requirements.txt (line 4)) (1.3.2)
[2024-11-18T18:16:49.103+0000] {process_utils.py:190} INFO - Collecting tensorflow==2.13.0 (from -r /tmp/venv1n4q6hf7/requirements.txt (line 5))
[2024-11-18T18:16:49.104+0000] {process_utils.py:190} INFO -   Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
[2024-11-18T18:16:49.493+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 1))
[2024-11-18T18:16:49.494+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T18:16:49.495+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 1)) (0.10.0)
[2024-11-18T18:16:49.519+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 1))
[2024-11-18T18:16:49.520+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:16:49.582+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (8.1.7)
[2024-11-18T18:16:49.582+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (3.1.0)
[2024-11-18T18:16:49.601+0000] {process_utils.py:190} INFO - Collecting entrypoints<1 (from mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2))
[2024-11-18T18:16:49.602+0000] {process_utils.py:190} INFO -   Using cached entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
[2024-11-18T18:16:49.603+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=2.1.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (3.1.43)
[2024-11-18T18:16:49.603+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (6.0.1)
[2024-11-18T18:16:49.604+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<5,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (4.25.2)
[2024-11-18T18:16:49.604+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz<2024 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T18:16:49.605+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (2.31.0)
[2024-11-18T18:16:49.605+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (23.2)
[2024-11-18T18:16:49.605+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (6.11.0)
[2024-11-18T18:16:49.606+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (0.4.4)
[2024-11-18T18:16:49.607+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (1.13.1)
[2024-11-18T18:16:49.607+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (7.0.0)
[2024-11-18T18:16:49.607+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (2.2.5)
[2024-11-18T18:16:49.608+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (1.24.4)
[2024-11-18T18:16:49.608+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (1.10.1)
[2024-11-18T18:16:49.625+0000] {process_utils.py:190} INFO - Collecting querystring-parser<2 (from mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2))
[2024-11-18T18:16:49.626+0000] {process_utils.py:190} INFO -   Using cached querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
[2024-11-18T18:16:49.627+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (1.4.51)
[2024-11-18T18:16:49.628+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow<16,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (14.0.2)
[2024-11-18T18:16:49.628+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (3.5.2)
[2024-11-18T18:16:49.629+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (3.7.5)
[2024-11-18T18:16:49.629+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<22 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (21.2.0)
[2024-11-18T18:16:49.630+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (3.1.3)
[2024-11-18T18:16:49.682+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venv1n4q6hf7/requirements.txt (line 3)) (2.8.2)
[2024-11-18T18:16:49.683+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venv1n4q6hf7/requirements.txt (line 3)) (2023.4)
[2024-11-18T18:16:49.704+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 4)) (1.4.2)
[2024-11-18T18:16:49.705+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 4)) (3.5.0)
[2024-11-18T18:16:49.741+0000] {process_utils.py:190} INFO - Collecting absl-py>=1.0.0 (from tensorflow==2.13.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 5))
[2024-11-18T18:16:49.742+0000] {process_utils.py:190} INFO -   Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
[2024-11-18T18:16:49.763+0000] {process_utils.py:190} INFO - Collecting astunparse>=1.6.0 (from tensorflow==2.13.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 5))
[2024-11-18T18:16:49.765+0000] {process_utils.py:190} INFO -   Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
[2024-11-18T18:16:49.784+0000] {process_utils.py:190} INFO - Collecting flatbuffers>=23.1.21 (from tensorflow==2.13.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 5))
[2024-11-18T18:16:49.785+0000] {process_utils.py:190} INFO -   Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
[2024-11-18T18:16:49.805+0000] {process_utils.py:190} INFO - Collecting gast<=0.4.0,>=0.2.1 (from tensorflow==2.13.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 5))
[2024-11-18T18:16:49.807+0000] {process_utils.py:190} INFO -   Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
[2024-11-18T18:16:49.825+0000] {process_utils.py:190} INFO - Collecting google-pasta>=0.1.1 (from tensorflow==2.13.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 5))
[2024-11-18T18:16:49.826+0000] {process_utils.py:190} INFO -   Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
[2024-11-18T18:16:49.827+0000] {process_utils.py:190} INFO - Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 5)) (1.60.0)
[2024-11-18T18:16:49.867+0000] {process_utils.py:190} INFO - Collecting h5py>=2.9.0 (from tensorflow==2.13.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 5))
[2024-11-18T18:16:49.868+0000] {process_utils.py:190} INFO -   Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
[2024-11-18T18:16:49.897+0000] {process_utils.py:190} INFO - Collecting keras<2.14,>=2.13.1 (from tensorflow==2.13.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 5))
[2024-11-18T18:16:49.898+0000] {process_utils.py:190} INFO -   Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
[2024-11-18T18:16:49.919+0000] {process_utils.py:190} INFO - Collecting libclang>=13.0.0 (from tensorflow==2.13.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 5))
[2024-11-18T18:16:49.920+0000] {process_utils.py:190} INFO -   Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
[2024-11-18T18:16:50.075+0000] {process_utils.py:190} INFO - Collecting numpy<2 (from mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2))
[2024-11-18T18:16:50.076+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-11-18T18:16:50.093+0000] {process_utils.py:190} INFO - Collecting opt-einsum>=2.3.2 (from tensorflow==2.13.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 5))
[2024-11-18T18:16:50.094+0000] {process_utils.py:190} INFO -   Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
[2024-11-18T18:16:50.095+0000] {process_utils.py:190} INFO - Requirement already satisfied: setuptools in /tmp/venv1n4q6hf7/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 5)) (69.0.2)
[2024-11-18T18:16:50.096+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.12.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:16:50.121+0000] {process_utils.py:190} INFO - Collecting tensorboard<2.14,>=2.13 (from tensorflow==2.13.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 5))
[2024-11-18T18:16:50.122+0000] {process_utils.py:190} INFO -   Using cached tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:16:50.141+0000] {process_utils.py:190} INFO - Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow==2.13.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 5))
[2024-11-18T18:16:50.142+0000] {process_utils.py:190} INFO -   Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
[2024-11-18T18:16:50.143+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.1.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 5)) (2.4.0)
[2024-11-18T18:16:50.188+0000] {process_utils.py:190} INFO - Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow==2.13.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 5))
[2024-11-18T18:16:50.189+0000] {process_utils.py:190} INFO -   Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
[2024-11-18T18:16:50.191+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt>=1.11.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:16:50.226+0000] {process_utils.py:190} INFO - Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow==2.13.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 5))
[2024-11-18T18:16:50.227+0000] {process_utils.py:190} INFO -   Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
[2024-11-18T18:16:50.235+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (1.3.0)
[2024-11-18T18:16:50.240+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (5.13.0)
[2024-11-18T18:16:50.243+0000] {process_utils.py:190} INFO - Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venv1n4q6hf7/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow==2.13.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 5)) (0.42.0)
[2024-11-18T18:16:50.248+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 1)) (1.26.18)
[2024-11-18T18:16:50.263+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (2.2.3)
[2024-11-18T18:16:50.264+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (2.1.2)
[2024-11-18T18:16:50.280+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (4.0.11)
[2024-11-18T18:16:50.305+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (3.17.0)
[2024-11-18T18:16:50.308+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (2.1.3)
[2024-11-18T18:16:50.332+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (1.1.1)
[2024-11-18T18:16:50.332+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (0.12.1)
[2024-11-18T18:16:50.333+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (4.54.1)
[2024-11-18T18:16:50.333+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (1.4.7)
[2024-11-18T18:16:50.345+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (10.4.0)
[2024-11-18T18:16:50.345+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (3.1.1)
[2024-11-18T18:16:50.391+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (3.3.2)
[2024-11-18T18:16:50.391+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (3.6)
[2024-11-18T18:16:50.392+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (2023.11.17)
[2024-11-18T18:16:50.613+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (3.0.3)
[2024-11-18T18:16:50.630+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth<3,>=1.6.3 in /home/***/.local/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 5)) (2.26.2)
[2024-11-18T18:16:50.652+0000] {process_utils.py:190} INFO - Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 5))
[2024-11-18T18:16:50.654+0000] {process_utils.py:190} INFO -   Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
[2024-11-18T18:16:50.682+0000] {process_utils.py:190} INFO - Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 5))
[2024-11-18T18:16:50.684+0000] {process_utils.py:190} INFO -   Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
[2024-11-18T18:16:50.826+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venv1n4q6hf7/requirements.txt (line 2)) (5.0.1)
[2024-11-18T18:16:50.837+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 5)) (5.3.2)
[2024-11-18T18:16:50.837+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 5)) (0.3.0)
[2024-11-18T18:16:50.838+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 5)) (4.9)
[2024-11-18T18:16:50.845+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 5)) (1.3.1)
[2024-11-18T18:16:50.979+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 5)) (0.5.1)
[2024-11-18T18:16:50.987+0000] {process_utils.py:190} INFO - Requirement already satisfied: oauthlib>=3.0.0 in /home/***/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv1n4q6hf7/requirements.txt (line 5)) (3.2.2)
[2024-11-18T18:16:51.021+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T18:16:51.022+0000] {process_utils.py:190} INFO - Using cached mlflow-2.10.2-py3-none-any.whl (19.5 MB)
[2024-11-18T18:16:51.043+0000] {process_utils.py:190} INFO - Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
[2024-11-18T18:16:51.550+0000] {process_utils.py:190} INFO - Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
[2024-11-18T18:16:51.551+0000] {process_utils.py:190} INFO - Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
[2024-11-18T18:16:51.552+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T18:16:51.565+0000] {process_utils.py:190} INFO - Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
[2024-11-18T18:16:51.566+0000] {process_utils.py:190} INFO - Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
[2024-11-18T18:16:51.567+0000] {process_utils.py:190} INFO - Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
[2024-11-18T18:16:51.568+0000] {process_utils.py:190} INFO - Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
[2024-11-18T18:16:51.569+0000] {process_utils.py:190} INFO - Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
[2024-11-18T18:16:51.576+0000] {process_utils.py:190} INFO - Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)
[2024-11-18T18:16:51.579+0000] {process_utils.py:190} INFO - Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
[2024-11-18T18:16:51.607+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-11-18T18:16:51.628+0000] {process_utils.py:190} INFO - Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
[2024-11-18T18:16:51.629+0000] {process_utils.py:190} INFO - Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
[2024-11-18T18:16:51.631+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T18:16:51.632+0000] {process_utils.py:190} INFO - Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
[2024-11-18T18:16:51.640+0000] {process_utils.py:190} INFO - Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
[2024-11-18T18:16:51.642+0000] {process_utils.py:190} INFO - Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
[2024-11-18T18:16:51.646+0000] {process_utils.py:190} INFO - Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[2024-11-18T18:16:51.647+0000] {process_utils.py:190} INFO - Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
[2024-11-18T18:16:51.648+0000] {process_utils.py:190} INFO - Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
[2024-11-18T18:16:53.765+0000] {process_utils.py:190} INFO - Installing collected packages: libclang, flatbuffers, typing-extensions, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, querystring-parser, opt-einsum, numpy, keras, google-pasta, gast, entrypoints, astunparse, absl-py, h5py, botocore, s3transfer, google-auth-oauthlib, tensorboard, mlflow, boto3, tensorflow
[2024-11-18T18:16:54.020+0000] {process_utils.py:190} INFO -   Attempting uninstall: typing-extensions
[2024-11-18T18:16:54.021+0000] {process_utils.py:190} INFO -     Found existing installation: typing_extensions 4.9.0
[2024-11-18T18:16:54.022+0000] {process_utils.py:190} INFO -     Not uninstalling typing-extensions at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv1n4q6hf7
[2024-11-18T18:16:54.022+0000] {process_utils.py:190} INFO -     Can't uninstall 'typing_extensions'. No files were found to uninstall.
[2024-11-18T18:16:54.298+0000] {process_utils.py:190} INFO -   Attempting uninstall: numpy
[2024-11-18T18:16:54.299+0000] {process_utils.py:190} INFO -     Found existing installation: numpy 1.24.4
[2024-11-18T18:16:54.300+0000] {process_utils.py:190} INFO -     Not uninstalling numpy at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv1n4q6hf7
[2024-11-18T18:16:54.300+0000] {process_utils.py:190} INFO -     Can't uninstall 'numpy'. No files were found to uninstall.
[2024-11-18T18:16:55.974+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T18:16:55.974+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T18:16:55.975+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv1n4q6hf7
[2024-11-18T18:16:55.975+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T18:16:56.381+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T18:16:56.382+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T18:16:56.382+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv1n4q6hf7
[2024-11-18T18:16:56.383+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T18:16:56.405+0000] {process_utils.py:190} INFO -   Attempting uninstall: google-auth-oauthlib
[2024-11-18T18:16:56.406+0000] {process_utils.py:190} INFO -     Found existing installation: google-auth-oauthlib 1.2.0
[2024-11-18T18:16:56.406+0000] {process_utils.py:190} INFO -     Not uninstalling google-auth-oauthlib at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv1n4q6hf7
[2024-11-18T18:16:56.406+0000] {process_utils.py:190} INFO -     Can't uninstall 'google-auth-oauthlib'. No files were found to uninstall.
[2024-11-18T18:16:56.612+0000] {process_utils.py:190} INFO -   Attempting uninstall: mlflow
[2024-11-18T18:16:56.614+0000] {process_utils.py:190} INFO -     Found existing installation: mlflow 2.17.0
[2024-11-18T18:16:56.614+0000] {process_utils.py:190} INFO -     Not uninstalling mlflow at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv1n4q6hf7
[2024-11-18T18:16:56.614+0000] {process_utils.py:190} INFO -     Can't uninstall 'mlflow'. No files were found to uninstall.
[2024-11-18T18:16:57.187+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T18:16:57.188+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T18:16:57.188+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv1n4q6hf7
[2024-11-18T18:16:57.189+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T18:17:04.569+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T18:17:04.570+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T18:17:04.570+0000] {process_utils.py:190} INFO - azure-core 1.29.6 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:17:04.570+0000] {process_utils.py:190} INFO - azure-mgmt-keyvault 10.3.1 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:17:04.571+0000] {process_utils.py:190} INFO - azure-mgmt-network 27.0.0 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:17:04.571+0000] {process_utils.py:190} INFO - graphene 3.4 requires typing-extensions<5,>=4.7.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:17:04.571+0000] {process_utils.py:190} INFO - pydantic 2.5.3 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:17:04.572+0000] {process_utils.py:190} INFO - pydantic-core 2.14.6 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:17:04.572+0000] {process_utils.py:190} INFO - Successfully installed absl-py-2.1.0 astunparse-1.6.3 boto3-1.28.0 botocore-1.31.85 entrypoints-0.4 flatbuffers-24.3.25 gast-0.4.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 h5py-3.11.0 keras-2.13.1 libclang-18.1.1 mlflow-2.10.2 numpy-1.24.3 opt-einsum-3.4.0 querystring-parser-1.2.4 s3transfer-0.6.2 tensorboard-2.13.0 tensorboard-data-server-0.7.2 tensorflow-2.13.0 tensorflow-estimator-2.13.0 tensorflow-io-gcs-filesystem-0.34.0 typing-extensions-4.5.0
[2024-11-18T18:17:04.644+0000] {process_utils.py:190} INFO - 
[2024-11-18T18:17:04.644+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.3.1
[2024-11-18T18:17:04.644+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T18:17:04.845+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv1n4q6hf7/bin/python /tmp/venv-callmbbnihsd/script.py /tmp/venv-callmbbnihsd/script.in /tmp/venv-callmbbnihsd/script.out /tmp/venv-callmbbnihsd/string_args.txt /tmp/venv-callmbbnihsd/termination.log
[2024-11-18T18:17:04.849+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:17:05.809+0000] {process_utils.py:190} INFO - 2024-11-18 18:17:05.809077: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-11-18T18:17:05.810+0000] {process_utils.py:190} INFO - 2024-11-18 18:17:05.810211: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T18:17:05.831+0000] {process_utils.py:190} INFO - 2024-11-18 18:17:05.831443: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T18:17:05.832+0000] {process_utils.py:190} INFO - 2024-11-18 18:17:05.831723: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-11-18T18:17:05.832+0000] {process_utils.py:190} INFO - To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-11-18T18:17:06.328+0000] {process_utils.py:190} INFO - 2024-11-18 18:17:06.328203: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-11-18T18:17:07.339+0000] {process_utils.py:190} INFO - Epoch 1/10
[2024-11-18T18:17:08.241+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 3:30 - loss: 0.3269 57/575 [=>............................] - ETA: 0s - loss: 0.1133  123/575 [=====>........................] - ETA: 0s - loss: 0.0803205/575 [=========>....................] - ETA: 0s - loss: 0.0631284/575 [=============>................] - ETA: 0s - loss: 0.0533366/575 [==================>...........] - ETA: 0s - loss: 0.0468446/575 [======================>.......] - ETA: 0s - loss: 0.0422525/575 [==========================>...] - ETA: 0s - loss: 0.0387575/575 [==============================] - 1s 933us/step - loss: 0.0370 - val_loss: 0.0055
[2024-11-18T18:17:08.242+0000] {process_utils.py:190} INFO - Epoch 2/10
[2024-11-18T18:17:08.681+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0165 85/575 [===>..........................] - ETA: 0s - loss: 0.0172168/575 [=======>......................] - ETA: 0s - loss: 0.0163248/575 [===========>..................] - ETA: 0s - loss: 0.0158326/575 [================>.............] - ETA: 0s - loss: 0.0153402/575 [===================>..........] - ETA: 0s - loss: 0.0150480/575 [========================>.....] - ETA: 0s - loss: 0.0146558/575 [============================>.] - ETA: 0s - loss: 0.0143575/575 [==============================] - 0s 764us/step - loss: 0.0142 - val_loss: 0.0046
[2024-11-18T18:17:08.681+0000] {process_utils.py:190} INFO - Epoch 3/10
[2024-11-18T18:17:09.117+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0109 83/575 [===>..........................] - ETA: 0s - loss: 0.0117164/575 [=======>......................] - ETA: 0s - loss: 0.0115242/575 [===========>..................] - ETA: 0s - loss: 0.0114322/575 [===============>..............] - ETA: 0s - loss: 0.0112404/575 [====================>.........] - ETA: 0s - loss: 0.0111486/575 [========================>.....] - ETA: 0s - loss: 0.0110572/575 [============================>.] - ETA: 0s - loss: 0.0109575/575 [==============================] - 0s 758us/step - loss: 0.0109 - val_loss: 0.0041
[2024-11-18T18:17:09.117+0000] {process_utils.py:190} INFO - Epoch 4/10
[2024-11-18T18:17:09.532+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0075 85/575 [===>..........................] - ETA: 0s - loss: 0.0100172/575 [=======>......................] - ETA: 0s - loss: 0.0097259/575 [============>.................] - ETA: 0s - loss: 0.0095346/575 [=================>............] - ETA: 0s - loss: 0.0094432/575 [=====================>........] - ETA: 0s - loss: 0.0093517/575 [=========================>....] - ETA: 0s - loss: 0.0092575/575 [==============================] - 0s 721us/step - loss: 0.0092 - val_loss: 0.0033
[2024-11-18T18:17:09.532+0000] {process_utils.py:190} INFO - Epoch 5/10
[2024-11-18T18:17:09.968+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0072 81/575 [===>..........................] - ETA: 0s - loss: 0.0083163/575 [=======>......................] - ETA: 0s - loss: 0.0083244/575 [===========>..................] - ETA: 0s - loss: 0.0083324/575 [===============>..............] - ETA: 0s - loss: 0.0082407/575 [====================>.........] - ETA: 0s - loss: 0.0081485/575 [========================>.....] - ETA: 0s - loss: 0.0081566/575 [============================>.] - ETA: 0s - loss: 0.0080575/575 [==============================] - 0s 758us/step - loss: 0.0080 - val_loss: 0.0030
[2024-11-18T18:17:09.968+0000] {process_utils.py:190} INFO - Epoch 6/10
[2024-11-18T18:17:10.413+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0081 80/575 [===>..........................] - ETA: 0s - loss: 0.0077162/575 [=======>......................] - ETA: 0s - loss: 0.0077241/575 [===========>..................] - ETA: 0s - loss: 0.0076320/575 [===============>..............] - ETA: 0s - loss: 0.0075398/575 [===================>..........] - ETA: 0s - loss: 0.0075474/575 [=======================>......] - ETA: 0s - loss: 0.0075550/575 [===========================>..] - ETA: 0s - loss: 0.0074575/575 [==============================] - 0s 774us/step - loss: 0.0074 - val_loss: 0.0027
[2024-11-18T18:17:10.414+0000] {process_utils.py:190} INFO - Epoch 7/10
[2024-11-18T18:17:10.854+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0072 83/575 [===>..........................] - ETA: 0s - loss: 0.0072167/575 [=======>......................] - ETA: 0s - loss: 0.0072248/575 [===========>..................] - ETA: 0s - loss: 0.0072326/575 [================>.............] - ETA: 0s - loss: 0.0071401/575 [===================>..........] - ETA: 0s - loss: 0.0071483/575 [========================>.....] - ETA: 0s - loss: 0.0071562/575 [============================>.] - ETA: 0s - loss: 0.0071575/575 [==============================] - 0s 765us/step - loss: 0.0071 - val_loss: 0.0026
[2024-11-18T18:17:10.854+0000] {process_utils.py:190} INFO - Epoch 8/10
[2024-11-18T18:17:11.272+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0061 85/575 [===>..........................] - ETA: 0s - loss: 0.0071171/575 [=======>......................] - ETA: 0s - loss: 0.0071254/575 [============>.................] - ETA: 0s - loss: 0.0070341/575 [================>.............] - ETA: 0s - loss: 0.0070426/575 [=====================>........] - ETA: 0s - loss: 0.0070512/575 [=========================>....] - ETA: 0s - loss: 0.0069575/575 [==============================] - 0s 727us/step - loss: 0.0069 - val_loss: 0.0022
[2024-11-18T18:17:11.273+0000] {process_utils.py:190} INFO - Epoch 9/10
[2024-11-18T18:17:11.695+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0070 87/575 [===>..........................] - ETA: 0s - loss: 0.0068171/575 [=======>......................] - ETA: 0s - loss: 0.0068253/575 [============>.................] - ETA: 0s - loss: 0.0067338/575 [================>.............] - ETA: 0s - loss: 0.0067424/575 [=====================>........] - ETA: 0s - loss: 0.0067509/575 [=========================>....] - ETA: 0s - loss: 0.0067575/575 [==============================] - 0s 735us/step - loss: 0.0067 - val_loss: 0.0022
[2024-11-18T18:17:11.696+0000] {process_utils.py:190} INFO - Epoch 10/10
[2024-11-18T18:17:12.128+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0057 81/575 [===>..........................] - ETA: 0s - loss: 0.0066164/575 [=======>......................] - ETA: 0s - loss: 0.0064249/575 [===========>..................] - ETA: 0s - loss: 0.0064333/575 [================>.............] - ETA: 0s - loss: 0.0065414/575 [====================>.........] - ETA: 0s - loss: 0.0065492/575 [========================>.....] - ETA: 0s - loss: 0.0065574/575 [============================>.] - ETA: 0s - loss: 0.0065575/575 [==============================] - 0s 752us/step - loss: 0.0065 - val_loss: 0.0022
[2024-11-18T18:17:12.523+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 30s101/719 [===>..........................] - ETA: 0s 212/719 [=======>......................] - ETA: 0s320/719 [============>.................] - ETA: 0s426/719 [================>.............] - ETA: 0s537/719 [=====================>........] - ETA: 0s647/719 [=========================>....] - ETA: 0s719/719 [==============================] - 0s 463us/step
[2024-11-18T18:17:13.062+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 7s112/719 [===>..........................] - ETA: 0s221/719 [========>.....................] - ETA: 0s326/719 [============>.................] - ETA: 0s428/719 [================>.............] - ETA: 0s530/719 [=====================>........] - ETA: 0s646/719 [=========================>....] - ETA: 0s719/719 [==============================] - 0s 462us/step
[2024-11-18T18:17:13.383+0000] {process_utils.py:190} INFO - /tmp/venv1n4q6hf7/lib/python3.8/site-packages/keras/src/engine/training.py:3000 UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
[2024-11-18T18:17:13.395+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-11-18T18:17:13.395+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callmbbnihsd/script.py", line 96, in <module>
[2024-11-18T18:17:13.396+0000] {process_utils.py:190} INFO -     res = train_challenger_model(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-18T18:17:13.396+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callmbbnihsd/script.py", line 82, in train_challenger_model
[2024-11-18T18:17:13.396+0000] {process_utils.py:190} INFO -     model.save(model_path)
[2024-11-18T18:17:13.396+0000] {process_utils.py:190} INFO -   File "/tmp/venv1n4q6hf7/lib/python3.8/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
[2024-11-18T18:17:13.396+0000] {process_utils.py:190} INFO -     raise e.with_traceback(filtered_tb) from None
[2024-11-18T18:17:13.396+0000] {process_utils.py:190} INFO -   File "/tmp/venv1n4q6hf7/lib/python3.8/site-packages/tensorflow/python/lib/io/file_io.py", line 513, in recursive_create_dir_v2
[2024-11-18T18:17:13.396+0000] {process_utils.py:190} INFO -     _pywrap_file_io.RecursivelyCreateDir(compat.path_to_bytes(path))
[2024-11-18T18:17:13.397+0000] {process_utils.py:190} INFO - tensorflow.python.framework.errors_impl.PermissionDeniedError: /models; Permission denied
[2024-11-18T18:17:14.267+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
/models; Permission denied
[2024-11-18T18:17:14.270+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=spotify_retrain_challenge_model_v3, task_id=train_challenger_model, execution_date=20241118T181119, start_date=20241118T181647, end_date=20241118T181714
[2024-11-18T18:17:14.293+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 78 for task train_challenger_model (Process returned non-zero exit status 1.
/models; Permission denied; 8254)
[2024-11-18T18:17:14.328+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-18T18:17:14.343+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
