[2024-11-18T18:14:15.502+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:14:14.799089+00:00 [queued]>
[2024-11-18T18:14:15.506+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:14:14.799089+00:00 [queued]>
[2024-11-18T18:14:15.507+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-11-18T18:14:15.514+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_challenger_model> on 2024-11-18 18:14:14.799089+00:00
[2024-11-18T18:14:15.517+0000] {standard_task_runner.py:60} INFO - Started process 6982 to run task
[2024-11-18T18:14:15.518+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_retrain_challenge_model_v3', 'train_challenger_model', 'manual__2024-11-18T18:14:14.799089+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/retrain_music_model.py', '--cfg-path', '/tmp/tmphs5nwov6']
[2024-11-18T18:14:15.520+0000] {standard_task_runner.py:88} INFO - Job 77: Subtask train_challenger_model
[2024-11-18T18:14:15.546+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:14:14.799089+00:00 [running]> on host 98017b53a184
[2024-11-18T18:14:15.584+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_retrain_challenge_model_v3' AIRFLOW_CTX_TASK_ID='train_challenger_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T18:14:14.799089+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T18:14:14.799089+00:00'
[2024-11-18T18:14:15.585+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvtfi96qnw --system-site-packages --python=python
[2024-11-18T18:14:15.589+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:14:15.913+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 114ms
[2024-11-18T18:14:15.913+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvtfi96qnw, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T18:14:15.914+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T18:14:15.914+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-11-18T18:14:15.914+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T18:14:15.932+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvtfi96qnw/bin/pip install -r /tmp/venvtfi96qnw/requirements.txt
[2024-11-18T18:14:15.936+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:14:16.868+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venvtfi96qnw/requirements.txt (line 1))
[2024-11-18T18:14:16.870+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T18:14:16.922+0000] {process_utils.py:190} INFO - Collecting mlflow==2.10.2 (from -r /tmp/venvtfi96qnw/requirements.txt (line 2))
[2024-11-18T18:14:16.924+0000] {process_utils.py:190} INFO -   Using cached mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
[2024-11-18T18:14:16.925+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvtfi96qnw/requirements.txt (line 3)) (2.0.3)
[2024-11-18T18:14:16.925+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn==1.3.2 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvtfi96qnw/requirements.txt (line 4)) (1.3.2)
[2024-11-18T18:14:17.027+0000] {process_utils.py:190} INFO - Collecting tensorflow==2.13.0 (from -r /tmp/venvtfi96qnw/requirements.txt (line 5))
[2024-11-18T18:14:17.028+0000] {process_utils.py:190} INFO -   Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
[2024-11-18T18:14:17.442+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venvtfi96qnw/requirements.txt (line 1))
[2024-11-18T18:14:17.444+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T18:14:17.445+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venvtfi96qnw/requirements.txt (line 1)) (0.10.0)
[2024-11-18T18:14:17.469+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venvtfi96qnw/requirements.txt (line 1))
[2024-11-18T18:14:17.471+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:14:17.525+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (8.1.7)
[2024-11-18T18:14:17.525+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (3.1.0)
[2024-11-18T18:14:17.542+0000] {process_utils.py:190} INFO - Collecting entrypoints<1 (from mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2))
[2024-11-18T18:14:17.543+0000] {process_utils.py:190} INFO -   Using cached entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
[2024-11-18T18:14:17.544+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=2.1.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (3.1.43)
[2024-11-18T18:14:17.545+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (6.0.1)
[2024-11-18T18:14:17.545+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<5,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (4.25.2)
[2024-11-18T18:14:17.546+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz<2024 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T18:14:17.546+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (2.31.0)
[2024-11-18T18:14:17.546+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (23.2)
[2024-11-18T18:14:17.547+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (6.11.0)
[2024-11-18T18:14:17.548+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (0.4.4)
[2024-11-18T18:14:17.548+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (1.13.1)
[2024-11-18T18:14:17.549+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (7.0.0)
[2024-11-18T18:14:17.549+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (2.2.5)
[2024-11-18T18:14:17.549+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (1.24.4)
[2024-11-18T18:14:17.550+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (1.10.1)
[2024-11-18T18:14:17.567+0000] {process_utils.py:190} INFO - Collecting querystring-parser<2 (from mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2))
[2024-11-18T18:14:17.568+0000] {process_utils.py:190} INFO -   Using cached querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
[2024-11-18T18:14:17.569+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (1.4.51)
[2024-11-18T18:14:17.570+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow<16,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (14.0.2)
[2024-11-18T18:14:17.571+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (3.5.2)
[2024-11-18T18:14:17.571+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (3.7.5)
[2024-11-18T18:14:17.572+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<22 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (21.2.0)
[2024-11-18T18:14:17.573+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (3.1.3)
[2024-11-18T18:14:17.627+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvtfi96qnw/requirements.txt (line 3)) (2.8.2)
[2024-11-18T18:14:17.628+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvtfi96qnw/requirements.txt (line 3)) (2023.4)
[2024-11-18T18:14:17.649+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvtfi96qnw/requirements.txt (line 4)) (1.4.2)
[2024-11-18T18:14:17.650+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvtfi96qnw/requirements.txt (line 4)) (3.5.0)
[2024-11-18T18:14:17.683+0000] {process_utils.py:190} INFO - Collecting absl-py>=1.0.0 (from tensorflow==2.13.0->-r /tmp/venvtfi96qnw/requirements.txt (line 5))
[2024-11-18T18:14:17.684+0000] {process_utils.py:190} INFO -   Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
[2024-11-18T18:14:17.701+0000] {process_utils.py:190} INFO - Collecting astunparse>=1.6.0 (from tensorflow==2.13.0->-r /tmp/venvtfi96qnw/requirements.txt (line 5))
[2024-11-18T18:14:17.702+0000] {process_utils.py:190} INFO -   Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
[2024-11-18T18:14:17.720+0000] {process_utils.py:190} INFO - Collecting flatbuffers>=23.1.21 (from tensorflow==2.13.0->-r /tmp/venvtfi96qnw/requirements.txt (line 5))
[2024-11-18T18:14:17.721+0000] {process_utils.py:190} INFO -   Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
[2024-11-18T18:14:17.741+0000] {process_utils.py:190} INFO - Collecting gast<=0.4.0,>=0.2.1 (from tensorflow==2.13.0->-r /tmp/venvtfi96qnw/requirements.txt (line 5))
[2024-11-18T18:14:17.742+0000] {process_utils.py:190} INFO -   Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
[2024-11-18T18:14:17.759+0000] {process_utils.py:190} INFO - Collecting google-pasta>=0.1.1 (from tensorflow==2.13.0->-r /tmp/venvtfi96qnw/requirements.txt (line 5))
[2024-11-18T18:14:17.760+0000] {process_utils.py:190} INFO -   Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
[2024-11-18T18:14:17.761+0000] {process_utils.py:190} INFO - Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvtfi96qnw/requirements.txt (line 5)) (1.60.0)
[2024-11-18T18:14:17.802+0000] {process_utils.py:190} INFO - Collecting h5py>=2.9.0 (from tensorflow==2.13.0->-r /tmp/venvtfi96qnw/requirements.txt (line 5))
[2024-11-18T18:14:17.803+0000] {process_utils.py:190} INFO -   Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
[2024-11-18T18:14:17.830+0000] {process_utils.py:190} INFO - Collecting keras<2.14,>=2.13.1 (from tensorflow==2.13.0->-r /tmp/venvtfi96qnw/requirements.txt (line 5))
[2024-11-18T18:14:17.831+0000] {process_utils.py:190} INFO -   Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
[2024-11-18T18:14:17.852+0000] {process_utils.py:190} INFO - Collecting libclang>=13.0.0 (from tensorflow==2.13.0->-r /tmp/venvtfi96qnw/requirements.txt (line 5))
[2024-11-18T18:14:17.853+0000] {process_utils.py:190} INFO -   Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
[2024-11-18T18:14:18.004+0000] {process_utils.py:190} INFO - Collecting numpy<2 (from mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2))
[2024-11-18T18:14:18.005+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-11-18T18:14:18.022+0000] {process_utils.py:190} INFO - Collecting opt-einsum>=2.3.2 (from tensorflow==2.13.0->-r /tmp/venvtfi96qnw/requirements.txt (line 5))
[2024-11-18T18:14:18.023+0000] {process_utils.py:190} INFO -   Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
[2024-11-18T18:14:18.024+0000] {process_utils.py:190} INFO - Requirement already satisfied: setuptools in /tmp/venvtfi96qnw/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvtfi96qnw/requirements.txt (line 5)) (69.0.2)
[2024-11-18T18:14:18.025+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.12.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvtfi96qnw/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:14:18.049+0000] {process_utils.py:190} INFO - Collecting tensorboard<2.14,>=2.13 (from tensorflow==2.13.0->-r /tmp/venvtfi96qnw/requirements.txt (line 5))
[2024-11-18T18:14:18.051+0000] {process_utils.py:190} INFO -   Using cached tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:14:18.079+0000] {process_utils.py:190} INFO - Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow==2.13.0->-r /tmp/venvtfi96qnw/requirements.txt (line 5))
[2024-11-18T18:14:18.082+0000] {process_utils.py:190} INFO -   Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
[2024-11-18T18:14:18.082+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.1.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvtfi96qnw/requirements.txt (line 5)) (2.4.0)
[2024-11-18T18:14:18.122+0000] {process_utils.py:190} INFO - Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow==2.13.0->-r /tmp/venvtfi96qnw/requirements.txt (line 5))
[2024-11-18T18:14:18.124+0000] {process_utils.py:190} INFO -   Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
[2024-11-18T18:14:18.125+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt>=1.11.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvtfi96qnw/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:14:18.202+0000] {process_utils.py:190} INFO - Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow==2.13.0->-r /tmp/venvtfi96qnw/requirements.txt (line 5))
[2024-11-18T18:14:18.203+0000] {process_utils.py:190} INFO -   Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
[2024-11-18T18:14:18.210+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (1.3.0)
[2024-11-18T18:14:18.213+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (5.13.0)
[2024-11-18T18:14:18.216+0000] {process_utils.py:190} INFO - Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venvtfi96qnw/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow==2.13.0->-r /tmp/venvtfi96qnw/requirements.txt (line 5)) (0.42.0)
[2024-11-18T18:14:18.221+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venvtfi96qnw/requirements.txt (line 1)) (1.26.18)
[2024-11-18T18:14:18.236+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (2.2.3)
[2024-11-18T18:14:18.236+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (2.1.2)
[2024-11-18T18:14:18.253+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (4.0.11)
[2024-11-18T18:14:18.280+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (3.17.0)
[2024-11-18T18:14:18.283+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (2.1.3)
[2024-11-18T18:14:18.307+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (1.1.1)
[2024-11-18T18:14:18.307+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (0.12.1)
[2024-11-18T18:14:18.308+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (4.54.1)
[2024-11-18T18:14:18.308+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (1.4.7)
[2024-11-18T18:14:18.315+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (10.4.0)
[2024-11-18T18:14:18.316+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (3.1.1)
[2024-11-18T18:14:18.358+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (3.3.2)
[2024-11-18T18:14:18.358+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (3.6)
[2024-11-18T18:14:18.359+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (2023.11.17)
[2024-11-18T18:14:18.648+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (3.0.3)
[2024-11-18T18:14:18.667+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth<3,>=1.6.3 in /home/***/.local/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvtfi96qnw/requirements.txt (line 5)) (2.26.2)
[2024-11-18T18:14:18.703+0000] {process_utils.py:190} INFO - Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvtfi96qnw/requirements.txt (line 5))
[2024-11-18T18:14:18.704+0000] {process_utils.py:190} INFO -   Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
[2024-11-18T18:14:18.733+0000] {process_utils.py:190} INFO - Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvtfi96qnw/requirements.txt (line 5))
[2024-11-18T18:14:18.734+0000] {process_utils.py:190} INFO -   Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
[2024-11-18T18:14:18.876+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvtfi96qnw/requirements.txt (line 2)) (5.0.1)
[2024-11-18T18:14:18.887+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvtfi96qnw/requirements.txt (line 5)) (5.3.2)
[2024-11-18T18:14:18.887+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvtfi96qnw/requirements.txt (line 5)) (0.3.0)
[2024-11-18T18:14:18.888+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvtfi96qnw/requirements.txt (line 5)) (4.9)
[2024-11-18T18:14:18.895+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvtfi96qnw/requirements.txt (line 5)) (1.3.1)
[2024-11-18T18:14:19.023+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvtfi96qnw/requirements.txt (line 5)) (0.5.1)
[2024-11-18T18:14:19.031+0000] {process_utils.py:190} INFO - Requirement already satisfied: oauthlib>=3.0.0 in /home/***/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvtfi96qnw/requirements.txt (line 5)) (3.2.2)
[2024-11-18T18:14:19.062+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T18:14:19.063+0000] {process_utils.py:190} INFO - Using cached mlflow-2.10.2-py3-none-any.whl (19.5 MB)
[2024-11-18T18:14:19.080+0000] {process_utils.py:190} INFO - Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
[2024-11-18T18:14:19.585+0000] {process_utils.py:190} INFO - Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
[2024-11-18T18:14:19.587+0000] {process_utils.py:190} INFO - Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
[2024-11-18T18:14:19.588+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T18:14:19.599+0000] {process_utils.py:190} INFO - Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
[2024-11-18T18:14:19.600+0000] {process_utils.py:190} INFO - Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
[2024-11-18T18:14:19.602+0000] {process_utils.py:190} INFO - Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
[2024-11-18T18:14:19.603+0000] {process_utils.py:190} INFO - Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
[2024-11-18T18:14:19.604+0000] {process_utils.py:190} INFO - Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
[2024-11-18T18:14:19.611+0000] {process_utils.py:190} INFO - Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)
[2024-11-18T18:14:19.613+0000] {process_utils.py:190} INFO - Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
[2024-11-18T18:14:19.640+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-11-18T18:14:19.657+0000] {process_utils.py:190} INFO - Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
[2024-11-18T18:14:19.658+0000] {process_utils.py:190} INFO - Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
[2024-11-18T18:14:19.659+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T18:14:19.660+0000] {process_utils.py:190} INFO - Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
[2024-11-18T18:14:19.666+0000] {process_utils.py:190} INFO - Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
[2024-11-18T18:14:19.668+0000] {process_utils.py:190} INFO - Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
[2024-11-18T18:14:19.671+0000] {process_utils.py:190} INFO - Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[2024-11-18T18:14:19.672+0000] {process_utils.py:190} INFO - Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
[2024-11-18T18:14:19.673+0000] {process_utils.py:190} INFO - Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
[2024-11-18T18:14:21.808+0000] {process_utils.py:190} INFO - Installing collected packages: libclang, flatbuffers, typing-extensions, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, querystring-parser, opt-einsum, numpy, keras, google-pasta, gast, entrypoints, astunparse, absl-py, h5py, botocore, s3transfer, google-auth-oauthlib, tensorboard, mlflow, boto3, tensorflow
[2024-11-18T18:14:22.059+0000] {process_utils.py:190} INFO -   Attempting uninstall: typing-extensions
[2024-11-18T18:14:22.060+0000] {process_utils.py:190} INFO -     Found existing installation: typing_extensions 4.9.0
[2024-11-18T18:14:22.061+0000] {process_utils.py:190} INFO -     Not uninstalling typing-extensions at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvtfi96qnw
[2024-11-18T18:14:22.061+0000] {process_utils.py:190} INFO -     Can't uninstall 'typing_extensions'. No files were found to uninstall.
[2024-11-18T18:14:22.338+0000] {process_utils.py:190} INFO -   Attempting uninstall: numpy
[2024-11-18T18:14:22.339+0000] {process_utils.py:190} INFO -     Found existing installation: numpy 1.24.4
[2024-11-18T18:14:22.339+0000] {process_utils.py:190} INFO -     Not uninstalling numpy at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvtfi96qnw
[2024-11-18T18:14:22.340+0000] {process_utils.py:190} INFO -     Can't uninstall 'numpy'. No files were found to uninstall.
[2024-11-18T18:14:24.043+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T18:14:24.044+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T18:14:24.044+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvtfi96qnw
[2024-11-18T18:14:24.045+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T18:14:24.500+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T18:14:24.501+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T18:14:24.502+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvtfi96qnw
[2024-11-18T18:14:24.502+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T18:14:24.524+0000] {process_utils.py:190} INFO -   Attempting uninstall: google-auth-oauthlib
[2024-11-18T18:14:24.526+0000] {process_utils.py:190} INFO -     Found existing installation: google-auth-oauthlib 1.2.0
[2024-11-18T18:14:24.526+0000] {process_utils.py:190} INFO -     Not uninstalling google-auth-oauthlib at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvtfi96qnw
[2024-11-18T18:14:24.527+0000] {process_utils.py:190} INFO -     Can't uninstall 'google-auth-oauthlib'. No files were found to uninstall.
[2024-11-18T18:14:24.729+0000] {process_utils.py:190} INFO -   Attempting uninstall: mlflow
[2024-11-18T18:14:24.730+0000] {process_utils.py:190} INFO -     Found existing installation: mlflow 2.17.0
[2024-11-18T18:14:24.731+0000] {process_utils.py:190} INFO -     Not uninstalling mlflow at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvtfi96qnw
[2024-11-18T18:14:24.731+0000] {process_utils.py:190} INFO -     Can't uninstall 'mlflow'. No files were found to uninstall.
[2024-11-18T18:14:25.308+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T18:14:25.309+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T18:14:25.309+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvtfi96qnw
[2024-11-18T18:14:25.310+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T18:14:32.493+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T18:14:32.494+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T18:14:32.494+0000] {process_utils.py:190} INFO - azure-core 1.29.6 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:14:32.494+0000] {process_utils.py:190} INFO - azure-mgmt-keyvault 10.3.1 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:14:32.494+0000] {process_utils.py:190} INFO - azure-mgmt-network 27.0.0 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:14:32.495+0000] {process_utils.py:190} INFO - graphene 3.4 requires typing-extensions<5,>=4.7.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:14:32.495+0000] {process_utils.py:190} INFO - pydantic 2.5.3 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:14:32.495+0000] {process_utils.py:190} INFO - pydantic-core 2.14.6 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:14:32.495+0000] {process_utils.py:190} INFO - Successfully installed absl-py-2.1.0 astunparse-1.6.3 boto3-1.28.0 botocore-1.31.85 entrypoints-0.4 flatbuffers-24.3.25 gast-0.4.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 h5py-3.11.0 keras-2.13.1 libclang-18.1.1 mlflow-2.10.2 numpy-1.24.3 opt-einsum-3.4.0 querystring-parser-1.2.4 s3transfer-0.6.2 tensorboard-2.13.0 tensorboard-data-server-0.7.2 tensorflow-2.13.0 tensorflow-estimator-2.13.0 tensorflow-io-gcs-filesystem-0.34.0 typing-extensions-4.5.0
[2024-11-18T18:14:32.571+0000] {process_utils.py:190} INFO - 
[2024-11-18T18:14:32.571+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.3.1
[2024-11-18T18:14:32.571+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T18:14:32.763+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvtfi96qnw/bin/python /tmp/venv-callr1q7nrsh/script.py /tmp/venv-callr1q7nrsh/script.in /tmp/venv-callr1q7nrsh/script.out /tmp/venv-callr1q7nrsh/string_args.txt /tmp/venv-callr1q7nrsh/termination.log
[2024-11-18T18:14:32.767+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:14:33.724+0000] {process_utils.py:190} INFO - 2024-11-18 18:14:33.724729: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-11-18T18:14:33.725+0000] {process_utils.py:190} INFO - 2024-11-18 18:14:33.725873: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T18:14:33.746+0000] {process_utils.py:190} INFO - 2024-11-18 18:14:33.746763: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T18:14:33.747+0000] {process_utils.py:190} INFO - 2024-11-18 18:14:33.747172: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-11-18T18:14:33.747+0000] {process_utils.py:190} INFO - To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-11-18T18:14:34.258+0000] {process_utils.py:190} INFO - 2024-11-18 18:14:34.258150: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-11-18T18:14:35.294+0000] {process_utils.py:190} INFO - Epoch 1/10
[2024-11-18T18:14:36.177+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 3:29 - loss: 0.3954 60/575 [==>...........................] - ETA: 0s - loss: 0.1559  131/575 [=====>........................] - ETA: 0s - loss: 0.1067217/575 [==========>...................] - ETA: 0s - loss: 0.0827298/575 [==============>...............] - ETA: 0s - loss: 0.0696380/575 [==================>...........] - ETA: 0s - loss: 0.0602462/575 [=======================>......] - ETA: 0s - loss: 0.0535546/575 [===========================>..] - ETA: 0s - loss: 0.0484575/575 [==============================] - 1s 902us/step - loss: 0.0469 - val_loss: 0.0065
[2024-11-18T18:14:36.177+0000] {process_utils.py:190} INFO - Epoch 2/10
[2024-11-18T18:14:36.607+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0166 84/575 [===>..........................] - ETA: 0s - loss: 0.0185168/575 [=======>......................] - ETA: 0s - loss: 0.0177253/575 [============>.................] - ETA: 0s - loss: 0.0172333/575 [================>.............] - ETA: 0s - loss: 0.0168402/575 [===================>..........] - ETA: 0s - loss: 0.0164490/575 [========================>.....] - ETA: 0s - loss: 0.0160575/575 [==============================] - 0s 748us/step - loss: 0.0156 - val_loss: 0.0051
[2024-11-18T18:14:36.608+0000] {process_utils.py:190} INFO - Epoch 3/10
[2024-11-18T18:14:37.032+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0145 85/575 [===>..........................] - ETA: 0s - loss: 0.0135171/575 [=======>......................] - ETA: 0s - loss: 0.0133254/575 [============>.................] - ETA: 0s - loss: 0.0131338/575 [================>.............] - ETA: 0s - loss: 0.0128421/575 [====================>.........] - ETA: 0s - loss: 0.0126505/575 [=========================>....] - ETA: 0s - loss: 0.0124575/575 [==============================] - 0s 737us/step - loss: 0.0122 - val_loss: 0.0044
[2024-11-18T18:14:37.032+0000] {process_utils.py:190} INFO - Epoch 4/10
[2024-11-18T18:14:37.456+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0107 81/575 [===>..........................] - ETA: 0s - loss: 0.0110165/575 [=======>......................] - ETA: 0s - loss: 0.0108250/575 [============>.................] - ETA: 0s - loss: 0.0107332/575 [================>.............] - ETA: 0s - loss: 0.0106414/575 [====================>.........] - ETA: 0s - loss: 0.0104499/575 [=========================>....] - ETA: 0s - loss: 0.0103575/575 [==============================] - 0s 738us/step - loss: 0.0102 - val_loss: 0.0037
[2024-11-18T18:14:37.457+0000] {process_utils.py:190} INFO - Epoch 5/10
[2024-11-18T18:14:37.878+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0083 84/575 [===>..........................] - ETA: 0s - loss: 0.0092170/575 [=======>......................] - ETA: 0s - loss: 0.0092255/575 [============>.................] - ETA: 0s - loss: 0.0092340/575 [================>.............] - ETA: 0s - loss: 0.0091423/575 [=====================>........] - ETA: 0s - loss: 0.0089505/575 [=========================>....] - ETA: 0s - loss: 0.0088575/575 [==============================] - 0s 733us/step - loss: 0.0088 - val_loss: 0.0031
[2024-11-18T18:14:37.879+0000] {process_utils.py:190} INFO - Epoch 6/10
[2024-11-18T18:14:38.385+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0088 86/575 [===>..........................] - ETA: 0s - loss: 0.0082171/575 [=======>......................] - ETA: 0s - loss: 0.0080255/575 [============>.................] - ETA: 0s - loss: 0.0080337/575 [================>.............] - ETA: 0s - loss: 0.0080418/575 [====================>.........] - ETA: 0s - loss: 0.0080496/575 [========================>.....] - ETA: 0s - loss: 0.0080574/575 [============================>.] - ETA: 0s - loss: 0.0079575/575 [==============================] - 1s 880us/step - loss: 0.0079 - val_loss: 0.0029
[2024-11-18T18:14:38.387+0000] {process_utils.py:190} INFO - Epoch 7/10
[2024-11-18T18:14:38.835+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 2s - loss: 0.0076 62/575 [==>...........................] - ETA: 0s - loss: 0.0077145/575 [======>.......................] - ETA: 0s - loss: 0.0075226/575 [==========>...................] - ETA: 0s - loss: 0.0075304/575 [==============>...............] - ETA: 0s - loss: 0.0074380/575 [==================>...........] - ETA: 0s - loss: 0.0074463/575 [=======================>......] - ETA: 0s - loss: 0.0073548/575 [===========================>..] - ETA: 0s - loss: 0.0074575/575 [==============================] - 0s 773us/step - loss: 0.0074 - val_loss: 0.0026
[2024-11-18T18:14:38.835+0000] {process_utils.py:190} INFO - Epoch 8/10
[2024-11-18T18:14:39.259+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0091 86/575 [===>..........................] - ETA: 0s - loss: 0.0074170/575 [=======>......................] - ETA: 0s - loss: 0.0073254/575 [============>.................] - ETA: 0s - loss: 0.0073338/575 [================>.............] - ETA: 0s - loss: 0.0073421/575 [====================>.........] - ETA: 0s - loss: 0.0073504/575 [=========================>....] - ETA: 0s - loss: 0.0072575/575 [==============================] - 0s 736us/step - loss: 0.0072 - val_loss: 0.0027
[2024-11-18T18:14:39.259+0000] {process_utils.py:190} INFO - Epoch 9/10
[2024-11-18T18:14:39.681+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0071 91/575 [===>..........................] - ETA: 0s - loss: 0.0071176/575 [========>.....................] - ETA: 0s - loss: 0.0070255/575 [============>.................] - ETA: 0s - loss: 0.0070335/575 [================>.............] - ETA: 0s - loss: 0.0069418/575 [====================>.........] - ETA: 0s - loss: 0.0069504/575 [=========================>....] - ETA: 0s - loss: 0.0069575/575 [==============================] - 0s 734us/step - loss: 0.0069 - val_loss: 0.0028
[2024-11-18T18:14:39.682+0000] {process_utils.py:190} INFO - Epoch 10/10
[2024-11-18T18:14:40.106+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0068 81/575 [===>..........................] - ETA: 0s - loss: 0.0069158/575 [=======>......................] - ETA: 0s - loss: 0.0069243/575 [===========>..................] - ETA: 0s - loss: 0.0069330/575 [================>.............] - ETA: 0s - loss: 0.0069412/575 [====================>.........] - ETA: 0s - loss: 0.0068495/575 [========================>.....] - ETA: 0s - loss: 0.0068575/575 [==============================] - 0s 739us/step - loss: 0.0068 - val_loss: 0.0023
[2024-11-18T18:14:40.493+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 28s106/719 [===>..........................] - ETA: 0s 218/719 [========>.....................] - ETA: 0s331/719 [============>.................] - ETA: 0s445/719 [=================>............] - ETA: 0s553/719 [======================>.......] - ETA: 0s660/719 [==========================>...] - ETA: 0s719/719 [==============================] - 0s 455us/step
[2024-11-18T18:14:41.031+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 7s106/719 [===>..........................] - ETA: 0s219/719 [========>.....................] - ETA: 0s326/719 [============>.................] - ETA: 0s440/719 [=================>............] - ETA: 0s554/719 [======================>.......] - ETA: 0s664/719 [==========================>...] - ETA: 0s719/719 [==============================] - 0s 453us/step
[2024-11-18T18:14:41.127+0000] {process_utils.py:190} INFO - /tmp/venvtfi96qnw/lib/python3.8/site-packages/keras/src/engine/training.py:3000 UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
[2024-11-18T18:14:41.135+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-11-18T18:14:41.135+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callr1q7nrsh/script.py", line 96, in <module>
[2024-11-18T18:14:41.136+0000] {process_utils.py:190} INFO -     res = train_challenger_model(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-18T18:14:41.136+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callr1q7nrsh/script.py", line 82, in train_challenger_model
[2024-11-18T18:14:41.136+0000] {process_utils.py:190} INFO -     model.save(model_path)
[2024-11-18T18:14:41.136+0000] {process_utils.py:190} INFO -   File "/tmp/venvtfi96qnw/lib/python3.8/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
[2024-11-18T18:14:41.136+0000] {process_utils.py:190} INFO -     raise e.with_traceback(filtered_tb) from None
[2024-11-18T18:14:41.136+0000] {process_utils.py:190} INFO -   File "/tmp/venvtfi96qnw/lib/python3.8/site-packages/tensorflow/python/lib/io/file_io.py", line 513, in recursive_create_dir_v2
[2024-11-18T18:14:41.136+0000] {process_utils.py:190} INFO -     _pywrap_file_io.RecursivelyCreateDir(compat.path_to_bytes(path))
[2024-11-18T18:14:41.136+0000] {process_utils.py:190} INFO - tensorflow.python.framework.errors_impl.PermissionDeniedError: /models; Permission denied
[2024-11-18T18:14:41.995+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
/models; Permission denied
[2024-11-18T18:14:41.997+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_retrain_challenge_model_v3, task_id=train_challenger_model, execution_date=20241118T181414, start_date=20241118T181415, end_date=20241118T181441
[2024-11-18T18:14:42.003+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 77 for task train_challenger_model (Process returned non-zero exit status 1.
/models; Permission denied; 6982)
[2024-11-18T18:14:42.030+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-18T18:14:42.042+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
